#include "fsb_core/recovered_battle.hpp"
#include "fsb_core/map_logic/map_setup.hpp"
#include "fsb_core/map.hpp"

// Generated by tools/parallel/C_MAPS/emit_map_setup_tables.py; edit the
// extractor, not this file. Temporary ABI boundary for the recovered map
// installers, whose original callers still use the old execution model.
namespace fsb::core {
bool RecoveredBattle::dispatch_c_maps_installers(Address entry){
    switch(entry){
    case 0x48752d:
    case 0x487fa2:
    case 0x488543:
    case 0x488583:
    case 0x4885ec:
    case 0x488902:
    case 0x48893d:
    case 0x48928d:
    case 0x489452:
    case 0x48968a:
    case 0x4896ca:
    case 0x489702:
    case 0x489f13:
    case 0x489f4e:
    case 0x489f89:
    case 0x489fc1:
    case 0x48a120:
    case 0x48a1aa:
    case 0x48a7da:
    case 0x48aa08:
    case 0x48ab3b:
    case 0x48ac68:
    case 0x48ad54:
    case 0x48b929:
    case 0x48b9fd:
    case 0x48beef:
    case 0x48bf97:
    case 0x48c1a8:
    case 0x48c27a:
    case 0x48c2b5:
    case 0x48cbe9:
    case 0x48cc24:
    case 0x48d274:
    case 0x48d40b:
    case 0x48d53e:
    case 0x48d5e0:
    case 0x48d6b4:
    case 0x48d81b:
    case 0x48d916:
    case 0x48d9ea:
    case 0x48db51:
    case 0x48dc43:
    case 0x48dd11:
    case 0x48e3fd:
    case 0x48e530:
    case 0x48ed2c:
    case 0x48ee5f:
    case 0x48f894:
    case 0x48f968:
    case 0x4900c6:
    case 0x49072d:
    case 0x490801:
    case 0x4908d2:
    case 0x490a05:
    case 0x490a42:
    case 0x491259:
    case 0x4912fe:
    case 0x491a09:
    case 0x491aae:
    case 0x491be8:
    case 0x491d54:
    case 0x491d8f:
    case 0x492665:
    case 0x492985:
    case 0x492ab7:
    case 0x492f74:
    case 0x49335d:
    case 0x4934ca:
    case 0x4935a5:
    case 0x493682:
    case 0x4937bb:
    case 0x4937f6:
    case 0x493984:
    case 0x493f23:
    case 0x4940a1:
    case 0x4943ff:
    case 0x4944d8:
    case 0x49457a:
    case 0x494743:
    case 0x4967c6:
    case 0x49692a:
    case 0x496965:
    case 0x4969a0:
    case 0x496a10:
    case 0x496a4b:
    case 0x496a8b:
    case 0x496ac6:
    case 0x496b33:
    case 0x496b73:
    case 0x496bae:
    case 0x496bef:
    case 0x496c2a:
    case 0x496c67:
    case 0x496ca7:
    case 0x496ce2:
    case 0x496dac:
    case 0x496df0:
    case 0x496e30:
    case 0x496e6b:
    case 0x496ea8:
    case 0x496ee3:
    case 0x496f23:
    case 0x496f63:
    case 0x496fa3:
    {
        Map map(memory_);
        if(!map_logic::install_map_overlays(memory_,map,entry))return false;
        result(0,0);return true; // The setup dispatcher ignores EAX.
    }
    default:return false;
    }
}
} // namespace fsb::core
