// Generated by tools/translate_battle.py; edit the generator, not this file.
// Original EXE SHA256: 710881d024ab1fcf738b342c248631363c9de3a51b32a7e3d61781b791eff454
#include "fsb_core/recovered_battle.hpp"
#include <cstring>
#include <cmath>
namespace fsb::core {
// 00463258_draw_party_status_panel_463258
void RecoveredBattle::fn_463258(){
goto L463258;
L463258: { // 55  push ebp
push(get(5,4,0));
}
L463259: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L46325b: { // 81ecd4010000  sub esp, 0x1d4
put(4,sub(get(4,4,0),0x1d4u,4,false),4,0);
}
L463261: { // 53  push ebx
push(get(3,4,0));
}
L463262: { // 56  push esi
push(get(6,4,0));
}
L463263: { // 8b7508  mov esi, dword ptr [ebp + 8]
put(6,read((0x8u+r[5]),4),4,0);
}
L463266: { // 33db  xor ebx, ebx
put(3,logic(get(3,4,0)^get(3,4,0),4),4,0);
}
L463268: { // 57  push edi
push(get(7,4,0));
}
L463269: { // 399e88010000  cmp dword ptr [esi + 0x188], ebx
sub(read((0x188u+r[6]),4),get(3,4,0),4);
}
L46326f: { // 0f8480070000  je 0x4639f5
if(condition(0))goto L4639f5;
}
L463275: { // 391d00658000  cmp dword ptr [0x806500], ebx
sub(read((0x806500u),4),get(3,4,0),4);
}
L46327b: { // 0f8474070000  je 0x4639f5
if(condition(0))goto L4639f5;
}
L463281: { // 53  push ebx
push(get(3,4,0));
}
L463282: { // 53  push ebx
push(get(3,4,0));
}
L463283: { // 891d00658000  mov dword ptr [0x806500], ebx
write((0x806500u),get(3,4,0),4);
}
L463289: { // ffb688010000  push dword ptr [esi + 0x188]
push(read((0x188u+r[6]),4));
}
L46328f: { // e8f829faff  call 0x405c8c
push(0x463294u);dispatch(0x405c8cu);
}
L463294: { // ffb688010000  push dword ptr [esi + 0x188]
push(read((0x188u+r[6]),4));
}
L46329a: { // e86229faff  call 0x405c01
push(0x46329fu);dispatch(0x405c01u);
}
L46329f: { // 8bf8  mov edi, eax
put(7,get(0,4,0),4,0);
}
L4632a1: { // 3bfb  cmp edi, ebx
sub(get(7,4,0),get(3,4,0),4);
}
L4632a3: { // 897dfc  mov dword ptr [ebp - 4], edi
write((0xfffffffcu+r[5]),get(7,4,0),4);
}
L4632a6: { // 752f  jne 0x4632d7
if(condition(1))goto L4632d7;
}
L4632a8: { // 68bb070000  push 0x7bb
push(0x7bbu);
}
L4632ad: { // 6a5c  push 0x5c
push(0x5cu);
}
L4632af: { // 685c285d00  push 0x5d285c
push(0x5d285cu);
}
L4632b4: { // e8b7410300  call 0x497470
push(0x4632b9u);dispatch(0x497470u);
}
L4632b9: { // 59  pop ecx
put(1,pop(),4,0);
}
L4632ba: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L4632bb: { // 59  pop ecx
put(1,pop(),4,0);
}
L4632bc: { // 50  push eax
push(get(0,4,0));
}
L4632bd: { // 6838285d00  push 0x5d2838
push(0x5d2838u);
}
L4632c2: { // 685c604a00  push 0x4a605c
push(0x4a605cu);
}
L4632c7: { // e85ee6f9ff  call 0x40192a
push(0x4632ccu);dispatch(0x40192au);
}
L4632cc: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L4632cf: { // 3bfb  cmp edi, ebx
sub(get(7,4,0),get(3,4,0),4);
}
L4632d1: { // 0f841e070000  je 0x4639f5
if(condition(0))goto L4639f5;
}
L4632d7: { // 53  push ebx
push(get(3,4,0));
}
L4632d8: { // ff35889e6d00  push dword ptr [0x6d9e88]
push(read((0x6d9e88u),4));
}
L4632de: { // 57  push edi
push(get(7,4,0));
}
L4632df: { // ff1590938500  call dword ptr [0x859390]
push(0x4632e5u);dispatch(0x859390u);
}
L4632e5: { // 6a01  push 1
push(0x1u);
}
L4632e7: { // 57  push edi
push(get(7,4,0));
}
L4632e8: { // ff1584938500  call dword ptr [0x859384]
push(0x4632eeu);dispatch(0x859384u);
}
L4632ee: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L4632f0: { // 391d203a8000  cmp dword ptr [0x803a20], ebx
sub(read((0x803a20u),4),get(3,4,0),4);
}
L4632f6: { // 8945f8  mov dword ptr [ebp - 8], eax
write((0xfffffff8u+r[5]),get(0,4,0),4);
}
L4632f9: { // 0f8ed3010000  jle 0x4634d2
if(condition(4))goto L4634d2;
}
L4632ff: { // c745f008000000  mov dword ptr [ebp - 0x10], 8
write((0xfffffff0u+r[5]),0x8u,4);
}
L463306: { // c745f480578000  mov dword ptr [ebp - 0xc], 0x805780
write((0xfffffff4u+r[5]),0x805780u,4);
}
L46330d: { // eb03  jmp 0x463312
goto L463312;
}
L46330f: { // 8b45f8  mov eax, dword ptr [ebp - 8]
put(0,read((0xfffffff8u+r[5]),4),4,0);
}
L463312: { // 8b3c8558225d00  mov edi, dword ptr [eax*4 + 0x5d2258]
put(7,read((0x5d2258u+r[0]*4u),4),4,0);
}
L463319: { // 33c9  xor ecx, ecx
put(1,logic(get(1,4,0)^get(1,4,0),4),4,0);
}
L46331b: { // 390c8540578000  cmp dword ptr [eax*4 + 0x805740], ecx
sub(read((0x805740u+r[0]*4u),4),get(1,4,0),4);
}
L463322: { // 8b5df0  mov ebx, dword ptr [ebp - 0x10]
put(3,read((0xfffffff0u+r[5]),4),4,0);
}
L463325: { // 0f9ec1  setle cl
put(1,condition(4),1,0);
}
L463328: { // 69ffbc000000  imul edi, edi, 0xbc
put(7,multiply(get(7,4,0),0xbcu,4),4,0);
}
L46332e: { // ffb71c7a6000  push dword ptr [edi + 0x607a1c]
push(read((0x607a1cu+r[7]),4));
}
L463334: { // 8bc1  mov eax, ecx
put(0,get(1,4,0),4,0);
}
L463336: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L463338: { // c1e603  shl esi, 3
put(6,shift(get(6,4,0),0x3u,4,0),4,0);
}
L46333b: { // ffb6dc274a00  push dword ptr [esi + 0x4a27dc]
push(read((0x4a27dcu+r[6]),4));
}
L463341: { // ffb6d8274a00  push dword ptr [esi + 0x4a27d8]
push(read((0x4a27d8u+r[6]),4));
}
L463347: { // 6a04  push 4
push(0x4u);
}
L463349: { // 6a0a  push 0xa
push(0xau);
}
L46334b: { // 53  push ebx
push(get(3,4,0));
}
L46334c: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L46334f: { // e88764fdff  call 0x4397db
push(0x463354u);dispatch(0x4397dbu);
}
L463354: { // 83c41c  add esp, 0x1c
put(4,add(get(4,4,0),0x1cu,4,false),4,0);
}
L463357: { // 83c320  add ebx, 0x20
put(3,add(get(3,4,0),0x20u,4,false),4,0);
}
L46335a: { // ffb7307a6000  push dword ptr [edi + 0x607a30]
push(read((0x607a30u+r[7]),4));
}
L463360: { // 8d4328  lea eax, [ebx + 0x28]
put(0,(0x28u+r[3]),4,0);
}
L463363: { // 6830285d00  push 0x5d2830
push(0x5d2830u);
}
L463368: { // ffb6dc274a00  push dword ptr [esi + 0x4a27dc]
push(read((0x4a27dcu+r[6]),4));
}
L46336e: { // ffb6d8274a00  push dword ptr [esi + 0x4a27d8]
push(read((0x4a27d8u+r[6]),4));
}
L463374: { // 6a0a  push 0xa
push(0xau);
}
L463376: { // 6a0a  push 0xa
push(0xau);
}
L463378: { // 50  push eax
push(get(0,4,0));
}
L463379: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L46337c: { // e85a64fdff  call 0x4397db
push(0x463381u);dispatch(0x4397dbu);
}
L463381: { // 83c420  add esp, 0x20
put(4,add(get(4,4,0),0x20u,4,false),4,0);
}
L463384: { // ffb7207a6000  push dword ptr [edi + 0x607a20]
push(read((0x607a20u+r[7]),4));
}
L46338a: { // 6820285d00  push 0x5d2820
push(0x5d2820u);
}
L46338f: { // ffb6dc274a00  push dword ptr [esi + 0x4a27dc]
push(read((0x4a27dcu+r[6]),4));
}
L463395: { // ffb6d8274a00  push dword ptr [esi + 0x4a27d8]
push(read((0x4a27d8u+r[6]),4));
}
L46339b: { // 6a0a  push 0xa
push(0xau);
}
L46339d: { // 6a1e  push 0x1e
push(0x1eu);
}
L46339f: { // ff75f0  push dword ptr [ebp - 0x10]
push(read((0xfffffff0u+r[5]),4));
}
L4633a2: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L4633a5: { // e83164fdff  call 0x4397db
push(0x4633aau);dispatch(0x4397dbu);
}
L4633aa: { // 8b45f8  mov eax, dword ptr [ebp - 8]
put(0,read((0xfffffff8u+r[5]),4),4,0);
}
L4633ad: { // 8b8f207a6000  mov ecx, dword ptr [edi + 0x607a20]
put(1,read((0x607a20u+r[7]),4),4,0);
}
L4633b3: { // 83c420  add esp, 0x20
put(4,add(get(4,4,0),0x20u,4,false),4,0);
}
L4633b6: { // 8b048540578000  mov eax, dword ptr [eax*4 + 0x805740]
put(0,read((0x805740u+r[0]*4u),4),4,0);
}
L4633bd: { // 8945ec  mov dword ptr [ebp - 0x14], eax
write((0xffffffecu+r[5]),get(0,4,0),4);
}
L4633c0: { // 8bc1  mov eax, ecx
put(0,get(1,4,0),4,0);
}
L4633c2: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4633c3: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L4633c5: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L4633c7: { // 3945ec  cmp dword ptr [ebp - 0x14], eax
sub(read((0xffffffecu+r[5]),4),get(0,4,0),4);
}
L4633ca: { // 7e04  jle 0x4633d0
if(condition(4))goto L4633d0;
}
L4633cc: { // 6a03  push 3
push(0x3u);
}
L4633ce: { // eb1b  jmp 0x4633eb
goto L4633eb;
}
L4633d0: { // 8bc1  mov eax, ecx
put(0,get(1,4,0),4,0);
}
L4633d2: { // 6a04  push 4
push(0x4u);
}
L4633d4: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4633d5: { // 59  pop ecx
put(1,pop(),4,0);
}
L4633d6: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L4633d8: { // 8b4df8  mov ecx, dword ptr [ebp - 8]
put(1,read((0xfffffff8u+r[5]),4),4,0);
}
L4633db: { // 8b0c8d40578000  mov ecx, dword ptr [ecx*4 + 0x805740]
put(1,read((0x805740u+r[1]*4u),4),4,0);
}
L4633e2: { // 894dec  mov dword ptr [ebp - 0x14], ecx
write((0xffffffecu+r[5]),get(1,4,0),4);
}
L4633e5: { // 3bc8  cmp ecx, eax
sub(get(1,4,0),get(0,4,0),4);
}
L4633e7: { // 7e05  jle 0x4633ee
if(condition(4))goto L4633ee;
}
L4633e9: { // 6a05  push 5
push(0x5u);
}
L4633eb: { // 58  pop eax
put(0,pop(),4,0);
}
L4633ec: { // eb08  jmp 0x4633f6
goto L4633f6;
}
L4633ee: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L4633f0: { // 85c9  test ecx, ecx
logic(get(1,4,0)&get(1,4,0),4);
}
L4633f2: { // 0f9fc0  setg al
put(0,condition(5),1,0);
}
L4633f5: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L4633f6: { // 8b4dec  mov ecx, dword ptr [ebp - 0x14]
put(1,read((0xffffffecu+r[5]),4),4,0);
}
L4633f9: { // 85c9  test ecx, ecx
logic(get(1,4,0)&get(1,4,0),4);
}
L4633fb: { // 7f02  jg 0x4633ff
if(condition(5))goto L4633ff;
}
L4633fd: { // 33c9  xor ecx, ecx
put(1,logic(get(1,4,0)^get(1,4,0),4),4,0);
}
L4633ff: { // c1e003  shl eax, 3
put(0,shift(get(0,4,0),0x3u,4,0),4,0);
}
L463402: { // 51  push ecx
push(get(1,4,0));
}
L463403: { // 688c345b00  push 0x5b348c
push(0x5b348cu);
}
L463408: { // ffb0dc274a00  push dword ptr [eax + 0x4a27dc]
push(read((0x4a27dcu+r[0]),4));
}
L46340e: { // ffb0d8274a00  push dword ptr [eax + 0x4a27d8]
push(read((0x4a27d8u+r[0]),4));
}
L463414: { // 6a0a  push 0xa
push(0xau);
}
L463416: { // 6a1e  push 0x1e
push(0x1eu);
}
L463418: { // 53  push ebx
push(get(3,4,0));
}
L463419: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L46341c: { // e8ba63fdff  call 0x4397db
push(0x463421u);dispatch(0x4397dbu);
}
L463421: { // 8b87287a6000  mov eax, dword ptr [edi + 0x607a28]
put(0,read((0x607a28u+r[7]),4),4,0);
}
L463427: { // 83c420  add esp, 0x20
put(4,add(get(4,4,0),0x20u,4,false),4,0);
}
L46342a: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L46342c: { // 7e5f  jle 0x46348d
if(condition(4))goto L46348d;
}
L46342e: { // 50  push eax
push(get(0,4,0));
}
L46342f: { // 6810285d00  push 0x5d2810
push(0x5d2810u);
}
L463434: { // ffb6dc274a00  push dword ptr [esi + 0x4a27dc]
push(read((0x4a27dcu+r[6]),4));
}
L46343a: { // ffb6d8274a00  push dword ptr [esi + 0x4a27d8]
push(read((0x4a27d8u+r[6]),4));
}
L463440: { // 6a0a  push 0xa
push(0xau);
}
L463442: { // 6a32  push 0x32
push(0x32u);
}
L463444: { // ff75f0  push dword ptr [ebp - 0x10]
push(read((0xfffffff0u+r[5]),4));
}
L463447: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L46344a: { // e88c63fdff  call 0x4397db
push(0x46344fu);dispatch(0x4397dbu);
}
L46344f: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L463451: { // 8b4df4  mov ecx, dword ptr [ebp - 0xc]
put(1,read((0xfffffff4u+r[5]),4),4,0);
}
L463454: { // 83c420  add esp, 0x20
put(4,add(get(4,4,0),0x20u,4,false),4,0);
}
L463457: { // 3987247a6000  cmp dword ptr [edi + 0x607a24], eax
sub(read((0x607a24u+r[7]),4),get(0,4,0),4);
}
L46345d: { // ff31  push dword ptr [ecx]
push(read((0x0u+r[1]),4));
}
L46345f: { // 0f9ec0  setle al
put(0,condition(4),1,0);
}
L463462: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L463463: { // 688c345b00  push 0x5b348c
push(0x5b348cu);
}
L463468: { // 83e003  and eax, 3
put(0,logic(get(0,4,0)&0x3u,4),4,0);
}
L46346b: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L46346c: { // c1e003  shl eax, 3
put(0,shift(get(0,4,0),0x3u,4,0),4,0);
}
L46346f: { // ffb0dc274a00  push dword ptr [eax + 0x4a27dc]
push(read((0x4a27dcu+r[0]),4));
}
L463475: { // ffb0d8274a00  push dword ptr [eax + 0x4a27d8]
push(read((0x4a27d8u+r[0]),4));
}
L46347b: { // 6a0a  push 0xa
push(0xau);
}
L46347d: { // 6a32  push 0x32
push(0x32u);
}
L46347f: { // 53  push ebx
push(get(3,4,0));
}
L463480: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L463483: { // e85363fdff  call 0x4397db
push(0x463488u);dispatch(0x4397dbu);
}
L463488: { // 83c420  add esp, 0x20
put(4,add(get(4,4,0),0x20u,4,false),4,0);
}
L46348b: { // eb23  jmp 0x4634b0
goto L4634b0;
}
L46348d: { // 68f0345b00  push 0x5b34f0
push(0x5b34f0u);
}
L463492: { // ffb6dc274a00  push dword ptr [esi + 0x4a27dc]
push(read((0x4a27dcu+r[6]),4));
}
L463498: { // ffb6d8274a00  push dword ptr [esi + 0x4a27d8]
push(read((0x4a27d8u+r[6]),4));
}
L46349e: { // 6a0a  push 0xa
push(0xau);
}
L4634a0: { // 6a32  push 0x32
push(0x32u);
}
L4634a2: { // ff75f0  push dword ptr [ebp - 0x10]
push(read((0xfffffff0u+r[5]),4));
}
L4634a5: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L4634a8: { // e82e63fdff  call 0x4397db
push(0x4634adu);dispatch(0x4397dbu);
}
L4634ad: { // 83c41c  add esp, 0x1c
put(4,add(get(4,4,0),0x1cu,4,false),4,0);
}
L4634b0: { // ff45f8  inc dword ptr [ebp - 8]
write((0xfffffff8u+r[5]),inc(read((0xfffffff8u+r[5]),4),4,1),4);
}
L4634b3: { // 8345f404  add dword ptr [ebp - 0xc], 4
write((0xfffffff4u+r[5]),add(read((0xfffffff4u+r[5]),4),0x4u,4,false),4);
}
L4634b7: { // 8b45f8  mov eax, dword ptr [ebp - 8]
put(0,read((0xfffffff8u+r[5]),4),4,0);
}
L4634ba: { // 8145f080000000  add dword ptr [ebp - 0x10], 0x80
write((0xfffffff0u+r[5]),add(read((0xfffffff0u+r[5]),4),0x80u,4,false),4);
}
L4634c1: { // 3b05203a8000  cmp eax, dword ptr [0x803a20]
sub(get(0,4,0),read((0x803a20u),4),4);
}
L4634c7: { // 0f8c42feffff  jl 0x46330f
if(condition(2))goto L46330f;
}
L4634cd: { // 8b7508  mov esi, dword ptr [ebp + 8]
put(6,read((0x8u+r[5]),4),4,0);
}
L4634d0: { // 33db  xor ebx, ebx
put(3,logic(get(3,4,0)^get(3,4,0),4),4,0);
}
L4634d2: { // ff7508  push dword ptr [ebp + 8]
push(read((0x8u+r[5]),4));
}
L4634d5: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L4634d8: { // ff1564938500  call dword ptr [0x859364]
push(0x4634deu);dispatch(0x859364u);
}
L4634de: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L4634e1: { // ffb688010000  push dword ptr [esi + 0x188]
push(read((0x188u+r[6]),4));
}
L4634e7: { // e83427faff  call 0x405c20
push(0x4634ecu);dispatch(0x405c20u);
}
L4634ec: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L4634ee: { // 391d203a8000  cmp dword ptr [0x803a20], ebx
sub(read((0x803a20u),4),get(3,4,0),4);
}
L4634f4: { // 8945f8  mov dword ptr [ebp - 8], eax
write((0xfffffff8u+r[5]),get(0,4,0),4);
}
L4634f7: { // 0f8ef8040000  jle 0x4639f5
if(condition(4))goto L4639f5;
}
L4634fd: { // 6a28  push 0x28
push(0x28u);
}
L4634ff: { // c745fc00578000  mov dword ptr [ebp - 4], 0x805700
write((0xfffffffcu+r[5]),0x805700u,4);
}
L463506: { // 5b  pop ebx
put(3,pop(),4,0);
}
L463507: { // c1e002  shl eax, 2
put(0,shift(get(0,4,0),0x2u,4,0),4,0);
}
L46350a: { // 8bb058225d00  mov esi, dword ptr [eax + 0x5d2258]
put(6,read((0x5d2258u+r[0]),4),4,0);
}
L463510: { // 8bce  mov ecx, esi
put(1,get(6,4,0),4,0);
}
L463512: { // 69c9bc000000  imul ecx, ecx, 0xbc
put(1,multiply(get(1,4,0),0xbcu,4),4,0);
}
L463518: { // 83b9987a600001  cmp dword ptr [ecx + 0x607a98], 1
sub(read((0x607a98u+r[1]),4),0x1u,4);
}
L46351f: { // 0f8e62010000  jle 0x463687
if(condition(4))goto L463687;
}
L463525: { // 8b8038588000  mov eax, dword ptr [eax + 0x805838]
put(0,read((0x805838u+r[0]),4),4,0);
}
L46352b: { // 6a10  push 0x10
push(0x10u);
}
L46352d: { // 5a  pop edx
put(2,pop(),4,0);
}
L46352e: { // 3bc2  cmp eax, edx
sub(get(0,4,0),get(2,4,0),4);
}
L463530: { // 8bca  mov ecx, edx
put(1,get(2,4,0),4,0);
}
L463532: { // 7f02  jg 0x463536
if(condition(5))goto L463536;
}
L463534: { // 8bc8  mov ecx, eax
put(1,get(0,4,0),4,0);
}
L463536: { // 85c9  test ecx, ecx
logic(get(1,4,0)&get(1,4,0),4);
}
L463538: { // 7d04  jge 0x46353e
if(condition(3))goto L46353e;
}
L46353a: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L46353c: { // eb06  jmp 0x463544
goto L463544;
}
L46353e: { // 3bc2  cmp eax, edx
sub(get(0,4,0),get(2,4,0),4);
}
L463540: { // 7e02  jle 0x463544
if(condition(4))goto L463544;
}
L463542: { // 8bc2  mov eax, edx
put(0,get(2,4,0),4,0);
}
L463544: { // 83fe06  cmp esi, 6
sub(get(6,4,0),0x6u,4);
}
L463547: { // 0f8496000000  je 0x4635e3
if(condition(0))goto L4635e3;
}
L46354d: { // 8d048508165b00  lea eax, [eax*4 + 0x5b1608]
put(0,(0x5b1608u+r[0]*4u),4,0);
}
L463554: { // 8db54cffffff  lea esi, [ebp - 0xb4]
put(6,(0xffffff4cu+r[5]),4,0);
}
L46355a: { // 8945f4  mov dword ptr [ebp - 0xc], eax
write((0xfffffff4u+r[5]),get(0,4,0),4);
}
L46355d: { // 8dbdfcfeffff  lea edi, [ebp - 0x104]
put(7,(0xfffffefcu+r[5]),4,0);
}
L463563: { // 8b00  mov eax, dword ptr [eax]
put(0,read((0x0u+r[0]),4),4,0);
}
L463565: { // c78550ffffff20000000  mov dword ptr [ebp - 0xb0], 0x20
write((0xffffff50u+r[5]),0x20u,4);
}
L46356f: { // 89854cffffff  mov dword ptr [ebp - 0xb4], eax
write((0xffffff4cu+r[5]),get(0,4,0),4);
}
L463575: { // c78554ffffff50000000  mov dword ptr [ebp - 0xac], 0x50
write((0xffffff54u+r[5]),0x50u,4);
}
L46357f: { // c78558ffffff30000000  mov dword ptr [ebp - 0xa8], 0x30
write((0xffffff58u+r[5]),0x30u,4);
}
L463589: { // 8d8dfcfeffff  lea ecx, [ebp - 0x104]
put(1,(0xfffffefcu+r[5]),4,0);
}
L46358f: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463590: { // 6a00  push 0
push(0x0u);
}
L463592: { // 51  push ecx
push(get(1,4,0));
}
L463593: { // ff35d8357700  push dword ptr [0x7735d8]
push(read((0x7735d8u),4));
}
L463599: { // 03c3  add eax, ebx
put(0,add(get(0,4,0),get(3,4,0),4,false),4,0);
}
L46359b: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L46359c: { // 6a2a  push 0x2a
push(0x2au);
}
L46359e: { // 50  push eax
push(get(0,4,0));
}
L46359f: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L4635a2: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4635a3: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L4635a9: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4635aa: { // e80428faff  call 0x405db3
push(0x4635afu);dispatch(0x405db3u);
}
L4635af: { // 8b45f4  mov eax, dword ptr [ebp - 0xc]
put(0,read((0xfffffff4u+r[5]),4),4,0);
}
L4635b2: { // 8365bc00  and dword ptr [ebp - 0x44], 0
write((0xffffffbcu+r[5]),logic(read((0xffffffbcu+r[5]),4)&0x0u,4),4);
}
L4635b6: { // 8d75bc  lea esi, [ebp - 0x44]
put(6,(0xffffffbcu+r[5]),4,0);
}
L4635b9: { // 8dbddcfeffff  lea edi, [ebp - 0x124]
put(7,(0xfffffedcu+r[5]),4,0);
}
L4635bf: { // 8b00  mov eax, dword ptr [eax]
put(0,read((0x0u+r[0]),4),4,0);
}
L4635c1: { // c745c030000000  mov dword ptr [ebp - 0x40], 0x30
write((0xffffffc0u+r[5]),0x30u,4);
}
L4635c8: { // 8945c4  mov dword ptr [ebp - 0x3c], eax
write((0xffffffc4u+r[5]),get(0,4,0),4);
}
L4635cb: { // c745c840000000  mov dword ptr [ebp - 0x38], 0x40
write((0xffffffc8u+r[5]),0x40u,4);
}
L4635d2: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4635d3: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4635d4: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4635d5: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4635d6: { // 6a00  push 0
push(0x0u);
}
L4635d8: { // 8d85dcfeffff  lea eax, [ebp - 0x124]
put(0,(0xfffffedcu+r[5]),4,0);
}
L4635de: { // e98c000000  jmp 0x46366f
goto L46366f;
}
L4635e3: { // 8d048550165b00  lea eax, [eax*4 + 0x5b1650]
put(0,(0x5b1650u+r[0]*4u),4,0);
}
L4635ea: { // 6a20  push 0x20
push(0x20u);
}
L4635ec: { // 8945f4  mov dword ptr [ebp - 0xc], eax
write((0xfffffff4u+r[5]),get(0,4,0),4);
}
L4635ef: { // 59  pop ecx
put(1,pop(),4,0);
}
L4635f0: { // 8b00  mov eax, dword ptr [eax]
put(0,read((0x0u+r[0]),4),4,0);
}
L4635f2: { // 8db55cffffff  lea esi, [ebp - 0xa4]
put(6,(0xffffff5cu+r[5]),4,0);
}
L4635f8: { // 8dbd7cfeffff  lea edi, [ebp - 0x184]
put(7,(0xfffffe7cu+r[5]),4,0);
}
L4635fe: { // 89855cffffff  mov dword ptr [ebp - 0xa4], eax
write((0xffffff5cu+r[5]),get(0,4,0),4);
}
L463604: { // 898d60ffffff  mov dword ptr [ebp - 0xa0], ecx
write((0xffffff60u+r[5]),get(1,4,0),4);
}
L46360a: { // 898d64ffffff  mov dword ptr [ebp - 0x9c], ecx
write((0xffffff64u+r[5]),get(1,4,0),4);
}
L463610: { // c78568ffffff30000000  mov dword ptr [ebp - 0x98], 0x30
write((0xffffff68u+r[5]),0x30u,4);
}
L46361a: { // 8d8d7cfeffff  lea ecx, [ebp - 0x184]
put(1,(0xfffffe7cu+r[5]),4,0);
}
L463620: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463621: { // 6a00  push 0
push(0x0u);
}
L463623: { // 51  push ecx
push(get(1,4,0));
}
L463624: { // ff35d8357700  push dword ptr [0x7735d8]
push(read((0x7735d8u),4));
}
L46362a: { // 03c3  add eax, ebx
put(0,add(get(0,4,0),get(3,4,0),4,false),4,0);
}
L46362c: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L46362d: { // 6a2a  push 0x2a
push(0x2au);
}
L46362f: { // 50  push eax
push(get(0,4,0));
}
L463630: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L463633: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463634: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L46363a: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L46363b: { // e87327faff  call 0x405db3
push(0x463640u);dispatch(0x405db3u);
}
L463640: { // 8b45f4  mov eax, dword ptr [ebp - 0xc]
put(0,read((0xfffffff4u+r[5]),4),4,0);
}
L463643: { // 83659c00  and dword ptr [ebp - 0x64], 0
write((0xffffff9cu+r[5]),logic(read((0xffffff9cu+r[5]),4)&0x0u,4),4);
}
L463647: { // 8d759c  lea esi, [ebp - 0x64]
put(6,(0xffffff9cu+r[5]),4,0);
}
L46364a: { // 8dbdbcfeffff  lea edi, [ebp - 0x144]
put(7,(0xfffffebcu+r[5]),4,0);
}
L463650: { // 8b00  mov eax, dword ptr [eax]
put(0,read((0x0u+r[0]),4),4,0);
}
L463652: { // c745a030000000  mov dword ptr [ebp - 0x60], 0x30
write((0xffffffa0u+r[5]),0x30u,4);
}
L463659: { // 8945a4  mov dword ptr [ebp - 0x5c], eax
write((0xffffffa4u+r[5]),get(0,4,0),4);
}
L46365c: { // c745a840000000  mov dword ptr [ebp - 0x58], 0x40
write((0xffffffa8u+r[5]),0x40u,4);
}
L463663: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463664: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463665: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463666: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463667: { // 6a00  push 0
push(0x0u);
}
L463669: { // 8d85bcfeffff  lea eax, [ebp - 0x144]
put(0,(0xfffffebcu+r[5]),4,0);
}
L46366f: { // 50  push eax
push(get(0,4,0));
}
L463670: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L463673: { // ff35d8357700  push dword ptr [0x7735d8]
push(read((0x7735d8u),4));
}
L463679: { // 6a2a  push 0x2a
push(0x2au);
}
L46367b: { // 53  push ebx
push(get(3,4,0));
}
L46367c: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L463682: { // e82c27faff  call 0x405db3
push(0x463687u);dispatch(0x405db3u);
}
L463687: { // 8b45fc  mov eax, dword ptr [ebp - 4]
put(0,read((0xfffffffcu+r[5]),4),4,0);
}
L46368a: { // f6400101  test byte ptr [eax + 1], 1
logic(read((0x1u+r[0]),1)&0x1u,1);
}
L46368e: { // 7458  je 0x4636e8
if(condition(0))goto L4636e8;
}
L463690: { // 83a51cffffff00  and dword ptr [ebp - 0xe4], 0
write((0xffffff1cu+r[5]),logic(read((0xffffff1cu+r[5]),4)&0x0u,4),4);
}
L463697: { // 8db51cffffff  lea esi, [ebp - 0xe4]
put(6,(0xffffff1cu+r[5]),4,0);
}
L46369d: { // 8dbd3cfeffff  lea edi, [ebp - 0x1c4]
put(7,(0xfffffe3cu+r[5]),4,0);
}
L4636a3: { // c78520ffffff40000000  mov dword ptr [ebp - 0xe0], 0x40
write((0xffffff20u+r[5]),0x40u,4);
}
L4636ad: { // c78524ffffff10000000  mov dword ptr [ebp - 0xdc], 0x10
write((0xffffff24u+r[5]),0x10u,4);
}
L4636b7: { // c78528ffffff50000000  mov dword ptr [ebp - 0xd8], 0x50
write((0xffffff28u+r[5]),0x50u,4);
}
L4636c1: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4636c2: { // 8d853cfeffff  lea eax, [ebp - 0x1c4]
put(0,(0xfffffe3cu+r[5]),4,0);
}
L4636c8: { // 6a00  push 0
push(0x0u);
}
L4636ca: { // 50  push eax
push(get(0,4,0));
}
L4636cb: { // 8d43d8  lea eax, [ebx - 0x28]
put(0,(0xffffffd8u+r[3]),4,0);
}
L4636ce: { // ff35d8357700  push dword ptr [0x7735d8]
push(read((0x7735d8u),4));
}
L4636d4: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4636d5: { // 6a3e  push 0x3e
push(0x3eu);
}
L4636d7: { // 50  push eax
push(get(0,4,0));
}
L4636d8: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L4636db: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4636dc: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L4636e2: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4636e3: { // e8cb26faff  call 0x405db3
push(0x4636e8u);dispatch(0x405db3u);
}
L4636e8: { // 8b45fc  mov eax, dword ptr [ebp - 4]
put(0,read((0xfffffffcu+r[5]),4),4,0);
}
L4636eb: { // f6400102  test byte ptr [eax + 1], 2
logic(read((0x1u+r[0]),1)&0x2u,1);
}
L4636ef: { // 7452  je 0x463743
if(condition(0))goto L463743;
}
L4636f1: { // 8db57cffffff  lea esi, [ebp - 0x84]
put(6,(0xffffff7cu+r[5]),4,0);
}
L4636f7: { // 8dbd9cfeffff  lea edi, [ebp - 0x164]
put(7,(0xfffffe9cu+r[5]),4,0);
}
L4636fd: { // c7857cffffff10000000  mov dword ptr [ebp - 0x84], 0x10
write((0xffffff7cu+r[5]),0x10u,4);
}
L463707: { // c7458040000000  mov dword ptr [ebp - 0x80], 0x40
write((0xffffff80u+r[5]),0x40u,4);
}
L46370e: { // c7458420000000  mov dword ptr [ebp - 0x7c], 0x20
write((0xffffff84u+r[5]),0x20u,4);
}
L463715: { // c7458850000000  mov dword ptr [ebp - 0x78], 0x50
write((0xffffff88u+r[5]),0x50u,4);
}
L46371c: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L46371d: { // 8d859cfeffff  lea eax, [ebp - 0x164]
put(0,(0xfffffe9cu+r[5]),4,0);
}
L463723: { // 6a00  push 0
push(0x0u);
}
L463725: { // 50  push eax
push(get(0,4,0));
}
L463726: { // 8d43e8  lea eax, [ebx - 0x18]
put(0,(0xffffffe8u+r[3]),4,0);
}
L463729: { // ff35d8357700  push dword ptr [0x7735d8]
push(read((0x7735d8u),4));
}
L46372f: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463730: { // 6a3e  push 0x3e
push(0x3eu);
}
L463732: { // 50  push eax
push(get(0,4,0));
}
L463733: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L463736: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463737: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L46373d: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L46373e: { // e87026faff  call 0x405db3
push(0x463743u);dispatch(0x405db3u);
}
L463743: { // 8b45fc  mov eax, dword ptr [ebp - 4]
put(0,read((0xfffffffcu+r[5]),4),4,0);
}
L463746: { // f6400104  test byte ptr [eax + 1], 4
logic(read((0x1u+r[0]),1)&0x4u,1);
}
L46374a: { // 745b  je 0x4637a7
if(condition(0))goto L4637a7;
}
L46374c: { // 8db53cffffff  lea esi, [ebp - 0xc4]
put(6,(0xffffff3cu+r[5]),4,0);
}
L463752: { // 8dbd5cfeffff  lea edi, [ebp - 0x1a4]
put(7,(0xfffffe5cu+r[5]),4,0);
}
L463758: { // c7853cffffff20000000  mov dword ptr [ebp - 0xc4], 0x20
write((0xffffff3cu+r[5]),0x20u,4);
}
L463762: { // c78540ffffff40000000  mov dword ptr [ebp - 0xc0], 0x40
write((0xffffff40u+r[5]),0x40u,4);
}
L46376c: { // c78544ffffff30000000  mov dword ptr [ebp - 0xbc], 0x30
write((0xffffff44u+r[5]),0x30u,4);
}
L463776: { // c78548ffffff50000000  mov dword ptr [ebp - 0xb8], 0x50
write((0xffffff48u+r[5]),0x50u,4);
}
L463780: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463781: { // 8d855cfeffff  lea eax, [ebp - 0x1a4]
put(0,(0xfffffe5cu+r[5]),4,0);
}
L463787: { // 6a00  push 0
push(0x0u);
}
L463789: { // 50  push eax
push(get(0,4,0));
}
L46378a: { // 8d43f8  lea eax, [ebx - 8]
put(0,(0xfffffff8u+r[3]),4,0);
}
L46378d: { // ff35d8357700  push dword ptr [0x7735d8]
push(read((0x7735d8u),4));
}
L463793: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463794: { // 6a3e  push 0x3e
push(0x3eu);
}
L463796: { // 50  push eax
push(get(0,4,0));
}
L463797: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L46379a: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L46379b: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L4637a1: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4637a2: { // e80c26faff  call 0x405db3
push(0x4637a7u);dispatch(0x405db3u);
}
L4637a7: { // 8b45fc  mov eax, dword ptr [ebp - 4]
put(0,read((0xfffffffcu+r[5]),4),4,0);
}
L4637aa: { // f6400108  test byte ptr [eax + 1], 8
logic(read((0x1u+r[0]),1)&0x8u,1);
}
L4637ae: { // 7447  je 0x4637f7
if(condition(0))goto L4637f7;
}
L4637b0: { // 6a40  push 0x40
push(0x40u);
}
L4637b2: { // 8d75cc  lea esi, [ebp - 0x34]
put(6,(0xffffffccu+r[5]),4,0);
}
L4637b5: { // 58  pop eax
put(0,pop(),4,0);
}
L4637b6: { // 8dbdecfeffff  lea edi, [ebp - 0x114]
put(7,(0xfffffeecu+r[5]),4,0);
}
L4637bc: { // c745cc30000000  mov dword ptr [ebp - 0x34], 0x30
write((0xffffffccu+r[5]),0x30u,4);
}
L4637c3: { // 8945d0  mov dword ptr [ebp - 0x30], eax
write((0xffffffd0u+r[5]),get(0,4,0),4);
}
L4637c6: { // 8945d4  mov dword ptr [ebp - 0x2c], eax
write((0xffffffd4u+r[5]),get(0,4,0),4);
}
L4637c9: { // c745d850000000  mov dword ptr [ebp - 0x28], 0x50
write((0xffffffd8u+r[5]),0x50u,4);
}
L4637d0: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4637d1: { // 8d85ecfeffff  lea eax, [ebp - 0x114]
put(0,(0xfffffeecu+r[5]),4,0);
}
L4637d7: { // 6a00  push 0
push(0x0u);
}
L4637d9: { // 50  push eax
push(get(0,4,0));
}
L4637da: { // 8d4308  lea eax, [ebx + 8]
put(0,(0x8u+r[3]),4,0);
}
L4637dd: { // ff35d8357700  push dword ptr [0x7735d8]
push(read((0x7735d8u),4));
}
L4637e3: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4637e4: { // 6a3e  push 0x3e
push(0x3eu);
}
L4637e6: { // 50  push eax
push(get(0,4,0));
}
L4637e7: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L4637ea: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4637eb: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L4637f1: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4637f2: { // e8bc25faff  call 0x405db3
push(0x4637f7u);dispatch(0x405db3u);
}
L4637f7: { // 8b45fc  mov eax, dword ptr [ebp - 4]
put(0,read((0xfffffffcu+r[5]),4),4,0);
}
L4637fa: { // 8b00  mov eax, dword ptr [eax]
put(0,read((0x0u+r[0]),4),4,0);
}
L4637fc: { // f6c410  test ah, 0x10
logic(get(0,1,8)&0x10u,1);
}
L4637ff: { // 7429  je 0x46382a
if(condition(0))goto L46382a;
}
L463801: { // 6a40  push 0x40
push(0x40u);
}
L463803: { // 8d75ac  lea esi, [ebp - 0x54]
put(6,(0xffffffacu+r[5]),4,0);
}
L463806: { // 58  pop eax
put(0,pop(),4,0);
}
L463807: { // 8dbdccfeffff  lea edi, [ebp - 0x134]
put(7,(0xfffffeccu+r[5]),4,0);
}
L46380d: { // 6a50  push 0x50
push(0x50u);
}
L46380f: { // 8945ac  mov dword ptr [ebp - 0x54], eax
write((0xffffffacu+r[5]),get(0,4,0),4);
}
L463812: { // 8945b0  mov dword ptr [ebp - 0x50], eax
write((0xffffffb0u+r[5]),get(0,4,0),4);
}
L463815: { // 58  pop eax
put(0,pop(),4,0);
}
L463816: { // 8945b4  mov dword ptr [ebp - 0x4c], eax
write((0xffffffb4u+r[5]),get(0,4,0),4);
}
L463819: { // 8945b8  mov dword ptr [ebp - 0x48], eax
write((0xffffffb8u+r[5]),get(0,4,0),4);
}
L46381c: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L46381d: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L46381e: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L46381f: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463820: { // 6a00  push 0
push(0x0u);
}
L463822: { // 8d85ccfeffff  lea eax, [ebp - 0x134]
put(0,(0xfffffeccu+r[5]),4,0);
}
L463828: { // eb31  jmp 0x46385b
goto L46385b;
}
L46382a: { // f6c420  test ah, 0x20
logic(get(0,1,8)&0x20u,1);
}
L46382d: { // 7447  je 0x463876
if(condition(0))goto L463876;
}
L46382f: { // 6a50  push 0x50
push(0x50u);
}
L463831: { // 8d758c  lea esi, [ebp - 0x74]
put(6,(0xffffff8cu+r[5]),4,0);
}
L463834: { // 58  pop eax
put(0,pop(),4,0);
}
L463835: { // 8dbdacfeffff  lea edi, [ebp - 0x154]
put(7,(0xfffffeacu+r[5]),4,0);
}
L46383b: { // 89458c  mov dword ptr [ebp - 0x74], eax
write((0xffffff8cu+r[5]),get(0,4,0),4);
}
L46383e: { // c7459040000000  mov dword ptr [ebp - 0x70], 0x40
write((0xffffff90u+r[5]),0x40u,4);
}
L463845: { // c7459460000000  mov dword ptr [ebp - 0x6c], 0x60
write((0xffffff94u+r[5]),0x60u,4);
}
L46384c: { // 894598  mov dword ptr [ebp - 0x68], eax
write((0xffffff98u+r[5]),get(0,4,0),4);
}
L46384f: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463850: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463851: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463852: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463853: { // 6a00  push 0
push(0x0u);
}
L463855: { // 8d85acfeffff  lea eax, [ebp - 0x154]
put(0,(0xfffffeacu+r[5]),4,0);
}
L46385b: { // 50  push eax
push(get(0,4,0));
}
L46385c: { // 8d4318  lea eax, [ebx + 0x18]
put(0,(0x18u+r[3]),4,0);
}
L46385f: { // ff35d8357700  push dword ptr [0x7735d8]
push(read((0x7735d8u),4));
}
L463865: { // 6a3e  push 0x3e
push(0x3eu);
}
L463867: { // 50  push eax
push(get(0,4,0));
}
L463868: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L46386b: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L463871: { // e83d25faff  call 0x405db3
push(0x463876u);dispatch(0x405db3u);
}
L463876: { // 8b45fc  mov eax, dword ptr [ebp - 4]
put(0,read((0xfffffffcu+r[5]),4),4,0);
}
L463879: { // 8b00  mov eax, dword ptr [eax]
put(0,read((0x0u+r[0]),4),4,0);
}
L46387b: { // f6c480  test ah, 0x80
logic(get(0,1,8)&0x80u,1);
}
L46387e: { // 7442  je 0x4638c2
if(condition(0))goto L4638c2;
}
L463880: { // 8db56cffffff  lea esi, [ebp - 0x94]
put(6,(0xffffff6cu+r[5]),4,0);
}
L463886: { // 8dbd8cfeffff  lea edi, [ebp - 0x174]
put(7,(0xfffffe8cu+r[5]),4,0);
}
L46388c: { // c7856cffffff70000000  mov dword ptr [ebp - 0x94], 0x70
write((0xffffff6cu+r[5]),0x70u,4);
}
L463896: { // c78570ffffff40000000  mov dword ptr [ebp - 0x90], 0x40
write((0xffffff70u+r[5]),0x40u,4);
}
L4638a0: { // c78574ffffff80000000  mov dword ptr [ebp - 0x8c], 0x80
write((0xffffff74u+r[5]),0x80u,4);
}
L4638aa: { // c78578ffffff50000000  mov dword ptr [ebp - 0x88], 0x50
write((0xffffff78u+r[5]),0x50u,4);
}
L4638b4: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4638b5: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4638b6: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4638b7: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4638b8: { // 6a00  push 0
push(0x0u);
}
L4638ba: { // 8d858cfeffff  lea eax, [ebp - 0x174]
put(0,(0xfffffe8cu+r[5]),4,0);
}
L4638c0: { // eb36  jmp 0x4638f8
goto L4638f8;
}
L4638c2: { // f6c440  test ah, 0x40
logic(get(0,1,8)&0x40u,1);
}
L4638c5: { // 744c  je 0x463913
if(condition(0))goto L463913;
}
L4638c7: { // 8d75dc  lea esi, [ebp - 0x24]
put(6,(0xffffffdcu+r[5]),4,0);
}
L4638ca: { // 8dbd6cfeffff  lea edi, [ebp - 0x194]
put(7,(0xfffffe6cu+r[5]),4,0);
}
L4638d0: { // c745dc60000000  mov dword ptr [ebp - 0x24], 0x60
write((0xffffffdcu+r[5]),0x60u,4);
}
L4638d7: { // c745e040000000  mov dword ptr [ebp - 0x20], 0x40
write((0xffffffe0u+r[5]),0x40u,4);
}
L4638de: { // c745e470000000  mov dword ptr [ebp - 0x1c], 0x70
write((0xffffffe4u+r[5]),0x70u,4);
}
L4638e5: { // c745e850000000  mov dword ptr [ebp - 0x18], 0x50
write((0xffffffe8u+r[5]),0x50u,4);
}
L4638ec: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4638ed: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4638ee: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4638ef: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4638f0: { // 6a00  push 0
push(0x0u);
}
L4638f2: { // 8d856cfeffff  lea eax, [ebp - 0x194]
put(0,(0xfffffe6cu+r[5]),4,0);
}
L4638f8: { // 50  push eax
push(get(0,4,0));
}
L4638f9: { // 8d4328  lea eax, [ebx + 0x28]
put(0,(0x28u+r[3]),4,0);
}
L4638fc: { // ff35d8357700  push dword ptr [0x7735d8]
push(read((0x7735d8u),4));
}
L463902: { // 6a3e  push 0x3e
push(0x3eu);
}
L463904: { // 50  push eax
push(get(0,4,0));
}
L463905: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L463908: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L46390e: { // e8a024faff  call 0x405db3
push(0x463913u);dispatch(0x405db3u);
}
L463913: { // 8b45fc  mov eax, dword ptr [ebp - 4]
put(0,read((0xfffffffcu+r[5]),4),4,0);
}
L463916: { // f6400201  test byte ptr [eax + 2], 1
logic(read((0x2u+r[0]),1)&0x1u,1);
}
L46391a: { // 7458  je 0x463974
if(condition(0))goto L463974;
}
L46391c: { // 83a52cffffff00  and dword ptr [ebp - 0xd4], 0
write((0xffffff2cu+r[5]),logic(read((0xffffff2cu+r[5]),4)&0x0u,4),4);
}
L463923: { // 8db52cffffff  lea esi, [ebp - 0xd4]
put(6,(0xffffff2cu+r[5]),4,0);
}
L463929: { // 8dbd4cfeffff  lea edi, [ebp - 0x1b4]
put(7,(0xfffffe4cu+r[5]),4,0);
}
L46392f: { // c78530ffffff50000000  mov dword ptr [ebp - 0xd0], 0x50
write((0xffffff30u+r[5]),0x50u,4);
}
L463939: { // c78534ffffff10000000  mov dword ptr [ebp - 0xcc], 0x10
write((0xffffff34u+r[5]),0x10u,4);
}
L463943: { // c78538ffffff60000000  mov dword ptr [ebp - 0xc8], 0x60
write((0xffffff38u+r[5]),0x60u,4);
}
L46394d: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L46394e: { // 8d854cfeffff  lea eax, [ebp - 0x1b4]
put(0,(0xfffffe4cu+r[5]),4,0);
}
L463954: { // 6a00  push 0
push(0x0u);
}
L463956: { // 50  push eax
push(get(0,4,0));
}
L463957: { // 8d4338  lea eax, [ebx + 0x38]
put(0,(0x38u+r[3]),4,0);
}
L46395a: { // ff35d8357700  push dword ptr [0x7735d8]
push(read((0x7735d8u),4));
}
L463960: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463961: { // 6a3e  push 0x3e
push(0x3eu);
}
L463963: { // 50  push eax
push(get(0,4,0));
}
L463964: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L463967: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463968: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L46396e: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L46396f: { // e83f24faff  call 0x405db3
push(0x463974u);dispatch(0x405db3u);
}
L463974: { // 8b45fc  mov eax, dword ptr [ebp - 4]
put(0,read((0xfffffffcu+r[5]),4),4,0);
}
L463977: { // f6400202  test byte ptr [eax + 2], 2
logic(read((0x2u+r[0]),1)&0x2u,1);
}
L46397b: { // 745b  je 0x4639d8
if(condition(0))goto L4639d8;
}
L46397d: { // 8db50cffffff  lea esi, [ebp - 0xf4]
put(6,(0xffffff0cu+r[5]),4,0);
}
L463983: { // 8dbd2cfeffff  lea edi, [ebp - 0x1d4]
put(7,(0xfffffe2cu+r[5]),4,0);
}
L463989: { // c7850cffffff10000000  mov dword ptr [ebp - 0xf4], 0x10
write((0xffffff0cu+r[5]),0x10u,4);
}
L463993: { // c78510ffffff50000000  mov dword ptr [ebp - 0xf0], 0x50
write((0xffffff10u+r[5]),0x50u,4);
}
L46399d: { // c78514ffffff20000000  mov dword ptr [ebp - 0xec], 0x20
write((0xffffff14u+r[5]),0x20u,4);
}
L4639a7: { // c78518ffffff60000000  mov dword ptr [ebp - 0xe8], 0x60
write((0xffffff18u+r[5]),0x60u,4);
}
L4639b1: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4639b2: { // 8d852cfeffff  lea eax, [ebp - 0x1d4]
put(0,(0xfffffe2cu+r[5]),4,0);
}
L4639b8: { // 6a00  push 0
push(0x0u);
}
L4639ba: { // 50  push eax
push(get(0,4,0));
}
L4639bb: { // 8d4348  lea eax, [ebx + 0x48]
put(0,(0x48u+r[3]),4,0);
}
L4639be: { // ff35d8357700  push dword ptr [0x7735d8]
push(read((0x7735d8u),4));
}
L4639c4: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4639c5: { // 6a3e  push 0x3e
push(0x3eu);
}
L4639c7: { // 50  push eax
push(get(0,4,0));
}
L4639c8: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L4639cb: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4639cc: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L4639d2: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4639d3: { // e8db23faff  call 0x405db3
push(0x4639d8u);dispatch(0x405db3u);
}
L4639d8: { // 8b45f8  mov eax, dword ptr [ebp - 8]
put(0,read((0xfffffff8u+r[5]),4),4,0);
}
L4639db: { // 8345fc04  add dword ptr [ebp - 4], 4
write((0xfffffffcu+r[5]),add(read((0xfffffffcu+r[5]),4),0x4u,4,false),4);
}
L4639df: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L4639e0: { // 81c380000000  add ebx, 0x80
put(3,add(get(3,4,0),0x80u,4,false),4,0);
}
L4639e6: { // 3b05203a8000  cmp eax, dword ptr [0x803a20]
sub(get(0,4,0),read((0x803a20u),4),4);
}
L4639ec: { // 8945f8  mov dword ptr [ebp - 8], eax
write((0xfffffff8u+r[5]),get(0,4,0),4);
}
L4639ef: { // 0f8c12fbffff  jl 0x463507
if(condition(2))goto L463507;
}
L4639f5: { // 5f  pop edi
put(7,pop(),4,0);
}
L4639f6: { // 5e  pop esi
put(6,pop(),4,0);
}
L4639f7: { // 5b  pop ebx
put(3,pop(),4,0);
}
L4639f8: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L4639f9: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 004639fc_party_status_panel_tick_mc_4639fc
void RecoveredBattle::fn_4639fc(){
goto L4639fc;
L4639fc: { // 55  push ebp
push(get(5,4,0));
}
L4639fd: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L4639ff: { // 83ec20  sub esp, 0x20
put(4,sub(get(4,4,0),0x20u,4,false),4,0);
}
L463a02: { // 53  push ebx
push(get(3,4,0));
}
L463a03: { // 8b5d08  mov ebx, dword ptr [ebp + 8]
put(3,read((0x8u+r[5]),4),4,0);
}
L463a06: { // 56  push esi
push(get(6,4,0));
}
L463a07: { // 57  push edi
push(get(7,4,0));
}
L463a08: { // 8b4320  mov eax, dword ptr [ebx + 0x20]
put(0,read((0x20u+r[3]),4),4,0);
}
L463a0b: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L463a0c: { // 0f8476010000  je 0x463b88
if(condition(0))goto L463b88;
}
L463a12: { // 83e809  sub eax, 9
put(0,sub(get(0,4,0),0x9u,4,false),4,0);
}
L463a15: { // 0f8433010000  je 0x463b4e
if(condition(0))goto L463b4e;
}
L463a1b: { // 6a0a  push 0xa
push(0xau);
}
L463a1d: { // 5f  pop edi
put(7,pop(),4,0);
}
L463a1e: { // 2bc7  sub eax, edi
put(0,sub(get(0,4,0),get(7,4,0),4,false),4,0);
}
L463a20: { // 0f84aa000000  je 0x463ad0
if(condition(0))goto L463ad0;
}
L463a26: { // 6a50  push 0x50
push(0x50u);
}
L463a28: { // 59  pop ecx
put(1,pop(),4,0);
}
L463a29: { // 2bc1  sub eax, ecx
put(0,sub(get(0,4,0),get(1,4,0),4,false),4,0);
}
L463a2b: { // 747c  je 0x463aa9
if(condition(0))goto L463aa9;
}
L463a2d: { // 2bc7  sub eax, edi
put(0,sub(get(0,4,0),get(7,4,0),4,false),4,0);
}
L463a2f: { // 7447  je 0x463a78
if(condition(0))goto L463a78;
}
L463a31: { // 2bc7  sub eax, edi
put(0,sub(get(0,4,0),get(7,4,0),4,false),4,0);
}
L463a33: { // 7410  je 0x463a45
if(condition(0))goto L463a45;
}
L463a35: { // 2bc1  sub eax, ecx
put(0,sub(get(0,4,0),get(1,4,0),4,false),4,0);
}
L463a37: { // 0f8552010000  jne 0x463b8f
if(condition(1))goto L463b8f;
}
L463a3d: { // 53  push ebx
push(get(3,4,0));
}
L463a3e: { // e815f8ffff  call 0x463258
push(0x463a43u);dispatch(0x463258u);
}
L463a43: { // eb7f  jmp 0x463ac4
goto L463ac4;
}
L463a45: { // 83836c010000fc  add dword ptr [ebx + 0x16c], -4
write((0x16cu+r[3]),add(read((0x16cu+r[3]),4),0xfffffffcu,4,false),4);
}
L463a4c: { // 83bb6c01000000  cmp dword ptr [ebx + 0x16c], 0
sub(read((0x16cu+r[3]),4),0x0u,4);
}
L463a53: { // 8db36c010000  lea esi, [ebx + 0x16c]
put(6,(0x16cu+r[3]),4,0);
}
L463a59: { // 0f8f30010000  jg 0x463b8f
if(condition(5))goto L463b8f;
}
L463a5f: { // 8d8388010000  lea eax, [ebx + 0x188]
put(0,(0x188u+r[3]),4,0);
}
L463a65: { // 6a01  push 1
push(0x1u);
}
L463a67: { // 50  push eax
push(get(0,4,0));
}
L463a68: { // e8a525faff  call 0x406012
push(0x463a6du);dispatch(0x406012u);
}
L463a6d: { // 832600  and dword ptr [esi], 0
write((0x0u+r[6]),logic(read((0x0u+r[6]),4)&0x0u,4),4);
}
L463a70: { // 897b20  mov dword ptr [ebx + 0x20], edi
write((0x20u+r[3]),get(7,4,0),4);
}
L463a73: { // e917010000  jmp 0x463b8f
goto L463b8f;
}
L463a78: { // 53  push ebx
push(get(3,4,0));
}
L463a79: { // e8daf7ffff  call 0x463258
push(0x463a7eu);dispatch(0x463258u);
}
L463a7e: { // 833d5c46800009  cmp dword ptr [0x80465c], 9
sub(read((0x80465cu),4),0x9u,4);
}
L463a85: { // 7516  jne 0x463a9d
if(condition(1))goto L463a9d;
}
L463a87: { // 833da0e5770001  cmp dword ptr [0x77e5a0], 1
sub(read((0x77e5a0u),4),0x1u,4);
}
L463a8e: { // 750d  jne 0x463a9d
if(condition(1))goto L463a9d;
}
L463a90: { // 833d0c30770000  cmp dword ptr [0x77300c], 0
sub(read((0x77300cu),4),0x0u,4);
}
L463a97: { // 0f85f2000000  jne 0x463b8f
if(condition(1))goto L463b8f;
}
L463a9d: { // c7432078000000  mov dword ptr [ebx + 0x20], 0x78
write((0x20u+r[3]),0x78u,4);
}
L463aa4: { // e9e6000000  jmp 0x463b8f
goto L463b8f;
}
L463aa9: { // 83836c01000004  add dword ptr [ebx + 0x16c], 4
write((0x16cu+r[3]),add(read((0x16cu+r[3]),4),0x4u,4,false),4);
}
L463ab0: { // 398b6c010000  cmp dword ptr [ebx + 0x16c], ecx
sub(read((0x16cu+r[3]),4),get(1,4,0),4);
}
L463ab6: { // 8d836c010000  lea eax, [ebx + 0x16c]
put(0,(0x16cu+r[3]),4,0);
}
L463abc: { // 0f8ccd000000  jl 0x463b8f
if(condition(2))goto L463b8f;
}
L463ac2: { // 8908  mov dword ptr [eax], ecx
write((0x0u+r[0]),get(1,4,0),4);
}
L463ac4: { // c743206e000000  mov dword ptr [ebx + 0x20], 0x6e
write((0x20u+r[3]),0x6eu,4);
}
L463acb: { // e9bf000000  jmp 0x463b8f
goto L463b8f;
}
L463ad0: { // 8b15203a8000  mov edx, dword ptr [0x803a20]
put(2,read((0x803a20u),4),4,0);
}
L463ad6: { // 83650800  and dword ptr [ebp + 8], 0
write((0x8u+r[5]),logic(read((0x8u+r[5]),4)&0x0u,4),4);
}
L463ada: { // 85d2  test edx, edx
logic(get(2,4,0)&get(2,4,0),4);
}
L463adc: { // 7e50  jle 0x463b2e
if(condition(4))goto L463b2e;
}
L463ade: { // be80578000  mov esi, 0x805780
put(6,0x805780u,4,0);
}
L463ae3: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L463ae6: { // 8bc8  mov ecx, eax
put(1,get(0,4,0),4,0);
}
L463ae8: { // c1e102  shl ecx, 2
put(1,shift(get(1,4,0),0x2u,4,0),4,0);
}
L463aeb: { // 8b8158225d00  mov eax, dword ptr [ecx + 0x5d2258]
put(0,read((0x5d2258u+r[1]),4),4,0);
}
L463af1: { // 69c0bc000000  imul eax, eax, 0xbc
put(0,multiply(get(0,4,0),0xbcu,4),4,0);
}
L463af7: { // ff4508  inc dword ptr [ebp + 8]
write((0x8u+r[5]),inc(read((0x8u+r[5]),4),4,1),4);
}
L463afa: { // 8bb8247a6000  mov edi, dword ptr [eax + 0x607a24]
put(7,read((0x607a24u+r[0]),4),4,0);
}
L463b00: { // 89b940578000  mov dword ptr [ecx + 0x805740], edi
write((0x805740u+r[1]),get(7,4,0),4);
}
L463b06: { // 8bb82c7a6000  mov edi, dword ptr [eax + 0x607a2c]
put(7,read((0x607a2cu+r[0]),4),4,0);
}
L463b0c: { // 893e  mov dword ptr [esi], edi
write((0x0u+r[6]),get(7,4,0),4);
}
L463b0e: { // 8bb8347a6000  mov edi, dword ptr [eax + 0x607a34]
put(7,read((0x607a34u+r[0]),4),4,0);
}
L463b14: { // 8b80107a6000  mov eax, dword ptr [eax + 0x607a10]
put(0,read((0x607a10u+r[0]),4),4,0);
}
L463b1a: { // 83c604  add esi, 4
put(6,add(get(6,4,0),0x4u,4,false),4,0);
}
L463b1d: { // 395508  cmp dword ptr [ebp + 8], edx
sub(read((0x8u+r[5]),4),get(2,4,0),4);
}
L463b20: { // 89b938588000  mov dword ptr [ecx + 0x805838], edi
write((0x805838u+r[1]),get(7,4,0),4);
}
L463b26: { // 898100578000  mov dword ptr [ecx + 0x805700], eax
write((0x805700u+r[1]),get(0,4,0),4);
}
L463b2c: { // 7cb5  jl 0x463ae3
if(condition(2))goto L463ae3;
}
L463b2e: { // 53  push ebx
push(get(3,4,0));
}
L463b2f: { // c7050065800001000000  mov dword ptr [0x806500], 1
write((0x806500u),0x1u,4);
}
L463b39: { // e81af7ffff  call 0x463258
push(0x463b3eu);dispatch(0x463258u);
}
L463b3e: { // 83a36c01000000  and dword ptr [ebx + 0x16c], 0
write((0x16cu+r[3]),logic(read((0x16cu+r[3]),4)&0x0u,4),4);
}
L463b45: { // c7432064000000  mov dword ptr [ebx + 0x20], 0x64
write((0x20u+r[3]),0x64u,4);
}
L463b4c: { // eb41  jmp 0x463b8f
goto L463b8f;
}
L463b4e: { // 833d5c46800009  cmp dword ptr [0x80465c], 9
sub(read((0x80465cu),4),0x9u,4);
}
L463b55: { // 7538  jne 0x463b8f
if(condition(1))goto L463b8f;
}
L463b57: { // 833da0e5770001  cmp dword ptr [0x77e5a0], 1
sub(read((0x77e5a0u),4),0x1u,4);
}
L463b5e: { // 752f  jne 0x463b8f
if(condition(1))goto L463b8f;
}
L463b60: { // 833d0c30770000  cmp dword ptr [0x77300c], 0
sub(read((0x77300cu),4),0x0u,4);
}
L463b67: { // 7426  je 0x463b8f
if(condition(0))goto L463b8f;
}
L463b69: { // a1203a8000  mov eax, dword ptr [0x803a20]
put(0,read((0x803a20u),4),4,0);
}
L463b6e: { // 6a50  push 0x50
push(0x50u);
}
L463b70: { // c1e007  shl eax, 7
put(0,shift(get(0,4,0),0x7u,4,0),4,0);
}
L463b73: { // 50  push eax
push(get(0,4,0));
}
L463b74: { // e80b24faff  call 0x405f84
push(0x463b79u);dispatch(0x405f84u);
}
L463b79: { // 898388010000  mov dword ptr [ebx + 0x188], eax
write((0x188u+r[3]),get(0,4,0),4);
}
L463b7f: { // c7432014000000  mov dword ptr [ebx + 0x20], 0x14
write((0x20u+r[3]),0x14u,4);
}
L463b86: { // eb07  jmp 0x463b8f
goto L463b8f;
}
L463b88: { // c743200a000000  mov dword ptr [ebx + 0x20], 0xa
write((0x20u+r[3]),0xau,4);
}
L463b8f: { // 8b4320  mov eax, dword ptr [ebx + 0x20]
put(0,read((0x20u+r[3]),4),4,0);
}
L463b92: { // 83f864  cmp eax, 0x64
sub(get(0,4,0),0x64u,4);
}
L463b95: { // 740a  je 0x463ba1
if(condition(0))goto L463ba1;
}
L463b97: { // 83f86e  cmp eax, 0x6e
sub(get(0,4,0),0x6eu,4);
}
L463b9a: { // 7405  je 0x463ba1
if(condition(0))goto L463ba1;
}
L463b9c: { // 83f878  cmp eax, 0x78
sub(get(0,4,0),0x78u,4);
}
L463b9f: { // 7550  jne 0x463bf1
if(condition(1))goto L463bf1;
}
L463ba1: { // 6a50  push 0x50
push(0x50u);
}
L463ba3: { // 8365f000  and dword ptr [ebp - 0x10], 0
write((0xfffffff0u+r[5]),logic(read((0xfffffff0u+r[5]),4)&0x0u,4),4);
}
L463ba7: { // 59  pop ecx
put(1,pop(),4,0);
}
L463ba8: { // 8d75f0  lea esi, [ebp - 0x10]
put(6,(0xfffffff0u+r[5]),4,0);
}
L463bab: { // 8bc1  mov eax, ecx
put(0,get(1,4,0),4,0);
}
L463bad: { // 8d7de0  lea edi, [ebp - 0x20]
put(7,(0xffffffe0u+r[5]),4,0);
}
L463bb0: { // 2b836c010000  sub eax, dword ptr [ebx + 0x16c]
put(0,sub(get(0,4,0),read((0x16cu+r[3]),4),4,false),4,0);
}
L463bb6: { // 894dfc  mov dword ptr [ebp - 4], ecx
write((0xfffffffcu+r[5]),get(1,4,0),4);
}
L463bb9: { // 6a01  push 1
push(0x1u);
}
L463bbb: { // 8945f4  mov dword ptr [ebp - 0xc], eax
write((0xfffffff4u+r[5]),get(0,4,0),4);
}
L463bbe: { // a1203a8000  mov eax, dword ptr [0x803a20]
put(0,read((0x803a20u),4),4,0);
}
L463bc3: { // c1e007  shl eax, 7
put(0,shift(get(0,4,0),0x7u,4,0),4,0);
}
L463bc6: { // 8945f8  mov dword ptr [ebp - 8], eax
write((0xfffffff8u+r[5]),get(0,4,0),4);
}
L463bc9: { // 8d45e0  lea eax, [ebp - 0x20]
put(0,(0xffffffe0u+r[5]),4,0);
}
L463bcc: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463bcd: { // 50  push eax
push(get(0,4,0));
}
L463bce: { // a170b47400  mov eax, dword ptr [0x74b470]
put(0,read((0x74b470u),4),4,0);
}
L463bd3: { // ffb388010000  push dword ptr [ebx + 0x188]
push(read((0x188u+r[3]),4));
}
L463bd9: { // 83c008  add eax, 8
put(0,add(get(0,4,0),0x8u,4,false),4,0);
}
L463bdc: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463bdd: { // 50  push eax
push(get(0,4,0));
}
L463bde: { // ff3568146e00  push dword ptr [0x6e1468]
push(read((0x6e1468u),4));
}
L463be4: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463be5: { // ff356cb16d00  push dword ptr [0x6db16c]
push(read((0x6db16cu),4));
}
L463beb: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L463bec: { // e8c221faff  call 0x405db3
push(0x463bf1u);dispatch(0x405db3u);
}
L463bf1: { // 5f  pop edi
put(7,pop(),4,0);
}
L463bf2: { // 5e  pop esi
put(6,pop(),4,0);
}
L463bf3: { // 5b  pop ebx
put(3,pop(),4,0);
}
L463bf4: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L463bf5: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00463bf8_draw_enemy_status_panel_463bf8
void RecoveredBattle::fn_463bf8(){
goto L463bf8;
L463bf8: { // 55  push ebp
push(get(5,4,0));
}
L463bf9: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L463bfb: { // 83ec0c  sub esp, 0xc
put(4,sub(get(4,4,0),0xcu,4,false),4,0);
}
L463bfe: { // 53  push ebx
push(get(3,4,0));
}
L463bff: { // 8b5d08  mov ebx, dword ptr [ebp + 8]
put(3,read((0x8u+r[5]),4),4,0);
}
L463c02: { // 56  push esi
push(get(6,4,0));
}
L463c03: { // 33f6  xor esi, esi
put(6,logic(get(6,4,0)^get(6,4,0),4),4,0);
}
L463c05: { // 39b388010000  cmp dword ptr [ebx + 0x188], esi
sub(read((0x188u+r[3]),4),get(6,4,0),4);
}
L463c0b: { // 57  push edi
push(get(7,4,0));
}
L463c0c: { // 0f84d1010000  je 0x463de3
if(condition(0))goto L463de3;
}
L463c12: { // 393504658000  cmp dword ptr [0x806504], esi
sub(read((0x806504u),4),get(6,4,0),4);
}
L463c18: { // 0f84c5010000  je 0x463de3
if(condition(0))goto L463de3;
}
L463c1e: { // 56  push esi
push(get(6,4,0));
}
L463c1f: { // 56  push esi
push(get(6,4,0));
}
L463c20: { // 893504658000  mov dword ptr [0x806504], esi
write((0x806504u),get(6,4,0),4);
}
L463c26: { // ffb388010000  push dword ptr [ebx + 0x188]
push(read((0x188u+r[3]),4));
}
L463c2c: { // e85b20faff  call 0x405c8c
push(0x463c31u);dispatch(0x405c8cu);
}
L463c31: { // ffb388010000  push dword ptr [ebx + 0x188]
push(read((0x188u+r[3]),4));
}
L463c37: { // e8c51ffaff  call 0x405c01
push(0x463c3cu);dispatch(0x405c01u);
}
L463c3c: { // 8bf8  mov edi, eax
put(7,get(0,4,0),4,0);
}
L463c3e: { // 3bfe  cmp edi, esi
sub(get(7,4,0),get(6,4,0),4);
}
L463c40: { // 897dfc  mov dword ptr [ebp - 4], edi
write((0xfffffffcu+r[5]),get(7,4,0),4);
}
L463c43: { // 752f  jne 0x463c74
if(condition(1))goto L463c74;
}
L463c45: { // 6869080000  push 0x869
push(0x869u);
}
L463c4a: { // 6a5c  push 0x5c
push(0x5cu);
}
L463c4c: { // 685c285d00  push 0x5d285c
push(0x5d285cu);
}
L463c51: { // e81a380300  call 0x497470
push(0x463c56u);dispatch(0x497470u);
}
L463c56: { // 59  pop ecx
put(1,pop(),4,0);
}
L463c57: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L463c58: { // 59  pop ecx
put(1,pop(),4,0);
}
L463c59: { // 50  push eax
push(get(0,4,0));
}
L463c5a: { // 6838285d00  push 0x5d2838
push(0x5d2838u);
}
L463c5f: { // 685c604a00  push 0x4a605c
push(0x4a605cu);
}
L463c64: { // e8c1dcf9ff  call 0x40192a
push(0x463c69u);dispatch(0x40192au);
}
L463c69: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L463c6c: { // 3bfe  cmp edi, esi
sub(get(7,4,0),get(6,4,0),4);
}
L463c6e: { // 0f846f010000  je 0x463de3
if(condition(0))goto L463de3;
}
L463c74: { // 56  push esi
push(get(6,4,0));
}
L463c75: { // ff35889e6d00  push dword ptr [0x6d9e88]
push(read((0x6d9e88u),4));
}
L463c7b: { // 57  push edi
push(get(7,4,0));
}
L463c7c: { // ff1590938500  call dword ptr [0x859390]
push(0x463c82u);dispatch(0x859390u);
}
L463c82: { // 6a01  push 1
push(0x1u);
}
L463c84: { // 57  push edi
push(get(7,4,0));
}
L463c85: { // ff1584938500  call dword ptr [0x859384]
push(0x463c8bu);dispatch(0x859384u);
}
L463c8b: { // 33c9  xor ecx, ecx
put(1,logic(get(1,4,0)^get(1,4,0),4),4,0);
}
L463c8d: { // 393584647700  cmp dword ptr [0x776484], esi
sub(read((0x776484u),4),get(6,4,0),4);
}
L463c93: { // 894df4  mov dword ptr [ebp - 0xc], ecx
write((0xfffffff4u+r[5]),get(1,4,0),4);
}
L463c96: { // 0f8e31010000  jle 0x463dcd
if(condition(4))goto L463dcd;
}
L463c9c: { // 6a18  push 0x18
push(0x18u);
}
L463c9e: { // c745f8646b8000  mov dword ptr [ebp - 8], 0x806b64
write((0xfffffff8u+r[5]),0x806b64u,4);
}
L463ca5: { // 5f  pop edi
put(7,pop(),4,0);
}
L463ca6: { // be84285d00  mov esi, 0x5d2884
put(6,0x5d2884u,4,0);
}
L463cab: { // 8b45f8  mov eax, dword ptr [ebp - 8]
put(0,read((0xfffffff8u+r[5]),4),4,0);
}
L463cae: { // 8b40fc  mov eax, dword ptr [eax - 4]
put(0,read((0xfffffffcu+r[0]),4),4,0);
}
L463cb1: { // 69c0ac010000  imul eax, eax, 0x1ac
put(0,multiply(get(0,4,0),0x1acu,4),4,0);
}
L463cb7: { // f680dc73800040  test byte ptr [eax + 0x8073dc], 0x40
logic(read((0x8073dcu+r[0]),1)&0x40u,1);
}
L463cbe: { // 0f84ec000000  je 0x463db0
if(condition(0))goto L463db0;
}
L463cc4: { // 8b45f8  mov eax, dword ptr [ebp - 8]
put(0,read((0xfffffff8u+r[5]),4),4,0);
}
L463cc7: { // 8b00  mov eax, dword ptr [eax]
put(0,read((0x0u+r[0]),4),4,0);
}
L463cc9: { // 6bc07c  imul eax, eax, 0x7c
put(0,multiply(get(0,4,0),0x7cu,4),4,0);
}
L463ccc: { // f680a89c600020  test byte ptr [eax + 0x609ca8], 0x20
logic(read((0x609ca8u+r[0]),1)&0x20u,1);
}
L463cd3: { // 7647  jbe 0x463d1c
if(condition(8))goto L463d1c;
}
L463cd5: { // bb7c285d00  mov ebx, 0x5d287c
put(3,0x5d287cu,4,0);
}
L463cda: { // 8d47f0  lea eax, [edi - 0x10]
put(0,(0xfffffff0u+r[7]),4,0);
}
L463cdd: { // 53  push ebx
push(get(3,4,0));
}
L463cde: { // ff35f4274a00  push dword ptr [0x4a27f4]
push(read((0x4a27f4u),4));
}
L463ce4: { // ff35f0274a00  push dword ptr [0x4a27f0]
push(read((0x4a27f0u),4));
}
L463cea: { // 6a0a  push 0xa
push(0xau);
}
L463cec: { // 50  push eax
push(get(0,4,0));
}
L463ced: { // 6a00  push 0
push(0x0u);
}
L463cef: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L463cf2: { // e8e45afdff  call 0x4397db
push(0x463cf7u);dispatch(0x4397dbu);
}
L463cf7: { // 83c41c  add esp, 0x1c
put(4,add(get(4,4,0),0x1cu,4,false),4,0);
}
L463cfa: { // 53  push ebx
push(get(3,4,0));
}
L463cfb: { // ff35fc274a00  push dword ptr [0x4a27fc]
push(read((0x4a27fcu),4));
}
L463d01: { // ff35f8274a00  push dword ptr [0x4a27f8]
push(read((0x4a27f8u),4));
}
L463d07: { // 6a0a  push 0xa
push(0xau);
}
L463d09: { // 57  push edi
push(get(7,4,0));
}
L463d0a: { // 6a00  push 0
push(0x0u);
}
L463d0c: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L463d0f: { // e8c75afdff  call 0x4397db
push(0x463d14u);dispatch(0x4397dbu);
}
L463d14: { // 83c41c  add esp, 0x1c
put(4,add(get(4,4,0),0x1cu,4,false),4,0);
}
L463d17: { // e991000000  jmp 0x463dad
goto L463dad;
}
L463d1c: { // 8b98b89c6000  mov ebx, dword ptr [eax + 0x609cb8]
put(3,read((0x609cb8u+r[0]),4),4,0);
}
L463d22: { // 8b0c8d00598000  mov ecx, dword ptr [ecx*4 + 0x805900]
put(1,read((0x805900u+r[1]*4u),4),4,0);
}
L463d29: { // 8bc3  mov eax, ebx
put(0,get(3,4,0),4,0);
}
L463d2b: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L463d2c: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L463d2e: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L463d30: { // 3bc8  cmp ecx, eax
sub(get(1,4,0),get(0,4,0),4);
}
L463d32: { // 7e04  jle 0x463d38
if(condition(4))goto L463d38;
}
L463d34: { // 6a03  push 3
push(0x3u);
}
L463d36: { // eb0e  jmp 0x463d46
goto L463d46;
}
L463d38: { // 8bc3  mov eax, ebx
put(0,get(3,4,0),4,0);
}
L463d3a: { // 6a04  push 4
push(0x4u);
}
L463d3c: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L463d3d: { // 5b  pop ebx
put(3,pop(),4,0);
}
L463d3e: { // f7fb  idiv ebx
divide(get(3,4,0),true);
}
L463d40: { // 3bc8  cmp ecx, eax
sub(get(1,4,0),get(0,4,0),4);
}
L463d42: { // 7e05  jle 0x463d49
if(condition(4))goto L463d49;
}
L463d44: { // 6a05  push 5
push(0x5u);
}
L463d46: { // 58  pop eax
put(0,pop(),4,0);
}
L463d47: { // eb08  jmp 0x463d51
goto L463d51;
}
L463d49: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L463d4b: { // 85c9  test ecx, ecx
logic(get(1,4,0)&get(1,4,0),4);
}
L463d4d: { // 0f9fc0  setg al
put(0,condition(5),1,0);
}
L463d50: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L463d51: { // 33db  xor ebx, ebx
put(3,logic(get(3,4,0)^get(3,4,0),4),4,0);
}
L463d53: { // 51  push ecx
push(get(1,4,0));
}
L463d54: { // 85c9  test ecx, ecx
logic(get(1,4,0)&get(1,4,0),4);
}
L463d56: { // 0f9ec3  setle bl
put(3,condition(4),1,0);
}
L463d59: { // c1e003  shl eax, 3
put(0,shift(get(0,4,0),0x3u,4,0),4,0);
}
L463d5c: { // 56  push esi
push(get(6,4,0));
}
L463d5d: { // 4b  dec ebx
put(3,inc(get(3,4,0),4,-1),4,0);
}
L463d5e: { // ffb0dc274a00  push dword ptr [eax + 0x4a27dc]
push(read((0x4a27dcu+r[0]),4));
}
L463d64: { // 83e303  and ebx, 3
put(3,logic(get(3,4,0)&0x3u,4),4,0);
}
L463d67: { // 43  inc ebx
put(3,inc(get(3,4,0),4,1),4,0);
}
L463d68: { // ffb0d8274a00  push dword ptr [eax + 0x4a27d8]
push(read((0x4a27d8u+r[0]),4));
}
L463d6e: { // 8d47f0  lea eax, [edi - 0x10]
put(0,(0xfffffff0u+r[7]),4,0);
}
L463d71: { // 6a0a  push 0xa
push(0xau);
}
L463d73: { // 50  push eax
push(get(0,4,0));
}
L463d74: { // 6a00  push 0
push(0x0u);
}
L463d76: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L463d79: { // e85d5afdff  call 0x4397db
push(0x463d7eu);dispatch(0x4397dbu);
}
L463d7e: { // 8b4df4  mov ecx, dword ptr [ebp - 0xc]
put(1,read((0xfffffff4u+r[5]),4),4,0);
}
L463d81: { // 83c420  add esp, 0x20
put(4,add(get(4,4,0),0x20u,4,false),4,0);
}
L463d84: { // 8bc3  mov eax, ebx
put(0,get(3,4,0),4,0);
}
L463d86: { // ff348d78598000  push dword ptr [ecx*4 + 0x805978]
push(read((0x805978u+r[1]*4u),4));
}
L463d8d: { // c1e003  shl eax, 3
put(0,shift(get(0,4,0),0x3u,4,0),4,0);
}
L463d90: { // 56  push esi
push(get(6,4,0));
}
L463d91: { // ffb0dc274a00  push dword ptr [eax + 0x4a27dc]
push(read((0x4a27dcu+r[0]),4));
}
L463d97: { // ffb0d8274a00  push dword ptr [eax + 0x4a27d8]
push(read((0x4a27d8u+r[0]),4));
}
L463d9d: { // 6a0a  push 0xa
push(0xau);
}
L463d9f: { // 57  push edi
push(get(7,4,0));
}
L463da0: { // 6a00  push 0
push(0x0u);
}
L463da2: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L463da5: { // e8315afdff  call 0x4397db
push(0x463daau);dispatch(0x4397dbu);
}
L463daa: { // 83c420  add esp, 0x20
put(4,add(get(4,4,0),0x20u,4,false),4,0);
}
L463dad: { // 8b5d08  mov ebx, dword ptr [ebp + 8]
put(3,read((0x8u+r[5]),4),4,0);
}
L463db0: { // 8b4df4  mov ecx, dword ptr [ebp - 0xc]
put(1,read((0xfffffff4u+r[5]),4),4,0);
}
L463db3: { // 8345f824  add dword ptr [ebp - 8], 0x24
write((0xfffffff8u+r[5]),add(read((0xfffffff8u+r[5]),4),0x24u,4,false),4);
}
L463db7: { // 41  inc ecx
put(1,inc(get(1,4,0),4,1),4,0);
}
L463db8: { // 83c720  add edi, 0x20
put(7,add(get(7,4,0),0x20u,4,false),4,0);
}
L463dbb: { // 3b0d84647700  cmp ecx, dword ptr [0x776484]
sub(get(1,4,0),read((0x776484u),4),4);
}
L463dc1: { // 894df4  mov dword ptr [ebp - 0xc], ecx
write((0xfffffff4u+r[5]),get(1,4,0),4);
}
L463dc4: { // 0f8ce1feffff  jl 0x463cab
if(condition(2))goto L463cab;
}
L463dca: { // 8b7dfc  mov edi, dword ptr [ebp - 4]
put(7,read((0xfffffffcu+r[5]),4),4,0);
}
L463dcd: { // ff7508  push dword ptr [ebp + 8]
push(read((0x8u+r[5]),4));
}
L463dd0: { // 57  push edi
push(get(7,4,0));
}
L463dd1: { // ff1564938500  call dword ptr [0x859364]
push(0x463dd7u);dispatch(0x859364u);
}
L463dd7: { // 57  push edi
push(get(7,4,0));
}
L463dd8: { // ffb388010000  push dword ptr [ebx + 0x188]
push(read((0x188u+r[3]),4));
}
L463dde: { // e83d1efaff  call 0x405c20
push(0x463de3u);dispatch(0x405c20u);
}
L463de3: { // 5f  pop edi
put(7,pop(),4,0);
}
L463de4: { // 5e  pop esi
put(6,pop(),4,0);
}
L463de5: { // 5b  pop ebx
put(3,pop(),4,0);
}
L463de6: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L463de7: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00463dea_draw_actor_status_icons_mc_463dea
void RecoveredBattle::fn_463dea(){
goto L463dea;
L463dea: { // 55  push ebp
push(get(5,4,0));
}
L463deb: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L463ded: { // 83ec1c  sub esp, 0x1c
put(4,sub(get(4,4,0),0x1cu,4,false),4,0);
}
L463df0: { // 56  push esi
push(get(6,4,0));
}
L463df1: { // 33f6  xor esi, esi
put(6,logic(get(6,4,0)^get(6,4,0),4),4,0);
}
L463df3: { // 393584647700  cmp dword ptr [0x776484], esi
sub(read((0x776484u),4),get(6,4,0),4);
}
L463df9: { // 8975f4  mov dword ptr [ebp - 0xc], esi
write((0xfffffff4u+r[5]),get(6,4,0),4);
}
L463dfc: { // 0f8ee2000000  jle 0x463ee4
if(condition(4))goto L463ee4;
}
L463e02: { // 57  push edi
push(get(7,4,0));
}
L463e03: { // 53  push ebx
push(get(3,4,0));
}
L463e04: { // c745f8c0578000  mov dword ptr [ebp - 8], 0x8057c0
write((0xfffffff8u+r[5]),0x8057c0u,4);
}
L463e0b: { // c745fc606b8000  mov dword ptr [ebp - 4], 0x806b60
write((0xfffffffcu+r[5]),0x806b60u,4);
}
L463e12: { // 8b45fc  mov eax, dword ptr [ebp - 4]
put(0,read((0xfffffffcu+r[5]),4),4,0);
}
L463e15: { // 8b08  mov ecx, dword ptr [eax]
put(1,read((0x0u+r[0]),4),4,0);
}
L463e17: { // 69c9ac010000  imul ecx, ecx, 0x1ac
put(1,multiply(get(1,4,0),0x1acu,4),4,0);
}
L463e1d: { // 81c1d8738000  add ecx, 0x8073d8
put(1,add(get(1,4,0),0x8073d8u,4,false),4,0);
}
L463e23: { // f6410440  test byte ptr [ecx + 4], 0x40
logic(read((0x4u+r[1]),1)&0x40u,1);
}
L463e27: { // 0f8498000000  je 0x463ec5
if(condition(0))goto L463ec5;
}
L463e2d: { // 8b45f8  mov eax, dword ptr [ebp - 8]
put(0,read((0xfffffff8u+r[5]),4),4,0);
}
L463e30: { // 8b38  mov edi, dword ptr [eax]
put(7,read((0x0u+r[0]),4),4,0);
}
L463e32: { // 85ff  test edi, edi
logic(get(7,4,0)&get(7,4,0),4);
}
L463e34: { // 0f8e8b000000  jle 0x463ec5
if(condition(4))goto L463ec5;
}
L463e3a: { // 8d0437  lea eax, [edi + esi]
put(0,(0x0u+r[7]+r[6]*1u),4,0);
}
L463e3d: { // 6a01  push 1
push(0x1u);
}
L463e3f: { // 8945f0  mov dword ptr [ebp - 0x10], eax
write((0xfffffff0u+r[5]),get(0,4,0),4);
}
L463e42: { // 8d45e4  lea eax, [ebp - 0x1c]
put(0,(0xffffffe4u+r[5]),4,0);
}
L463e45: { // 50  push eax
push(get(0,4,0));
}
L463e46: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L463e49: { // bb00000100  mov ebx, 0x10000
put(3,0x10000u,4,0);
}
L463e4e: { // 8365e400  and dword ptr [ebp - 0x1c], 0
write((0xffffffe4u+r[5]),logic(read((0xffffffe4u+r[5]),4)&0x0u,4),4);
}
L463e52: { // ffb088010000  push dword ptr [eax + 0x188]
push(read((0x188u+r[0]),4));
}
L463e58: { // 8b4124  mov eax, dword ptr [ecx + 0x24]
put(0,read((0x24u+r[1]),4),4,0);
}
L463e5b: { // 2b4110  sub eax, dword ptr [ecx + 0x10]
put(0,sub(get(0,4,0),read((0x10u+r[1]),4),4,false),4,0);
}
L463e5e: { // 8975e8  mov dword ptr [ebp - 0x18], esi
write((0xffffffe8u+r[5]),get(6,4,0),4);
}
L463e61: { // c745ec38000000  mov dword ptr [ebp - 0x14], 0x38
write((0xffffffecu+r[5]),0x38u,4);
}
L463e68: { // 03410c  add eax, dword ptr [ecx + 0xc]
put(0,add(get(0,4,0),read((0xcu+r[1]),4),4,false),4,0);
}
L463e6b: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L463e6c: { // f7fb  idiv ebx
divide(get(3,4,0),true);
}
L463e6e: { // 8bd8  mov ebx, eax
put(3,get(0,4,0),4,0);
}
L463e70: { // a140146e00  mov eax, dword ptr [0x6e1440]
put(0,read((0x6e1440u),4),4,0);
}
L463e75: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L463e76: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L463e78: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L463e7a: { // 03d8  add ebx, eax
put(3,add(get(3,4,0),get(0,4,0),4,false),4,0);
}
L463e7c: { // 8b4120  mov eax, dword ptr [ecx + 0x20]
put(0,read((0x20u+r[1]),4),4,0);
}
L463e7f: { // 034108  add eax, dword ptr [ecx + 8]
put(0,add(get(0,4,0),read((0x8u+r[1]),4),4,false),4,0);
}
L463e82: { // b900000100  mov ecx, 0x10000
put(1,0x10000u,4,0);
}
L463e87: { // 2b1dc4737800  sub ebx, dword ptr [0x7873c4]
put(3,sub(get(3,4,0),read((0x7873c4u),4),4,false),4,0);
}
L463e8d: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L463e8e: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L463e90: { // 031d349d6d00  add ebx, dword ptr [0x6d9d34]
put(3,add(get(3,4,0),read((0x6d9d34u),4),4,false),4,0);
}
L463e96: { // 2bdf  sub ebx, edi
put(3,sub(get(3,4,0),get(7,4,0),4,false),4,0);
}
L463e98: { // 83eb17  sub ebx, 0x17
put(3,sub(get(3,4,0),0x17u,4,false),4,0);
}
L463e9b: { // 53  push ebx
push(get(3,4,0));
}
L463e9c: { // 8bc8  mov ecx, eax
put(1,get(0,4,0),4,0);
}
L463e9e: { // a1b0126e00  mov eax, dword ptr [0x6e12b0]
put(0,read((0x6e12b0u),4),4,0);
}
L463ea3: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L463ea4: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L463ea6: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L463ea8: { // 03c8  add ecx, eax
put(1,add(get(1,4,0),get(0,4,0),4,false),4,0);
}
L463eaa: { // a1309d6d00  mov eax, dword ptr [0x6d9d30]
put(0,read((0x6d9d30u),4),4,0);
}
L463eaf: { // 2b0dc0737800  sub ecx, dword ptr [0x7873c0]
put(1,sub(get(1,4,0),read((0x7873c0u),4),4,false),4,0);
}
L463eb5: { // 8d4401f0  lea eax, [ecx + eax - 0x10]
put(0,(0xfffffff0u+r[1]+r[0]*1u),4,0);
}
L463eb9: { // 50  push eax
push(get(0,4,0));
}
L463eba: { // ff356cb16d00  push dword ptr [0x6db16c]
push(read((0x6db16cu),4));
}
L463ec0: { // e8111ffaff  call 0x405dd6
push(0x463ec5u);dispatch(0x405dd6u);
}
L463ec5: { // ff45f4  inc dword ptr [ebp - 0xc]
write((0xfffffff4u+r[5]),inc(read((0xfffffff4u+r[5]),4),4,1),4);
}
L463ec8: { // 8345fc24  add dword ptr [ebp - 4], 0x24
write((0xfffffffcu+r[5]),add(read((0xfffffffcu+r[5]),4),0x24u,4,false),4);
}
L463ecc: { // 8b45f4  mov eax, dword ptr [ebp - 0xc]
put(0,read((0xfffffff4u+r[5]),4),4,0);
}
L463ecf: { // 8345f804  add dword ptr [ebp - 8], 4
write((0xfffffff8u+r[5]),add(read((0xfffffff8u+r[5]),4),0x4u,4,false),4);
}
L463ed3: { // 83c620  add esi, 0x20
put(6,add(get(6,4,0),0x20u,4,false),4,0);
}
L463ed6: { // 3b0584647700  cmp eax, dword ptr [0x776484]
sub(get(0,4,0),read((0x776484u),4),4);
}
L463edc: { // 0f8c30ffffff  jl 0x463e12
if(condition(2))goto L463e12;
}
L463ee2: { // 5b  pop ebx
put(3,pop(),4,0);
}
L463ee3: { // 5f  pop edi
put(7,pop(),4,0);
}
L463ee4: { // 5e  pop esi
put(6,pop(),4,0);
}
L463ee5: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L463ee6: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00463ee9_enemy_status_panel_tick_mc_463ee9
void RecoveredBattle::fn_463ee9(){
goto L463ee9;
L463ee9: { // 55  push ebp
push(get(5,4,0));
}
L463eea: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L463eec: { // 51  push ecx
push(get(1,4,0));
}
L463eed: { // 53  push ebx
push(get(3,4,0));
}
L463eee: { // 56  push esi
push(get(6,4,0));
}
L463eef: { // 57  push edi
push(get(7,4,0));
}
L463ef0: { // 8b7d08  mov edi, dword ptr [ebp + 8]
put(7,read((0x8u+r[5]),4),4,0);
}
L463ef3: { // 8b4720  mov eax, dword ptr [edi + 0x20]
put(0,read((0x20u+r[7]),4),4,0);
}
L463ef6: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L463ef7: { // 0f84f9010000  je 0x4640f6
if(condition(0))goto L4640f6;
}
L463efd: { // 83e809  sub eax, 9
put(0,sub(get(0,4,0),0x9u,4,false),4,0);
}
L463f00: { // 0f84ab010000  je 0x4640b1
if(condition(0))goto L4640b1;
}
L463f06: { // 83e80a  sub eax, 0xa
put(0,sub(get(0,4,0),0xau,4,false),4,0);
}
L463f09: { // 0f8442010000  je 0x464051
if(condition(0))goto L464051;
}
L463f0f: { // 83e850  sub eax, 0x50
put(0,sub(get(0,4,0),0x50u,4,false),4,0);
}
L463f12: { // 0f84e7000000  je 0x463fff
if(condition(0))goto L463fff;
}
L463f18: { // 83e80a  sub eax, 0xa
put(0,sub(get(0,4,0),0xau,4,false),4,0);
}
L463f1b: { // 7415  je 0x463f32
if(condition(0))goto L463f32;
}
L463f1d: { // 83e85a  sub eax, 0x5a
put(0,sub(get(0,4,0),0x5au,4,false),4,0);
}
L463f20: { // 0f85cc000000  jne 0x463ff2
if(condition(1))goto L463ff2;
}
L463f26: { // c747206e000000  mov dword ptr [edi + 0x20], 0x6e
write((0x20u+r[7]),0x6eu,4);
}
L463f2d: { // e9c0000000  jmp 0x463ff2
goto L463ff2;
}
L463f32: { // 57  push edi
push(get(7,4,0));
}
L463f33: { // e8c0fcffff  call 0x463bf8
push(0x463f38u);dispatch(0x463bf8u);
}
L463f38: { // 833d5c46800009  cmp dword ptr [0x80465c], 9
sub(read((0x80465cu),4),0x9u,4);
}
L463f3f: { // 6a02  push 2
push(0x2u);
}
L463f41: { // baf0000000  mov edx, 0xf0
put(2,0xf0u,4,0);
}
L463f46: { // 5e  pop esi
put(6,pop(),4,0);
}
L463f47: { // bb68010000  mov ebx, 0x168
put(3,0x168u,4,0);
}
L463f4c: { // 7512  jne 0x463f60
if(condition(1))goto L463f60;
}
L463f4e: { // 833da0e5770001  cmp dword ptr [0x77e5a0], 1
sub(read((0x77e5a0u),4),0x1u,4);
}
L463f55: { // 7509  jne 0x463f60
if(condition(1))goto L463f60;
}
L463f57: { // 833d1030770000  cmp dword ptr [0x773010], 0
sub(read((0x773010u),4),0x0u,4);
}
L463f5e: { // 750f  jne 0x463f6f
if(condition(1))goto L463f6f;
}
L463f60: { // 8bc2  mov eax, edx
put(0,get(2,4,0),4,0);
}
L463f62: { // 89b020548000  mov dword ptr [eax + 0x805420], esi
write((0x805420u+r[0]),get(6,4,0),4);
}
L463f68: { // 83c004  add eax, 4
put(0,add(get(0,4,0),0x4u,4,false),4,0);
}
L463f6b: { // 3bc3  cmp eax, ebx
sub(get(0,4,0),get(3,4,0),4);
}
L463f6d: { // 7cf3  jl 0x463f62
if(condition(2))goto L463f62;
}
L463f6f: { // bf00568000  mov edi, 0x805600
put(7,0x805600u,4,0);
}
L463f74: { // b82cd88000  mov eax, 0x80d82c
put(0,0x80d82cu,4,0);
}
L463f79: { // 8b08  mov ecx, dword ptr [eax]
put(1,read((0x0u+r[0]),4),4,0);
}
L463f7b: { // f7c100040100  test ecx, 0x10400
logic(get(1,4,0)&0x10400u,4);
}
L463f81: { // 7405  je 0x463f88
if(condition(0))goto L463f88;
}
L463f83: { // f6c140  test cl, 0x40
logic(get(1,1,0)&0x40u,1);
}
L463f86: { // 7502  jne 0x463f8a
if(condition(1))goto L463f8a;
}
L463f88: { // 8937  mov dword ptr [edi], esi
write((0x0u+r[7]),get(6,4,0),4);
}
L463f8a: { // 05ac010000  add eax, 0x1ac
put(0,add(get(0,4,0),0x1acu,4,false),4,0);
}
L463f8f: { // 83c704  add edi, 4
put(7,add(get(7,4,0),0x4u,4,false),4,0);
}
L463f92: { // 3d540a8100  cmp eax, 0x810a54
sub(get(0,4,0),0x810a54u,4);
}
L463f97: { // 7ce0  jl 0x463f79
if(condition(2))goto L463f79;
}
L463f99: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L463f9b: { // 897dfc  mov dword ptr [ebp - 4], edi
write((0xfffffffcu+r[5]),get(7,4,0),4);
}
L463f9e: { // 8d8a10ffffff  lea ecx, [edx - 0xf0]
put(1,(0xffffff10u+r[2]),4,0);
}
L463fa4: { // 8bb110558000  mov esi, dword ptr [ecx + 0x805510]
put(6,read((0x805510u+r[1]),4),4,0);
}
L463faa: { // 8d81c0578000  lea eax, [ecx + 0x8057c0]
put(0,(0x8057c0u+r[1]),4,0);
}
L463fb0: { // 8d8910558000  lea ecx, [ecx + 0x805510]
put(1,(0x805510u+r[1]),4,0);
}
L463fb6: { // 2930  sub dword ptr [eax], esi
write((0x0u+r[0]),sub(read((0x0u+r[0]),4),get(6,4,0),4,false),4);
}
L463fb8: { // 3938  cmp dword ptr [eax], edi
sub(read((0x0u+r[0]),4),get(7,4,0),4);
}
L463fba: { // 7f06  jg 0x463fc2
if(condition(5))goto L463fc2;
}
L463fbc: { // 8938  mov dword ptr [eax], edi
write((0x0u+r[0]),get(7,4,0),4);
}
L463fbe: { // 8939  mov dword ptr [ecx], edi
write((0x0u+r[1]),get(7,4,0),4);
}
L463fc0: { // eb03  jmp 0x463fc5
goto L463fc5;
}
L463fc2: { // ff45fc  inc dword ptr [ebp - 4]
write((0xfffffffcu+r[5]),inc(read((0xfffffffcu+r[5]),4),4,1),4);
}
L463fc5: { // 83c204  add edx, 4
put(2,add(get(2,4,0),0x4u,4,false),4,0);
}
L463fc8: { // 3bd3  cmp edx, ebx
sub(get(2,4,0),get(3,4,0),4);
}
L463fca: { // 7cd2  jl 0x463f9e
if(condition(2))goto L463f9e;
}
L463fcc: { // 397dfc  cmp dword ptr [ebp - 4], edi
sub(read((0xfffffffcu+r[5]),4),get(7,4,0),4);
}
L463fcf: { // 751e  jne 0x463fef
if(condition(1))goto L463fef;
}
L463fd1: { // 8b7508  mov esi, dword ptr [ebp + 8]
put(6,read((0x8u+r[5]),4),4,0);
}
L463fd4: { // 6a01  push 1
push(0x1u);
}
L463fd6: { // 8d8688010000  lea eax, [esi + 0x188]
put(0,(0x188u+r[6]),4,0);
}
L463fdc: { // 50  push eax
push(get(0,4,0));
}
L463fdd: { // e83020faff  call 0x406012
push(0x463fe2u);dispatch(0x406012u);
}
L463fe2: { // 89be6c010000  mov dword ptr [esi + 0x16c], edi
write((0x16cu+r[6]),get(7,4,0),4);
}
L463fe8: { // c746200a000000  mov dword ptr [esi + 0x20], 0xa
write((0x20u+r[6]),0xau,4);
}
L463fef: { // 8b7d08  mov edi, dword ptr [ebp + 8]
put(7,read((0x8u+r[5]),4),4,0);
}
L463ff2: { // 57  push edi
push(get(7,4,0));
}
L463ff3: { // e8f2fdffff  call 0x463dea
push(0x463ff8u);dispatch(0x463deau);
}
L463ff8: { // 5f  pop edi
put(7,pop(),4,0);
}
L463ff9: { // 5e  pop esi
put(6,pop(),4,0);
}
L463ffa: { // 5b  pop ebx
put(3,pop(),4,0);
}
L463ffb: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L463ffc: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
L463fff: { // 8365fc00  and dword ptr [ebp - 4], 0
write((0xfffffffcu+r[5]),logic(read((0xfffffffcu+r[5]),4)&0x0u,4),4);
}
L464003: { // 6a20  push 0x20
push(0x20u);
}
L464005: { // baf0000000  mov edx, 0xf0
put(2,0xf0u,4,0);
}
L46400a: { // bb68010000  mov ebx, 0x168
put(3,0x168u,4,0);
}
L46400f: { // 5e  pop esi
put(6,pop(),4,0);
}
L464010: { // 8d8a10ffffff  lea ecx, [edx - 0xf0]
put(1,(0xffffff10u+r[2]),4,0);
}
L464016: { // 8bb910558000  mov edi, dword ptr [ecx + 0x805510]
put(7,read((0x805510u+r[1]),4),4,0);
}
L46401c: { // 8d81c0578000  lea eax, [ecx + 0x8057c0]
put(0,(0x8057c0u+r[1]),4,0);
}
L464022: { // 8d8910558000  lea ecx, [ecx + 0x805510]
put(1,(0x805510u+r[1]),4,0);
}
L464028: { // 0138  add dword ptr [eax], edi
write((0x0u+r[0]),add(read((0x0u+r[0]),4),get(7,4,0),4,false),4);
}
L46402a: { // 3930  cmp dword ptr [eax], esi
sub(read((0x0u+r[0]),4),get(6,4,0),4);
}
L46402c: { // 7c07  jl 0x464035
if(condition(2))goto L464035;
}
L46402e: { // 832100  and dword ptr [ecx], 0
write((0x0u+r[1]),logic(read((0x0u+r[1]),4)&0x0u,4),4);
}
L464031: { // 8930  mov dword ptr [eax], esi
write((0x0u+r[0]),get(6,4,0),4);
}
L464033: { // eb03  jmp 0x464038
goto L464038;
}
L464035: { // ff45fc  inc dword ptr [ebp - 4]
write((0xfffffffcu+r[5]),inc(read((0xfffffffcu+r[5]),4),4,1),4);
}
L464038: { // 83c204  add edx, 4
put(2,add(get(2,4,0),0x4u,4,false),4,0);
}
L46403b: { // 3bd3  cmp edx, ebx
sub(get(2,4,0),get(3,4,0),4);
}
L46403d: { // 7cd1  jl 0x464010
if(condition(2))goto L464010;
}
L46403f: { // 837dfc00  cmp dword ptr [ebp - 4], 0
sub(read((0xfffffffcu+r[5]),4),0x0u,4);
}
L464043: { // 75aa  jne 0x463fef
if(condition(1))goto L463fef;
}
L464045: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L464048: { // c740206e000000  mov dword ptr [eax + 0x20], 0x6e
write((0x20u+r[0]),0x6eu,4);
}
L46404f: { // eb9e  jmp 0x463fef
goto L463fef;
}
L464051: { // 6a02  push 2
push(0x2u);
}
L464053: { // b9f0000000  mov ecx, 0xf0
put(1,0xf0u,4,0);
}
L464058: { // ba40d98000  mov edx, 0x80d940
put(2,0x80d940u,4,0);
}
L46405d: { // 5e  pop esi
put(6,pop(),4,0);
}
L46405e: { // 8b02  mov eax, dword ptr [edx]
put(0,read((0x0u+r[2]),4),4,0);
}
L464060: { // 89b120548000  mov dword ptr [ecx + 0x805420], esi
write((0x805420u+r[1]),get(6,4,0),4);
}
L464066: { // 81c2ac010000  add edx, 0x1ac
put(2,add(get(2,4,0),0x1acu,4,false),4,0);
}
L46406c: { // 83c104  add ecx, 4
put(1,add(get(1,4,0),0x4u,4,false),4,0);
}
L46406f: { // 8d04c0  lea eax, [eax + eax*8]
put(0,(0x0u+r[0]+r[0]*8u),4,0);
}
L464072: { // c1e002  shl eax, 2
put(0,shift(get(0,4,0),0x2u,4,0),4,0);
}
L464075: { // 81fa680b8100  cmp edx, 0x810b68
sub(get(2,4,0),0x810b68u,4);
}
L46407b: { // 8b98746b8000  mov ebx, dword ptr [eax + 0x806b74]
put(3,read((0x806b74u+r[0]),4),4,0);
}
L464081: { // 8b80786b8000  mov eax, dword ptr [eax + 0x806b78]
put(0,read((0x806b78u+r[0]),4),4,0);
}
L464087: { // 89990c588000  mov dword ptr [ecx + 0x80580c], ebx
write((0x80580cu+r[1]),get(3,4,0),4);
}
L46408d: { // 898184588000  mov dword ptr [ecx + 0x805884], eax
write((0x805884u+r[1]),get(0,4,0),4);
}
L464093: { // 7cc9  jl 0x46405e
if(condition(2))goto L46405e;
}
L464095: { // 57  push edi
push(get(7,4,0));
}
L464096: { // c7050465800001000000  mov dword ptr [0x806504], 1
write((0x806504u),0x1u,4);
}
L4640a0: { // e853fbffff  call 0x463bf8
push(0x4640a5u);dispatch(0x463bf8u);
}
L4640a5: { // c7472064000000  mov dword ptr [edi + 0x20], 0x64
write((0x20u+r[7]),0x64u,4);
}
L4640ac: { // e941ffffff  jmp 0x463ff2
goto L463ff2;
}
L4640b1: { // 833d5c46800009  cmp dword ptr [0x80465c], 9
sub(read((0x80465cu),4),0x9u,4);
}
L4640b8: { // 0f8534ffffff  jne 0x463ff2
if(condition(1))goto L463ff2;
}
L4640be: { // 833da0e5770001  cmp dword ptr [0x77e5a0], 1
sub(read((0x77e5a0u),4),0x1u,4);
}
L4640c5: { // 0f8527ffffff  jne 0x463ff2
if(condition(1))goto L463ff2;
}
L4640cb: { // 833d1030770000  cmp dword ptr [0x773010], 0
sub(read((0x773010u),4),0x0u,4);
}
L4640d2: { // 0f841affffff  je 0x463ff2
if(condition(0))goto L463ff2;
}
L4640d8: { // 68c0030000  push 0x3c0
push(0x3c0u);
}
L4640dd: { // 6a38  push 0x38
push(0x38u);
}
L4640df: { // e8a01efaff  call 0x405f84
push(0x4640e4u);dispatch(0x405f84u);
}
L4640e4: { // 898788010000  mov dword ptr [edi + 0x188], eax
write((0x188u+r[7]),get(0,4,0),4);
}
L4640ea: { // c7472014000000  mov dword ptr [edi + 0x20], 0x14
write((0x20u+r[7]),0x14u,4);
}
L4640f1: { // e9fcfeffff  jmp 0x463ff2
goto L463ff2;
}
L4640f6: { // c747200a000000  mov dword ptr [edi + 0x20], 0xa
write((0x20u+r[7]),0xau,4);
}
L4640fd: { // e9f0feffff  jmp 0x463ff2
goto L463ff2;
}
}
// 00464102_spawn_battle_status_panel_objects_464102
void RecoveredBattle::fn_464102(){
goto L464102;
L464102: { // 833dfc64800000  cmp dword ptr [0x8064fc], 0
sub(read((0x8064fcu),4),0x0u,4);
}
L464109: { // 56  push esi
push(get(6,4,0));
}
L46410a: { // be00000300  mov esi, 0x30000
put(6,0x30000u,4,0);
}
L46410f: { // 751e  jne 0x46412f
if(condition(1))goto L46412f;
}
L464111: { // 6a00  push 0
push(0x0u);
}
L464113: { // 56  push esi
push(get(6,4,0));
}
L464114: { // 68e93e4600  push 0x463ee9
push(0x463ee9u);
}
L464119: { // ff35e8566d00  push dword ptr [0x6d56e8]
push(read((0x6d56e8u),4));
}
L46411f: { // e856e6f9ff  call 0x40277a
push(0x464124u);dispatch(0x40277au);
}
L464124: { // 50  push eax
push(get(0,4,0));
}
L464125: { // e897e5f9ff  call 0x4026c1
push(0x46412au);dispatch(0x4026c1u);
}
L46412a: { // a3fc648000  mov dword ptr [0x8064fc], eax
write((0x8064fcu),get(0,4,0),4);
}
L46412f: { // 833df864800000  cmp dword ptr [0x8064f8], 0
sub(read((0x8064f8u),4),0x0u,4);
}
L464136: { // 751e  jne 0x464156
if(condition(1))goto L464156;
}
L464138: { // 6a00  push 0
push(0x0u);
}
L46413a: { // 56  push esi
push(get(6,4,0));
}
L46413b: { // 68fc394600  push 0x4639fc
push(0x4639fcu);
}
L464140: { // ff35e8566d00  push dword ptr [0x6d56e8]
push(read((0x6d56e8u),4));
}
L464146: { // e82fe6f9ff  call 0x40277a
push(0x46414bu);dispatch(0x40277au);
}
L46414b: { // 50  push eax
push(get(0,4,0));
}
L46414c: { // e870e5f9ff  call 0x4026c1
push(0x464151u);dispatch(0x4026c1u);
}
L464151: { // a3f8648000  mov dword ptr [0x8064f8], eax
write((0x8064f8u),get(0,4,0),4);
}
L464156: { // 5e  pop esi
put(6,pop(),4,0);
}
L464157: { // c3  ret 
pop();r[4]+=0;return;
}
}
} // namespace fsb::core
