// Generated by tools/translate_battle.py; edit the generator, not this file.
// Original EXE SHA256: 710881d024ab1fcf738b342c248631363c9de3a51b32a7e3d61781b791eff454
#include "fsb_core/recovered_battle.hpp"
#include <cstring>
#include <cmath>
namespace fsb::core {
// 00464c59_battle_screen_flash_transition_mc_464c59
void RecoveredBattle::fn_464c59(){
goto L464c59;
L464c59: { // 55  push ebp
push(get(5,4,0));
}
L464c5a: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L464c5c: { // 81ec00040000  sub esp, 0x400
put(4,sub(get(4,4,0),0x400u,4,false),4,0);
}
L464c62: { // 56  push esi
push(get(6,4,0));
}
L464c63: { // 33f6  xor esi, esi
put(6,logic(get(6,4,0)^get(6,4,0),4),4,0);
}
L464c65: { // 3935103a5d00  cmp dword ptr [0x5d3a10], esi
sub(read((0x5d3a10u),4),get(6,4,0),4);
}
L464c6b: { // 746a  je 0x464cd7
if(condition(0))goto L464cd7;
}
L464c6d: { // 397508  cmp dword ptr [ebp + 8], esi
sub(read((0x8u+r[5]),4),get(6,4,0),4);
}
L464c70: { // c7055c4a8000ffffff00  mov dword ptr [0x804a5c], 0xffffff
write((0x804a5cu),0xffffffu,4);
}
L464c7a: { // 7429  je 0x464ca5
if(condition(0))goto L464ca5;
}
L464c7c: { // 6800010000  push 0x100
push(0x100u);
}
L464c81: { // 8d8500fcffff  lea eax, [ebp - 0x400]
put(0,(0xfffffc00u+r[5]),4,0);
}
L464c87: { // 56  push esi
push(get(6,4,0));
}
L464c88: { // 50  push eax
push(get(0,4,0));
}
L464c89: { // e8c8fff9ff  call 0x404c56
push(0x464c8eu);dispatch(0x404c56u);
}
L464c8e: { // 6a60  push 0x60
push(0x60u);
}
L464c90: { // 6a32  push 0x32
push(0x32u);
}
L464c92: { // 8d8540fcffff  lea eax, [ebp - 0x3c0]
put(0,(0xfffffc40u+r[5]),4,0);
}
L464c98: { // 68a0468000  push 0x8046a0
push(0x8046a0u);
}
L464c9d: { // 50  push eax
push(get(0,4,0));
}
L464c9e: { // e81801faff  call 0x404dbb
push(0x464ca3u);dispatch(0x404dbbu);
}
L464ca3: { // eb19  jmp 0x464cbe
goto L464cbe;
}
L464ca5: { // 6800040000  push 0x400
push(0x400u);
}
L464caa: { // 8d8500fcffff  lea eax, [ebp - 0x400]
put(0,(0xfffffc00u+r[5]),4,0);
}
L464cb0: { // 6860468000  push 0x804660
push(0x804660u);
}
L464cb5: { // 50  push eax
push(get(0,4,0));
}
L464cb6: { // e8d52a0300  call 0x497790
push(0x464cbbu);dispatch(0x497790u);
}
L464cbb: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L464cbe: { // ff750c  push dword ptr [ebp + 0xc]
push(read((0xcu+r[5]),4));
}
L464cc1: { // 8d8500fcffff  lea eax, [ebp - 0x400]
put(0,(0xfffffc00u+r[5]),4,0);
}
L464cc7: { // 56  push esi
push(get(6,4,0));
}
L464cc8: { // 56  push esi
push(get(6,4,0));
}
L464cc9: { // 50  push eax
push(get(0,4,0));
}
L464cca: { // e89c06faff  call 0x40536b
push(0x464ccfu);dispatch(0x40536bu);
}
L464ccf: { // 8935103a5d00  mov dword ptr [0x5d3a10], esi
write((0x5d3a10u),get(6,4,0),4);
}
L464cd5: { // eb13  jmp 0x464cea
goto L464cea;
}
L464cd7: { // e89608faff  call 0x405572
push(0x464cdcu);dispatch(0x405572u);
}
L464cdc: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L464cde: { // 750a  jne 0x464cea
if(condition(1))goto L464cea;
}
L464ce0: { // c705103a5d0001000000  mov dword ptr [0x5d3a10], 1
write((0x5d3a10u),0x1u,4);
}
L464cea: { // a1103a5d00  mov eax, dword ptr [0x5d3a10]
put(0,read((0x5d3a10u),4),4,0);
}
L464cef: { // 5e  pop esi
put(6,pop(),4,0);
}
L464cf0: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L464cf1: { // c20800  ret 8
pop();r[4]+=0x8u;return;
}
}
// 00464d59_battle_melee_action_dispatch_464d59
void RecoveredBattle::fn_464d59(){
goto L464d59;
L464d59: { // 55  push ebp
push(get(5,4,0));
}
L464d5a: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L464d5c: { // 53  push ebx
push(get(3,4,0));
}
L464d5d: { // 56  push esi
push(get(6,4,0));
}
L464d5e: { // 8b7508  mov esi, dword ptr [ebp + 8]
put(6,read((0x8u+r[5]),4),4,0);
}
L464d61: { // 57  push edi
push(get(7,4,0));
}
L464d62: { // 8b864c010000  mov eax, dword ptr [esi + 0x14c]
put(0,read((0x14cu+r[6]),4),4,0);
}
L464d68: { // 83f897  cmp eax, -0x69
sub(get(0,4,0),0xffffff97u,4);
}
L464d6b: { // 0f8f0e010000  jg 0x464e7f
if(condition(5))goto L464e7f;
}
L464d71: { // 746a  je 0x464ddd
if(condition(0))goto L464ddd;
}
L464d73: { // 83f892  cmp eax, -0x6e
sub(get(0,4,0),0xffffff92u,4);
}
L464d76: { // 0f8514030000  jne 0x465090
if(condition(1))goto L465090;
}
L464d7c: { // 8b0df0598000  mov ecx, dword ptr [0x8059f0]
put(1,read((0x8059f0u),4),4,0);
}
L464d82: { // 6a40  push 0x40
push(0x40u);
}
L464d84: { // 5f  pop edi
put(7,pop(),4,0);
}
L464d85: { // 8b4108  mov eax, dword ptr [ecx + 8]
put(0,read((0x8u+r[1]),4),4,0);
}
L464d88: { // 6a30  push 0x30
push(0x30u);
}
L464d8a: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L464d8b: { // f7ff  idiv edi
divide(get(7,4,0),true);
}
L464d8d: { // 5f  pop edi
put(7,pop(),4,0);
}
L464d8e: { // 894114  mov dword ptr [ecx + 0x14], eax
write((0x14u+r[1]),get(0,4,0),4);
}
L464d91: { // 8b0df0598000  mov ecx, dword ptr [0x8059f0]
put(1,read((0x8059f0u),4),4,0);
}
L464d97: { // 8b410c  mov eax, dword ptr [ecx + 0xc]
put(0,read((0xcu+r[1]),4),4,0);
}
L464d9a: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L464d9b: { // f7ff  idiv edi
divide(get(7,4,0),true);
}
L464d9d: { // 894118  mov dword ptr [ecx + 0x18], eax
write((0x18u+r[1]),get(0,4,0),4);
}
L464da0: { // 8b3df0598000  mov edi, dword ptr [0x8059f0]
put(7,read((0x8059f0u),4),4,0);
}
L464da6: { // b900000100  mov ecx, 0x10000
put(1,0x10000u,4,0);
}
L464dab: { // 8b4714  mov eax, dword ptr [edi + 0x14]
put(0,read((0x14u+r[7]),4),4,0);
}
L464dae: { // 8bd9  mov ebx, ecx
put(3,get(1,4,0),4,0);
}
L464db0: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L464db1: { // f7fb  idiv ebx
divide(get(3,4,0),true);
}
L464db3: { // 898728010000  mov dword ptr [edi + 0x128], eax
write((0x128u+r[7]),get(0,4,0),4);
}
L464db9: { // 8b3df0598000  mov edi, dword ptr [0x8059f0]
put(7,read((0x8059f0u),4),4,0);
}
L464dbf: { // 8b4718  mov eax, dword ptr [edi + 0x18]
put(0,read((0x18u+r[7]),4),4,0);
}
L464dc2: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L464dc3: { // f7fb  idiv ebx
divide(get(3,4,0),true);
}
L464dc5: { // 89872c010000  mov dword ptr [edi + 0x12c], eax
write((0x12cu+r[7]),get(0,4,0),4);
}
L464dcb: { // a1f0598000  mov eax, dword ptr [0x8059f0]
put(0,read((0x8059f0u),4),4,0);
}
L464dd0: { // 094804  or dword ptr [eax + 4], ecx
write((0x4u+r[0]),logic(read((0x4u+r[0]),4)|get(1,4,0),4),4);
}
L464dd3: { // 6683667a00  and word ptr [esi + 0x7a], 0
write((0x7au+r[6]),logic(read((0x7au+r[6]),2)&0x0u,2),2);
}
L464dd8: { // e93a040000  jmp 0x465217
goto L465217;
}
L464ddd: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L464ddf: { // 39050ca57700  cmp dword ptr [0x77a50c], eax
sub(read((0x77a50cu),4),get(0,4,0),4);
}
L464de5: { // 894508  mov dword ptr [ebp + 8], eax
write((0x8u+r[5]),get(0,4,0),4);
}
L464de8: { // 0f8e29040000  jle 0x465217
if(condition(4))goto L465217;
}
L464dee: { // bb903f7700  mov ebx, 0x773f90
put(3,0x773f90u,4,0);
}
L464df3: { // 8bf8  mov edi, eax
put(7,get(0,4,0),4,0);
}
L464df5: { // c1e702  shl edi, 2
put(7,shift(get(7,4,0),0x2u,4,0),4,0);
}
L464df8: { // f6870856800002  test byte ptr [edi + 0x805608], 2
logic(read((0x805608u+r[7]),1)&0x2u,1);
}
L464dff: { // 7411  je 0x464e12
if(condition(0))goto L464e12;
}
L464e01: { // ff33  push dword ptr [ebx]
push(read((0x0u+r[3]),4));
}
L464e03: { // ffb7f8598000  push dword ptr [edi + 0x8059f8]
push(read((0x8059f8u+r[7]),4));
}
L464e09: { // e8b0f8ffff  call 0x4646be
push(0x464e0eu);dispatch(0x4646beu);
}
L464e0e: { // 66ff467c  inc word ptr [esi + 0x7c]
write((0x7cu+r[6]),inc(read((0x7cu+r[6]),2),2,1),2);
}
L464e12: { // f6870856800020  test byte ptr [edi + 0x805608], 0x20
logic(read((0x805608u+r[7]),1)&0x20u,1);
}
L464e19: { // 7415  je 0x464e30
if(condition(0))goto L464e30;
}
L464e1b: { // ff35d0607700  push dword ptr [0x7760d0]
push(read((0x7760d0u),4));
}
L464e21: { // ff35f0598000  push dword ptr [0x8059f0]
push(read((0x8059f0u),4));
}
L464e27: { // e892f8ffff  call 0x4646be
push(0x464e2cu);dispatch(0x4646beu);
}
L464e2c: { // 66ff467c  inc word ptr [esi + 0x7c]
write((0x7cu+r[6]),inc(read((0x7cu+r[6]),2),2,1),2);
}
L464e30: { // f6870856800008  test byte ptr [edi + 0x805608], 8
logic(read((0x805608u+r[7]),1)&0x8u,1);
}
L464e37: { // 7411  je 0x464e4a
if(condition(0))goto L464e4a;
}
L464e39: { // ff33  push dword ptr [ebx]
push(read((0x0u+r[3]),4));
}
L464e3b: { // ffb7f8598000  push dword ptr [edi + 0x8059f8]
push(read((0x8059f8u+r[7]),4));
}
L464e41: { // e867f9ffff  call 0x4647ad
push(0x464e46u);dispatch(0x4647adu);
}
L464e46: { // 66ff467c  inc word ptr [esi + 0x7c]
write((0x7cu+r[6]),inc(read((0x7cu+r[6]),2),2,1),2);
}
L464e4a: { // f6870856800080  test byte ptr [edi + 0x805608], 0x80
logic(read((0x805608u+r[7]),1)&0x80u,1);
}
L464e51: { // 7411  je 0x464e64
if(condition(0))goto L464e64;
}
L464e53: { // ff33  push dword ptr [ebx]
push(read((0x0u+r[3]),4));
}
L464e55: { // ffb7f8598000  push dword ptr [edi + 0x8059f8]
push(read((0x8059f8u+r[7]),4));
}
L464e5b: { // e84df9ffff  call 0x4647ad
push(0x464e60u);dispatch(0x4647adu);
}
L464e60: { // 66ff467c  inc word ptr [esi + 0x7c]
write((0x7cu+r[6]),inc(read((0x7cu+r[6]),2),2,1),2);
}
L464e64: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L464e67: { // 83c310  add ebx, 0x10
put(3,add(get(3,4,0),0x10u,4,false),4,0);
}
L464e6a: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L464e6b: { // 3b050ca57700  cmp eax, dword ptr [0x77a50c]
sub(get(0,4,0),read((0x77a50cu),4),4);
}
L464e71: { // 894508  mov dword ptr [ebp + 8], eax
write((0x8u+r[5]),get(0,4,0),4);
}
L464e74: { // 0f8c79ffffff  jl 0x464df3
if(condition(2))goto L464df3;
}
L464e7a: { // e998030000  jmp 0x465217
goto L465217;
}
L464e7f: { // 83f8ec  cmp eax, -0x14
sub(get(0,4,0),0xffffffecu,4);
}
L464e82: { // 0f8f80010000  jg 0x465008
if(condition(5))goto L465008;
}
L464e88: { // 0f8471010000  je 0x464fff
if(condition(0))goto L464fff;
}
L464e8e: { // 83f89c  cmp eax, -0x64
sub(get(0,4,0),0xffffff9cu,4);
}
L464e91: { // 0f85f9010000  jne 0x465090
if(condition(1))goto L465090;
}
L464e97: { // 83650800  and dword ptr [ebp + 8], 0
write((0x8u+r[5]),logic(read((0x8u+r[5]),4)&0x0u,4),4);
}
L464e9b: { // 833d0ca5770000  cmp dword ptr [0x77a50c], 0
sub(read((0x77a50cu),4),0x0u,4);
}
L464ea2: { // 0f8e6f030000  jle 0x465217
if(condition(4))goto L465217;
}
L464ea8: { // 8d7e3c  lea edi, [esi + 0x3c]
put(7,(0x3cu+r[6]),4,0);
}
L464eab: { // bbfffffeff  mov ebx, 0xfffeffff
put(3,0xfffeffffu,4,0);
}
L464eb0: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L464eb3: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L464eb5: { // c1e602  shl esi, 2
put(6,shift(get(6,4,0),0x2u,4,0),4,0);
}
L464eb8: { // f6860856800001  test byte ptr [esi + 0x805608], 1
logic(read((0x805608u+r[6]),1)&0x1u,1);
}
L464ebf: { // 743e  je 0x464eff
if(condition(0))goto L464eff;
}
L464ec1: { // ffb6f8598000  push dword ptr [esi + 0x8059f8]
push(read((0x8059f8u+r[6]),4));
}
L464ec7: { // 8db6f8598000  lea esi, [esi + 0x8059f8]
put(6,(0x8059f8u+r[6]),4,0);
}
L464ecd: { // e89a8cffff  call 0x45db6c
push(0x464ed2u);dispatch(0x45db6cu);
}
L464ed2: { // a1f0598000  mov eax, dword ptr [0x8059f0]
put(0,read((0x8059f0u),4),4,0);
}
L464ed7: { // 8b8010010000  mov eax, dword ptr [eax + 0x110]
put(0,read((0x110u+r[0]),4),4,0);
}
L464edd: { // 8b048598f45b00  mov eax, dword ptr [eax*4 + 0x5bf498]
put(0,read((0x5bf498u+r[0]*4u),4),4,0);
}
L464ee4: { // ff3485882c5d00  push dword ptr [eax*4 + 0x5d2c88]
push(read((0x5d2c88u+r[0]*4u),4));
}
L464eeb: { // ff36  push dword ptr [esi]
push(read((0x0u+r[6]),4));
}
L464eed: { // e84f29feff  call 0x447841
push(0x464ef2u);dispatch(0x447841u);
}
L464ef2: { // 8b36  mov esi, dword ptr [esi]
put(6,read((0x0u+r[6]),4),4,0);
}
L464ef4: { // 215e04  and dword ptr [esi + 4], ebx
write((0x4u+r[6]),logic(read((0x4u+r[6]),4)&get(3,4,0),4),4);
}
L464ef7: { // 800f01  or byte ptr [edi], 1
write((0x0u+r[7]),logic(read((0x0u+r[7]),1)|0x1u,1),1);
}
L464efa: { // e9e7000000  jmp 0x464fe6
goto L464fe6;
}
L464eff: { // ffb6f8598000  push dword ptr [esi + 0x8059f8]
push(read((0x8059f8u+r[6]),4));
}
L464f05: { // e8628cffff  call 0x45db6c
push(0x464f0au);dispatch(0x45db6cu);
}
L464f0a: { // a1f0598000  mov eax, dword ptr [0x8059f0]
put(0,read((0x8059f0u),4),4,0);
}
L464f0f: { // 8b8010010000  mov eax, dword ptr [eax + 0x110]
put(0,read((0x110u+r[0]),4),4,0);
}
L464f15: { // 8b048598f45b00  mov eax, dword ptr [eax*4 + 0x5bf498]
put(0,read((0x5bf498u+r[0]*4u),4),4,0);
}
L464f1c: { // ff3485182b5d00  push dword ptr [eax*4 + 0x5d2b18]
push(read((0x5d2b18u+r[0]*4u),4));
}
L464f23: { // ffb6f8598000  push dword ptr [esi + 0x8059f8]
push(read((0x8059f8u+r[6]),4));
}
L464f29: { // e81329feff  call 0x447841
push(0x464f2eu);dispatch(0x447841u);
}
L464f2e: { // 8b86f8598000  mov eax, dword ptr [esi + 0x8059f8]
put(0,read((0x8059f8u+r[6]),4),4,0);
}
L464f34: { // ff7510  push dword ptr [ebp + 0x10]
push(read((0x10u+r[5]),4));
}
L464f37: { // 215804  and dword ptr [eax + 4], ebx
write((0x4u+r[0]),logic(read((0x4u+r[0]),4)&get(3,4,0),4),4);
}
L464f3a: { // 800f01  or byte ptr [edi], 1
write((0x0u+r[7]),logic(read((0x0u+r[7]),1)|0x1u,1),1);
}
L464f3d: { // 8b86f8598000  mov eax, dword ptr [esi + 0x8059f8]
put(0,read((0x8059f8u+r[6]),4),4,0);
}
L464f43: { // ff701c  push dword ptr [eax + 0x1c]
push(read((0x1cu+r[0]),4));
}
L464f46: { // e845310300  call 0x498090
push(0x464f4bu);dispatch(0x498090u);
}
L464f4b: { // 6a10  push 0x10
push(0x10u);
}
L464f4d: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L464f4e: { // 59  pop ecx
put(1,pop(),4,0);
}
L464f4f: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L464f51: { // 8b86f8598000  mov eax, dword ptr [esi + 0x8059f8]
put(0,read((0x8059f8u+r[6]),4),4,0);
}
L464f57: { // 81c2b8010000  add edx, 0x1b8
put(2,add(get(2,4,0),0x1b8u,4,false),4,0);
}
L464f5d: { // c1e210  shl edx, 0x10
put(2,shift(get(2,4,0),0x10u,4,0),4,0);
}
L464f60: { // 035010  add edx, dword ptr [eax + 0x10]
put(2,add(get(2,4,0),read((0x10u+r[0]),4),4,false),4,0);
}
L464f63: { // 52  push edx
push(get(2,4,0));
}
L464f64: { // e827310300  call 0x498090
push(0x464f69u);dispatch(0x498090u);
}
L464f69: { // 6a10  push 0x10
push(0x10u);
}
L464f6b: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L464f6c: { // 59  pop ecx
put(1,pop(),4,0);
}
L464f6d: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L464f6f: { // 8b86f8598000  mov eax, dword ptr [esi + 0x8059f8]
put(0,read((0x8059f8u+r[6]),4),4,0);
}
L464f75: { // 81c288010000  add edx, 0x188
put(2,add(get(2,4,0),0x188u,4,false),4,0);
}
L464f7b: { // c1e210  shl edx, 0x10
put(2,shift(get(2,4,0),0x10u,4,0),4,0);
}
L464f7e: { // 03500c  add edx, dword ptr [eax + 0xc]
put(2,add(get(2,4,0),read((0xcu+r[0]),4),4,false),4,0);
}
L464f81: { // 52  push edx
push(get(2,4,0));
}
L464f82: { // e809310300  call 0x498090
push(0x464f87u);dispatch(0x498090u);
}
L464f87: { // 6a10  push 0x10
push(0x10u);
}
L464f89: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L464f8a: { // 59  pop ecx
put(1,pop(),4,0);
}
L464f8b: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L464f8d: { // 8b86f8598000  mov eax, dword ptr [esi + 0x8059f8]
put(0,read((0x8059f8u+r[6]),4),4,0);
}
L464f93: { // 83ea08  sub edx, 8
put(2,sub(get(2,4,0),0x8u,4,false),4,0);
}
L464f96: { // c1e210  shl edx, 0x10
put(2,shift(get(2,4,0),0x10u,4,0),4,0);
}
L464f99: { // 035008  add edx, dword ptr [eax + 8]
put(2,add(get(2,4,0),read((0x8u+r[0]),4),4,false),4,0);
}
L464f9c: { // 52  push edx
push(get(2,4,0));
}
L464f9d: { // e885fcffff  call 0x464c27
push(0x464fa2u);dispatch(0x464c27u);
}
L464fa2: { // a1f0598000  mov eax, dword ptr [0x8059f0]
put(0,read((0x8059f0u),4),4,0);
}
L464fa7: { // 8bb6f8598000  mov esi, dword ptr [esi + 0x8059f8]
put(6,read((0x8059f8u+r[6]),4),4,0);
}
L464fad: { // 8b8010010000  mov eax, dword ptr [eax + 0x110]
put(0,read((0x110u+r[0]),4),4,0);
}
L464fb3: { // ff3485402f5d00  push dword ptr [eax*4 + 0x5d2f40]
push(read((0x5d2f40u+r[0]*4u),4));
}
L464fba: { // 8b4610  mov eax, dword ptr [esi + 0x10]
put(0,read((0x10u+r[6]),4),4,0);
}
L464fbd: { // 050000c001  add eax, 0x1c00000
put(0,add(get(0,4,0),0x1c00000u,4,false),4,0);
}
L464fc2: { // ff761c  push dword ptr [esi + 0x1c]
push(read((0x1cu+r[6]),4));
}
L464fc5: { // 50  push eax
push(get(0,4,0));
}
L464fc6: { // 8b460c  mov eax, dword ptr [esi + 0xc]
put(0,read((0xcu+r[6]),4),4,0);
}
L464fc9: { // 0500009001  add eax, 0x1900000
put(0,add(get(0,4,0),0x1900000u,4,false),4,0);
}
L464fce: { // 50  push eax
push(get(0,4,0));
}
L464fcf: { // ff7608  push dword ptr [esi + 8]
push(read((0x8u+r[6]),4));
}
L464fd2: { // e850fcffff  call 0x464c27
push(0x464fd7u);dispatch(0x464c27u);
}
L464fd7: { // a1143a5d00  mov eax, dword ptr [0x5d3a14]
put(0,read((0x5d3a14u),4),4,0);
}
L464fdc: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L464fde: { // 7c06  jl 0x464fe6
if(condition(2))goto L464fe6;
}
L464fe0: { // 50  push eax
push(get(0,4,0));
}
L464fe1: { // e88d03fdff  call 0x435373
push(0x464fe6u);dispatch(0x435373u);
}
L464fe6: { // ff4508  inc dword ptr [ebp + 8]
write((0x8u+r[5]),inc(read((0x8u+r[5]),4),4,1),4);
}
L464fe9: { // 47  inc edi
put(7,inc(get(7,4,0),4,1),4,0);
}
L464fea: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L464fed: { // 47  inc edi
put(7,inc(get(7,4,0),4,1),4,0);
}
L464fee: { // 3b050ca57700  cmp eax, dword ptr [0x77a50c]
sub(get(0,4,0),read((0x77a50cu),4),4);
}
L464ff4: { // 0f8cb6feffff  jl 0x464eb0
if(condition(2))goto L464eb0;
}
L464ffa: { // e918020000  jmp 0x465217
goto L465217;
}
L464fff: { // 66ff4e7c  dec word ptr [esi + 0x7c]
write((0x7cu+r[6]),inc(read((0x7cu+r[6]),2),2,-1),2);
}
L465003: { // e90f020000  jmp 0x465217
goto L465217;
}
L465008: { // 83f8fe  cmp eax, -2
sub(get(0,4,0),0xfffffffeu,4);
}
L46500b: { // 7f54  jg 0x465061
if(condition(5))goto L465061;
}
L46500d: { // 7446  je 0x465055
if(condition(0))goto L465055;
}
L46500f: { // 83f8f4  cmp eax, -0xc
sub(get(0,4,0),0xfffffff4u,4);
}
L465012: { // 7c7c  jl 0x465090
if(condition(2))goto L465090;
}
L465014: { // 83f8f6  cmp eax, -0xa
sub(get(0,4,0),0xfffffff6u,4);
}
L465017: { // 7f77  jg 0x465090
if(condition(5))goto L465090;
}
L465019: { // a10ca57700  mov eax, dword ptr [0x77a50c]
put(0,read((0x77a50cu),4),4,0);
}
L46501e: { // 33c9  xor ecx, ecx
put(1,logic(get(1,4,0)^get(1,4,0),4),4,0);
}
L465020: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L465022: { // 7e17  jle 0x46503b
if(condition(4))goto L46503b;
}
L465024: { // 8bbea8010000  mov edi, dword ptr [esi + 0x1a8]
put(7,read((0x1a8u+r[6]),4),4,0);
}
L46502a: { // baf8598000  mov edx, 0x8059f8
put(2,0x8059f8u,4,0);
}
L46502f: { // 393a  cmp dword ptr [edx], edi
sub(read((0x0u+r[2]),4),get(7,4,0),4);
}
L465031: { // 7408  je 0x46503b
if(condition(0))goto L46503b;
}
L465033: { // 41  inc ecx
put(1,inc(get(1,4,0),4,1),4,0);
}
L465034: { // 83c204  add edx, 4
put(2,add(get(2,4,0),0x4u,4,false),4,0);
}
L465037: { // 3bc8  cmp ecx, eax
sub(get(1,4,0),get(0,4,0),4);
}
L465039: { // 7cf4  jl 0x46502f
if(condition(2))goto L46502f;
}
L46503b: { // 8b86a8010000  mov eax, dword ptr [esi + 0x1a8]
put(0,read((0x1a8u+r[6]),4),4,0);
}
L465041: { // 80480601  or byte ptr [eax + 6], 1
write((0x6u+r[0]),logic(read((0x6u+r[0]),1)|0x1u,1),1);
}
L465045: { // 6681644e3cfeff  and word ptr [esi + ecx*2 + 0x3c], 0xfffe
write((0x3cu+r[6]+r[1]*2u),logic(read((0x3cu+r[6]+r[1]*2u),2)&0xfffeu,2),2);
}
L46504c: { // 8d444e3c  lea eax, [esi + ecx*2 + 0x3c]
put(0,(0x3cu+r[6]+r[1]*2u),4,0);
}
L465050: { // e9c2010000  jmp 0x465217
goto L465217;
}
L465055: { // 830d143a5d00ff  or dword ptr [0x5d3a14], 0xffffffff
write((0x5d3a14u),logic(read((0x5d3a14u),4)|0xffffffffu,4),4);
}
L46505c: { // e9b6010000  jmp 0x465217
goto L465217;
}
L465061: { // 83f8ff  cmp eax, -1
sub(get(0,4,0),0xffffffffu,4);
}
L465064: { // 0f8496010000  je 0x465200
if(condition(0))goto L465200;
}
L46506a: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L46506c: { // 3bc7  cmp eax, edi
sub(get(0,4,0),get(7,4,0),4);
}
L46506e: { // 0f8420010000  je 0x465194
if(condition(0))goto L465194;
}
L465074: { // 83f80a  cmp eax, 0xa
sub(get(0,4,0),0xau,4);
}
L465077: { // 0f84ea000000  je 0x465167
if(condition(0))goto L465167;
}
L46507d: { // 83f814  cmp eax, 0x14
sub(get(0,4,0),0x14u,4);
}
L465080: { // 0f849c000000  je 0x465122
if(condition(0))goto L465122;
}
L465086: { // 83f81e  cmp eax, 0x1e
sub(get(0,4,0),0x1eu,4);
}
L465089: { // 742f  je 0x4650ba
if(condition(0))goto L4650ba;
}
L46508b: { // 83f828  cmp eax, 0x28
sub(get(0,4,0),0x28u,4);
}
L46508e: { // 7412  je 0x4650a2
if(condition(0))goto L4650a2;
}
L465090: { // 50  push eax
push(get(0,4,0));
}
L465091: { // 68bc425d00  push 0x5d42bc
push(0x5d42bcu);
}
L465096: { // e83dcaf9ff  call 0x401ad8
push(0x46509bu);dispatch(0x401ad8u);
}
L46509b: { // 59  pop ecx
put(1,pop(),4,0);
}
L46509c: { // 59  pop ecx
put(1,pop(),4,0);
}
L46509d: { // e975010000  jmp 0x465217
goto L465217;
}
L4650a2: { // e80fd2ffff  call 0x4622b6
push(0x4650a7u);dispatch(0x4622b6u);
}
L4650a7: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L4650a9: { // 0f8468010000  je 0x465217
if(condition(0))goto L465217;
}
L4650af: { // 56  push esi
push(get(6,4,0));
}
L4650b0: { // e86888ffff  call 0x45d91d
push(0x4650b5u);dispatch(0x45d91du);
}
L4650b5: { // e95d010000  jmp 0x465217
goto L465217;
}
L4650ba: { // 8b3d78747800  mov edi, dword ptr [0x787478]
put(7,read((0x787478u),4),4,0);
}
L4650c0: { // b900000100  mov ecx, 0x10000
put(1,0x10000u,4,0);
}
L4650c5: { // 69ffac010000  imul edi, edi, 0x1ac
put(7,multiply(get(7,4,0),0x1acu,4),4,0);
}
L4650cb: { // 8bd9  mov ebx, ecx
put(3,get(1,4,0),4,0);
}
L4650cd: { // 8b87e4738000  mov eax, dword ptr [edi + 0x8073e4]
put(0,read((0x8073e4u+r[7]),4),4,0);
}
L4650d3: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4650d4: { // f7fb  idiv ebx
divide(get(3,4,0),true);
}
L4650d6: { // 8bd8  mov ebx, eax
put(3,get(0,4,0),4,0);
}
L4650d8: { // a140146e00  mov eax, dword ptr [0x6e1440]
put(0,read((0x6e1440u),4),4,0);
}
L4650dd: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4650de: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L4650e0: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L4650e2: { // 03d8  add ebx, eax
put(3,add(get(3,4,0),get(0,4,0),4,false),4,0);
}
L4650e4: { // a170b47400  mov eax, dword ptr [0x74b470]
put(0,read((0x74b470u),4),4,0);
}
L4650e9: { // 2b1dc4737800  sub ebx, dword ptr [0x7873c4]
put(3,sub(get(3,4,0),read((0x7873c4u),4),4,false),4,0);
}
L4650ef: { // 8d4403e8  lea eax, [ebx + eax - 0x18]
put(0,(0xffffffe8u+r[3]+r[0]*1u),4,0);
}
L4650f3: { // 50  push eax
push(get(0,4,0));
}
L4650f4: { // 8b87e0738000  mov eax, dword ptr [edi + 0x8073e0]
put(0,read((0x8073e0u+r[7]),4),4,0);
}
L4650fa: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4650fb: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L4650fd: { // 8bc8  mov ecx, eax
put(1,get(0,4,0),4,0);
}
L4650ff: { // a1b0126e00  mov eax, dword ptr [0x6e12b0]
put(0,read((0x6e12b0u),4),4,0);
}
L465104: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L465105: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L465107: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L465109: { // 03c8  add ecx, eax
put(1,add(get(1,4,0),get(0,4,0),4,false),4,0);
}
L46510b: { // 2b0dc0737800  sub ecx, dword ptr [0x7873c0]
put(1,sub(get(1,4,0),read((0x7873c0u),4),4,false),4,0);
}
L465111: { // 030d68146e00  add ecx, dword ptr [0x6e1468]
put(1,add(get(1,4,0),read((0x6e1468u),4),4,false),4,0);
}
L465117: { // 51  push ecx
push(get(1,4,0));
}
L465118: { // e8e6d0ffff  call 0x462203
push(0x46511du);dispatch(0x462203u);
}
L46511d: { // e9d5000000  jmp 0x4651f7
goto L4651f7;
}
L465122: { // 66397e7a  cmp word ptr [esi + 0x7a], di
sub(read((0x7au+r[6]),2),get(7,2,0),2);
}
L465126: { // 0f85eb000000  jne 0x465217
if(condition(1))goto L465217;
}
L46512c: { // 66397e7c  cmp word ptr [esi + 0x7c], di
sub(read((0x7cu+r[6]),2),get(7,2,0),2);
}
L465130: { // 0f85e1000000  jne 0x465217
if(condition(1))goto L465217;
}
L465136: { // a10ca57700  mov eax, dword ptr [0x77a50c]
put(0,read((0x77a50cu),4),4,0);
}
L46513b: { // 33d2  xor edx, edx
put(2,logic(get(2,4,0)^get(2,4,0),4),4,0);
}
L46513d: { // 3bc7  cmp eax, edi
sub(get(0,4,0),get(7,4,0),4);
}
L46513f: { // 7e0f  jle 0x465150
if(condition(4))goto L465150;
}
L465141: { // 8d4e3c  lea ecx, [esi + 0x3c]
put(1,(0x3cu+r[6]),4,0);
}
L465144: { // 663939  cmp word ptr [ecx], di
sub(read((0x0u+r[1]),2),get(7,2,0),2);
}
L465147: { // 7507  jne 0x465150
if(condition(1))goto L465150;
}
L465149: { // 42  inc edx
put(2,inc(get(2,4,0),4,1),4,0);
}
L46514a: { // 41  inc ecx
put(1,inc(get(1,4,0),4,1),4,0);
}
L46514b: { // 41  inc ecx
put(1,inc(get(1,4,0),4,1),4,0);
}
L46514c: { // 3bd0  cmp edx, eax
sub(get(2,4,0),get(0,4,0),4);
}
L46514e: { // 7cf4  jl 0x465144
if(condition(2))goto L465144;
}
L465150: { // 3bd0  cmp edx, eax
sub(get(2,4,0),get(0,4,0),4);
}
L465152: { // 0f85bf000000  jne 0x465217
if(condition(1))goto L465217;
}
L465158: { // c7864c0100001e000000  mov dword ptr [esi + 0x14c], 0x1e
write((0x14cu+r[6]),0x1eu,4);
}
L465162: { // e9b0000000  jmp 0x465217
goto L465217;
}
L465167: { // e84ad1ffff  call 0x4622b6
push(0x46516cu);dispatch(0x4622b6u);
}
L46516c: { // a1f0598000  mov eax, dword ptr [0x8059f0]
put(0,read((0x8059f0u),4),4,0);
}
L465171: { // 8b550c  mov edx, dword ptr [ebp + 0xc]
put(2,read((0xcu+r[5]),4),4,0);
}
L465174: { // 8b8810010000  mov ecx, dword ptr [eax + 0x110]
put(1,read((0x110u+r[0]),4),4,0);
}
L46517a: { // ff348a  push dword ptr [edx + ecx*4]
push(read((0x0u+r[2]+r[1]*4u),4));
}
L46517d: { // 50  push eax
push(get(0,4,0));
}
L46517e: { // e8be26feff  call 0x447841
push(0x465183u);dispatch(0x447841u);
}
L465183: { // a1f0598000  mov eax, dword ptr [0x8059f0]
put(0,read((0x8059f0u),4),4,0);
}
L465188: { // 806006fe  and byte ptr [eax + 6], 0xfe
write((0x6u+r[0]),logic(read((0x6u+r[0]),1)&0xfeu,1),1);
}
L46518c: { // 66c7467a0100  mov word ptr [esi + 0x7a], 1
write((0x7au+r[6]),0x1u,2);
}
L465192: { // eb63  jmp 0x4651f7
goto L4651f7;
}
L465194: { // 8b3d78747800  mov edi, dword ptr [0x787478]
put(7,read((0x787478u),4),4,0);
}
L46519a: { // b900000100  mov ecx, 0x10000
put(1,0x10000u,4,0);
}
L46519f: { // 69ffac010000  imul edi, edi, 0x1ac
put(7,multiply(get(7,4,0),0x1acu,4),4,0);
}
L4651a5: { // 8bd9  mov ebx, ecx
put(3,get(1,4,0),4,0);
}
L4651a7: { // 8b87e4738000  mov eax, dword ptr [edi + 0x8073e4]
put(0,read((0x8073e4u+r[7]),4),4,0);
}
L4651ad: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4651ae: { // f7fb  idiv ebx
divide(get(3,4,0),true);
}
L4651b0: { // 8bd8  mov ebx, eax
put(3,get(0,4,0),4,0);
}
L4651b2: { // a140146e00  mov eax, dword ptr [0x6e1440]
put(0,read((0x6e1440u),4),4,0);
}
L4651b7: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4651b8: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L4651ba: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L4651bc: { // 03d8  add ebx, eax
put(3,add(get(3,4,0),get(0,4,0),4,false),4,0);
}
L4651be: { // a170b47400  mov eax, dword ptr [0x74b470]
put(0,read((0x74b470u),4),4,0);
}
L4651c3: { // 2b1dc4737800  sub ebx, dword ptr [0x7873c4]
put(3,sub(get(3,4,0),read((0x7873c4u),4),4,false),4,0);
}
L4651c9: { // 8d4403e8  lea eax, [ebx + eax - 0x18]
put(0,(0xffffffe8u+r[3]+r[0]*1u),4,0);
}
L4651cd: { // 50  push eax
push(get(0,4,0));
}
L4651ce: { // 8b87e0738000  mov eax, dword ptr [edi + 0x8073e0]
put(0,read((0x8073e0u+r[7]),4),4,0);
}
L4651d4: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4651d5: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L4651d7: { // 8bc8  mov ecx, eax
put(1,get(0,4,0),4,0);
}
L4651d9: { // a1b0126e00  mov eax, dword ptr [0x6e12b0]
put(0,read((0x6e12b0u),4),4,0);
}
L4651de: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4651df: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L4651e1: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L4651e3: { // 03c8  add ecx, eax
put(1,add(get(1,4,0),get(0,4,0),4,false),4,0);
}
L4651e5: { // 2b0dc0737800  sub ecx, dword ptr [0x7873c0]
put(1,sub(get(1,4,0),read((0x7873c0u),4),4,false),4,0);
}
L4651eb: { // 030d68146e00  add ecx, dword ptr [0x6e1468]
put(1,add(get(1,4,0),read((0x6e1468u),4),4,false),4,0);
}
L4651f1: { // 51  push ecx
push(get(1,4,0));
}
L4651f2: { // e859cfffff  call 0x462150
push(0x4651f7u);dispatch(0x462150u);
}
L4651f7: { // 83864c0100000a  add dword ptr [esi + 0x14c], 0xa
write((0x14cu+r[6]),add(read((0x14cu+r[6]),4),0xau,4,false),4);
}
L4651fe: { // eb17  jmp 0x465217
goto L465217;
}
L465200: { // 830d143a5d00ff  or dword ptr [0x5d3a14], 0xffffffff
write((0x5d3a14u),logic(read((0x5d3a14u),4)|0xffffffffu,4),4);
}
L465207: { // 6a40  push 0x40
push(0x40u);
}
L465209: { // 83c63c  add esi, 0x3c
put(6,add(get(6,4,0),0x3cu,4,false),4,0);
}
L46520c: { // 6a00  push 0
push(0x0u);
}
L46520e: { // 56  push esi
push(get(6,4,0));
}
L46520f: { // e85c2b0300  call 0x497d70
push(0x465214u);dispatch(0x497d70u);
}
L465214: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L465217: { // 5f  pop edi
put(7,pop(),4,0);
}
L465218: { // 5e  pop esi
put(6,pop(),4,0);
}
L465219: { // 5b  pop ebx
put(3,pop(),4,0);
}
L46521a: { // 5d  pop ebp
put(5,pop(),4,0);
}
L46521b: { // c20c00  ret 0xc
pop();r[4]+=0xcu;return;
}
}
// 0046542d_battle_status_phase_gate_sequence_mc_46542d
void RecoveredBattle::fn_46542d(){
goto L46542d;
L46542d: { // 53  push ebx
push(get(3,4,0));
}
L46542e: { // 56  push esi
push(get(6,4,0));
}
L46542f: { // 8b74240c  mov esi, dword ptr [esp + 0xc]
put(6,read((0xcu+r[4]),4),4,0);
}
L465433: { // b938ffffff  mov ecx, 0xffffff38
put(1,0xffffff38u,4,0);
}
L465438: { // 57  push edi
push(get(7,4,0));
}
L465439: { // 8b864c010000  mov eax, dword ptr [esi + 0x14c]
put(0,read((0x14cu+r[6]),4),4,0);
}
L46543f: { // 3bc1  cmp eax, ecx
sub(get(0,4,0),get(1,4,0),4);
}
L465441: { // 7f7b  jg 0x4654be
if(condition(5))goto L4654be;
}
L465443: { // 7443  je 0x465488
if(condition(0))goto L465488;
}
L465445: { // 3d06ffffff  cmp eax, 0xffffff06
sub(get(0,4,0),0xffffff06u,4);
}
L46544a: { // 0f85d8010000  jne 0x465628
if(condition(1))goto L465628;
}
L465450: { // a10ca57700  mov eax, dword ptr [0x77a50c]
put(0,read((0x77a50cu),4),4,0);
}
L465455: { // 33d2  xor edx, edx
put(2,logic(get(2,4,0)^get(2,4,0),4),4,0);
}
L465457: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L465459: { // 7e17  jle 0x465472
if(condition(4))goto L465472;
}
L46545b: { // 8bb6a8010000  mov esi, dword ptr [esi + 0x1a8]
put(6,read((0x1a8u+r[6]),4),4,0);
}
L465461: { // b9f8598000  mov ecx, 0x8059f8
put(1,0x8059f8u,4,0);
}
L465466: { // 3931  cmp dword ptr [ecx], esi
sub(read((0x0u+r[1]),4),get(6,4,0),4);
}
L465468: { // 7408  je 0x465472
if(condition(0))goto L465472;
}
L46546a: { // 42  inc edx
put(2,inc(get(2,4,0),4,1),4,0);
}
L46546b: { // 83c104  add ecx, 4
put(1,add(get(1,4,0),0x4u,4,false),4,0);
}
L46546e: { // 3bd0  cmp edx, eax
sub(get(2,4,0),get(0,4,0),4);
}
L465470: { // 7cf4  jl 0x465466
if(condition(2))goto L465466;
}
L465472: { // 8b3495f8598000  mov esi, dword ptr [edx*4 + 0x8059f8]
put(6,read((0x8059f8u+r[2]*4u),4),4,0);
}
L465479: { // 56  push esi
push(get(6,4,0));
}
L46547a: { // e85affffff  call 0x4653d9
push(0x46547fu);dispatch(0x4653d9u);
}
L46547f: { // 806606fe  and byte ptr [esi + 6], 0xfe
write((0x6u+r[6]),logic(read((0x6u+r[6]),1)&0xfeu,1),1);
}
L465483: { // e9a0010000  jmp 0x465628
goto L465628;
}
L465488: { // a10ca57700  mov eax, dword ptr [0x77a50c]
put(0,read((0x77a50cu),4),4,0);
}
L46548d: { // 33c9  xor ecx, ecx
put(1,logic(get(1,4,0)^get(1,4,0),4),4,0);
}
L46548f: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L465491: { // 7e17  jle 0x4654aa
if(condition(4))goto L4654aa;
}
L465493: { // 8bbea8010000  mov edi, dword ptr [esi + 0x1a8]
put(7,read((0x1a8u+r[6]),4),4,0);
}
L465499: { // baf8598000  mov edx, 0x8059f8
put(2,0x8059f8u,4,0);
}
L46549e: { // 393a  cmp dword ptr [edx], edi
sub(read((0x0u+r[2]),4),get(7,4,0),4);
}
L4654a0: { // 7408  je 0x4654aa
if(condition(0))goto L4654aa;
}
L4654a2: { // 41  inc ecx
put(1,inc(get(1,4,0),4,1),4,0);
}
L4654a3: { // 83c204  add edx, 4
put(2,add(get(2,4,0),0x4u,4,false),4,0);
}
L4654a6: { // 3bc8  cmp ecx, eax
sub(get(1,4,0),get(0,4,0),4);
}
L4654a8: { // 7cf4  jl 0x46549e
if(condition(2))goto L46549e;
}
L4654aa: { // 8b048df8598000  mov eax, dword ptr [ecx*4 + 0x8059f8]
put(0,read((0x8059f8u+r[1]*4u),4),4,0);
}
L4654b1: { // 80480601  or byte ptr [eax + 6], 1
write((0x6u+r[0]),logic(read((0x6u+r[0]),1)|0x1u,1),1);
}
L4654b5: { // 66ff4e78  dec word ptr [esi + 0x78]
write((0x78u+r[6]),inc(read((0x78u+r[6]),2),2,-1),2);
}
L4654b9: { // e96a010000  jmp 0x465628
goto L465628;
}
L4654be: { // 83f8ec  cmp eax, -0x14
sub(get(0,4,0),0xffffffecu,4);
}
L4654c1: { // 7f49  jg 0x46550c
if(condition(5))goto L46550c;
}
L4654c3: { // 743e  je 0x465503
if(condition(0))goto L465503;
}
L4654c5: { // 83f89c  cmp eax, -0x64
sub(get(0,4,0),0xffffff9cu,4);
}
L4654c8: { // 0f855a010000  jne 0x465628
if(condition(1))goto L465628;
}
L4654ce: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L4654d0: { // 393d0ca57700  cmp dword ptr [0x77a50c], edi
sub(read((0x77a50cu),4),get(7,4,0),4);
}
L4654d6: { // 7e1c  jle 0x4654f4
if(condition(4))goto L4654f4;
}
L4654d8: { // bbf8598000  mov ebx, 0x8059f8
put(3,0x8059f8u,4,0);
}
L4654dd: { // ff33  push dword ptr [ebx]
push(read((0x0u+r[3]),4));
}
L4654df: { // e846feffff  call 0x46532a
push(0x4654e4u);dispatch(0x46532au);
}
L4654e4: { // 66ff4678  inc word ptr [esi + 0x78]
write((0x78u+r[6]),inc(read((0x78u+r[6]),2),2,1),2);
}
L4654e8: { // 47  inc edi
put(7,inc(get(7,4,0),4,1),4,0);
}
L4654e9: { // 83c304  add ebx, 4
put(3,add(get(3,4,0),0x4u,4,false),4,0);
}
L4654ec: { // 3b3d0ca57700  cmp edi, dword ptr [0x77a50c]
sub(get(7,4,0),read((0x77a50cu),4),4);
}
L4654f2: { // 7ce9  jl 0x4654dd
if(condition(2))goto L4654dd;
}
L4654f4: { // c7864c0100001e000000  mov dword ptr [esi + 0x14c], 0x1e
write((0x14cu+r[6]),0x1eu,4);
}
L4654fe: { // e925010000  jmp 0x465628
goto L465628;
}
L465503: { // 66ff4e7a  dec word ptr [esi + 0x7a]
write((0x7au+r[6]),inc(read((0x7au+r[6]),2),2,-1),2);
}
L465507: { // e91c010000  jmp 0x465628
goto L465628;
}
L46550c: { // 83f8f4  cmp eax, -0xc
sub(get(0,4,0),0xfffffff4u,4);
}
L46550f: { // 0f8c13010000  jl 0x465628
if(condition(2))goto L465628;
}
L465515: { // 83f8f6  cmp eax, -0xa
sub(get(0,4,0),0xfffffff6u,4);
}
L465518: { // 0f8ed3000000  jle 0x4655f1
if(condition(4))goto L4655f1;
}
L46551e: { // 83f8ff  cmp eax, -1
sub(get(0,4,0),0xffffffffu,4);
}
L465521: { // 0f84b8000000  je 0x4655df
if(condition(0))goto L4655df;
}
L465527: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L465529: { // 0f849a000000  je 0x4655c9
if(condition(0))goto L4655c9;
}
L46552f: { // 83f80a  cmp eax, 0xa
sub(get(0,4,0),0xau,4);
}
L465532: { // 7472  je 0x4655a6
if(condition(0))goto L4655a6;
}
L465534: { // 83f81e  cmp eax, 0x1e
sub(get(0,4,0),0x1eu,4);
}
L465537: { // 7425  je 0x46555e
if(condition(0))goto L46555e;
}
L465539: { // 83f828  cmp eax, 0x28
sub(get(0,4,0),0x28u,4);
}
L46553c: { // 0f85e6000000  jne 0x465628
if(condition(1))goto L465628;
}
L465542: { // 6a1e  push 0x1e
push(0x1eu);
}
L465544: { // 6a00  push 0
push(0x0u);
}
L465546: { // e80ef7ffff  call 0x464c59
push(0x46554bu);dispatch(0x464c59u);
}
L46554b: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L46554d: { // 0f84d5000000  je 0x465628
if(condition(0))goto L465628;
}
L465553: { // 56  push esi
push(get(6,4,0));
}
L465554: { // e8c483ffff  call 0x45d91d
push(0x465559u);dispatch(0x45d91du);
}
L465559: { // e9ca000000  jmp 0x465628
goto L465628;
}
L46555e: { // 66837e7800  cmp word ptr [esi + 0x78], 0
sub(read((0x78u+r[6]),2),0x0u,2);
}
L465563: { // 0f85bf000000  jne 0x465628
if(condition(1))goto L465628;
}
L465569: { // 66837e7a00  cmp word ptr [esi + 0x7a], 0
sub(read((0x7au+r[6]),2),0x0u,2);
}
L46556e: { // 0f85b4000000  jne 0x465628
if(condition(1))goto L465628;
}
L465574: { // a10ca57700  mov eax, dword ptr [0x77a50c]
put(0,read((0x77a50cu),4),4,0);
}
L465579: { // 33d2  xor edx, edx
put(2,logic(get(2,4,0)^get(2,4,0),4),4,0);
}
L46557b: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L46557d: { // 7e10  jle 0x46558f
if(condition(4))goto L46558f;
}
L46557f: { // 8d4e3c  lea ecx, [esi + 0x3c]
put(1,(0x3cu+r[6]),4,0);
}
L465582: { // 66833900  cmp word ptr [ecx], 0
sub(read((0x0u+r[1]),2),0x0u,2);
}
L465586: { // 7507  jne 0x46558f
if(condition(1))goto L46558f;
}
L465588: { // 42  inc edx
put(2,inc(get(2,4,0),4,1),4,0);
}
L465589: { // 41  inc ecx
put(1,inc(get(1,4,0),4,1),4,0);
}
L46558a: { // 41  inc ecx
put(1,inc(get(1,4,0),4,1),4,0);
}
L46558b: { // 3bd0  cmp edx, eax
sub(get(2,4,0),get(0,4,0),4);
}
L46558d: { // 7cf3  jl 0x465582
if(condition(2))goto L465582;
}
L46558f: { // 3bd0  cmp edx, eax
sub(get(2,4,0),get(0,4,0),4);
}
L465591: { // 0f8591000000  jne 0x465628
if(condition(1))goto L465628;
}
L465597: { // c7864c01000028000000  mov dword ptr [esi + 0x14c], 0x28
write((0x14cu+r[6]),0x28u,4);
}
L4655a1: { // e982000000  jmp 0x465628
goto L465628;
}
L4655a6: { // a1f0598000  mov eax, dword ptr [0x8059f0]
put(0,read((0x8059f0u),4),4,0);
}
L4655ab: { // 8b542414  mov edx, dword ptr [esp + 0x14]
put(2,read((0x14u+r[4]),4),4,0);
}
L4655af: { // 806006fe  and byte ptr [eax + 6], 0xfe
write((0x6u+r[0]),logic(read((0x6u+r[0]),1)&0xfeu,1),1);
}
L4655b3: { // a1f0598000  mov eax, dword ptr [0x8059f0]
put(0,read((0x8059f0u),4),4,0);
}
L4655b8: { // 8b8810010000  mov ecx, dword ptr [eax + 0x110]
put(1,read((0x110u+r[0]),4),4,0);
}
L4655be: { // ff348a  push dword ptr [edx + ecx*4]
push(read((0x0u+r[2]+r[1]*4u),4));
}
L4655c1: { // 50  push eax
push(get(0,4,0));
}
L4655c2: { // e87a22feff  call 0x447841
push(0x4655c7u);dispatch(0x447841u);
}
L4655c7: { // eb0d  jmp 0x4655d6
goto L4655d6;
}
L4655c9: { // 6a1e  push 0x1e
push(0x1eu);
}
L4655cb: { // 6a01  push 1
push(0x1u);
}
L4655cd: { // e887f6ffff  call 0x464c59
push(0x4655d2u);dispatch(0x464c59u);
}
L4655d2: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L4655d4: { // 7452  je 0x465628
if(condition(0))goto L465628;
}
L4655d6: { // 83864c0100000a  add dword ptr [esi + 0x14c], 0xa
write((0x14cu+r[6]),add(read((0x14cu+r[6]),4),0xau,4,false),4);
}
L4655dd: { // eb49  jmp 0x465628
goto L465628;
}
L4655df: { // 6a40  push 0x40
push(0x40u);
}
L4655e1: { // 83c63c  add esi, 0x3c
put(6,add(get(6,4,0),0x3cu,4,false),4,0);
}
L4655e4: { // 6a00  push 0
push(0x0u);
}
L4655e6: { // 56  push esi
push(get(6,4,0));
}
L4655e7: { // e884270300  call 0x497d70
push(0x4655ecu);dispatch(0x497d70u);
}
L4655ec: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L4655ef: { // eb37  jmp 0x465628
goto L465628;
}
L4655f1: { // a10ca57700  mov eax, dword ptr [0x77a50c]
put(0,read((0x77a50cu),4),4,0);
}
L4655f6: { // 33c9  xor ecx, ecx
put(1,logic(get(1,4,0)^get(1,4,0),4),4,0);
}
L4655f8: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L4655fa: { // 7e17  jle 0x465613
if(condition(4))goto L465613;
}
L4655fc: { // 8bbea8010000  mov edi, dword ptr [esi + 0x1a8]
put(7,read((0x1a8u+r[6]),4),4,0);
}
L465602: { // baf8598000  mov edx, 0x8059f8
put(2,0x8059f8u,4,0);
}
L465607: { // 393a  cmp dword ptr [edx], edi
sub(read((0x0u+r[2]),4),get(7,4,0),4);
}
L465609: { // 7408  je 0x465613
if(condition(0))goto L465613;
}
L46560b: { // 41  inc ecx
put(1,inc(get(1,4,0),4,1),4,0);
}
L46560c: { // 83c204  add edx, 4
put(2,add(get(2,4,0),0x4u,4,false),4,0);
}
L46560f: { // 3bc8  cmp ecx, eax
sub(get(1,4,0),get(0,4,0),4);
}
L465611: { // 7cf4  jl 0x465607
if(condition(2))goto L465607;
}
L465613: { // 8b86a8010000  mov eax, dword ptr [esi + 0x1a8]
put(0,read((0x1a8u+r[6]),4),4,0);
}
L465619: { // 80480601  or byte ptr [eax + 6], 1
write((0x6u+r[0]),logic(read((0x6u+r[0]),1)|0x1u,1),1);
}
L46561d: { // 6681644e3cfeff  and word ptr [esi + ecx*2 + 0x3c], 0xfffe
write((0x3cu+r[6]+r[1]*2u),logic(read((0x3cu+r[6]+r[1]*2u),2)&0xfffeu,2),2);
}
L465624: { // 8d444e3c  lea eax, [esi + ecx*2 + 0x3c]
put(0,(0x3cu+r[6]+r[1]*2u),4,0);
}
L465628: { // 5f  pop edi
put(7,pop(),4,0);
}
L465629: { // 5e  pop esi
put(6,pop(),4,0);
}
L46562a: { // 5b  pop ebx
put(3,pop(),4,0);
}
L46562b: { // c20800  ret 8
pop();r[4]+=0x8u;return;
}
}
} // namespace fsb::core
