// Generated by tools/translate_battle.py; edit the generator, not this file.
// Original EXE SHA256: 710881d024ab1fcf738b342c248631363c9de3a51b32a7e3d61781b791eff454
#include "fsb_core/recovered_battle.hpp"
#include <cstring>
#include <cmath>
namespace fsb::core {
// 00499160_crt_chkstk_499160
void RecoveredBattle::fn_499160(){
goto L499160;
L499160: { // 51  push ecx
push(get(1,4,0));
}
L499161: { // 3d00100000  cmp eax, 0x1000
sub(get(0,4,0),0x1000u,4);
}
L499166: { // 8d4c2408  lea ecx, [esp + 8]
put(1,(0x8u+r[4]),4,0);
}
L49916a: { // 7214  jb 0x499180
if(condition(6))goto L499180;
}
L49916c: { // 81e900100000  sub ecx, 0x1000
put(1,sub(get(1,4,0),0x1000u,4,false),4,0);
}
L499172: { // 2d00100000  sub eax, 0x1000
put(0,sub(get(0,4,0),0x1000u,4,false),4,0);
}
L499177: { // 8501  test dword ptr [ecx], eax
logic(read((0x0u+r[1]),4)&get(0,4,0),4);
}
L499179: { // 3d00100000  cmp eax, 0x1000
sub(get(0,4,0),0x1000u,4);
}
L49917e: { // 73ec  jae 0x49916c
if(condition(7))goto L49916c;
}
L499180: { // 2bc8  sub ecx, eax
put(1,sub(get(1,4,0),get(0,4,0),4,false),4,0);
}
L499182: { // 8bc4  mov eax, esp
put(0,get(4,4,0),4,0);
}
L499184: { // 8501  test dword ptr [ecx], eax
logic(read((0x0u+r[1]),4)&get(0,4,0),4);
}
L499186: { // 8be1  mov esp, ecx
put(4,get(1,4,0),4,0);
}
L499188: { // 8b08  mov ecx, dword ptr [eax]
put(1,read((0x0u+r[0]),4),4,0);
}
L49918a: { // 8b4004  mov eax, dword ptr [eax + 4]
put(0,read((0x4u+r[0]),4),4,0);
}
L49918d: { // 50  push eax
push(get(0,4,0));
}
L49918e: { // c3  ret 
pop();r[4]+=0;return;
}
}
} // namespace fsb::core
