// Generated by tools/translate_battle.py; edit the generator, not this file.
// Original EXE SHA256: 710881d024ab1fcf738b342c248631363c9de3a51b32a7e3d61781b791eff454
#include "fsb_core/recovered_battle.hpp"
#include <cstring>
#include <cmath>
namespace fsb::core {
// 00488dea_setup_conveyor_objects_mc_488dea
void RecoveredBattle::fn_488dea(){
goto L488dea;
L488dea: { // 55  push ebp
push(get(5,4,0));
}
L488deb: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L488ded: { // 83ec20  sub esp, 0x20
put(4,sub(get(4,4,0),0x20u,4,false),4,0);
}
L488df0: { // 56  push esi
push(get(6,4,0));
}
L488df1: { // 57  push edi
push(get(7,4,0));
}
L488df2: { // 6a0d  push 0xd
push(0xdu);
}
L488df4: { // 8d75f0  lea esi, [ebp - 0x10]
put(6,(0xfffffff0u+r[5]),4,0);
}
L488df7: { // 59  pop ecx
put(1,pop(),4,0);
}
L488df8: { // 8d7de0  lea edi, [ebp - 0x20]
put(7,(0xffffffe0u+r[5]),4,0);
}
L488dfb: { // 6a0a  push 0xa
push(0xau);
}
L488dfd: { // 894df0  mov dword ptr [ebp - 0x10], ecx
write((0xfffffff0u+r[5]),get(1,4,0),4);
}
L488e00: { // 58  pop eax
put(0,pop(),4,0);
}
L488e01: { // 894df8  mov dword ptr [ebp - 8], ecx
write((0xfffffff8u+r[5]),get(1,4,0),4);
}
L488e04: { // 8945f4  mov dword ptr [ebp - 0xc], eax
write((0xfffffff4u+r[5]),get(0,4,0),4);
}
L488e07: { // 8945fc  mov dword ptr [ebp - 4], eax
write((0xfffffffcu+r[5]),get(0,4,0),4);
}
L488e0a: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L488e0b: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L488e0c: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L488e0d: { // 680f010000  push 0x10f
push(0x10fu);
}
L488e12: { // 8d45e0  lea eax, [ebp - 0x20]
put(0,(0xffffffe0u+r[5]),4,0);
}
L488e15: { // 68808c4800  push 0x488c80
push(0x488c80u);
}
L488e1a: { // 50  push eax
push(get(0,4,0));
}
L488e1b: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L488e1c: { // e8faecfcff  call 0x457b1b
push(0x488e21u);dispatch(0x457b1bu);
}
L488e21: { // 6a15  push 0x15
push(0x15u);
}
L488e23: { // a318668000  mov dword ptr [0x806618], eax
write((0x806618u),get(0,4,0),4);
}
L488e28: { // 59  pop ecx
put(1,pop(),4,0);
}
L488e29: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L488e2b: { // 894820  mov dword ptr [eax + 0x20], ecx
write((0x20u+r[0]),get(1,4,0),4);
}
L488e2e: { // a118668000  mov eax, dword ptr [0x806618]
put(0,read((0x806618u),4),4,0);
}
L488e33: { // 51  push ecx
push(get(1,4,0));
}
L488e34: { // 897824  mov dword ptr [eax + 0x24], edi
write((0x24u+r[0]),get(7,4,0),4);
}
L488e37: { // e8fae10000  call 0x497036
push(0x488e3cu);dispatch(0x497036u);
}
L488e3c: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L488e3e: { // 741f  je 0x488e5f
if(condition(0))goto L488e5f;
}
L488e40: { // a1200d7e00  mov eax, dword ptr [0x7e0d20]
put(0,read((0x7e0d20u),4),4,0);
}
L488e45: { // 6bc034  imul eax, eax, 0x34
put(0,multiply(get(0,4,0),0x34u,4),4,0);
}
L488e48: { // 8b88c8bc7c00  mov ecx, dword ptr [eax + 0x7cbcc8]
put(1,read((0x7cbcc8u+r[0]),4),4,0);
}
L488e4e: { // 8d80c8bc7c00  lea eax, [eax + 0x7cbcc8]
put(0,(0x7cbcc8u+r[0]),4,0);
}
L488e54: { // 80e57f  and ch, 0x7f
put(1,logic(get(1,1,8)&0x7fu,1),1,8);
}
L488e57: { // 81c900000100  or ecx, 0x10000
put(1,logic(get(1,4,0)|0x10000u,4),4,0);
}
L488e5d: { // 8908  mov dword ptr [eax], ecx
write((0x0u+r[0]),get(1,4,0),4);
}
L488e5f: { // 687a894800  push 0x48897a
push(0x48897au);
}
L488e64: { // e8334afdff  call 0x45d89c
push(0x488e69u);dispatch(0x45d89cu);
}
L488e69: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L488e6b: { // 57  push edi
push(get(7,4,0));
}
L488e6c: { // 6afe  push -2
push(0xfffffffeu);
}
L488e6e: { // 57  push edi
push(get(7,4,0));
}
L488e6f: { // 834e0440  or dword ptr [esi + 4], 0x40
write((0x4u+r[6]),logic(read((0x4u+r[6]),4)|0x40u,4),4);
}
L488e73: { // c78630010000d0000000  mov dword ptr [esi + 0x130], 0xd0
write((0x130u+r[6]),0xd0u,4);
}
L488e7d: { // c78634010000f2000000  mov dword ptr [esi + 0x134], 0xf2
write((0x134u+r[6]),0xf2u,4);
}
L488e87: { // c7863801000002000000  mov dword ptr [esi + 0x138], 2
write((0x138u+r[6]),0x2u,4);
}
L488e91: { // 89be08010000  mov dword ptr [esi + 0x108], edi
write((0x108u+r[6]),get(7,4,0),4);
}
L488e97: { // 89be0c010000  mov dword ptr [esi + 0x10c], edi
write((0x10cu+r[6]),get(7,4,0),4);
}
L488e9d: { // 89be10010000  mov dword ptr [esi + 0x110], edi
write((0x110u+r[6]),get(7,4,0),4);
}
L488ea3: { // 89be04010000  mov dword ptr [esi + 0x104], edi
write((0x104u+r[6]),get(7,4,0),4);
}
L488ea9: { // a19c225d00  mov eax, dword ptr [0x5d229c]
put(0,read((0x5d229cu),4),4,0);
}
L488eae: { // 56  push esi
push(get(6,4,0));
}
L488eaf: { // 898660010000  mov dword ptr [esi + 0x160], eax
write((0x160u+r[6]),get(0,4,0),4);
}
L488eb5: { // e8ba48fdff  call 0x45d774
push(0x488ebau);dispatch(0x45d774u);
}
L488eba: { // 81460c0000ffff  add dword ptr [esi + 0xc], 0xffff0000
write((0xcu+r[6]),add(read((0xcu+r[6]),4),0xffff0000u,4,false),4);
}
L488ec1: { // 68a78a4800  push 0x488aa7
push(0x488aa7u);
}
L488ec6: { // e8d149fdff  call 0x45d89c
push(0x488ecbu);dispatch(0x45d89cu);
}
L488ecb: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L488ecd: { // 57  push edi
push(get(7,4,0));
}
L488ece: { // 6afe  push -2
push(0xfffffffeu);
}
L488ed0: { // 57  push edi
push(get(7,4,0));
}
L488ed1: { // 834e0440  or dword ptr [esi + 4], 0x40
write((0x4u+r[6]),logic(read((0x4u+r[6]),4)|0x40u,4),4);
}
L488ed5: { // c78630010000d0000000  mov dword ptr [esi + 0x130], 0xd0
write((0x130u+r[6]),0xd0u,4);
}
L488edf: { // c78634010000f2000000  mov dword ptr [esi + 0x134], 0xf2
write((0x134u+r[6]),0xf2u,4);
}
L488ee9: { // 89be38010000  mov dword ptr [esi + 0x138], edi
write((0x138u+r[6]),get(7,4,0),4);
}
L488eef: { // 89be08010000  mov dword ptr [esi + 0x108], edi
write((0x108u+r[6]),get(7,4,0),4);
}
L488ef5: { // 89be0c010000  mov dword ptr [esi + 0x10c], edi
write((0x10cu+r[6]),get(7,4,0),4);
}
L488efb: { // 89be10010000  mov dword ptr [esi + 0x110], edi
write((0x110u+r[6]),get(7,4,0),4);
}
L488f01: { // 89be04010000  mov dword ptr [esi + 0x104], edi
write((0x104u+r[6]),get(7,4,0),4);
}
L488f07: { // a19c225d00  mov eax, dword ptr [0x5d229c]
put(0,read((0x5d229cu),4),4,0);
}
L488f0c: { // 56  push esi
push(get(6,4,0));
}
L488f0d: { // 898660010000  mov dword ptr [esi + 0x160], eax
write((0x160u+r[6]),get(0,4,0),4);
}
L488f13: { // e85c48fdff  call 0x45d774
push(0x488f18u);dispatch(0x45d774u);
}
L488f18: { // 81460c00000100  add dword ptr [esi + 0xc], 0x10000
write((0xcu+r[6]),add(read((0xcu+r[6]),4),0x10000u,4,false),4);
}
L488f1f: { // ff461c  inc dword ptr [esi + 0x1c]
write((0x1cu+r[6]),inc(read((0x1cu+r[6]),4),4,1),4);
}
L488f22: { // 5f  pop edi
put(7,pop(),4,0);
}
L488f23: { // 5e  pop esi
put(6,pop(),4,0);
}
L488f24: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L488f25: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00488f26_setup_conveyor_objects_mc_488f26
void RecoveredBattle::fn_488f26(){
goto L488f26;
L488f26: { // 53  push ebx
push(get(3,4,0));
}
L488f27: { // 56  push esi
push(get(6,4,0));
}
L488f28: { // 57  push edi
push(get(7,4,0));
}
L488f29: { // 687a894800  push 0x48897a
push(0x48897au);
}
L488f2e: { // e86949fdff  call 0x45d89c
push(0x488f33u);dispatch(0x45d89cu);
}
L488f33: { // 6a01  push 1
push(0x1u);
}
L488f35: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L488f37: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L488f39: { // 5b  pop ebx
put(3,pop(),4,0);
}
L488f3a: { // 834e0440  or dword ptr [esi + 4], 0x40
write((0x4u+r[6]),logic(read((0x4u+r[6]),4)|0x40u,4),4);
}
L488f3e: { // 57  push edi
push(get(7,4,0));
}
L488f3f: { // c78630010000d0000000  mov dword ptr [esi + 0x130], 0xd0
write((0x130u+r[6]),0xd0u,4);
}
L488f49: { // c78634010000f3000000  mov dword ptr [esi + 0x134], 0xf3
write((0x134u+r[6]),0xf3u,4);
}
L488f53: { // c7863801000002000000  mov dword ptr [esi + 0x138], 2
write((0x138u+r[6]),0x2u,4);
}
L488f5d: { // 89be08010000  mov dword ptr [esi + 0x108], edi
write((0x108u+r[6]),get(7,4,0),4);
}
L488f63: { // 899e0c010000  mov dword ptr [esi + 0x10c], ebx
write((0x10cu+r[6]),get(3,4,0),4);
}
L488f69: { // 89be10010000  mov dword ptr [esi + 0x110], edi
write((0x110u+r[6]),get(7,4,0),4);
}
L488f6f: { // 89be04010000  mov dword ptr [esi + 0x104], edi
write((0x104u+r[6]),get(7,4,0),4);
}
L488f75: { // a19c225d00  mov eax, dword ptr [0x5d229c]
put(0,read((0x5d229cu),4),4,0);
}
L488f7a: { // 6afe  push -2
push(0xfffffffeu);
}
L488f7c: { // 57  push edi
push(get(7,4,0));
}
L488f7d: { // 56  push esi
push(get(6,4,0));
}
L488f7e: { // 898660010000  mov dword ptr [esi + 0x160], eax
write((0x160u+r[6]),get(0,4,0),4);
}
L488f84: { // e8eb47fdff  call 0x45d774
push(0x488f89u);dispatch(0x45d774u);
}
L488f89: { // 81460c0000ffff  add dword ptr [esi + 0xc], 0xffff0000
write((0xcu+r[6]),add(read((0xcu+r[6]),4),0xffff0000u,4,false),4);
}
L488f90: { // 68a78a4800  push 0x488aa7
push(0x488aa7u);
}
L488f95: { // e80249fdff  call 0x45d89c
push(0x488f9au);dispatch(0x45d89cu);
}
L488f9a: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L488f9c: { // 57  push edi
push(get(7,4,0));
}
L488f9d: { // 6afe  push -2
push(0xfffffffeu);
}
L488f9f: { // 57  push edi
push(get(7,4,0));
}
L488fa0: { // 834e0440  or dword ptr [esi + 4], 0x40
write((0x4u+r[6]),logic(read((0x4u+r[6]),4)|0x40u,4),4);
}
L488fa4: { // c78630010000d0000000  mov dword ptr [esi + 0x130], 0xd0
write((0x130u+r[6]),0xd0u,4);
}
L488fae: { // c78634010000f3000000  mov dword ptr [esi + 0x134], 0xf3
write((0x134u+r[6]),0xf3u,4);
}
L488fb8: { // 89be38010000  mov dword ptr [esi + 0x138], edi
write((0x138u+r[6]),get(7,4,0),4);
}
L488fbe: { // 89be08010000  mov dword ptr [esi + 0x108], edi
write((0x108u+r[6]),get(7,4,0),4);
}
L488fc4: { // 899e0c010000  mov dword ptr [esi + 0x10c], ebx
write((0x10cu+r[6]),get(3,4,0),4);
}
L488fca: { // 89be10010000  mov dword ptr [esi + 0x110], edi
write((0x110u+r[6]),get(7,4,0),4);
}
L488fd0: { // 89be04010000  mov dword ptr [esi + 0x104], edi
write((0x104u+r[6]),get(7,4,0),4);
}
L488fd6: { // a19c225d00  mov eax, dword ptr [0x5d229c]
put(0,read((0x5d229cu),4),4,0);
}
L488fdb: { // 56  push esi
push(get(6,4,0));
}
L488fdc: { // 898660010000  mov dword ptr [esi + 0x160], eax
write((0x160u+r[6]),get(0,4,0),4);
}
L488fe2: { // e88d47fdff  call 0x45d774
push(0x488fe7u);dispatch(0x45d774u);
}
L488fe7: { // b900000100  mov ecx, 0x10000
put(1,0x10000u,4,0);
}
L488fec: { // 014e0c  add dword ptr [esi + 0xc], ecx
write((0xcu+r[6]),add(read((0xcu+r[6]),4),get(1,4,0),4,false),4);
}
L488fef: { // ff461c  inc dword ptr [esi + 0x1c]
write((0x1cu+r[6]),inc(read((0x1cu+r[6]),4),4,1),4);
}
L488ff2: { // 8b15200d7e00  mov edx, dword ptr [0x7e0d20]
put(2,read((0x7e0d20u),4),4,0);
}
L488ff8: { // beff7fffff  mov esi, 0xffff7fff
put(6,0xffff7fffu,4,0);
}
L488ffd: { // 8bc2  mov eax, edx
put(0,get(2,4,0),4,0);
}
L488fff: { // 69c0b0000000  imul eax, eax, 0xb0
put(0,multiply(get(0,4,0),0xb0u,4),4,0);
}
L489005: { // 8b9804bd7c00  mov ebx, dword ptr [eax + 0x7cbd04]
put(3,read((0x7cbd04u+r[0]),4),4,0);
}
L48900b: { // 8db804bd7c00  lea edi, [eax + 0x7cbd04]
put(7,(0x7cbd04u+r[0]),4,0);
}
L489011: { // 23de  and ebx, esi
put(3,logic(get(3,4,0)&get(6,4,0),4),4,0);
}
L489013: { // 0bd9  or ebx, ecx
put(3,logic(get(3,4,0)|get(1,4,0),4),4,0);
}
L489015: { // 891f  mov dword ptr [edi], ebx
write((0x0u+r[7]),get(3,4,0),4);
}
L489017: { // 8b9808bd7c00  mov ebx, dword ptr [eax + 0x7cbd08]
put(3,read((0x7cbd08u+r[0]),4),4,0);
}
L48901d: { // 8db808bd7c00  lea edi, [eax + 0x7cbd08]
put(7,(0x7cbd08u+r[0]),4,0);
}
L489023: { // 23de  and ebx, esi
put(3,logic(get(3,4,0)&get(6,4,0),4),4,0);
}
L489025: { // 0bd9  or ebx, ecx
put(3,logic(get(3,4,0)|get(1,4,0),4),4,0);
}
L489027: { // 8d800cbd7c00  lea eax, [eax + 0x7cbd0c]
put(0,(0x7cbd0cu+r[0]),4,0);
}
L48902d: { // 891f  mov dword ptr [edi], ebx
write((0x0u+r[7]),get(3,4,0),4);
}
L48902f: { // 8b38  mov edi, dword ptr [eax]
put(7,read((0x0u+r[0]),4),4,0);
}
L489031: { // 23fe  and edi, esi
put(7,logic(get(7,4,0)&get(6,4,0),4),4,0);
}
L489033: { // 0bf9  or edi, ecx
put(7,logic(get(7,4,0)|get(1,4,0),4),4,0);
}
L489035: { // 8938  mov dword ptr [eax], edi
write((0x0u+r[0]),get(7,4,0),4);
}
L489037: { // 8d0452  lea eax, [edx + edx*2]
put(0,(0x0u+r[2]+r[2]*2u),4,0);
}
L48903a: { // 8b148580bd7c00  mov edx, dword ptr [eax*4 + 0x7cbd80]
put(2,read((0x7cbd80u+r[0]*4u),4),4,0);
}
L489041: { // 5f  pop edi
put(7,pop(),4,0);
}
L489042: { // 8d048580bd7c00  lea eax, [eax*4 + 0x7cbd80]
put(0,(0x7cbd80u+r[0]*4u),4,0);
}
L489049: { // 23d6  and edx, esi
put(2,logic(get(2,4,0)&get(6,4,0),4),4,0);
}
L48904b: { // 0bd1  or edx, ecx
put(2,logic(get(2,4,0)|get(1,4,0),4),4,0);
}
L48904d: { // 5e  pop esi
put(6,pop(),4,0);
}
L48904e: { // 8910  mov dword ptr [eax], edx
write((0x0u+r[0]),get(2,4,0),4);
}
L489050: { // 5b  pop ebx
put(3,pop(),4,0);
}
L489051: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00489052_setup_conveyor_objects_mc_489052
void RecoveredBattle::fn_489052(){
goto L489052;
L489052: { // 53  push ebx
push(get(3,4,0));
}
L489053: { // 56  push esi
push(get(6,4,0));
}
L489054: { // 57  push edi
push(get(7,4,0));
}
L489055: { // 687a894800  push 0x48897a
push(0x48897au);
}
L48905a: { // e83d48fdff  call 0x45d89c
push(0x48905fu);dispatch(0x45d89cu);
}
L48905f: { // 6a01  push 1
push(0x1u);
}
L489061: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L489063: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L489065: { // 5b  pop ebx
put(3,pop(),4,0);
}
L489066: { // 834e0440  or dword ptr [esi + 4], 0x40
write((0x4u+r[6]),logic(read((0x4u+r[6]),4)|0x40u,4),4);
}
L48906a: { // 57  push edi
push(get(7,4,0));
}
L48906b: { // c78630010000d0000000  mov dword ptr [esi + 0x130], 0xd0
write((0x130u+r[6]),0xd0u,4);
}
L489075: { // c78634010000f3000000  mov dword ptr [esi + 0x134], 0xf3
write((0x134u+r[6]),0xf3u,4);
}
L48907f: { // c7863801000002000000  mov dword ptr [esi + 0x138], 2
write((0x138u+r[6]),0x2u,4);
}
L489089: { // 89be08010000  mov dword ptr [esi + 0x108], edi
write((0x108u+r[6]),get(7,4,0),4);
}
L48908f: { // 899e0c010000  mov dword ptr [esi + 0x10c], ebx
write((0x10cu+r[6]),get(3,4,0),4);
}
L489095: { // 89be10010000  mov dword ptr [esi + 0x110], edi
write((0x110u+r[6]),get(7,4,0),4);
}
L48909b: { // 89be04010000  mov dword ptr [esi + 0x104], edi
write((0x104u+r[6]),get(7,4,0),4);
}
L4890a1: { // a19c225d00  mov eax, dword ptr [0x5d229c]
put(0,read((0x5d229cu),4),4,0);
}
L4890a6: { // 6afe  push -2
push(0xfffffffeu);
}
L4890a8: { // 57  push edi
push(get(7,4,0));
}
L4890a9: { // 56  push esi
push(get(6,4,0));
}
L4890aa: { // 898660010000  mov dword ptr [esi + 0x160], eax
write((0x160u+r[6]),get(0,4,0),4);
}
L4890b0: { // e8bf46fdff  call 0x45d774
push(0x4890b5u);dispatch(0x45d774u);
}
L4890b5: { // 81460c0000ffff  add dword ptr [esi + 0xc], 0xffff0000
write((0xcu+r[6]),add(read((0xcu+r[6]),4),0xffff0000u,4,false),4);
}
L4890bc: { // 68a78a4800  push 0x488aa7
push(0x488aa7u);
}
L4890c1: { // e8d647fdff  call 0x45d89c
push(0x4890c6u);dispatch(0x45d89cu);
}
L4890c6: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L4890c8: { // 57  push edi
push(get(7,4,0));
}
L4890c9: { // 6afe  push -2
push(0xfffffffeu);
}
L4890cb: { // 57  push edi
push(get(7,4,0));
}
L4890cc: { // 834e0440  or dword ptr [esi + 4], 0x40
write((0x4u+r[6]),logic(read((0x4u+r[6]),4)|0x40u,4),4);
}
L4890d0: { // c78630010000d0000000  mov dword ptr [esi + 0x130], 0xd0
write((0x130u+r[6]),0xd0u,4);
}
L4890da: { // c78634010000f3000000  mov dword ptr [esi + 0x134], 0xf3
write((0x134u+r[6]),0xf3u,4);
}
L4890e4: { // 89be38010000  mov dword ptr [esi + 0x138], edi
write((0x138u+r[6]),get(7,4,0),4);
}
L4890ea: { // 89be08010000  mov dword ptr [esi + 0x108], edi
write((0x108u+r[6]),get(7,4,0),4);
}
L4890f0: { // 899e0c010000  mov dword ptr [esi + 0x10c], ebx
write((0x10cu+r[6]),get(3,4,0),4);
}
L4890f6: { // 89be10010000  mov dword ptr [esi + 0x110], edi
write((0x110u+r[6]),get(7,4,0),4);
}
L4890fc: { // 89be04010000  mov dword ptr [esi + 0x104], edi
write((0x104u+r[6]),get(7,4,0),4);
}
L489102: { // a19c225d00  mov eax, dword ptr [0x5d229c]
put(0,read((0x5d229cu),4),4,0);
}
L489107: { // 56  push esi
push(get(6,4,0));
}
L489108: { // 898660010000  mov dword ptr [esi + 0x160], eax
write((0x160u+r[6]),get(0,4,0),4);
}
L48910e: { // e86146fdff  call 0x45d774
push(0x489113u);dispatch(0x45d774u);
}
L489113: { // b900000100  mov ecx, 0x10000
put(1,0x10000u,4,0);
}
L489118: { // 014e0c  add dword ptr [esi + 0xc], ecx
write((0xcu+r[6]),add(read((0xcu+r[6]),4),get(1,4,0),4,false),4);
}
L48911b: { // ff461c  inc dword ptr [esi + 0x1c]
write((0x1cu+r[6]),inc(read((0x1cu+r[6]),4),4,1),4);
}
L48911e: { // 8b15200d7e00  mov edx, dword ptr [0x7e0d20]
put(2,read((0x7e0d20u),4),4,0);
}
L489124: { // beff7fffff  mov esi, 0xffff7fff
put(6,0xffff7fffu,4,0);
}
L489129: { // 8bc2  mov eax, edx
put(0,get(2,4,0),4,0);
}
L48912b: { // 69c0f4000000  imul eax, eax, 0xf4
put(0,multiply(get(0,4,0),0xf4u,4),4,0);
}
L489131: { // 8b98f0bc7c00  mov ebx, dword ptr [eax + 0x7cbcf0]
put(3,read((0x7cbcf0u+r[0]),4),4,0);
}
L489137: { // 8db8f0bc7c00  lea edi, [eax + 0x7cbcf0]
put(7,(0x7cbcf0u+r[0]),4,0);
}
L48913d: { // 23de  and ebx, esi
put(3,logic(get(3,4,0)&get(6,4,0),4),4,0);
}
L48913f: { // 0bd9  or ebx, ecx
put(3,logic(get(3,4,0)|get(1,4,0),4),4,0);
}
L489141: { // 891f  mov dword ptr [edi], ebx
write((0x0u+r[7]),get(3,4,0),4);
}
L489143: { // 8b98f4bc7c00  mov ebx, dword ptr [eax + 0x7cbcf4]
put(3,read((0x7cbcf4u+r[0]),4),4,0);
}
L489149: { // 8db8f4bc7c00  lea edi, [eax + 0x7cbcf4]
put(7,(0x7cbcf4u+r[0]),4,0);
}
L48914f: { // 23de  and ebx, esi
put(3,logic(get(3,4,0)&get(6,4,0),4),4,0);
}
L489151: { // 0bd9  or ebx, ecx
put(3,logic(get(3,4,0)|get(1,4,0),4),4,0);
}
L489153: { // 8d80f8bc7c00  lea eax, [eax + 0x7cbcf8]
put(0,(0x7cbcf8u+r[0]),4,0);
}
L489159: { // 891f  mov dword ptr [edi], ebx
write((0x0u+r[7]),get(3,4,0),4);
}
L48915b: { // 8b38  mov edi, dword ptr [eax]
put(7,read((0x0u+r[0]),4),4,0);
}
L48915d: { // 23fe  and edi, esi
put(7,logic(get(7,4,0)&get(6,4,0),4),4,0);
}
L48915f: { // 0bf9  or edi, ecx
put(7,logic(get(7,4,0)|get(1,4,0),4),4,0);
}
L489161: { // 8938  mov dword ptr [eax], edi
write((0x0u+r[0]),get(7,4,0),4);
}
L489163: { // 8d0452  lea eax, [edx + edx*2]
put(0,(0x0u+r[2]+r[2]*2u),4,0);
}
L489166: { // 8b1485bcbc7c00  mov edx, dword ptr [eax*4 + 0x7cbcbc]
put(2,read((0x7cbcbcu+r[0]*4u),4),4,0);
}
L48916d: { // 5f  pop edi
put(7,pop(),4,0);
}
L48916e: { // 8d0485bcbc7c00  lea eax, [eax*4 + 0x7cbcbc]
put(0,(0x7cbcbcu+r[0]*4u),4,0);
}
L489175: { // 23d6  and edx, esi
put(2,logic(get(2,4,0)&get(6,4,0),4),4,0);
}
L489177: { // 0bd1  or edx, ecx
put(2,logic(get(2,4,0)|get(1,4,0),4),4,0);
}
L489179: { // 5e  pop esi
put(6,pop(),4,0);
}
L48917a: { // 8910  mov dword ptr [eax], edx
write((0x0u+r[0]),get(2,4,0),4);
}
L48917c: { // 5b  pop ebx
put(3,pop(),4,0);
}
L48917d: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 0048917e_setup_conveyor_objects_mc_48917e
void RecoveredBattle::fn_48917e(){
goto L48917e;
L48917e: { // 53  push ebx
push(get(3,4,0));
}
L48917f: { // 56  push esi
push(get(6,4,0));
}
L489180: { // 57  push edi
push(get(7,4,0));
}
L489181: { // 687a894800  push 0x48897a
push(0x48897au);
}
L489186: { // e81147fdff  call 0x45d89c
push(0x48918bu);dispatch(0x45d89cu);
}
L48918b: { // 6a01  push 1
push(0x1u);
}
L48918d: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L48918f: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L489191: { // 5b  pop ebx
put(3,pop(),4,0);
}
L489192: { // 834e0440  or dword ptr [esi + 4], 0x40
write((0x4u+r[6]),logic(read((0x4u+r[6]),4)|0x40u,4),4);
}
L489196: { // 57  push edi
push(get(7,4,0));
}
L489197: { // c78630010000d0000000  mov dword ptr [esi + 0x130], 0xd0
write((0x130u+r[6]),0xd0u,4);
}
L4891a1: { // c78634010000f3000000  mov dword ptr [esi + 0x134], 0xf3
write((0x134u+r[6]),0xf3u,4);
}
L4891ab: { // c7863801000002000000  mov dword ptr [esi + 0x138], 2
write((0x138u+r[6]),0x2u,4);
}
L4891b5: { // 89be08010000  mov dword ptr [esi + 0x108], edi
write((0x108u+r[6]),get(7,4,0),4);
}
L4891bb: { // 899e0c010000  mov dword ptr [esi + 0x10c], ebx
write((0x10cu+r[6]),get(3,4,0),4);
}
L4891c1: { // 89be10010000  mov dword ptr [esi + 0x110], edi
write((0x110u+r[6]),get(7,4,0),4);
}
L4891c7: { // 89be04010000  mov dword ptr [esi + 0x104], edi
write((0x104u+r[6]),get(7,4,0),4);
}
L4891cd: { // a19c225d00  mov eax, dword ptr [0x5d229c]
put(0,read((0x5d229cu),4),4,0);
}
L4891d2: { // 6afe  push -2
push(0xfffffffeu);
}
L4891d4: { // 57  push edi
push(get(7,4,0));
}
L4891d5: { // 56  push esi
push(get(6,4,0));
}
L4891d6: { // 898660010000  mov dword ptr [esi + 0x160], eax
write((0x160u+r[6]),get(0,4,0),4);
}
L4891dc: { // e89345fdff  call 0x45d774
push(0x4891e1u);dispatch(0x45d774u);
}
L4891e1: { // 81460c0000ffff  add dword ptr [esi + 0xc], 0xffff0000
write((0xcu+r[6]),add(read((0xcu+r[6]),4),0xffff0000u,4,false),4);
}
L4891e8: { // 68a78a4800  push 0x488aa7
push(0x488aa7u);
}
L4891ed: { // e8aa46fdff  call 0x45d89c
push(0x4891f2u);dispatch(0x45d89cu);
}
L4891f2: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L4891f4: { // 57  push edi
push(get(7,4,0));
}
L4891f5: { // 6afe  push -2
push(0xfffffffeu);
}
L4891f7: { // 57  push edi
push(get(7,4,0));
}
L4891f8: { // 834e0440  or dword ptr [esi + 4], 0x40
write((0x4u+r[6]),logic(read((0x4u+r[6]),4)|0x40u,4),4);
}
L4891fc: { // c78630010000d0000000  mov dword ptr [esi + 0x130], 0xd0
write((0x130u+r[6]),0xd0u,4);
}
L489206: { // c78634010000f3000000  mov dword ptr [esi + 0x134], 0xf3
write((0x134u+r[6]),0xf3u,4);
}
L489210: { // 89be38010000  mov dword ptr [esi + 0x138], edi
write((0x138u+r[6]),get(7,4,0),4);
}
L489216: { // 89be08010000  mov dword ptr [esi + 0x108], edi
write((0x108u+r[6]),get(7,4,0),4);
}
L48921c: { // 899e0c010000  mov dword ptr [esi + 0x10c], ebx
write((0x10cu+r[6]),get(3,4,0),4);
}
L489222: { // 89be10010000  mov dword ptr [esi + 0x110], edi
write((0x110u+r[6]),get(7,4,0),4);
}
L489228: { // 89be04010000  mov dword ptr [esi + 0x104], edi
write((0x104u+r[6]),get(7,4,0),4);
}
L48922e: { // a19c225d00  mov eax, dword ptr [0x5d229c]
put(0,read((0x5d229cu),4),4,0);
}
L489233: { // 56  push esi
push(get(6,4,0));
}
L489234: { // 898660010000  mov dword ptr [esi + 0x160], eax
write((0x160u+r[6]),get(0,4,0),4);
}
L48923a: { // e83545fdff  call 0x45d774
push(0x48923fu);dispatch(0x45d774u);
}
L48923f: { // b900000100  mov ecx, 0x10000
put(1,0x10000u,4,0);
}
L489244: { // 014e0c  add dword ptr [esi + 0xc], ecx
write((0xcu+r[6]),add(read((0xcu+r[6]),4),get(1,4,0),4,false),4);
}
L489247: { // ff461c  inc dword ptr [esi + 0x1c]
write((0x1cu+r[6]),inc(read((0x1cu+r[6]),4),4,1),4);
}
L48924a: { // a1200d7e00  mov eax, dword ptr [0x7e0d20]
put(0,read((0x7e0d20u),4),4,0);
}
L48924f: { // beff7fffff  mov esi, 0xffff7fff
put(6,0xffff7fffu,4,0);
}
L489254: { // 6bc070  imul eax, eax, 0x70
put(0,multiply(get(0,4,0),0x70u,4),4,0);
}
L489257: { // 8bb8f8bc7c00  mov edi, dword ptr [eax + 0x7cbcf8]
put(7,read((0x7cbcf8u+r[0]),4),4,0);
}
L48925d: { // 8d90f8bc7c00  lea edx, [eax + 0x7cbcf8]
put(2,(0x7cbcf8u+r[0]),4,0);
}
L489263: { // 23fe  and edi, esi
put(7,logic(get(7,4,0)&get(6,4,0),4),4,0);
}
L489265: { // 0bf9  or edi, ecx
put(7,logic(get(7,4,0)|get(1,4,0),4),4,0);
}
L489267: { // 893a  mov dword ptr [edx], edi
write((0x0u+r[2]),get(7,4,0),4);
}
L489269: { // 8bb8fcbc7c00  mov edi, dword ptr [eax + 0x7cbcfc]
put(7,read((0x7cbcfcu+r[0]),4),4,0);
}
L48926f: { // 8d90fcbc7c00  lea edx, [eax + 0x7cbcfc]
put(2,(0x7cbcfcu+r[0]),4,0);
}
L489275: { // 23fe  and edi, esi
put(7,logic(get(7,4,0)&get(6,4,0),4),4,0);
}
L489277: { // 0bf9  or edi, ecx
put(7,logic(get(7,4,0)|get(1,4,0),4),4,0);
}
L489279: { // 8d8000bd7c00  lea eax, [eax + 0x7cbd00]
put(0,(0x7cbd00u+r[0]),4,0);
}
L48927f: { // 893a  mov dword ptr [edx], edi
write((0x0u+r[2]),get(7,4,0),4);
}
L489281: { // 5f  pop edi
put(7,pop(),4,0);
}
L489282: { // 8b10  mov edx, dword ptr [eax]
put(2,read((0x0u+r[0]),4),4,0);
}
L489284: { // 23d6  and edx, esi
put(2,logic(get(2,4,0)&get(6,4,0),4),4,0);
}
L489286: { // 5e  pop esi
put(6,pop(),4,0);
}
L489287: { // 0bd1  or edx, ecx
put(2,logic(get(2,4,0)|get(1,4,0),4),4,0);
}
L489289: { // 5b  pop ebx
put(3,pop(),4,0);
}
L48928a: { // 8910  mov dword ptr [eax], edx
write((0x0u+r[0]),get(2,4,0),4);
}
L48928c: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 0048948d_setup_tzg0_vent_animation_objects_mc_48948d
void RecoveredBattle::fn_48948d(){
goto L48948d;
L48948d: { // 55  push ebp
push(get(5,4,0));
}
L48948e: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L489490: { // 83ec20  sub esp, 0x20
put(4,sub(get(4,4,0),0x20u,4,false),4,0);
}
L489493: { // 8365f000  and dword ptr [ebp - 0x10], 0
write((0xfffffff0u+r[5]),logic(read((0xfffffff0u+r[5]),4)&0x0u,4),4);
}
L489497: { // 8365f800  and dword ptr [ebp - 8], 0
write((0xfffffff8u+r[5]),logic(read((0xfffffff8u+r[5]),4)&0x0u,4),4);
}
L48949b: { // 53  push ebx
push(get(3,4,0));
}
L48949c: { // 56  push esi
push(get(6,4,0));
}
L48949d: { // 57  push edi
push(get(7,4,0));
}
L48949e: { // 83cbff  or ebx, 0xffffffff
put(3,logic(get(3,4,0)|0xffffffffu,4),4,0);
}
L4894a1: { // 8d75f0  lea esi, [ebp - 0x10]
put(6,(0xfffffff0u+r[5]),4,0);
}
L4894a4: { // 8d7de0  lea edi, [ebp - 0x20]
put(7,(0xffffffe0u+r[5]),4,0);
}
L4894a7: { // 895df4  mov dword ptr [ebp - 0xc], ebx
write((0xfffffff4u+r[5]),get(3,4,0),4);
}
L4894aa: { // 895dfc  mov dword ptr [ebp - 4], ebx
write((0xfffffffcu+r[5]),get(3,4,0),4);
}
L4894ad: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4894ae: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4894af: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4894b0: { // 6802080000  push 0x802
push(0x802u);
}
L4894b5: { // 8d45e0  lea eax, [ebp - 0x20]
put(0,(0xffffffe0u+r[5]),4,0);
}
L4894b8: { // 686f6c4800  push 0x486c6f
push(0x486c6fu);
}
L4894bd: { // 50  push eax
push(get(0,4,0));
}
L4894be: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4894bf: { // e857e6fcff  call 0x457b1b
push(0x4894c4u);dispatch(0x457b1bu);
}
L4894c4: { // 8365f000  and dword ptr [ebp - 0x10], 0
write((0xfffffff0u+r[5]),logic(read((0xfffffff0u+r[5]),4)&0x0u,4),4);
}
L4894c8: { // 8365f800  and dword ptr [ebp - 8], 0
write((0xfffffff8u+r[5]),logic(read((0xfffffff8u+r[5]),4)&0x0u,4),4);
}
L4894cc: { // 8d75f0  lea esi, [ebp - 0x10]
put(6,(0xfffffff0u+r[5]),4,0);
}
L4894cf: { // 8d7de0  lea edi, [ebp - 0x20]
put(7,(0xffffffe0u+r[5]),4,0);
}
L4894d2: { // 895df4  mov dword ptr [ebp - 0xc], ebx
write((0xfffffff4u+r[5]),get(3,4,0),4);
}
L4894d5: { // 895dfc  mov dword ptr [ebp - 4], ebx
write((0xfffffffcu+r[5]),get(3,4,0),4);
}
L4894d8: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4894d9: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4894da: { // a318668000  mov dword ptr [0x806618], eax
write((0x806618u),get(0,4,0),4);
}
L4894df: { // c740201e000000  mov dword ptr [eax + 0x20], 0x1e
write((0x20u+r[0]),0x1eu,4);
}
L4894e6: { // a118668000  mov eax, dword ptr [0x806618]
put(0,read((0x806618u),4),4,0);
}
L4894eb: { // 6802040000  push 0x402
push(0x402u);
}
L4894f0: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4894f1: { // 89582c  mov dword ptr [eax + 0x2c], ebx
write((0x2cu+r[0]),get(3,4,0),4);
}
L4894f4: { // 8d45e0  lea eax, [ebp - 0x20]
put(0,(0xffffffe0u+r[5]),4,0);
}
L4894f7: { // 68f96c4800  push 0x486cf9
push(0x486cf9u);
}
L4894fc: { // 50  push eax
push(get(0,4,0));
}
L4894fd: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4894fe: { // e818e6fcff  call 0x457b1b
push(0x489503u);dispatch(0x457b1bu);
}
L489503: { // 8365f000  and dword ptr [ebp - 0x10], 0
write((0xfffffff0u+r[5]),logic(read((0xfffffff0u+r[5]),4)&0x0u,4),4);
}
L489507: { // 8365f800  and dword ptr [ebp - 8], 0
write((0xfffffff8u+r[5]),logic(read((0xfffffff8u+r[5]),4)&0x0u,4),4);
}
L48950b: { // 8d75f0  lea esi, [ebp - 0x10]
put(6,(0xfffffff0u+r[5]),4,0);
}
L48950e: { // 8d7de0  lea edi, [ebp - 0x20]
put(7,(0xffffffe0u+r[5]),4,0);
}
L489511: { // 895df4  mov dword ptr [ebp - 0xc], ebx
write((0xfffffff4u+r[5]),get(3,4,0),4);
}
L489514: { // 895dfc  mov dword ptr [ebp - 4], ebx
write((0xfffffffcu+r[5]),get(3,4,0),4);
}
L489517: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489518: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489519: { // a318668000  mov dword ptr [0x806618], eax
write((0x806618u),get(0,4,0),4);
}
L48951e: { // c740201e000000  mov dword ptr [eax + 0x20], 0x1e
write((0x20u+r[0]),0x1eu,4);
}
L489525: { // a118668000  mov eax, dword ptr [0x806618]
put(0,read((0x806618u),4),4,0);
}
L48952a: { // 6802020000  push 0x202
push(0x202u);
}
L48952f: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489530: { // 89582c  mov dword ptr [eax + 0x2c], ebx
write((0x2cu+r[0]),get(3,4,0),4);
}
L489533: { // 8d45e0  lea eax, [ebp - 0x20]
put(0,(0xffffffe0u+r[5]),4,0);
}
L489536: { // 68716d4800  push 0x486d71
push(0x486d71u);
}
L48953b: { // 50  push eax
push(get(0,4,0));
}
L48953c: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L48953d: { // e8d9e5fcff  call 0x457b1b
push(0x489542u);dispatch(0x457b1bu);
}
L489542: { // a318668000  mov dword ptr [0x806618], eax
write((0x806618u),get(0,4,0),4);
}
L489547: { // c740201e000000  mov dword ptr [eax + 0x20], 0x1e
write((0x20u+r[0]),0x1eu,4);
}
L48954e: { // a118668000  mov eax, dword ptr [0x806618]
put(0,read((0x806618u),4),4,0);
}
L489553: { // 6a07  push 7
push(0x7u);
}
L489555: { // 8d75f0  lea esi, [ebp - 0x10]
put(6,(0xfffffff0u+r[5]),4,0);
}
L489558: { // 8d7de0  lea edi, [ebp - 0x20]
put(7,(0xffffffe0u+r[5]),4,0);
}
L48955b: { // 89582c  mov dword ptr [eax + 0x2c], ebx
write((0x2cu+r[0]),get(3,4,0),4);
}
L48955e: { // 58  pop eax
put(0,pop(),4,0);
}
L48955f: { // 6a09  push 9
push(0x9u);
}
L489561: { // 8945f0  mov dword ptr [ebp - 0x10], eax
write((0xfffffff0u+r[5]),get(0,4,0),4);
}
L489564: { // 5b  pop ebx
put(3,pop(),4,0);
}
L489565: { // 8945f8  mov dword ptr [ebp - 8], eax
write((0xfffffff8u+r[5]),get(0,4,0),4);
}
L489568: { // 895df4  mov dword ptr [ebp - 0xc], ebx
write((0xfffffff4u+r[5]),get(3,4,0),4);
}
L48956b: { // 895dfc  mov dword ptr [ebp - 4], ebx
write((0xfffffffcu+r[5]),get(3,4,0),4);
}
L48956e: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L48956f: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489570: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489571: { // 6802080000  push 0x802
push(0x802u);
}
L489576: { // 8d45e0  lea eax, [ebp - 0x20]
put(0,(0xffffffe0u+r[5]),4,0);
}
L489579: { // 686f6c4800  push 0x486c6f
push(0x486c6fu);
}
L48957e: { // 50  push eax
push(get(0,4,0));
}
L48957f: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489580: { // e896e5fcff  call 0x457b1b
push(0x489585u);dispatch(0x457b1bu);
}
L489585: { // a318668000  mov dword ptr [0x806618], eax
write((0x806618u),get(0,4,0),4);
}
L48958a: { // c740201f000000  mov dword ptr [eax + 0x20], 0x1f
write((0x20u+r[0]),0x1fu,4);
}
L489591: { // a118668000  mov eax, dword ptr [0x806618]
put(0,read((0x806618u),4),4,0);
}
L489596: { // 6a07  push 7
push(0x7u);
}
L489598: { // 8d75f0  lea esi, [ebp - 0x10]
put(6,(0xfffffff0u+r[5]),4,0);
}
L48959b: { // c7402c1e000000  mov dword ptr [eax + 0x2c], 0x1e
write((0x2cu+r[0]),0x1eu,4);
}
L4895a2: { // 58  pop eax
put(0,pop(),4,0);
}
L4895a3: { // 8d7de0  lea edi, [ebp - 0x20]
put(7,(0xffffffe0u+r[5]),4,0);
}
L4895a6: { // 8945f0  mov dword ptr [ebp - 0x10], eax
write((0xfffffff0u+r[5]),get(0,4,0),4);
}
L4895a9: { // 895df4  mov dword ptr [ebp - 0xc], ebx
write((0xfffffff4u+r[5]),get(3,4,0),4);
}
L4895ac: { // 8945f8  mov dword ptr [ebp - 8], eax
write((0xfffffff8u+r[5]),get(0,4,0),4);
}
L4895af: { // 895dfc  mov dword ptr [ebp - 4], ebx
write((0xfffffffcu+r[5]),get(3,4,0),4);
}
L4895b2: { // 6802040000  push 0x402
push(0x402u);
}
L4895b7: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4895b8: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4895b9: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4895ba: { // 8d45e0  lea eax, [ebp - 0x20]
put(0,(0xffffffe0u+r[5]),4,0);
}
L4895bd: { // 68f96c4800  push 0x486cf9
push(0x486cf9u);
}
L4895c2: { // 50  push eax
push(get(0,4,0));
}
L4895c3: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4895c4: { // e852e5fcff  call 0x457b1b
push(0x4895c9u);dispatch(0x457b1bu);
}
L4895c9: { // a318668000  mov dword ptr [0x806618], eax
write((0x806618u),get(0,4,0),4);
}
L4895ce: { // c740201f000000  mov dword ptr [eax + 0x20], 0x1f
write((0x20u+r[0]),0x1fu,4);
}
L4895d5: { // a118668000  mov eax, dword ptr [0x806618]
put(0,read((0x806618u),4),4,0);
}
L4895da: { // 6a07  push 7
push(0x7u);
}
L4895dc: { // 8d75f0  lea esi, [ebp - 0x10]
put(6,(0xfffffff0u+r[5]),4,0);
}
L4895df: { // 8d7de0  lea edi, [ebp - 0x20]
put(7,(0xffffffe0u+r[5]),4,0);
}
L4895e2: { // c7402c1e000000  mov dword ptr [eax + 0x2c], 0x1e
write((0x2cu+r[0]),0x1eu,4);
}
L4895e9: { // 58  pop eax
put(0,pop(),4,0);
}
L4895ea: { // 8945f0  mov dword ptr [ebp - 0x10], eax
write((0xfffffff0u+r[5]),get(0,4,0),4);
}
L4895ed: { // 895df4  mov dword ptr [ebp - 0xc], ebx
write((0xfffffff4u+r[5]),get(3,4,0),4);
}
L4895f0: { // 8945f8  mov dword ptr [ebp - 8], eax
write((0xfffffff8u+r[5]),get(0,4,0),4);
}
L4895f3: { // 895dfc  mov dword ptr [ebp - 4], ebx
write((0xfffffffcu+r[5]),get(3,4,0),4);
}
L4895f6: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4895f7: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4895f8: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4895f9: { // 6802020000  push 0x202
push(0x202u);
}
L4895fe: { // 8d45e0  lea eax, [ebp - 0x20]
put(0,(0xffffffe0u+r[5]),4,0);
}
L489601: { // 68716d4800  push 0x486d71
push(0x486d71u);
}
L489606: { // 50  push eax
push(get(0,4,0));
}
L489607: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489608: { // e80ee5fcff  call 0x457b1b
push(0x48960du);dispatch(0x457b1bu);
}
L48960d: { // a318668000  mov dword ptr [0x806618], eax
write((0x806618u),get(0,4,0),4);
}
L489612: { // c740201f000000  mov dword ptr [eax + 0x20], 0x1f
write((0x20u+r[0]),0x1fu,4);
}
L489619: { // a118668000  mov eax, dword ptr [0x806618]
put(0,read((0x806618u),4),4,0);
}
L48961e: { // 6a10  push 0x10
push(0x10u);
}
L489620: { // 8d75f0  lea esi, [ebp - 0x10]
put(6,(0xfffffff0u+r[5]),4,0);
}
L489623: { // 8d7de0  lea edi, [ebp - 0x20]
put(7,(0xffffffe0u+r[5]),4,0);
}
L489626: { // c7402c1e000000  mov dword ptr [eax + 0x2c], 0x1e
write((0x2cu+r[0]),0x1eu,4);
}
L48962d: { // 58  pop eax
put(0,pop(),4,0);
}
L48962e: { // c745f004000000  mov dword ptr [ebp - 0x10], 4
write((0xfffffff0u+r[5]),0x4u,4);
}
L489635: { // 8945f4  mov dword ptr [ebp - 0xc], eax
write((0xfffffff4u+r[5]),get(0,4,0),4);
}
L489638: { // c745f80b000000  mov dword ptr [ebp - 8], 0xb
write((0xfffffff8u+r[5]),0xbu,4);
}
L48963f: { // 8945fc  mov dword ptr [ebp - 4], eax
write((0xfffffffcu+r[5]),get(0,4,0),4);
}
L489642: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489643: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489644: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489645: { // 6802020000  push 0x202
push(0x202u);
}
L48964a: { // 8d45e0  lea eax, [ebp - 0x20]
put(0,(0xffffffe0u+r[5]),4,0);
}
L48964d: { // 688c6b4800  push 0x486b8c
push(0x486b8cu);
}
L489652: { // 50  push eax
push(get(0,4,0));
}
L489653: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489654: { // e8c2e4fcff  call 0x457b1b
push(0x489659u);dispatch(0x457b1bu);
}
L489659: { // 6a07  push 7
push(0x7u);
}
L48965b: { // 8d75f0  lea esi, [ebp - 0x10]
put(6,(0xfffffff0u+r[5]),4,0);
}
L48965e: { // 58  pop eax
put(0,pop(),4,0);
}
L48965f: { // 8d7de0  lea edi, [ebp - 0x20]
put(7,(0xffffffe0u+r[5]),4,0);
}
L489662: { // 8945f0  mov dword ptr [ebp - 0x10], eax
write((0xfffffff0u+r[5]),get(0,4,0),4);
}
L489665: { // 895df4  mov dword ptr [ebp - 0xc], ebx
write((0xfffffff4u+r[5]),get(3,4,0),4);
}
L489668: { // 8945f8  mov dword ptr [ebp - 8], eax
write((0xfffffff8u+r[5]),get(0,4,0),4);
}
L48966b: { // 895dfc  mov dword ptr [ebp - 4], ebx
write((0xfffffffcu+r[5]),get(3,4,0),4);
}
L48966e: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L48966f: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489670: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489671: { // 6802080000  push 0x802
push(0x802u);
}
L489676: { // 8d45e0  lea eax, [ebp - 0x20]
put(0,(0xffffffe0u+r[5]),4,0);
}
L489679: { // 688c6b4800  push 0x486b8c
push(0x486b8cu);
}
L48967e: { // 50  push eax
push(get(0,4,0));
}
L48967f: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L489680: { // e896e4fcff  call 0x457b1b
push(0x489685u);dispatch(0x457b1bu);
}
L489685: { // 5f  pop edi
put(7,pop(),4,0);
}
L489686: { // 5e  pop esi
put(6,pop(),4,0);
}
L489687: { // 5b  pop ebx
put(3,pop(),4,0);
}
L489688: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L489689: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00488c80_tbs0_00_conveyor_item_use_overlay_handler_mc_488c80
void RecoveredBattle::fn_488c80(){
goto L488c80;
L488c80: { // 53  push ebx
push(get(3,4,0));
}
L488c81: { // 56  push esi
push(get(6,4,0));
}
L488c82: { // 8b74240c  mov esi, dword ptr [esp + 0xc]
put(6,read((0xcu+r[4]),4),4,0);
}
L488c86: { // 57  push edi
push(get(7,4,0));
}
L488c87: { // ff7620  push dword ptr [esi + 0x20]
push(read((0x20u+r[6]),4));
}
L488c8a: { // e8a7e30000  call 0x497036
push(0x488c8fu);dispatch(0x497036u);
}
L488c8f: { // 33db  xor ebx, ebx
put(3,logic(get(3,4,0)^get(3,4,0),4),4,0);
}
L488c91: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L488c93: { // 0f85b0000000  jne 0x488d49
if(condition(1))goto L488d49;
}
L488c99: { // 391d58738000  cmp dword ptr [0x807358], ebx
sub(read((0x807358u),4),get(3,4,0),4);
}
L488c9f: { // 0f8ea4000000  jle 0x488d49
if(condition(4))goto L488d49;
}
L488ca5: { // 6a70  push 0x70
push(0x70u);
}
L488ca7: { // e8548afaff  call 0x431700
push(0x488cacu);dispatch(0x431700u);
}
L488cac: { // a802  test al, 2
logic(get(0,1,0)&0x2u,1);
}
L488cae: { // 0f8495000000  je 0x488d49
if(condition(0))goto L488d49;
}
L488cb4: { // ff0d58738000  dec dword ptr [0x807358]
write((0x807358u),inc(read((0x807358u),4),4,-1),4);
}
L488cba: { // 684a010000  push 0x14a
push(0x14au);
}
L488cbf: { // ff3584936100  push dword ptr [0x619384]
push(read((0x619384u),4));
}
L488cc5: { // bf98658000  mov edi, 0x806598
put(7,0x806598u,4,0);
}
L488cca: { // 68808a5f00  push 0x5f8a80
push(0x5f8a80u);
}
L488ccf: { // 57  push edi
push(get(7,4,0));
}
L488cd0: { // e8fb050100  call 0x4992d0
push(0x488cd5u);dispatch(0x4992d0u);
}
L488cd5: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L488cd8: { // 881d206a8000  mov byte ptr [0x806a20], bl
write((0x806a20u),get(3,1,0),1);
}
L488cde: { // 57  push edi
push(get(7,4,0));
}
L488cdf: { // bf206a8000  mov edi, 0x806a20
put(7,0x806a20u,4,0);
}
L488ce4: { // 57  push edi
push(get(7,4,0));
}
L488ce5: { // e826e60000  call 0x497310
push(0x488ceau);dispatch(0x497310u);
}
L488cea: { // a11c3a8000  mov eax, dword ptr [0x803a1c]
put(0,read((0x803a1cu),4),4,0);
}
L488cef: { // 59  pop ecx
put(1,pop(),4,0);
}
L488cf0: { // 69c0ac010000  imul eax, eax, 0x1ac
put(0,multiply(get(0,4,0),0x1acu,4),4,0);
}
L488cf6: { // 80a0dc7380007f  and byte ptr [eax + 0x8073dc], 0x7f
write((0x8073dcu+r[0]),logic(read((0x8073dcu+r[0]),1)&0x7fu,1),1);
}
L488cfd: { // 59  pop ecx
put(1,pop(),4,0);
}
L488cfe: { // 8d80dc738000  lea eax, [eax + 0x8073dc]
put(0,(0x8073dcu+r[0]),4,0);
}
L488d04: { // 57  push edi
push(get(7,4,0));
}
L488d05: { // bf20668000  mov edi, 0x806620
put(7,0x806620u,4,0);
}
L488d0a: { // 682c8a5f00  push 0x5f8a2c
push(0x5f8a2cu);
}
L488d0f: { // 57  push edi
push(get(7,4,0));
}
L488d10: { // c7462401000000  mov dword ptr [esi + 0x24], 1
write((0x24u+r[6]),0x1u,4);
}
L488d17: { // e8b4050100  call 0x4992d0
push(0x488d1cu);dispatch(0x4992d0u);
}
L488d1c: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L488d1f: { // 6aff  push -1
push(0xffffffffu);
}
L488d21: { // 57  push edi
push(get(7,4,0));
}
L488d22: { // e82ff1fcff  call 0x457e56
push(0x488d27u);dispatch(0x457e56u);
}
L488d27: { // 50  push eax
push(get(0,4,0));
}
L488d28: { // e889acf8ff  call 0x4139b6
push(0x488d2du);dispatch(0x4139b6u);
}
L488d2d: { // a3206b8000  mov dword ptr [0x806b20], eax
write((0x806b20u),get(0,4,0),4);
}
L488d32: { // 8b7620  mov esi, dword ptr [esi + 0x20]
put(6,read((0x20u+r[6]),4),4,0);
}
L488d35: { // 8d04f6  lea eax, [esi + esi*8]
put(0,(0x0u+r[6]+r[6]*8u),4,0);
}
L488d38: { // ff348560406000  push dword ptr [eax*4 + 0x604060]
push(read((0x604060u+r[0]*4u),4));
}
L488d3f: { // e82fc6faff  call 0x435373
push(0x488d44u);dispatch(0x435373u);
}
L488d44: { // e99b000000  jmp 0x488de4
goto L488de4;
}
L488d49: { // 395e18  cmp dword ptr [esi + 0x18], ebx
sub(read((0x18u+r[6]),4),get(3,4,0),4);
}
L488d4c: { // 0f868b000000  jbe 0x488ddd
if(condition(8))goto L488ddd;
}
L488d52: { // 837e2401  cmp dword ptr [esi + 0x24], 1
sub(read((0x24u+r[6]),4),0x1u,4);
}
L488d56: { // 0f8581000000  jne 0x488ddd
if(condition(1))goto L488ddd;
}
L488d5c: { // ff35206b8000  push dword ptr [0x806b20]
push(read((0x806b20u),4));
}
L488d62: { // e82c99f7ff  call 0x402693
push(0x488d67u);dispatch(0x402693u);
}
L488d67: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L488d69: { // 7579  jne 0x488de4
if(condition(1))goto L488de4;
}
L488d6b: { // 6a01  push 1
push(0x1u);
}
L488d6d: { // 891d206b8000  mov dword ptr [0x806b20], ebx
write((0x806b20u),get(3,4,0),4);
}
L488d73: { // ff7620  push dword ptr [esi + 0x20]
push(read((0x20u+r[6]),4));
}
L488d76: { // 895e18  mov dword ptr [esi + 0x18], ebx
write((0x18u+r[6]),get(3,4,0),4);
}
L488d79: { // e8e7e20000  call 0x497065
push(0x488d7eu);dispatch(0x497065u);
}
L488d7e: { // a11c3a8000  mov eax, dword ptr [0x803a1c]
put(0,read((0x803a1cu),4),4,0);
}
L488d83: { // 8b0d200d7e00  mov ecx, dword ptr [0x7e0d20]
put(1,read((0x7e0d20u),4),4,0);
}
L488d89: { // 69c0ac010000  imul eax, eax, 0x1ac
put(0,multiply(get(0,4,0),0x1acu,4),4,0);
}
L488d8f: { // 8088dc73800080  or byte ptr [eax + 0x8073dc], 0x80
write((0x8073dcu+r[0]),logic(read((0x8073dcu+r[0]),1)|0x80u,1),1);
}
L488d96: { // 8d80dc738000  lea eax, [eax + 0x8073dc]
put(0,(0x8073dcu+r[0]),4,0);
}
L488d9c: { // 8bc1  mov eax, ecx
put(0,get(1,4,0),4,0);
}
L488d9e: { // 6bc078  imul eax, eax, 0x78
put(0,multiply(get(0,4,0),0x78u,4),4,0);
}
L488da1: { // c780303d7b001d000000  mov dword ptr [eax + 0x7b3d30], 0x1d
write((0x7b3d30u+r[0]),0x1du,4);
}
L488dab: { // c7803c3d7b001e000000  mov dword ptr [eax + 0x7b3d3c], 0x1e
write((0x7b3d3cu+r[0]),0x1eu,4);
}
L488db5: { // c780483d7b001f000000  mov dword ptr [eax + 0x7b3d48], 0x1f
write((0x7b3d48u+r[0]),0x1fu,4);
}
L488dbf: { // 8d0489  lea eax, [ecx + ecx*4]
put(0,(0x0u+r[1]+r[1]*4u),4,0);
}
L488dc2: { // 8b0cc5d4bc7c00  mov ecx, dword ptr [eax*8 + 0x7cbcd4]
put(1,read((0x7cbcd4u+r[0]*8u),4),4,0);
}
L488dc9: { // 8d04c5d4bc7c00  lea eax, [eax*8 + 0x7cbcd4]
put(0,(0x7cbcd4u+r[0]*8u),4,0);
}
L488dd0: { // 80e57f  and ch, 0x7f
put(1,logic(get(1,1,8)&0x7fu,1),1,8);
}
L488dd3: { // 81c900000100  or ecx, 0x10000
put(1,logic(get(1,4,0)|0x10000u,4),4,0);
}
L488dd9: { // 8908  mov dword ptr [eax], ecx
write((0x0u+r[0]),get(1,4,0),4);
}
L488ddb: { // eb03  jmp 0x488de0
goto L488de0;
}
L488ddd: { // 895e18  mov dword ptr [esi + 0x18], ebx
write((0x18u+r[6]),get(3,4,0),4);
}
L488de0: { // 806603fd  and byte ptr [esi + 3], 0xfd
write((0x3u+r[6]),logic(read((0x3u+r[6]),1)&0xfdu,1),1);
}
L488de4: { // 5f  pop edi
put(7,pop(),4,0);
}
L488de5: { // 5e  pop esi
put(6,pop(),4,0);
}
L488de6: { // 5b  pop ebx
put(3,pop(),4,0);
}
L488de7: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00486fab_item_gate_control_popup_handler_mc_486fab
void RecoveredBattle::fn_486fab(){
goto L486fab;
L486fab: { // 53  push ebx
push(get(3,4,0));
}
L486fac: { // 56  push esi
push(get(6,4,0));
}
L486fad: { // 8b74240c  mov esi, dword ptr [esp + 0xc]
put(6,read((0xcu+r[4]),4),4,0);
}
L486fb1: { // 33db  xor ebx, ebx
put(3,logic(get(3,4,0)^get(3,4,0),4),4,0);
}
L486fb3: { // 57  push edi
push(get(7,4,0));
}
L486fb4: { // 8b462c  mov eax, dword ptr [esi + 0x2c]
put(0,read((0x2cu+r[6]),4),4,0);
}
L486fb7: { // 391c85306e8000  cmp dword ptr [eax*4 + 0x806e30], ebx
sub(read((0x806e30u+r[0]*4u),4),get(3,4,0),4);
}
L486fbe: { // 0f8e9d000000  jle 0x487061
if(condition(4))goto L487061;
}
L486fc4: { // ff7620  push dword ptr [esi + 0x20]
push(read((0x20u+r[6]),4));
}
L486fc7: { // e86a000100  call 0x497036
push(0x486fccu);dispatch(0x497036u);
}
L486fcc: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L486fce: { // 0f858d000000  jne 0x487061
if(condition(1))goto L487061;
}
L486fd4: { // 8b462c  mov eax, dword ptr [esi + 0x2c]
put(0,read((0x2cu+r[6]),4),4,0);
}
L486fd7: { // ff0c85306e8000  dec dword ptr [eax*4 + 0x806e30]
write((0x806e30u+r[0]*4u),inc(read((0x806e30u+r[0]*4u),4),4,-1),4);
}
L486fde: { // bf98658000  mov edi, 0x806598
put(7,0x806598u,4,0);
}
L486fe3: { // 8d0485306e8000  lea eax, [eax*4 + 0x806e30]
put(0,(0x806e30u+r[0]*4u),4,0);
}
L486fea: { // a11c3a8000  mov eax, dword ptr [0x803a1c]
put(0,read((0x803a1cu),4),4,0);
}
L486fef: { // 69c0ac010000  imul eax, eax, 0x1ac
put(0,multiply(get(0,4,0),0x1acu,4),4,0);
}
L486ff5: { // 80a0dc7380007f  and byte ptr [eax + 0x8073dc], 0x7f
write((0x8073dcu+r[0]),logic(read((0x8073dcu+r[0]),1)&0x7fu,1),1);
}
L486ffc: { // 8d80dc738000  lea eax, [eax + 0x8073dc]
put(0,(0x8073dcu+r[0]),4,0);
}
L487002: { // 8b462c  mov eax, dword ptr [esi + 0x2c]
put(0,read((0x2cu+r[6]),4),4,0);
}
L487005: { // 50  push eax
push(get(0,4,0));
}
L487006: { // 6bc04c  imul eax, eax, 0x4c
put(0,multiply(get(0,4,0),0x4cu,4),4,0);
}
L487009: { // ffb08c316100  push dword ptr [eax + 0x61318c]
push(read((0x61318cu+r[0]),4));
}
L48700f: { // 68608a5f00  push 0x5f8a60
push(0x5f8a60u);
}
L487014: { // 57  push edi
push(get(7,4,0));
}
L487015: { // e8b6220100  call 0x4992d0
push(0x48701au);dispatch(0x4992d0u);
}
L48701a: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L48701d: { // 881d206a8000  mov byte ptr [0x806a20], bl
write((0x806a20u),get(3,1,0),1);
}
L487023: { // 57  push edi
push(get(7,4,0));
}
L487024: { // bf206a8000  mov edi, 0x806a20
put(7,0x806a20u,4,0);
}
L487029: { // 57  push edi
push(get(7,4,0));
}
L48702a: { // e8e1020100  call 0x497310
push(0x48702fu);dispatch(0x497310u);
}
L48702f: { // 59  pop ecx
put(1,pop(),4,0);
}
L487030: { // c7462801000000  mov dword ptr [esi + 0x28], 1
write((0x28u+r[6]),0x1u,4);
}
L487037: { // 59  pop ecx
put(1,pop(),4,0);
}
L487038: { // be20668000  mov esi, 0x806620
put(6,0x806620u,4,0);
}
L48703d: { // 57  push edi
push(get(7,4,0));
}
L48703e: { // 682c8a5f00  push 0x5f8a2c
push(0x5f8a2cu);
}
L487043: { // 56  push esi
push(get(6,4,0));
}
L487044: { // e887220100  call 0x4992d0
push(0x487049u);dispatch(0x4992d0u);
}
L487049: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L48704c: { // 6aff  push -1
push(0xffffffffu);
}
L48704e: { // 56  push esi
push(get(6,4,0));
}
L48704f: { // e8020efdff  call 0x457e56
push(0x487054u);dispatch(0x457e56u);
}
L487054: { // 50  push eax
push(get(0,4,0));
}
L487055: { // e85cc9f8ff  call 0x4139b6
push(0x48705au);dispatch(0x4139b6u);
}
L48705a: { // a3206b8000  mov dword ptr [0x806b20], eax
write((0x806b20u),get(0,4,0),4);
}
L48705f: { // eb5f  jmp 0x4870c0
goto L4870c0;
}
L487061: { // 395e18  cmp dword ptr [esi + 0x18], ebx
sub(read((0x18u+r[6]),4),get(3,4,0),4);
}
L487064: { // 7653  jbe 0x4870b9
if(condition(8))goto L4870b9;
}
L487066: { // ff35206b8000  push dword ptr [0x806b20]
push(read((0x806b20u),4));
}
L48706c: { // e822b6f7ff  call 0x402693
push(0x487071u);dispatch(0x402693u);
}
L487071: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L487073: { // 754b  jne 0x4870c0
if(condition(1))goto L4870c0;
}
L487075: { // 837e2801  cmp dword ptr [esi + 0x28], 1
sub(read((0x28u+r[6]),4),0x1u,4);
}
L487079: { // 7545  jne 0x4870c0
if(condition(1))goto L4870c0;
}
L48707b: { // a11c3a8000  mov eax, dword ptr [0x803a1c]
put(0,read((0x803a1cu),4),4,0);
}
L487080: { // 6a01  push 1
push(0x1u);
}
L487082: { // 69c0ac010000  imul eax, eax, 0x1ac
put(0,multiply(get(0,4,0),0x1acu,4),4,0);
}
L487088: { // 8088dc73800080  or byte ptr [eax + 0x8073dc], 0x80
write((0x8073dcu+r[0]),logic(read((0x8073dcu+r[0]),1)|0x80u,1),1);
}
L48708f: { // 891d206b8000  mov dword ptr [0x806b20], ebx
write((0x806b20u),get(3,4,0),4);
}
L487095: { // ff7620  push dword ptr [esi + 0x20]
push(read((0x20u+r[6]),4));
}
L487098: { // 8d80dc738000  lea eax, [eax + 0x8073dc]
put(0,(0x8073dcu+r[0]),4,0);
}
L48709e: { // e8c2ff0000  call 0x497065
push(0x4870a3u);dispatch(0x497065u);
}
L4870a3: { // 6861010000  push 0x161
push(0x161u);
}
L4870a8: { // e8c6e2faff  call 0x435373
push(0x4870adu);dispatch(0x435373u);
}
L4870ad: { // c7462802000000  mov dword ptr [esi + 0x28], 2
write((0x28u+r[6]),0x2u,4);
}
L4870b4: { // 895e18  mov dword ptr [esi + 0x18], ebx
write((0x18u+r[6]),get(3,4,0),4);
}
L4870b7: { // eb07  jmp 0x4870c0
goto L4870c0;
}
L4870b9: { // 806603fd  and byte ptr [esi + 3], 0xfd
write((0x3u+r[6]),logic(read((0x3u+r[6]),1)&0xfdu,1),1);
}
L4870bd: { // 895e18  mov dword ptr [esi + 0x18], ebx
write((0x18u+r[6]),get(3,4,0),4);
}
L4870c0: { // 5f  pop edi
put(7,pop(),4,0);
}
L4870c1: { // 5e  pop esi
put(6,pop(),4,0);
}
L4870c2: { // 5b  pop ebx
put(3,pop(),4,0);
}
L4870c3: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00489ffc_tso0_drill_item_event2c_control_handler_mc_489ffc
void RecoveredBattle::fn_489ffc(){
goto L489ffc;
L489ffc: { // 53  push ebx
push(get(3,4,0));
}
L489ffd: { // 56  push esi
push(get(6,4,0));
}
L489ffe: { // 8b74240c  mov esi, dword ptr [esp + 0xc]
put(6,read((0xcu+r[4]),4),4,0);
}
L48a002: { // ff7624  push dword ptr [esi + 0x24]
push(read((0x24u+r[6]),4));
}
L48a005: { // e82cd00000  call 0x497036
push(0x48a00au);dispatch(0x497036u);
}
L48a00a: { // 33db  xor ebx, ebx
put(3,logic(get(3,4,0)^get(3,4,0),4),4,0);
}
L48a00c: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L48a00e: { // 0f8491000000  je 0x48a0a5
if(condition(0))goto L48a0a5;
}
L48a014: { // 391d74738000  cmp dword ptr [0x807374], ebx
sub(read((0x807374u),4),get(3,4,0),4);
}
L48a01a: { // 0f8e85000000  jle 0x48a0a5
if(condition(4))goto L48a0a5;
}
L48a020: { // ff0d74738000  dec dword ptr [0x807374]
write((0x807374u),inc(read((0x807374u),4),4,-1),4);
}
L48a026: { // 6851010000  push 0x151
push(0x151u);
}
L48a02b: { // ff3598956100  push dword ptr [0x619598]
push(read((0x619598u),4));
}
L48a031: { // be98658000  mov esi, 0x806598
put(6,0x806598u,4,0);
}
L48a036: { // 68808a5f00  push 0x5f8a80
push(0x5f8a80u);
}
L48a03b: { // 56  push esi
push(get(6,4,0));
}
L48a03c: { // e88ff20000  call 0x4992d0
push(0x48a041u);dispatch(0x4992d0u);
}
L48a041: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L48a044: { // 881d206a8000  mov byte ptr [0x806a20], bl
write((0x806a20u),get(3,1,0),1);
}
L48a04a: { // 56  push esi
push(get(6,4,0));
}
L48a04b: { // be206a8000  mov esi, 0x806a20
put(6,0x806a20u,4,0);
}
L48a050: { // 56  push esi
push(get(6,4,0));
}
L48a051: { // e8bad20000  call 0x497310
push(0x48a056u);dispatch(0x497310u);
}
L48a056: { // a11c3a8000  mov eax, dword ptr [0x803a1c]
put(0,read((0x803a1cu),4),4,0);
}
L48a05b: { // 59  pop ecx
put(1,pop(),4,0);
}
L48a05c: { // 69c0ac010000  imul eax, eax, 0x1ac
put(0,multiply(get(0,4,0),0x1acu,4),4,0);
}
L48a062: { // 80a0dc7380007f  and byte ptr [eax + 0x8073dc], 0x7f
write((0x8073dcu+r[0]),logic(read((0x8073dcu+r[0]),1)&0x7fu,1),1);
}
L48a069: { // 59  pop ecx
put(1,pop(),4,0);
}
L48a06a: { // 8d80dc738000  lea eax, [eax + 0x8073dc]
put(0,(0x8073dcu+r[0]),4,0);
}
L48a070: { // 56  push esi
push(get(6,4,0));
}
L48a071: { // a118668000  mov eax, dword ptr [0x806618]
put(0,read((0x806618u),4),4,0);
}
L48a076: { // be20668000  mov esi, 0x806620
put(6,0x806620u,4,0);
}
L48a07b: { // 682c8a5f00  push 0x5f8a2c
push(0x5f8a2cu);
}
L48a080: { // 56  push esi
push(get(6,4,0));
}
L48a081: { // c7402801000000  mov dword ptr [eax + 0x28], 1
write((0x28u+r[0]),0x1u,4);
}
L48a088: { // e843f20000  call 0x4992d0
push(0x48a08du);dispatch(0x4992d0u);
}
L48a08d: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L48a090: { // 6aff  push -1
push(0xffffffffu);
}
L48a092: { // 56  push esi
push(get(6,4,0));
}
L48a093: { // e8beddfcff  call 0x457e56
push(0x48a098u);dispatch(0x457e56u);
}
L48a098: { // 50  push eax
push(get(0,4,0));
}
L48a099: { // e81899f8ff  call 0x4139b6
push(0x48a09eu);dispatch(0x4139b6u);
}
L48a09e: { // a3206b8000  mov dword ptr [0x806b20], eax
write((0x806b20u),get(0,4,0),4);
}
L48a0a3: { // eb76  jmp 0x48a11b
goto L48a11b;
}
L48a0a5: { // 395e18  cmp dword ptr [esi + 0x18], ebx
sub(read((0x18u+r[6]),4),get(3,4,0),4);
}
L48a0a8: { // 766a  jbe 0x48a114
if(condition(8))goto L48a114;
}
L48a0aa: { // ff35206b8000  push dword ptr [0x806b20]
push(read((0x806b20u),4));
}
L48a0b0: { // e8de85f7ff  call 0x402693
push(0x48a0b5u);dispatch(0x402693u);
}
L48a0b5: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L48a0b7: { // 7562  jne 0x48a11b
if(condition(1))goto L48a11b;
}
L48a0b9: { // a118668000  mov eax, dword ptr [0x806618]
put(0,read((0x806618u),4),4,0);
}
L48a0be: { // 83782801  cmp dword ptr [eax + 0x28], 1
sub(read((0x28u+r[0]),4),0x1u,4);
}
L48a0c2: { // 7557  jne 0x48a11b
if(condition(1))goto L48a11b;
}
L48a0c4: { // 53  push ebx
push(get(3,4,0));
}
L48a0c5: { // 891d206b8000  mov dword ptr [0x806b20], ebx
write((0x806b20u),get(3,4,0),4);
}
L48a0cb: { // ff7624  push dword ptr [esi + 0x24]
push(read((0x24u+r[6]),4));
}
L48a0ce: { // 895e18  mov dword ptr [esi + 0x18], ebx
write((0x18u+r[6]),get(3,4,0),4);
}
L48a0d1: { // e88fcf0000  call 0x497065
push(0x48a0d6u);dispatch(0x497065u);
}
L48a0d6: { // 6a01  push 1
push(0x1u);
}
L48a0d8: { // ff7620  push dword ptr [esi + 0x20]
push(read((0x20u+r[6]),4));
}
L48a0db: { // e885cf0000  call 0x497065
push(0x48a0e0u);dispatch(0x497065u);
}
L48a0e0: { // a11c3a8000  mov eax, dword ptr [0x803a1c]
put(0,read((0x803a1cu),4),4,0);
}
L48a0e5: { // 685f010000  push 0x15f
push(0x15fu);
}
L48a0ea: { // 69c0ac010000  imul eax, eax, 0x1ac
put(0,multiply(get(0,4,0),0x1acu,4),4,0);
}
L48a0f0: { // 8088dc73800080  or byte ptr [eax + 0x8073dc], 0x80
write((0x8073dcu+r[0]),logic(read((0x8073dcu+r[0]),1)|0x80u,1),1);
}
L48a0f7: { // 806603fd  and byte ptr [esi + 3], 0xfd
write((0x3u+r[6]),logic(read((0x3u+r[6]),1)&0xfdu,1),1);
}
L48a0fb: { // 8d80dc738000  lea eax, [eax + 0x8073dc]
put(0,(0x8073dcu+r[0]),4,0);
}
L48a101: { // e86db2faff  call 0x435373
push(0x48a106u);dispatch(0x435373u);
}
L48a106: { // a118668000  mov eax, dword ptr [0x806618]
put(0,read((0x806618u),4),4,0);
}
L48a10b: { // c7402802000000  mov dword ptr [eax + 0x28], 2
write((0x28u+r[0]),0x2u,4);
}
L48a112: { // eb07  jmp 0x48a11b
goto L48a11b;
}
L48a114: { // 806603fd  and byte ptr [esi + 3], 0xfd
write((0x3u+r[6]),logic(read((0x3u+r[6]),1)&0xfdu,1),1);
}
L48a118: { // 895e18  mov dword ptr [esi + 0x18], ebx
write((0x18u+r[6]),get(3,4,0),4);
}
L48a11b: { // 5e  pop esi
put(6,pop(),4,0);
}
L48a11c: { // 5b  pop ebx
put(3,pop(),4,0);
}
L48a11d: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00487208_tile_overlay_state_machine_mc_487208
void RecoveredBattle::fn_487208(){
goto L487208;
L487208: { // 55  push ebp
push(get(5,4,0));
}
L487209: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L48720b: { // 8b15200d7e00  mov edx, dword ptr [0x7e0d20]
put(2,read((0x7e0d20u),4),4,0);
}
L487211: { // 53  push ebx
push(get(3,4,0));
}
L487212: { // 56  push esi
push(get(6,4,0));
}
L487213: { // 8b7508  mov esi, dword ptr [ebp + 8]
put(6,read((0x8u+r[5]),4),4,0);
}
L487216: { // 57  push edi
push(get(7,4,0));
}
L487217: { // bb00002000  mov ebx, 0x200000
put(3,0x200000u,4,0);
}
L48721c: { // 8b4608  mov eax, dword ptr [esi + 8]
put(0,read((0x8u+r[6]),4),4,0);
}
L48721f: { // 0fafc2  imul eax, edx
put(0,multiply(get(0,4,0),get(2,4,0),4),4,0);
}
L487222: { // 034604  add eax, dword ptr [esi + 4]
put(0,add(get(0,4,0),read((0x4u+r[6]),4),4,false),4,0);
}
L487225: { // 8bc8  mov ecx, eax
put(1,get(0,4,0),4,0);
}
L487227: { // 03d0  add edx, eax
put(2,add(get(2,4,0),get(0,4,0),4,false),4,0);
}
L487229: { // c1e102  shl ecx, 2
put(1,shift(get(1,4,0),0x2u,4,0),4,0);
}
L48722c: { // 8bb9a0bc7c00  mov edi, dword ptr [ecx + 0x7cbca0]
put(7,read((0x7cbca0u+r[1]),4),4,0);
}
L487232: { // 897d08  mov dword ptr [ebp + 8], edi
write((0x8u+r[5]),get(7,4,0),4);
}
L487235: { // 81e70000e003  and edi, 0x3e00000
put(7,logic(get(7,4,0)&0x3e00000u,4),4,0);
}
L48723b: { // 3bdf  cmp ebx, edi
sub(get(3,4,0),get(7,4,0),4);
}
L48723d: { // 8b5e18  mov ebx, dword ptr [esi + 0x18]
put(3,read((0x18u+r[6]),4),4,0);
}
L487240: { // 1bff  sbb edi, edi
put(7,sub(get(7,4,0),get(7,4,0),4,true),4,0);
}
L487242: { // 83e72c  and edi, 0x2c
put(7,logic(get(7,4,0)&0x2cu,4),4,0);
}
L487245: { // 83c70b  add edi, 0xb
put(7,add(get(7,4,0),0xbu,4,false),4,0);
}
L487248: { // 83fb06  cmp ebx, 6
sub(get(3,4,0),0x6u,4);
}
L48724b: { // 7756  ja 0x4872a3
if(condition(9))goto L4872a3;
}
L48724d: { // 7443  je 0x487292
if(condition(0))goto L487292;
}
L48724f: { // 85db  test ebx, ebx
logic(get(3,4,0)&get(3,4,0),4);
}
L487251: { // 0f85fd010000  jne 0x487454
if(condition(1))goto L487454;
}
L487257: { // 8d7701  lea esi, [edi + 1]
put(6,(0x1u+r[7]),4,0);
}
L48725a: { // 8d0440  lea eax, [eax + eax*2]
put(0,(0x0u+r[0]+r[0]*2u),4,0);
}
L48725d: { // 89b1300d7e00  mov dword ptr [ecx + 0x7e0d30], esi
write((0x7e0d30u+r[1]),get(6,4,0),4);
}
L487263: { // 8b7508  mov esi, dword ptr [ebp + 8]
put(6,read((0x8u+r[5]),4),4,0);
}
L487266: { // 211c85a43c7b00  and dword ptr [eax*4 + 0x7b3ca4], ebx
write((0x7b3ca4u+r[0]*4u),logic(read((0x7b3ca4u+r[0]*4u),4)&get(3,4,0),4),4);
}
L48726d: { // 8d0452  lea eax, [edx + edx*2]
put(0,(0x0u+r[2]+r[2]*2u),4,0);
}
L487270: { // 83c70c  add edi, 0xc
put(7,add(get(7,4,0),0xcu,4,false),4,0);
}
L487273: { // 81ce00020000  or esi, 0x200
put(6,logic(get(6,4,0)|0x200u,4),4,0);
}
L487279: { // 211c85a43c7b00  and dword ptr [eax*4 + 0x7b3ca4], ebx
write((0x7b3ca4u+r[0]*4u),logic(read((0x7b3ca4u+r[0]*4u),4)&get(3,4,0),4),4);
}
L487280: { // 893c95300d7e00  mov dword ptr [edx*4 + 0x7e0d30], edi
write((0x7e0d30u+r[2]*4u),get(7,4,0),4);
}
L487287: { // 89b1a0bc7c00  mov dword ptr [ecx + 0x7cbca0], esi
write((0x7cbca0u+r[1]),get(6,4,0),4);
}
L48728d: { // e9c2010000  jmp 0x487454
goto L487454;
}
L487292: { // 8d4702  lea eax, [edi + 2]
put(0,(0x2u+r[7]),4,0);
}
L487295: { // 83c70d  add edi, 0xd
put(7,add(get(7,4,0),0xdu,4,false),4,0);
}
L487298: { // 8981300d7e00  mov dword ptr [ecx + 0x7e0d30], eax
write((0x7e0d30u+r[1]),get(0,4,0),4);
}
L48729e: { // e9ff000000  jmp 0x4873a2
goto L4873a2;
}
L4872a3: { // 83fb12  cmp ebx, 0x12
sub(get(3,4,0),0x12u,4);
}
L4872a6: { // 772d  ja 0x4872d5
if(condition(9))goto L4872d5;
}
L4872a8: { // 741a  je 0x4872c4
if(condition(0))goto L4872c4;
}
L4872aa: { // 83fb0c  cmp ebx, 0xc
sub(get(3,4,0),0xcu,4);
}
L4872ad: { // 0f85a1010000  jne 0x487454
if(condition(1))goto L487454;
}
L4872b3: { // 8d4703  lea eax, [edi + 3]
put(0,(0x3u+r[7]),4,0);
}
L4872b6: { // 83c70e  add edi, 0xe
put(7,add(get(7,4,0),0xeu,4,false),4,0);
}
L4872b9: { // 8981300d7e00  mov dword ptr [ecx + 0x7e0d30], eax
write((0x7e0d30u+r[1]),get(0,4,0),4);
}
L4872bf: { // e9de000000  jmp 0x4873a2
goto L4873a2;
}
L4872c4: { // 8d4704  lea eax, [edi + 4]
put(0,(0x4u+r[7]),4,0);
}
L4872c7: { // 83c70f  add edi, 0xf
put(7,add(get(7,4,0),0xfu,4,false),4,0);
}
L4872ca: { // 8981300d7e00  mov dword ptr [ecx + 0x7e0d30], eax
write((0x7e0d30u+r[1]),get(0,4,0),4);
}
L4872d0: { // e9cd000000  jmp 0x4873a2
goto L4873a2;
}
L4872d5: { // 6a18  push 0x18
push(0x18u);
}
L4872d7: { // 5f  pop edi
put(7,pop(),4,0);
}
L4872d8: { // 3bdf  cmp ebx, edi
sub(get(3,4,0),get(7,4,0),4);
}
L4872da: { // 0f84ff000000  je 0x4873df
if(condition(0))goto L4873df;
}
L4872e0: { // 83fb1e  cmp ebx, 0x1e
sub(get(3,4,0),0x1eu,4);
}
L4872e3: { // 0f84df000000  je 0x4873c8
if(condition(0))goto L4873c8;
}
L4872e9: { // 83fb24  cmp ebx, 0x24
sub(get(3,4,0),0x24u,4);
}
L4872ec: { // 0f84bc000000  je 0x4873ae
if(condition(0))goto L4873ae;
}
L4872f2: { // 83fb2a  cmp ebx, 0x2a
sub(get(3,4,0),0x2au,4);
}
L4872f5: { // 0f849d000000  je 0x487398
if(condition(0))goto L487398;
}
L4872fb: { // 83fb30  cmp ebx, 0x30
sub(get(3,4,0),0x30u,4);
}
L4872fe: { // 747e  je 0x48737e
if(condition(0))goto L48737e;
}
L487300: { // 83fb36  cmp ebx, 0x36
sub(get(3,4,0),0x36u,4);
}
L487303: { // 0f854b010000  jne 0x487454
if(condition(1))goto L487454;
}
L487309: { // 8b7d08  mov edi, dword ptr [ebp + 8]
put(7,read((0x8u+r[5]),4),4,0);
}
L48730c: { // c781300d7e000b000000  mov dword ptr [ecx + 0x7e0d30], 0xb
write((0x7e0d30u+r[1]),0xbu,4);
}
L487316: { // c70495300d7e0016000000  mov dword ptr [edx*4 + 0x7e0d30], 0x16
write((0x7e0d30u+r[2]*4u),0x16u,4);
}
L487321: { // 8d0440  lea eax, [eax + eax*2]
put(0,(0x0u+r[0]+r[0]*2u),4,0);
}
L487324: { // 8d1452  lea edx, [edx + edx*2]
put(2,(0x0u+r[2]+r[2]*2u),4,0);
}
L487327: { // 81e7fffdffff  and edi, 0xfffffdff
put(7,logic(get(7,4,0)&0xfffffdffu,4),4,0);
}
L48732d: { // c1e002  shl eax, 2
put(0,shift(get(0,4,0),0x2u,4,0),4,0);
}
L487330: { // c1e202  shl edx, 2
put(2,shift(get(2,4,0),0x2u,4,0),4,0);
}
L487333: { // c780a03c7b0019000000  mov dword ptr [eax + 0x7b3ca0], 0x19
write((0x7b3ca0u+r[0]),0x19u,4);
}
L48733d: { // 89b9a0bc7c00  mov dword ptr [ecx + 0x7cbca0], edi
write((0x7cbca0u+r[1]),get(7,4,0),4);
}
L487343: { // c782a03c7b001a000000  mov dword ptr [edx + 0x7b3ca0], 0x1a
write((0x7b3ca0u+r[2]),0x1au,4);
}
L48734d: { // 8388a43c7b00ff  or dword ptr [eax + 0x7b3ca4], 0xffffffff
write((0x7b3ca4u+r[0]),logic(read((0x7b3ca4u+r[0]),4)|0xffffffffu,4),4);
}
L487354: { // 838aa43c7b00ff  or dword ptr [edx + 0x7b3ca4], 0xffffffff
write((0x7b3ca4u+r[2]),logic(read((0x7b3ca4u+r[2]),4)|0xffffffffu,4),4);
}
L48735b: { // 806603fd  and byte ptr [esi + 3], 0xfd
write((0x3u+r[6]),logic(read((0x3u+r[6]),1)&0xfdu,1),1);
}
L48735f: { // 834e18ff  or dword ptr [esi + 0x18], 0xffffffff
write((0x18u+r[6]),logic(read((0x18u+r[6]),4)|0xffffffffu,4),4);
}
L487363: { // 8b81a0bc7c00  mov eax, dword ptr [ecx + 0x7cbca0]
put(0,read((0x7cbca0u+r[1]),4),4,0);
}
L487369: { // 25ffff3ffc  and eax, 0xfc3fffff
put(0,logic(get(0,4,0)&0xfc3fffffu,4),4,0);
}
L48736e: { // 0d00002000  or eax, 0x200000
put(0,logic(get(0,4,0)|0x200000u,4),4,0);
}
L487373: { // 8981a0bc7c00  mov dword ptr [ecx + 0x7cbca0], eax
write((0x7cbca0u+r[1]),get(0,4,0),4);
}
L487379: { // e9d6000000  jmp 0x487454
goto L487454;
}
L48737e: { // c781300d7e000c000000  mov dword ptr [ecx + 0x7e0d30], 0xc
write((0x7e0d30u+r[1]),0xcu,4);
}
L487388: { // c70495300d7e0017000000  mov dword ptr [edx*4 + 0x7e0d30], 0x17
write((0x7e0d30u+r[2]*4u),0x17u,4);
}
L487393: { // e9bc000000  jmp 0x487454
goto L487454;
}
L487398: { // c781300d7e000d000000  mov dword ptr [ecx + 0x7e0d30], 0xd
write((0x7e0d30u+r[1]),0xdu,4);
}
L4873a2: { // 893c95300d7e00  mov dword ptr [edx*4 + 0x7e0d30], edi
write((0x7e0d30u+r[2]*4u),get(7,4,0),4);
}
L4873a9: { // e9a6000000  jmp 0x487454
goto L487454;
}
L4873ae: { // c781300d7e000e000000  mov dword ptr [ecx + 0x7e0d30], 0xe
write((0x7e0d30u+r[1]),0xeu,4);
}
L4873b8: { // c70495300d7e0019000000  mov dword ptr [edx*4 + 0x7e0d30], 0x19
write((0x7e0d30u+r[2]*4u),0x19u,4);
}
L4873c3: { // e98c000000  jmp 0x487454
goto L487454;
}
L4873c8: { // c781300d7e000f000000  mov dword ptr [ecx + 0x7e0d30], 0xf
write((0x7e0d30u+r[1]),0xfu,4);
}
L4873d2: { // c70495300d7e001a000000  mov dword ptr [edx*4 + 0x7e0d30], 0x1a
write((0x7e0d30u+r[2]*4u),0x1au,4);
}
L4873dd: { // eb75  jmp 0x487454
goto L487454;
}
L4873df: { // 8b7d08  mov edi, dword ptr [ebp + 8]
put(7,read((0x8u+r[5]),4),4,0);
}
L4873e2: { // c781300d7e0009000000  mov dword ptr [ecx + 0x7e0d30], 9
write((0x7e0d30u+r[1]),0x9u,4);
}
L4873ec: { // 81e70000e0ff  and edi, 0xffe00000
put(7,logic(get(7,4,0)&0xffe00000u,4),4,0);
}
L4873f2: { // c70495300d7e000a000000  mov dword ptr [edx*4 + 0x7e0d30], 0xa
write((0x7e0d30u+r[2]*4u),0xau,4);
}
L4873fd: { // 4f  dec edi
put(7,inc(get(7,4,0),4,-1),4,0);
}
L4873fe: { // 337d08  xor edi, dword ptr [ebp + 8]
put(7,logic(get(7,4,0)^read((0x8u+r[5]),4),4),4,0);
}
L487401: { // 81e70000e003  and edi, 0x3e00000
put(7,logic(get(7,4,0)&0x3e00000u,4),4,0);
}
L487407: { // 337d08  xor edi, dword ptr [ebp + 8]
put(7,logic(get(7,4,0)^read((0x8u+r[5]),4),4),4,0);
}
L48740a: { // f7c70000e003  test edi, 0x3e00000
logic(get(7,4,0)&0x3e00000u,4);
}
L487410: { // 89b9a0bc7c00  mov dword ptr [ecx + 0x7cbca0], edi
write((0x7cbca0u+r[1]),get(7,4,0),4);
}
L487416: { // 753c  jne 0x487454
if(condition(1))goto L487454;
}
L487418: { // 806603fd  and byte ptr [esi + 3], 0xfd
write((0x3u+r[6]),logic(read((0x3u+r[6]),1)&0xfdu,1),1);
}
L48741c: { // 8d0440  lea eax, [eax + eax*2]
put(0,(0x0u+r[0]+r[0]*2u),4,0);
}
L48741f: { // 8d1452  lea edx, [edx + edx*2]
put(2,(0x0u+r[2]+r[2]*2u),4,0);
}
L487422: { // c1e002  shl eax, 2
put(0,shift(get(0,4,0),0x2u,4,0),4,0);
}
L487425: { // c1e202  shl edx, 2
put(2,shift(get(2,4,0),0x2u,4,0),4,0);
}
L487428: { // 83a0a03c7b0000  and dword ptr [eax + 0x7b3ca0], 0
write((0x7b3ca0u+r[0]),logic(read((0x7b3ca0u+r[0]),4)&0x0u,4),4);
}
L48742f: { // c782a03c7b0001000000  mov dword ptr [edx + 0x7b3ca0], 1
write((0x7b3ca0u+r[2]),0x1u,4);
}
L487439: { // 8388a43c7b00ff  or dword ptr [eax + 0x7b3ca4], 0xffffffff
write((0x7b3ca4u+r[0]),logic(read((0x7b3ca4u+r[0]),4)|0xffffffffu,4),4);
}
L487440: { // 838aa43c7b00ff  or dword ptr [edx + 0x7b3ca4], 0xffffffff
write((0x7b3ca4u+r[2]),logic(read((0x7b3ca4u+r[2]),4)|0xffffffffu,4),4);
}
L487447: { // 83661800  and dword ptr [esi + 0x18], 0
write((0x18u+r[6]),logic(read((0x18u+r[6]),4)&0x0u,4),4);
}
L48744b: { // 6681a1a2bc7c001ffc  and word ptr [ecx + 0x7cbca2], 0xfc1f
write((0x7cbca2u+r[1]),logic(read((0x7cbca2u+r[1]),2)&0xfc1fu,2),2);
}
L487454: { // 5f  pop edi
put(7,pop(),4,0);
}
L487455: { // 5e  pop esi
put(6,pop(),4,0);
}
L487456: { // 5b  pop ebx
put(3,pop(),4,0);
}
L487457: { // 5d  pop ebp
put(5,pop(),4,0);
}
L487458: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
} // namespace fsb::core
