// Generated by tools/translate_battle.py; edit the generator, not this file.
// Original EXE SHA256: 710881d024ab1fcf738b342c248631363c9de3a51b32a7e3d61781b791eff454
#include "fsb_core/recovered_battle.hpp"
#include <cstring>
#include <cmath>
namespace fsb::core {
// 004015c2_clip_rect_to_bounds_mc_4015c2
void RecoveredBattle::fn_4015c2(){
goto L4015c2;
L4015c2: { // 55  push ebp
push(get(5,4,0));
}
L4015c3: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L4015c5: { // 8b4d08  mov ecx, dword ptr [ebp + 8]
put(1,read((0x8u+r[5]),4),4,0);
}
L4015c8: { // 53  push ebx
push(get(3,4,0));
}
L4015c9: { // 8b4514  mov eax, dword ptr [ebp + 0x14]
put(0,read((0x14u+r[5]),4),4,0);
}
L4015cc: { // 56  push esi
push(get(6,4,0));
}
L4015cd: { // 8b750c  mov esi, dword ptr [ebp + 0xc]
put(6,read((0xcu+r[5]),4),4,0);
}
L4015d0: { // 8b11  mov edx, dword ptr [ecx]
put(2,read((0x0u+r[1]),4),4,0);
}
L4015d2: { // 57  push edi
push(get(7,4,0));
}
L4015d3: { // 8b3e  mov edi, dword ptr [esi]
put(7,read((0x0u+r[6]),4),4,0);
}
L4015d5: { // 3bfa  cmp edi, edx
sub(get(7,4,0),get(2,4,0),4);
}
L4015d7: { // 7d08  jge 0x4015e1
if(condition(3))goto L4015e1;
}
L4015d9: { // 2bd7  sub edx, edi
put(2,sub(get(2,4,0),get(7,4,0),4,false),4,0);
}
L4015db: { // 0110  add dword ptr [eax], edx
write((0x0u+r[0]),add(read((0x0u+r[0]),4),get(2,4,0),4,false),4);
}
L4015dd: { // 8b11  mov edx, dword ptr [ecx]
put(2,read((0x0u+r[1]),4),4,0);
}
L4015df: { // 8916  mov dword ptr [esi], edx
write((0x0u+r[6]),get(2,4,0),4);
}
L4015e1: { // 8b7d10  mov edi, dword ptr [ebp + 0x10]
put(7,read((0x10u+r[5]),4),4,0);
}
L4015e4: { // 8b5104  mov edx, dword ptr [ecx + 4]
put(2,read((0x4u+r[1]),4),4,0);
}
L4015e7: { // 8b1f  mov ebx, dword ptr [edi]
put(3,read((0x0u+r[7]),4),4,0);
}
L4015e9: { // 3bda  cmp ebx, edx
sub(get(3,4,0),get(2,4,0),4);
}
L4015eb: { // 7d0a  jge 0x4015f7
if(condition(3))goto L4015f7;
}
L4015ed: { // 2bd3  sub edx, ebx
put(2,sub(get(2,4,0),get(3,4,0),4,false),4,0);
}
L4015ef: { // 015004  add dword ptr [eax + 4], edx
write((0x4u+r[0]),add(read((0x4u+r[0]),4),get(2,4,0),4,false),4);
}
L4015f2: { // 8b5104  mov edx, dword ptr [ecx + 4]
put(2,read((0x4u+r[1]),4),4,0);
}
L4015f5: { // 8917  mov dword ptr [edi], edx
write((0x0u+r[7]),get(2,4,0),4);
}
L4015f7: { // 8b16  mov edx, dword ptr [esi]
put(2,read((0x0u+r[6]),4),4,0);
}
L4015f9: { // 8b18  mov ebx, dword ptr [eax]
put(3,read((0x0u+r[0]),4),4,0);
}
L4015fb: { // 8b7008  mov esi, dword ptr [eax + 8]
put(6,read((0x8u+r[0]),4),4,0);
}
L4015fe: { // 89550c  mov dword ptr [ebp + 0xc], edx
write((0xcu+r[5]),get(2,4,0),4);
}
L401601: { // 8b5108  mov edx, dword ptr [ecx + 8]
put(2,read((0x8u+r[1]),4),4,0);
}
L401604: { // 2bf3  sub esi, ebx
put(6,sub(get(6,4,0),get(3,4,0),4,false),4,0);
}
L401606: { // 03750c  add esi, dword ptr [ebp + 0xc]
put(6,add(get(6,4,0),read((0xcu+r[5]),4),4,false),4,0);
}
L401609: { // 3bd6  cmp edx, esi
sub(get(2,4,0),get(6,4,0),4);
}
L40160b: { // 7d08  jge 0x401615
if(condition(3))goto L401615;
}
L40160d: { // 2b550c  sub edx, dword ptr [ebp + 0xc]
put(2,sub(get(2,4,0),read((0xcu+r[5]),4),4,false),4,0);
}
L401610: { // 03d3  add edx, ebx
put(2,add(get(2,4,0),get(3,4,0),4,false),4,0);
}
L401612: { // 895008  mov dword ptr [eax + 8], edx
write((0x8u+r[0]),get(2,4,0),4);
}
L401615: { // 8b5004  mov edx, dword ptr [eax + 4]
put(2,read((0x4u+r[0]),4),4,0);
}
L401618: { // 8b700c  mov esi, dword ptr [eax + 0xc]
put(6,read((0xcu+r[0]),4),4,0);
}
L40161b: { // 8b3f  mov edi, dword ptr [edi]
put(7,read((0x0u+r[7]),4),4,0);
}
L40161d: { // 8b490c  mov ecx, dword ptr [ecx + 0xc]
put(1,read((0xcu+r[1]),4),4,0);
}
L401620: { // 2bf2  sub esi, edx
put(6,sub(get(6,4,0),get(2,4,0),4,false),4,0);
}
L401622: { // 03f7  add esi, edi
put(6,add(get(6,4,0),get(7,4,0),4,false),4,0);
}
L401624: { // 3bce  cmp ecx, esi
sub(get(1,4,0),get(6,4,0),4);
}
L401626: { // 7d07  jge 0x40162f
if(condition(3))goto L40162f;
}
L401628: { // 2bcf  sub ecx, edi
put(1,sub(get(1,4,0),get(7,4,0),4,false),4,0);
}
L40162a: { // 03ca  add ecx, edx
put(1,add(get(1,4,0),get(2,4,0),4,false),4,0);
}
L40162c: { // 89480c  mov dword ptr [eax + 0xc], ecx
write((0xcu+r[0]),get(1,4,0),4);
}
L40162f: { // 8b4808  mov ecx, dword ptr [eax + 8]
put(1,read((0x8u+r[0]),4),4,0);
}
L401632: { // 2b08  sub ecx, dword ptr [eax]
put(1,sub(get(1,4,0),read((0x0u+r[0]),4),4,false),4,0);
}
L401634: { // 85c9  test ecx, ecx
logic(get(1,4,0)&get(1,4,0),4);
}
L401636: { // 7e0e  jle 0x401646
if(condition(4))goto L401646;
}
L401638: { // 8b400c  mov eax, dword ptr [eax + 0xc]
put(0,read((0xcu+r[0]),4),4,0);
}
L40163b: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L40163d: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L40163f: { // 7e05  jle 0x401646
if(condition(4))goto L401646;
}
L401641: { // 6a01  push 1
push(0x1u);
}
L401643: { // 58  pop eax
put(0,pop(),4,0);
}
L401644: { // eb02  jmp 0x401648
goto L401648;
}
L401646: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L401648: { // 5f  pop edi
put(7,pop(),4,0);
}
L401649: { // 5e  pop esi
put(6,pop(),4,0);
}
L40164a: { // 5b  pop ebx
put(3,pop(),4,0);
}
L40164b: { // 5d  pop ebp
put(5,pop(),4,0);
}
L40164c: { // c21000  ret 0x10
pop();r[4]+=0x10u;return;
}
}
// 004029db_reset_object_bucket_handles_mc_4029db
void RecoveredBattle::fn_4029db(){
goto L4029db;
L4029db: { // b9f84c6d00  mov ecx, 0x6d4cf8
put(1,0x6d4cf8u,4,0);
}
L4029e0: { // 8b815cfeffff  mov eax, dword ptr [ecx - 0x1a4]
put(0,read((0xfffffe5cu+r[1]),4),4,0);
}
L4029e6: { // 3bc1  cmp eax, ecx
sub(get(0,4,0),get(1,4,0),4);
}
L4029e8: { // 7409  je 0x4029f3
if(condition(0))goto L4029f3;
}
L4029ea: { // 834820ff  or dword ptr [eax + 0x20], 0xffffffff
write((0x20u+r[0]),logic(read((0x20u+r[0]),4)|0xffffffffu,4),4);
}
L4029ee: { // 8b4004  mov eax, dword ptr [eax + 4]
put(0,read((0x4u+r[0]),4),4,0);
}
L4029f1: { // ebf3  jmp 0x4029e6
goto L4029e6;
}
L4029f3: { // 81c150030000  add ecx, 0x350
put(1,add(get(1,4,0),0x350u,4,false),4,0);
}
L4029f9: { // 81f928646d00  cmp ecx, 0x6d6428
sub(get(1,4,0),0x6d6428u,4);
}
L4029ff: { // 7cdf  jl 0x4029e0
if(condition(2))goto L4029e0;
}
L402a01: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00407ffd_advance_frame_loop_state_mc_407ffd
void RecoveredBattle::fn_407ffd(){
goto L407ffd;
L407ffd: { // a158a56d00  mov eax, dword ptr [0x6da558]
put(0,read((0x6da558u),4),4,0);
}
L408002: { // 56  push esi
push(get(6,4,0));
}
L408003: { // 33f6  xor esi, esi
put(6,logic(get(6,4,0)^get(6,4,0),4),4,0);
}
L408005: { // 3bc6  cmp eax, esi
sub(get(0,4,0),get(6,4,0),4);
}
L408007: { // 741d  je 0x408026
if(condition(0))goto L408026;
}
L408009: { // 3935a0666d00  cmp dword ptr [0x6d66a0], esi
sub(read((0x6d66a0u),4),get(6,4,0),4);
}
L40800f: { // 7511  jne 0x408022
if(condition(1))goto L408022;
}
L408011: { // 56  push esi
push(get(6,4,0));
}
L408012: { // 56  push esi
push(get(6,4,0));
}
L408013: { // 6a10  push 0x10
push(0x10u);
}
L408015: { // e8f590ffff  call 0x40110f
push(0x40801au);dispatch(0x40110fu);
}
L40801a: { // ff05a0666d00  inc dword ptr [0x6d66a0]
write((0x6d66a0u),inc(read((0x6d66a0u),4),4,1),4);
}
L408020: { // eb57  jmp 0x408079
goto L408079;
}
L408022: { // 3bc6  cmp eax, esi
sub(get(0,4,0),get(6,4,0),4);
}
L408024: { // 753b  jne 0x408061
if(condition(1))goto L408061;
}
L408026: { // 39350c0e6e00  cmp dword ptr [0x6e0e0c], esi
sub(read((0x6e0e0cu),4),get(6,4,0),4);
}
L40802c: { // 7433  je 0x408061
if(condition(0))goto L408061;
}
L40802e: { // 39352c6b6d00  cmp dword ptr [0x6d6b2c], esi
sub(read((0x6d6b2cu),4),get(6,4,0),4);
}
L408034: { // 7505  jne 0x40803b
if(condition(1))goto L40803b;
}
L408036: { // e8a0a9ffff  call 0x4029db
push(0x40803bu);dispatch(0x4029dbu);
}
L40803b: { // 3935609e6d00  cmp dword ptr [0x6d9e60], esi
sub(read((0x6d9e60u),4),get(6,4,0),4);
}
L408041: { // 740c  je 0x40804f
if(condition(0))goto L40804f;
}
L408043: { // 813d2c6b6d00ea010000  cmp dword ptr [0x6d6b2c], 0x1ea
sub(read((0x6d6b2cu),4),0x1eau,4);
}
L40804d: { // 7e0a  jle 0x408059
if(condition(4))goto L408059;
}
L40804f: { // c70558a56d0001000000  mov dword ptr [0x6da558], 1
write((0x6da558u),0x1u,4);
}
L408059: { // ff052c6b6d00  inc dword ptr [0x6d6b2c]
write((0x6d6b2cu),inc(read((0x6d6b2cu),4),4,1),4);
}
L40805f: { // eb18  jmp 0x408079
goto L408079;
}
L408061: { // 393548146e00  cmp dword ptr [0x6e1448], esi
sub(read((0x6e1448u),4),get(6,4,0),4);
}
L408067: { // 7410  je 0x408079
if(condition(0))goto L408079;
}
L408069: { // 893548146e00  mov dword ptr [0x6e1448], esi
write((0x6e1448u),get(6,4,0),4);
}
L40806f: { // c7050c0e6e0001000000  mov dword ptr [0x6e0e0c], 1
write((0x6e0e0cu),0x1u,4);
}
L408079: { // 393540a66d00  cmp dword ptr [0x6da640], esi
sub(read((0x6da640u),4),get(6,4,0),4);
}
L40807f: { // 7421  je 0x4080a2
if(condition(0))goto L4080a2;
}
L408081: { // 393510a66d00  cmp dword ptr [0x6da610], esi
sub(read((0x6da610u),4),get(6,4,0),4);
}
L408087: { // 7419  je 0x4080a2
if(condition(0))goto L4080a2;
}
L408089: { // 3935acad6d00  cmp dword ptr [0x6dadac], esi
sub(read((0x6dadacu),4),get(6,4,0),4);
}
L40808f: { // 7411  je 0x4080a2
if(condition(0))goto L4080a2;
}
L408091: { // 3935b0ad6d00  cmp dword ptr [0x6dadb0], esi
sub(read((0x6dadb0u),4),get(6,4,0),4);
}
L408097: { // 7409  je 0x4080a2
if(condition(0))goto L4080a2;
}
L408099: { // 56  push esi
push(get(6,4,0));
}
L40809a: { // 56  push esi
push(get(6,4,0));
}
L40809b: { // 6a10  push 0x10
push(0x10u);
}
L40809d: { // e86d90ffff  call 0x40110f
push(0x4080a2u);dispatch(0x40110fu);
}
L4080a2: { // ff05d4a26d00  inc dword ptr [0x6da2d4]
write((0x6da2d4u),inc(read((0x6da2d4u),4),4,1),4);
}
L4080a8: { // 8325c09e6d00ef  and dword ptr [0x6d9ec0], 0xffffffef
write((0x6d9ec0u),logic(read((0x6d9ec0u),4)&0xffffffefu,4),4);
}
L4080af: { // 8935dca26d00  mov dword ptr [0x6da2dc], esi
write((0x6da2dcu),get(6,4,0),4);
}
L4080b5: { // 8935046b6d00  mov dword ptr [0x6d6b04], esi
write((0x6d6b04u),get(6,4,0),4);
}
L4080bb: { // 893544146e00  mov dword ptr [0x6e1444], esi
write((0x6e1444u),get(6,4,0),4);
}
L4080c1: { // 8935444b6d00  mov dword ptr [0x6d4b44], esi
write((0x6d4b44u),get(6,4,0),4);
}
L4080c7: { // 8935384b6d00  mov dword ptr [0x6d4b38], esi
write((0x6d4b38u),get(6,4,0),4);
}
L4080cd: { // 8935b8b67400  mov dword ptr [0x74b6b8], esi
write((0x74b6b8u),get(6,4,0),4);
}
L4080d3: { // 89352c9d6d00  mov dword ptr [0x6d9d2c], esi
write((0x6d9d2cu),get(6,4,0),4);
}
L4080d9: { // 8935289d6d00  mov dword ptr [0x6d9d28], esi
write((0x6d9d28u),get(6,4,0),4);
}
L4080df: { // 5e  pop esi
put(6,pop(),4,0);
}
L4080e0: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00401c34_scale_rect_to_screen_mc_401c34
void RecoveredBattle::fn_401c34(){
goto L401c34;
L401c34: { // f605bc9e6d0008  test byte ptr [0x6d9ebc], 8
logic(read((0x6d9ebcu),1)&0x8u,1);
}
L401c3b: { // 56  push esi
push(get(6,4,0));
}
L401c3c: { // 57  push edi
push(get(7,4,0));
}
L401c3d: { // 7527  jne 0x401c66
if(condition(1))goto L401c66;
}
L401c3f: { // 6817050000  push 0x517
push(0x517u);
}
L401c44: { // 6a5c  push 0x5c
push(0x5cu);
}
L401c46: { // 6878604a00  push 0x4a6078
push(0x4a6078u);
}
L401c4b: { // e820580900  call 0x497470
push(0x401c50u);dispatch(0x497470u);
}
L401c50: { // 59  pop ecx
put(1,pop(),4,0);
}
L401c51: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L401c52: { // 59  pop ecx
put(1,pop(),4,0);
}
L401c53: { // 50  push eax
push(get(0,4,0));
}
L401c54: { // 686c624a00  push 0x4a626c
push(0x4a626cu);
}
L401c59: { // 685c604a00  push 0x4a605c
push(0x4a605cu);
}
L401c5e: { // e8c7fcffff  call 0x40192a
push(0x401c63u);dispatch(0x40192au);
}
L401c63: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L401c66: { // 8b35f8666d00  mov esi, dword ptr [0x6d66f8]
put(6,read((0x6d66f8u),4),4,0);
}
L401c6c: { // 8b4c240c  mov ecx, dword ptr [esp + 0xc]
put(1,read((0xcu+r[4]),4),4,0);
}
L401c70: { // 2b35f0666d00  sub esi, dword ptr [0x6d66f0]
put(6,sub(get(6,4,0),read((0x6d66f0u),4),4,false),4,0);
}
L401c76: { // 8b3dfc666d00  mov edi, dword ptr [0x6d66fc]
put(7,read((0x6d66fcu),4),4,0);
}
L401c7c: { // 2b3df4666d00  sub edi, dword ptr [0x6d66f4]
put(7,sub(get(7,4,0),read((0x6d66f4u),4),4,false),4,0);
}
L401c82: { // 8bc6  mov eax, esi
put(0,get(6,4,0),4,0);
}
L401c84: { // 0faf01  imul eax, dword ptr [ecx]
put(0,multiply(get(0,4,0),read((0x0u+r[1]),4),4),4,0);
}
L401c87: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L401c88: { // f73d4c504a00  idiv dword ptr [0x4a504c]
divide(read((0x4a504cu),4),true);
}
L401c8e: { // 8901  mov dword ptr [ecx], eax
write((0x0u+r[1]),get(0,4,0),4);
}
L401c90: { // 8bc6  mov eax, esi
put(0,get(6,4,0),4,0);
}
L401c92: { // 0faf4108  imul eax, dword ptr [ecx + 8]
put(0,multiply(get(0,4,0),read((0x8u+r[1]),4),4),4,0);
}
L401c96: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L401c97: { // f73d4c504a00  idiv dword ptr [0x4a504c]
divide(read((0x4a504cu),4),true);
}
L401c9d: { // 894108  mov dword ptr [ecx + 8], eax
write((0x8u+r[1]),get(0,4,0),4);
}
L401ca0: { // 8bc7  mov eax, edi
put(0,get(7,4,0),4,0);
}
L401ca2: { // 0faf4104  imul eax, dword ptr [ecx + 4]
put(0,multiply(get(0,4,0),read((0x4u+r[1]),4),4),4,0);
}
L401ca6: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L401ca7: { // f73d50504a00  idiv dword ptr [0x4a5050]
divide(read((0x4a5050u),4),true);
}
L401cad: { // 894104  mov dword ptr [ecx + 4], eax
write((0x4u+r[1]),get(0,4,0),4);
}
L401cb0: { // 8bc7  mov eax, edi
put(0,get(7,4,0),4,0);
}
L401cb2: { // 0faf410c  imul eax, dword ptr [ecx + 0xc]
put(0,multiply(get(0,4,0),read((0xcu+r[1]),4),4),4,0);
}
L401cb6: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L401cb7: { // f73d50504a00  idiv dword ptr [0x4a5050]
divide(read((0x4a5050u),4),true);
}
L401cbd: { // 89410c  mov dword ptr [ecx + 0xc], eax
write((0xcu+r[1]),get(0,4,0),4);
}
L401cc0: { // ff35f4666d00  push dword ptr [0x6d66f4]
push(read((0x6d66f4u),4));
}
L401cc6: { // ff35f0666d00  push dword ptr [0x6d66f0]
push(read((0x6d66f0u),4));
}
L401ccc: { // 51  push ecx
push(get(1,4,0));
}
L401ccd: { // ff15a8948500  call dword ptr [0x8594a8]
push(0x401cd3u);dispatch(0x8594a8u);
}
L401cd3: { // 5f  pop edi
put(7,pop(),4,0);
}
L401cd4: { // 5e  pop esi
put(6,pop(),4,0);
}
L401cd5: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00406d98_spawn_centered_viewport_tween_mc_406d98
void RecoveredBattle::fn_406d98(){
goto L406d98;
L406d98: { // 55  push ebp
push(get(5,4,0));
}
L406d99: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L406d9b: { // 83ec10  sub esp, 0x10
put(4,sub(get(4,4,0),0x10u,4,false),4,0);
}
L406d9e: { // a14c504a00  mov eax, dword ptr [0x4a504c]
put(0,read((0x4a504cu),4),4,0);
}
L406da3: { // 56  push esi
push(get(6,4,0));
}
L406da4: { // 8b750c  mov esi, dword ptr [ebp + 0xc]
put(6,read((0xcu+r[5]),4),4,0);
}
L406da7: { // 57  push edi
push(get(7,4,0));
}
L406da8: { // 2bc6  sub eax, esi
put(0,sub(get(0,4,0),get(6,4,0),4,false),4,0);
}
L406daa: { // 8b7d10  mov edi, dword ptr [ebp + 0x10]
put(7,read((0x10u+r[5]),4),4,0);
}
L406dad: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L406dae: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L406db0: { // ff7518  push dword ptr [ebp + 0x18]
push(read((0x18u+r[5]),4));
}
L406db3: { // 8bc8  mov ecx, eax
put(1,get(0,4,0),4,0);
}
L406db5: { // a150504a00  mov eax, dword ptr [0x4a5050]
put(0,read((0x4a5050u),4),4,0);
}
L406dba: { // 2bc7  sub eax, edi
put(0,sub(get(0,4,0),get(7,4,0),4,false),4,0);
}
L406dbc: { // ff7514  push dword ptr [ebp + 0x14]
push(read((0x14u+r[5]),4));
}
L406dbf: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L406dc0: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L406dc2: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L406dc4: { // 8945f4  mov dword ptr [ebp - 0xc], eax
write((0xfffffff4u+r[5]),get(0,4,0),4);
}
L406dc7: { // 03c7  add eax, edi
put(0,add(get(0,4,0),get(7,4,0),4,false),4,0);
}
L406dc9: { // 8945fc  mov dword ptr [ebp - 4], eax
write((0xfffffffcu+r[5]),get(0,4,0),4);
}
L406dcc: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L406dcf: { // d1f9  sar ecx, 1
put(1,shift(get(1,4,0),0x1u,4,2),4,0);
}
L406dd1: { // 50  push eax
push(get(0,4,0));
}
L406dd2: { // 894df0  mov dword ptr [ebp - 0x10], ecx
write((0xfffffff0u+r[5]),get(1,4,0),4);
}
L406dd5: { // ff7508  push dword ptr [ebp + 8]
push(read((0x8u+r[5]),4));
}
L406dd8: { // 03ce  add ecx, esi
put(1,add(get(1,4,0),get(6,4,0),4,false),4,0);
}
L406dda: { // 894df8  mov dword ptr [ebp - 8], ecx
write((0xfffffff8u+r[5]),get(1,4,0),4);
}
L406ddd: { // e851ffffff  call 0x406d33
push(0x406de2u);dispatch(0x406d33u);
}
L406de2: { // 5f  pop edi
put(7,pop(),4,0);
}
L406de3: { // 5e  pop esi
put(6,pop(),4,0);
}
L406de4: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L406de5: { // c21400  ret 0x14
pop();r[4]+=0x14u;return;
}
}
// 00406d33_spawn_viewport_tween_mc_406d33
void RecoveredBattle::fn_406d33(){
goto L406d33;
L406d33: { // 56  push esi
push(get(6,4,0));
}
L406d34: { // 57  push edi
push(get(7,4,0));
}
L406d35: { // 6a00  push 0
push(0x0u);
}
L406d37: { // 6a00  push 0
push(0x0u);
}
L406d39: { // 68e86d4000  push 0x406de8
push(0x406de8u);
}
L406d3e: { // ff35f84c6d00  push dword ptr [0x6d4cf8]
push(read((0x6d4cf8u),4));
}
L406d44: { // e831baffff  call 0x40277a
push(0x406d49u);dispatch(0x40277au);
}
L406d49: { // 50  push eax
push(get(0,4,0));
}
L406d4a: { // e872b9ffff  call 0x4026c1
push(0x406d4fu);dispatch(0x4026c1u);
}
L406d4f: { // 6a2c  push 0x2c
push(0x2cu);
}
L406d51: { // 6a01  push 1
push(0x1u);
}
L406d53: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L406d55: { // e8f7a3ffff  call 0x401151
push(0x406d5au);dispatch(0x401151u);
}
L406d5a: { // 8986a4010000  mov dword ptr [esi + 0x1a4], eax
write((0x1a4u+r[6]),get(0,4,0),4);
}
L406d60: { // be90666d00  mov esi, 0x6d6690
put(6,0x6d6690u,4,0);
}
L406d65: { // 8bf8  mov edi, eax
put(7,get(0,4,0),4,0);
}
L406d67: { // 8b4c240c  mov ecx, dword ptr [esp + 0xc]
put(1,read((0xcu+r[4]),4),4,0);
}
L406d6b: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L406d6c: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L406d6d: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L406d6e: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L406d6f: { // 8b742410  mov esi, dword ptr [esp + 0x10]
put(6,read((0x10u+r[4]),4),4,0);
}
L406d73: { // 8d7810  lea edi, [eax + 0x10]
put(7,(0x10u+r[0]),4,0);
}
L406d76: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L406d77: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L406d78: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L406d79: { // 83f901  cmp ecx, 1
sub(get(1,4,0),0x1u,4);
}
L406d7c: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L406d7d: { // 7d03  jge 0x406d82
if(condition(3))goto L406d82;
}
L406d7f: { // 6a01  push 1
push(0x1u);
}
L406d81: { // 59  pop ecx
put(1,pop(),4,0);
}
L406d82: { // 894820  mov dword ptr [eax + 0x20], ecx
write((0x20u+r[0]),get(1,4,0),4);
}
L406d85: { // 8b4c2414  mov ecx, dword ptr [esp + 0x14]
put(1,read((0x14u+r[4]),4),4,0);
}
L406d89: { // 894824  mov dword ptr [eax + 0x24], ecx
write((0x24u+r[0]),get(1,4,0),4);
}
L406d8c: { // 8b4c2418  mov ecx, dword ptr [esp + 0x18]
put(1,read((0x18u+r[4]),4),4,0);
}
L406d90: { // 5f  pop edi
put(7,pop(),4,0);
}
L406d91: { // 894828  mov dword ptr [eax + 0x28], ecx
write((0x28u+r[0]),get(1,4,0),4);
}
L406d94: { // 5e  pop esi
put(6,pop(),4,0);
}
L406d95: { // c21000  ret 0x10
pop();r[4]+=0x10u;return;
}
}
} // namespace fsb::core
