// Generated by tools/translate_battle.py; edit the generator, not this file.
// Original EXE SHA256: 710881d024ab1fcf738b342c248631363c9de3a51b32a7e3d61781b791eff454
#include "fsb_core/recovered_battle.hpp"
#include <cstring>
#include <cmath>
namespace fsb::core {
// 00454f71_release_active_sparkle_objects_mc_454f71
void RecoveredBattle::fn_454f71(){
goto L454f71;
L454f71: { // 57  push edi
push(get(7,4,0));
}
L454f72: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L454f74: { // 393d58b57a00  cmp dword ptr [0x7ab558], edi
sub(read((0x7ab558u),4),get(7,4,0),4);
}
L454f7a: { // 7e1f  jle 0x454f9b
if(condition(4))goto L454f9b;
}
L454f7c: { // 56  push esi
push(get(6,4,0));
}
L454f7d: { // bedcb27a00  mov esi, 0x7ab2dc
put(6,0x7ab2dcu,4,0);
}
L454f82: { // 8b06  mov eax, dword ptr [esi]
put(0,read((0x0u+r[6]),4),4,0);
}
L454f84: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L454f86: { // 7406  je 0x454f8e
if(condition(0))goto L454f8e;
}
L454f88: { // 50  push eax
push(get(0,4,0));
}
L454f89: { // e88f890000  call 0x45d91d
push(0x454f8eu);dispatch(0x45d91du);
}
L454f8e: { // 47  inc edi
put(7,inc(get(7,4,0),4,1),4,0);
}
L454f8f: { // 83c608  add esi, 8
put(6,add(get(6,4,0),0x8u,4,false),4,0);
}
L454f92: { // 3b3d58b57a00  cmp edi, dword ptr [0x7ab558]
sub(get(7,4,0),read((0x7ab558u),4),4);
}
L454f98: { // 7ce8  jl 0x454f82
if(condition(2))goto L454f82;
}
L454f9a: { // 5e  pop esi
put(6,pop(),4,0);
}
L454f9b: { // 5f  pop edi
put(7,pop(),4,0);
}
L454f9c: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00454f9d_spawn_map_sparkle_objects_for_map_mc_454f9d
void RecoveredBattle::fn_454f9d(){
goto L454f9d;
L454f9d: { // 55  push ebp
push(get(5,4,0));
}
L454f9e: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L454fa0: { // 51  push ecx
push(get(1,4,0));
}
L454fa1: { // 51  push ecx
push(get(1,4,0));
}
L454fa2: { // 0fbf0538d45c00  movsx eax, word ptr [0x5cd438]
put(0,((read((0x5cd438u),2)^0x8000u)-0x8000u),4,0);
}
L454fa9: { // 8365fc00  and dword ptr [ebp - 4], 0
write((0xfffffffcu+r[5]),logic(read((0xfffffffcu+r[5]),4)&0x0u,4),4);
}
L454fad: { // 8365f800  and dword ptr [ebp - 8], 0
write((0xfffffff8u+r[5]),logic(read((0xfffffff8u+r[5]),4)&0x0u,4),4);
}
L454fb1: { // 3b4508  cmp eax, dword ptr [ebp + 8]
sub(get(0,4,0),read((0x8u+r[5]),4),4);
}
L454fb4: { // 0f8fd3000000  jg 0x45508d
if(condition(5))goto L45508d;
}
L454fba: { // 57  push edi
push(get(7,4,0));
}
L454fbb: { // 56  push esi
push(get(6,4,0));
}
L454fbc: { // 53  push ebx
push(get(3,4,0));
}
L454fbd: { // b838d45c00  mov eax, 0x5cd438
put(0,0x5cd438u,4,0);
}
L454fc2: { // bbdcb27a00  mov ebx, 0x7ab2dc
put(3,0x7ab2dcu,4,0);
}
L454fc7: { // be3bd45c00  mov esi, 0x5cd43b
put(6,0x5cd43bu,4,0);
}
L454fcc: { // 0fbf00  movsx eax, word ptr [eax]
put(0,((read((0x0u+r[0]),2)^0x8000u)-0x8000u),4,0);
}
L454fcf: { // 3b4508  cmp eax, dword ptr [ebp + 8]
sub(get(0,4,0),read((0x8u+r[5]),4),4);
}
L454fd2: { // 0f859c000000  jne 0x455074
if(condition(1))goto L455074;
}
L454fd8: { // 68a7744800  push 0x4874a7
push(0x4874a7u);
}
L454fdd: { // e8ba880000  call 0x45d89c
push(0x454fe2u);dispatch(0x45d89cu);
}
L454fe2: { // 8b4dfc  mov ecx, dword ptr [ebp - 4]
put(1,read((0xfffffffcu+r[5]),4),4,0);
}
L454fe5: { // 6a01  push 1
push(0x1u);
}
L454fe7: { // 8bf8  mov edi, eax
put(7,get(0,4,0),4,0);
}
L454fe9: { // 83e11f  and ecx, 0x1f
put(1,logic(get(1,4,0)&0x1fu,4),4,0);
}
L454fec: { // 58  pop eax
put(0,pop(),4,0);
}
L454fed: { // 834f0440  or dword ptr [edi + 4], 0x40
write((0x4u+r[7]),logic(read((0x4u+r[7]),4)|0x40u,4),4);
}
L454ff1: { // c78730010000d0000000  mov dword ptr [edi + 0x130], 0xd0
write((0x130u+r[7]),0xd0u,4);
}
L454ffb: { // d3e0  shl eax, cl
put(0,shift(get(0,4,0),get(1,1,0),4,0),4,0);
}
L454ffd: { // 8b4dfc  mov ecx, dword ptr [ebp - 4]
put(1,read((0xfffffffcu+r[5]),4),4,0);
}
L455000: { // c78734010000cb000000  mov dword ptr [edi + 0x134], 0xcb
write((0x134u+r[7]),0xcbu,4);
}
L45500a: { // c1f905  sar ecx, 5
put(1,shift(get(1,4,0),0x5u,4,2),4,0);
}
L45500d: { // 85048dd8b47a00  test dword ptr [ecx*4 + 0x7ab4d8], eax
logic(read((0x7ab4d8u+r[1]*4u),4)&get(0,4,0),4);
}
L455014: { // 0fbe4606  movsx eax, byte ptr [esi + 6]
put(0,((read((0x6u+r[6]),1)^0x80u)-0x80u),4,0);
}
L455018: { // 7406  je 0x455020
if(condition(0))goto L455020;
}
L45501a: { // 8d440001  lea eax, [eax + eax + 1]
put(0,(0x1u+r[0]+r[0]*1u),4,0);
}
L45501e: { // eb02  jmp 0x455022
goto L455022;
}
L455020: { // d1e0  shl eax, 1
put(0,shift(get(0,4,0),0x1u,4,0),4,0);
}
L455022: { // 898738010000  mov dword ptr [edi + 0x138], eax
write((0x138u+r[7]),get(0,4,0),4);
}
L455028: { // 0fbe4601  movsx eax, byte ptr [esi + 1]
put(0,((read((0x1u+r[6]),1)^0x80u)-0x80u),4,0);
}
L45502c: { // 50  push eax
push(get(0,4,0));
}
L45502d: { // 0fbe06  movsx eax, byte ptr [esi]
put(0,((read((0x0u+r[6]),1)^0x80u)-0x80u),4,0);
}
L455030: { // 50  push eax
push(get(0,4,0));
}
L455031: { // 0fbe46ff  movsx eax, byte ptr [esi - 1]
put(0,((read((0xffffffffu+r[6]),1)^0x80u)-0x80u),4,0);
}
L455035: { // 50  push eax
push(get(0,4,0));
}
L455036: { // 57  push edi
push(get(7,4,0));
}
L455037: { // e838870000  call 0x45d774
push(0x45503cu);dispatch(0x45d774u);
}
L45503c: { // 0fbe06  movsx eax, byte ptr [esi]
put(0,((read((0x0u+r[6]),1)^0x80u)-0x80u),4,0);
}
L45503f: { // 8b0dc4607700  mov ecx, dword ptr [0x7760c4]
put(1,read((0x7760c4u),4),4,0);
}
L455045: { // 0fafc8  imul ecx, eax
put(1,multiply(get(1,4,0),get(0,4,0),4),4,0);
}
L455048: { // 0fbe4601  movsx eax, byte ptr [esi + 1]
put(0,((read((0x1u+r[6]),1)^0x80u)-0x80u),4,0);
}
L45504c: { // c1e00c  shl eax, 0xc
put(0,shift(get(0,4,0),0xcu,4,0),4,0);
}
L45504f: { // 03c8  add ecx, eax
put(1,add(get(1,4,0),get(0,4,0),4,false),4,0);
}
L455051: { // 0fbe46ff  movsx eax, byte ptr [esi - 1]
put(0,((read((0xffffffffu+r[6]),1)^0x80u)-0x80u),4,0);
}
L455055: { // 03c8  add ecx, eax
put(1,add(get(1,4,0),get(0,4,0),4,false),4,0);
}
L455057: { // 800c8da1bc7c0002  or byte ptr [ecx*4 + 0x7cbca1], 2
write((0x7cbca1u+r[1]*4u),logic(read((0x7cbca1u+r[1]*4u),1)|0x2u,1),1);
}
L45505f: { // ff45f8  inc dword ptr [ebp - 8]
write((0xfffffff8u+r[5]),inc(read((0xfffffff8u+r[5]),4),4,1),4);
}
L455062: { // 8d048da0bc7c00  lea eax, [ecx*4 + 0x7cbca0]
put(0,(0x7cbca0u+r[1]*4u),4,0);
}
L455069: { // 8b45fc  mov eax, dword ptr [ebp - 4]
put(0,read((0xfffffffcu+r[5]),4),4,0);
}
L45506c: { // 8943fc  mov dword ptr [ebx - 4], eax
write((0xfffffffcu+r[3]),get(0,4,0),4);
}
L45506f: { // 893b  mov dword ptr [ebx], edi
write((0x0u+r[3]),get(7,4,0),4);
}
L455071: { // 83c308  add ebx, 8
put(3,add(get(3,4,0),0x8u,4,false),4,0);
}
L455074: { // 83c60a  add esi, 0xa
put(6,add(get(6,4,0),0xau,4,false),4,0);
}
L455077: { // ff45fc  inc dword ptr [ebp - 4]
write((0xfffffffcu+r[5]),inc(read((0xfffffffcu+r[5]),4),4,1),4);
}
L45507a: { // 0fbf4efd  movsx ecx, word ptr [esi - 3]
put(1,((read((0xfffffffdu+r[6]),2)^0x8000u)-0x8000u),4,0);
}
L45507e: { // 3b4d08  cmp ecx, dword ptr [ebp + 8]
sub(get(1,4,0),read((0x8u+r[5]),4),4);
}
L455081: { // 8d46fd  lea eax, [esi - 3]
put(0,(0xfffffffdu+r[6]),4,0);
}
L455084: { // 0f8e42ffffff  jle 0x454fcc
if(condition(4))goto L454fcc;
}
L45508a: { // 5b  pop ebx
put(3,pop(),4,0);
}
L45508b: { // 5e  pop esi
put(6,pop(),4,0);
}
L45508c: { // 5f  pop edi
put(7,pop(),4,0);
}
L45508d: { // 8b45f8  mov eax, dword ptr [ebp - 8]
put(0,read((0xfffffff8u+r[5]),4),4,0);
}
L455090: { // a358b57a00  mov dword ptr [0x7ab558], eax
write((0x7ab558u),get(0,4,0),4);
}
L455095: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L455096: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00455099_collect_map_sparkle_item_for_object_mc_455099
void RecoveredBattle::fn_455099(){
goto L455099;
L455099: { // 55  push ebp
push(get(5,4,0));
}
L45509a: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L45509c: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L45509f: { // 8b1558b57a00  mov edx, dword ptr [0x7ab558]
put(2,read((0x7ab558u),4),4,0);
}
L4550a5: { // 69c0ac010000  imul eax, eax, 0x1ac
put(0,multiply(get(0,4,0),0x1acu,4),4,0);
}
L4550ab: { // 53  push ebx
push(get(3,4,0));
}
L4550ac: { // 8b5d0c  mov ebx, dword ptr [ebp + 0xc]
put(3,read((0xcu+r[5]),4),4,0);
}
L4550af: { // 56  push esi
push(get(6,4,0));
}
L4550b0: { // 57  push edi
push(get(7,4,0));
}
L4550b1: { // 05d8738000  add eax, 0x8073d8
put(0,add(get(0,4,0),0x8073d8u,4,false),4,0);
}
L4550b6: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L4550b8: { // 85d2  test edx, edx
logic(get(2,4,0)&get(2,4,0),4);
}
L4550ba: { // 7e74  jle 0x455130
if(condition(4))goto L455130;
}
L4550bc: { // b9dcb27a00  mov ecx, 0x7ab2dc
put(1,0x7ab2dcu,4,0);
}
L4550c1: { // 3b01  cmp eax, dword ptr [ecx]
sub(get(0,4,0),read((0x0u+r[1]),4),4);
}
L4550c3: { // 740a  je 0x4550cf
if(condition(0))goto L4550cf;
}
L4550c5: { // 47  inc edi
put(7,inc(get(7,4,0),4,1),4,0);
}
L4550c6: { // 83c108  add ecx, 8
put(1,add(get(1,4,0),0x8u,4,false),4,0);
}
L4550c9: { // 3bfa  cmp edi, edx
sub(get(7,4,0),get(2,4,0),4);
}
L4550cb: { // 7cf4  jl 0x4550c1
if(condition(2))goto L4550c1;
}
L4550cd: { // eb61  jmp 0x455130
goto L455130;
}
L4550cf: { // 8b04fdd8b27a00  mov eax, dword ptr [edi*8 + 0x7ab2d8]
put(0,read((0x7ab2d8u+r[7]*8u),4),4,0);
}
L4550d6: { // 8b34fddcb27a00  mov esi, dword ptr [edi*8 + 0x7ab2dc]
put(6,read((0x7ab2dcu+r[7]*8u),4),4,0);
}
L4550dd: { // 6a01  push 1
push(0x1u);
}
L4550df: { // 8d1480  lea edx, [eax + eax*4]
put(2,(0x0u+r[0]+r[0]*4u),4,0);
}
L4550e2: { // d1e2  shl edx, 1
put(2,shift(get(2,4,0),0x1u,4,0),4,0);
}
L4550e4: { // 0fbe8a41d45c00  movsx ecx, byte ptr [edx + 0x5cd441]
put(1,((read((0x5cd441u+r[2]),1)^0x80u)-0x80u),4,0);
}
L4550eb: { // 8d4c0901  lea ecx, [ecx + ecx + 1]
put(1,(0x1u+r[1]+r[1]*1u),4,0);
}
L4550ef: { // 898e38010000  mov dword ptr [esi + 0x138], ecx
write((0x138u+r[6]),get(1,4,0),4);
}
L4550f5: { // 8bc8  mov ecx, eax
put(1,get(0,4,0),4,0);
}
L4550f7: { // 83e11f  and ecx, 0x1f
put(1,logic(get(1,4,0)&0x1fu,4),4,0);
}
L4550fa: { // 5e  pop esi
put(6,pop(),4,0);
}
L4550fb: { // c1f805  sar eax, 5
put(0,shift(get(0,4,0),0x5u,4,2),4,0);
}
L4550fe: { // d3e6  shl esi, cl
put(6,shift(get(6,4,0),get(1,1,0),4,0),4,0);
}
L455100: { // 8d0c85d8b47a00  lea ecx, [eax*4 + 0x7ab4d8]
put(1,(0x7ab4d8u+r[0]*4u),4,0);
}
L455107: { // 8b0485d8b47a00  mov eax, dword ptr [eax*4 + 0x7ab4d8]
put(0,read((0x7ab4d8u+r[0]*4u),4),4,0);
}
L45510e: { // 85c6  test esi, eax
logic(get(6,4,0)&get(0,4,0),4);
}
L455110: { // 7405  je 0x455117
if(condition(0))goto L455117;
}
L455112: { // 832300  and dword ptr [ebx], 0
write((0x0u+r[3]),logic(read((0x0u+r[3]),4)&0x0u,4),4);
}
L455115: { // eb19  jmp 0x455130
goto L455130;
}
L455117: { // 0bc6  or eax, esi
put(0,logic(get(0,4,0)|get(6,4,0),4),4,0);
}
L455119: { // 8901  mov dword ptr [ecx], eax
write((0x0u+r[1]),get(0,4,0),4);
}
L45511b: { // 8b4d10  mov ecx, dword ptr [ebp + 0x10]
put(1,read((0x10u+r[5]),4),4,0);
}
L45511e: { // 0fbf823ed45c00  movsx eax, word ptr [edx + 0x5cd43e]
put(0,((read((0x5cd43eu+r[2]),2)^0x8000u)-0x8000u),4,0);
}
L455125: { // 8903  mov dword ptr [ebx], eax
write((0x0u+r[3]),get(0,4,0),4);
}
L455127: { // 0fbe8240d45c00  movsx eax, byte ptr [edx + 0x5cd440]
put(0,((read((0x5cd440u+r[2]),1)^0x80u)-0x80u),4,0);
}
L45512e: { // 8901  mov dword ptr [ecx], eax
write((0x0u+r[1]),get(0,4,0),4);
}
L455130: { // 3b3d58b57a00  cmp edi, dword ptr [0x7ab558]
sub(get(7,4,0),read((0x7ab558u),4),4);
}
L455136: { // 750c  jne 0x455144
if(condition(1))goto L455144;
}
L455138: { // ff7510  push dword ptr [ebp + 0x10]
push(read((0x10u+r[5]),4));
}
L45513b: { // 53  push ebx
push(get(3,4,0));
}
L45513c: { // ff7508  push dword ptr [ebp + 8]
push(read((0x8u+r[5]),4));
}
L45513f: { // e81f020000  call 0x455363
push(0x455144u);dispatch(0x455363u);
}
L455144: { // 5f  pop edi
put(7,pop(),4,0);
}
L455145: { // 5e  pop esi
put(6,pop(),4,0);
}
L455146: { // 5b  pop ebx
put(3,pop(),4,0);
}
L455147: { // 5d  pop ebp
put(5,pop(),4,0);
}
L455148: { // c20c00  ret 0xc
pop();r[4]+=0xcu;return;
}
}
// 004552a3_spawn_map_sparkle_object_mc_4552a3
void RecoveredBattle::fn_4552a3(){
goto L4552a3;
L4552a3: { // 55  push ebp
push(get(5,4,0));
}
L4552a4: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L4552a6: { // 51  push ecx
push(get(1,4,0));
}
L4552a7: { // 8365fc00  and dword ptr [ebp - 4], 0
write((0xfffffffcu+r[5]),logic(read((0xfffffffcu+r[5]),4)&0x0u,4),4);
}
L4552ab: { // 53  push ebx
push(get(3,4,0));
}
L4552ac: { // 56  push esi
push(get(6,4,0));
}
L4552ad: { // 57  push edi
push(get(7,4,0));
}
L4552ae: { // b860b57a00  mov eax, 0x7ab560
put(0,0x7ab560u,4,0);
}
L4552b3: { // 833800  cmp dword ptr [eax], 0
sub(read((0x0u+r[0]),4),0x0u,4);
}
L4552b6: { // 740d  je 0x4552c5
if(condition(0))goto L4552c5;
}
L4552b8: { // ff45fc  inc dword ptr [ebp - 4]
write((0xfffffffcu+r[5]),inc(read((0xfffffffcu+r[5]),4),4,1),4);
}
L4552bb: { // 83c004  add eax, 4
put(0,add(get(0,4,0),0x4u,4,false),4,0);
}
L4552be: { // 3da0b57a00  cmp eax, 0x7ab5a0
sub(get(0,4,0),0x7ab5a0u,4);
}
L4552c3: { // 7cee  jl 0x4552b3
if(condition(2))goto L4552b3;
}
L4552c5: { // 837dfc10  cmp dword ptr [ebp - 4], 0x10
sub(read((0xfffffffcu+r[5]),4),0x10u,4);
}
L4552c9: { // 0f848d000000  je 0x45535c
if(condition(0))goto L45535c;
}
L4552cf: { // 6838524500  push 0x455238
push(0x455238u);
}
L4552d4: { // e8c3850000  call 0x45d89c
push(0x4552d9u);dispatch(0x45d89cu);
}
L4552d9: { // 8b7d10  mov edi, dword ptr [ebp + 0x10]
put(7,read((0x10u+r[5]),4),4,0);
}
L4552dc: { // 8b5d08  mov ebx, dword ptr [ebp + 8]
put(3,read((0x8u+r[5]),4),4,0);
}
L4552df: { // 57  push edi
push(get(7,4,0));
}
L4552e0: { // 8bf0  mov esi, eax
put(6,get(0,4,0),4,0);
}
L4552e2: { // ff750c  push dword ptr [ebp + 0xc]
push(read((0xcu+r[5]),4));
}
L4552e5: { // 8b4514  mov eax, dword ptr [ebp + 0x14]
put(0,read((0x14u+r[5]),4),4,0);
}
L4552e8: { // 814e0440000400  or dword ptr [esi + 4], 0x40040
write((0x4u+r[6]),logic(read((0x4u+r[6]),4)|0x40040u,4),4);
}
L4552ef: { // 03c0  add eax, eax
put(0,add(get(0,4,0),get(0,4,0),4,false),4,0);
}
L4552f1: { // 53  push ebx
push(get(3,4,0));
}
L4552f2: { // 56  push esi
push(get(6,4,0));
}
L4552f3: { // c78630010000d0000000  mov dword ptr [esi + 0x130], 0xd0
write((0x130u+r[6]),0xd0u,4);
}
L4552fd: { // c78634010000cb000000  mov dword ptr [esi + 0x134], 0xcb
write((0x134u+r[6]),0xcbu,4);
}
L455307: { // 898638010000  mov dword ptr [esi + 0x138], eax
write((0x138u+r[6]),get(0,4,0),4);
}
L45530d: { // e862840000  call 0x45d774
push(0x455312u);dispatch(0x45d774u);
}
L455312: { // 8b4514  mov eax, dword ptr [ebp + 0x14]
put(0,read((0x14u+r[5]),4),4,0);
}
L455315: { // 8b4dfc  mov ecx, dword ptr [ebp - 4]
put(1,read((0xfffffffcu+r[5]),4),4,0);
}
L455318: { // 898690010000  mov dword ptr [esi + 0x190], eax
write((0x190u+r[6]),get(0,4,0),4);
}
L45531e: { // 8b4518  mov eax, dword ptr [ebp + 0x18]
put(0,read((0x18u+r[5]),4),4,0);
}
L455321: { // 898694010000  mov dword ptr [esi + 0x194], eax
write((0x194u+r[6]),get(0,4,0),4);
}
L455327: { // 8b451c  mov eax, dword ptr [ebp + 0x1c]
put(0,read((0x1cu+r[5]),4),4,0);
}
L45532a: { // 898698010000  mov dword ptr [esi + 0x198], eax
write((0x198u+r[6]),get(0,4,0),4);
}
L455330: { // 898e9c010000  mov dword ptr [esi + 0x19c], ecx
write((0x19cu+r[6]),get(1,4,0),4);
}
L455336: { // a1c4607700  mov eax, dword ptr [0x7760c4]
put(0,read((0x7760c4u),4),4,0);
}
L45533b: { // 89348d60b57a00  mov dword ptr [ecx*4 + 0x7ab560], esi
write((0x7ab560u+r[1]*4u),get(6,4,0),4);
}
L455342: { // 0faf450c  imul eax, dword ptr [ebp + 0xc]
put(0,multiply(get(0,4,0),read((0xcu+r[5]),4),4),4,0);
}
L455346: { // c1e70c  shl edi, 0xc
put(7,shift(get(7,4,0),0xcu,4,0),4,0);
}
L455349: { // 03d8  add ebx, eax
put(3,add(get(3,4,0),get(0,4,0),4,false),4,0);
}
L45534b: { // 03fb  add edi, ebx
put(7,add(get(7,4,0),get(3,4,0),4,false),4,0);
}
L45534d: { // 800cbda1bc7c0002  or byte ptr [edi*4 + 0x7cbca1], 2
write((0x7cbca1u+r[7]*4u),logic(read((0x7cbca1u+r[7]*4u),1)|0x2u,1),1);
}
L455355: { // 8d04bda0bc7c00  lea eax, [edi*4 + 0x7cbca0]
put(0,(0x7cbca0u+r[7]*4u),4,0);
}
L45535c: { // 5f  pop edi
put(7,pop(),4,0);
}
L45535d: { // 5e  pop esi
put(6,pop(),4,0);
}
L45535e: { // 5b  pop ebx
put(3,pop(),4,0);
}
L45535f: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L455360: { // c21800  ret 0x18
pop();r[4]+=0x18u;return;
}
}
// 00455363_clear_object_sparkle_state_mc_455363
void RecoveredBattle::fn_455363(){
goto L455363;
L455363: { // 55  push ebp
push(get(5,4,0));
}
L455364: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L455366: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L455369: { // 69c0ac010000  imul eax, eax, 0x1ac
put(0,multiply(get(0,4,0),0x1acu,4),4,0);
}
L45536f: { // 05d8738000  add eax, 0x8073d8
put(0,add(get(0,4,0),0x8073d8u,4,false),4,0);
}
L455374: { // f6400604  test byte ptr [eax + 6], 4
logic(read((0x6u+r[0]),1)&0x4u,1);
}
L455378: { // 742c  je 0x4553a6
if(condition(0))goto L4553a6;
}
L45537a: { // 8b8890010000  mov ecx, dword ptr [eax + 0x190]
put(1,read((0x190u+r[0]),4),4,0);
}
L455380: { // 8b550c  mov edx, dword ptr [ebp + 0xc]
put(2,read((0xcu+r[5]),4),4,0);
}
L455383: { // 8d4c0901  lea ecx, [ecx + ecx + 1]
put(1,(0x1u+r[1]+r[1]*1u),4,0);
}
L455387: { // 898838010000  mov dword ptr [eax + 0x138], ecx
write((0x138u+r[0]),get(1,4,0),4);
}
L45538d: { // 8b8894010000  mov ecx, dword ptr [eax + 0x194]
put(1,read((0x194u+r[0]),4),4,0);
}
L455393: { // 890a  mov dword ptr [edx], ecx
write((0x0u+r[2]),get(1,4,0),4);
}
L455395: { // 8b5510  mov edx, dword ptr [ebp + 0x10]
put(2,read((0x10u+r[5]),4),4,0);
}
L455398: { // 8b8898010000  mov ecx, dword ptr [eax + 0x198]
put(1,read((0x198u+r[0]),4),4,0);
}
L45539e: { // 890a  mov dword ptr [edx], ecx
write((0x0u+r[2]),get(1,4,0),4);
}
L4553a0: { // 806006fb  and byte ptr [eax + 6], 0xfb
write((0x6u+r[0]),logic(read((0x6u+r[0]),1)&0xfbu,1),1);
}
L4553a4: { // eb0c  jmp 0x4553b2
goto L4553b2;
}
L4553a6: { // 8b450c  mov eax, dword ptr [ebp + 0xc]
put(0,read((0xcu+r[5]),4),4,0);
}
L4553a9: { // 832000  and dword ptr [eax], 0
write((0x0u+r[0]),logic(read((0x0u+r[0]),4)&0x0u,4),4);
}
L4553ac: { // 8b4510  mov eax, dword ptr [ebp + 0x10]
put(0,read((0x10u+r[5]),4),4,0);
}
L4553af: { // 832000  and dword ptr [eax], 0
write((0x0u+r[0]),logic(read((0x0u+r[0]),4)&0x0u,4),4);
}
L4553b2: { // 5d  pop ebp
put(5,pop(),4,0);
}
L4553b3: { // c20c00  ret 0xc
pop();r[4]+=0xcu;return;
}
}
// 0045584f_clear_or_mask_occupancy_grid_mc_45584f
void RecoveredBattle::fn_45584f(){
goto L45584f;
L45584f: { // 53  push ebx
push(get(3,4,0));
}
L455850: { // 56  push esi
push(get(6,4,0));
}
L455851: { // 8b74240c  mov esi, dword ptr [esp + 0xc]
put(6,read((0xcu+r[4]),4),4,0);
}
L455855: { // 57  push edi
push(get(7,4,0));
}
L455856: { // 85f6  test esi, esi
logic(get(6,4,0)&get(6,4,0),4);
}
L455858: { // 7421  je 0x45587b
if(condition(0))goto L45587b;
}
L45585a: { // 8b0dc00d8000  mov ecx, dword ptr [0x800dc0]
put(1,read((0x800dc0u),4),4,0);
}
L455860: { // 85c9  test ecx, ecx
logic(get(1,4,0)&get(1,4,0),4);
}
L455862: { // 7e55  jle 0x4558b9
if(condition(4))goto L4558b9;
}
L455864: { // b8a0bc7a00  mov eax, 0x7abca0
put(0,0x7abca0u,4,0);
}
L455869: { // ba00100000  mov edx, 0x1000
put(2,0x1000u,4,0);
}
L45586e: { // 2130  and dword ptr [eax], esi
write((0x0u+r[0]),logic(read((0x0u+r[0]),4)&get(6,4,0),4),4);
}
L455870: { // 83c004  add eax, 4
put(0,add(get(0,4,0),0x4u,4,false),4,0);
}
L455873: { // 4a  dec edx
put(2,inc(get(2,4,0),4,-1),4,0);
}
L455874: { // 75f8  jne 0x45586e
if(condition(1))goto L45586e;
}
L455876: { // 49  dec ecx
put(1,inc(get(1,4,0),4,-1),4,0);
}
L455877: { // 75f0  jne 0x455869
if(condition(1))goto L455869;
}
L455879: { // eb3e  jmp 0x4558b9
goto L4558b9;
}
L45587b: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L45587d: { // 393dc00d8000  cmp dword ptr [0x800dc0], edi
sub(read((0x800dc0u),4),get(7,4,0),4);
}
L455883: { // 7e34  jle 0x4558b9
if(condition(4))goto L4558b9;
}
L455885: { // bba0bc7a00  mov ebx, 0x7abca0
put(3,0x7abca0u,4,0);
}
L45588a: { // be240d7e00  mov esi, 0x7e0d24
put(6,0x7e0d24u,4,0);
}
L45588f: { // 8b46fc  mov eax, dword ptr [esi - 4]
put(0,read((0xfffffffcu+r[6]),4),4,0);
}
L455892: { // 0faf06  imul eax, dword ptr [esi]
put(0,multiply(get(0,4,0),read((0x0u+r[6]),4),4),4,0);
}
L455895: { // c1e002  shl eax, 2
put(0,shift(get(0,4,0),0x2u,4,0),4,0);
}
L455898: { // 50  push eax
push(get(0,4,0));
}
L455899: { // 6a00  push 0
push(0x0u);
}
L45589b: { // 53  push ebx
push(get(3,4,0));
}
L45589c: { // e8cf240400  call 0x497d70
push(0x4558a1u);dispatch(0x497d70u);
}
L4558a1: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L4558a4: { // 47  inc edi
put(7,inc(get(7,4,0),4,1),4,0);
}
L4558a5: { // 81c628800000  add esi, 0x8028
put(6,add(get(6,4,0),0x8028u,4,false),4,0);
}
L4558ab: { // 81c300400000  add ebx, 0x4000
put(3,add(get(3,4,0),0x4000u,4,false),4,0);
}
L4558b1: { // 3b3dc00d8000  cmp edi, dword ptr [0x800dc0]
sub(get(7,4,0),read((0x800dc0u),4),4);
}
L4558b7: { // 7cd6  jl 0x45588f
if(condition(2))goto L45588f;
}
L4558b9: { // 5f  pop edi
put(7,pop(),4,0);
}
L4558ba: { // 5e  pop esi
put(6,pop(),4,0);
}
L4558bb: { // 5b  pop ebx
put(3,pop(),4,0);
}
L4558bc: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 0045733a_e2_current_map_object_spawn_45733a
void RecoveredBattle::fn_45733a(){
goto L45733a;
L45733a: { // 55  push ebp
push(get(5,4,0));
}
L45733b: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L45733d: { // 83ec10  sub esp, 0x10
put(4,sub(get(4,4,0),0x10u,4,false),4,0);
}
L457340: { // 8b4d0c  mov ecx, dword ptr [ebp + 0xc]
put(1,read((0xcu+r[5]),4),4,0);
}
L457343: { // 53  push ebx
push(get(3,4,0));
}
L457344: { // 0faf0dc4607700  imul ecx, dword ptr [0x7760c4]
put(1,multiply(get(1,4,0),read((0x7760c4u),4),4),4,0);
}
L45734b: { // 034d08  add ecx, dword ptr [ebp + 8]
put(1,add(get(1,4,0),read((0x8u+r[5]),4),4,false),4,0);
}
L45734e: { // 33db  xor ebx, ebx
put(3,logic(get(3,4,0)^get(3,4,0),4),4,0);
}
L457350: { // 395d1c  cmp dword ptr [ebp + 0x1c], ebx
sub(read((0x1cu+r[5]),4),get(3,4,0),4);
}
L457353: { // 0f84d4000000  je 0x45742d
if(condition(0))goto L45742d;
}
L457359: { // 8b4518  mov eax, dword ptr [ebp + 0x18]
put(0,read((0x18u+r[5]),4),4,0);
}
L45735c: { // 3bc3  cmp eax, ebx
sub(get(0,4,0),get(3,4,0),4);
}
L45735e: { // 0f8ec9000000  jle 0x45742d
if(condition(4))goto L45742d;
}
L457364: { // 57  push edi
push(get(7,4,0));
}
L457365: { // 56  push esi
push(get(6,4,0));
}
L457366: { // 8945f8  mov dword ptr [ebp - 8], eax
write((0xfffffff8u+r[5]),get(0,4,0),4);
}
L457369: { // 8b5514  mov edx, dword ptr [ebp + 0x14]
put(2,read((0x14u+r[5]),4),4,0);
}
L45736c: { // 85d2  test edx, edx
logic(get(2,4,0)&get(2,4,0),4);
}
L45736e: { // 0f8ea5000000  jle 0x457419
if(condition(4))goto L457419;
}
L457374: { // 8b451c  mov eax, dword ptr [ebp + 0x1c]
put(0,read((0x1cu+r[5]),4),4,0);
}
L457377: { // 8955fc  mov dword ptr [ebp - 4], edx
write((0xfffffffcu+r[5]),get(2,4,0),4);
}
L45737a: { // 8d0498  lea eax, [eax + ebx*4]
put(0,(0x0u+r[0]+r[3]*4u),4,0);
}
L45737d: { // 8d1c93  lea ebx, [ebx + edx*4]
put(3,(0x0u+r[3]+r[2]*4u),4,0);
}
L457380: { // 895df0  mov dword ptr [ebp - 0x10], ebx
write((0xfffffff0u+r[5]),get(3,4,0),4);
}
L457383: { // 8d148da0bc7c00  lea edx, [ecx*4 + 0x7cbca0]
put(2,(0x7cbca0u+r[1]*4u),4,0);
}
L45738a: { // 8d348d304d7e00  lea esi, [ecx*4 + 0x7e4d30]
put(6,(0x7e4d30u+r[1]*4u),4,0);
}
L457391: { // 895508  mov dword ptr [ebp + 8], edx
write((0x8u+r[5]),get(2,4,0),4);
}
L457394: { // 89450c  mov dword ptr [ebp + 0xc], eax
write((0xcu+r[5]),get(0,4,0),4);
}
L457397: { // c7451802000000  mov dword ptr [ebp + 0x18], 2
write((0x18u+r[5]),0x2u,4);
}
L45739e: { // 8b38  mov edi, dword ptr [eax]
put(7,read((0x0u+r[0]),4),4,0);
}
L4573a0: { // 89be00c0ffff  mov dword ptr [esi - 0x4000], edi
write((0xffffc000u+r[6]),get(7,4,0),4);
}
L4573a6: { // 8b4004  mov eax, dword ptr [eax + 4]
put(0,read((0x4u+r[0]),4),4,0);
}
L4573a9: { // 8bf8  mov edi, eax
put(7,get(0,4,0),4,0);
}
L4573ab: { // 25ffff0000  and eax, 0xffff
put(0,logic(get(0,4,0)&0xffffu,4),4,0);
}
L4573b0: { // c1ff10  sar edi, 0x10
put(7,shift(get(7,4,0),0x10u,4,2),4,0);
}
L4573b3: { // 3d04010000  cmp eax, 0x104
sub(get(0,4,0),0x104u,4);
}
L4573b8: { // 897df4  mov dword ptr [ebp - 0xc], edi
write((0xfffffff4u+r[5]),get(7,4,0),4);
}
L4573bb: { // 8906  mov dword ptr [esi], eax
write((0x0u+r[6]),get(0,4,0),4);
}
L4573bd: { // 7d2f  jge 0x4573ee
if(condition(3))goto L4573ee;
}
L4573bf: { // 8b1c8538fc5c00  mov ebx, dword ptr [eax*4 + 0x5cfc38]
put(3,read((0x5cfc38u+r[0]*4u),4),4,0);
}
L4573c6: { // 8bc7  mov eax, edi
put(0,get(7,4,0),4,0);
}
L4573c8: { // 6a04  push 4
push(0x4u);
}
L4573ca: { // 83e3e0  and ebx, 0xffffffe0
put(3,logic(get(3,4,0)&0xffffffe0u,4),4,0);
}
L4573cd: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4573ce: { // 5f  pop edi
put(7,pop(),4,0);
}
L4573cf: { // f7ff  idiv edi
divide(get(7,4,0),true);
}
L4573d1: { // 83e007  and eax, 7
put(0,logic(get(0,4,0)&0x7u,4),4,0);
}
L4573d4: { // c1e002  shl eax, 2
put(0,shift(get(0,4,0),0x2u,4,0),4,0);
}
L4573d7: { // 0bd8  or ebx, eax
put(3,logic(get(3,4,0)|get(0,4,0),4),4,0);
}
L4573d9: { // 8b45f4  mov eax, dword ptr [ebp - 0xc]
put(0,read((0xfffffff4u+r[5]),4),4,0);
}
L4573dc: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4573dd: { // f7ff  idiv edi
divide(get(7,4,0),true);
}
L4573df: { // 83e203  and edx, 3
put(2,logic(get(2,4,0)&0x3u,4),4,0);
}
L4573e2: { // 0bda  or ebx, edx
put(3,logic(get(3,4,0)|get(2,4,0),4),4,0);
}
L4573e4: { // 8b5508  mov edx, dword ptr [ebp + 8]
put(2,read((0x8u+r[5]),4),4,0);
}
L4573e7: { // 891a  mov dword ptr [edx], ebx
write((0x0u+r[2]),get(3,4,0),4);
}
L4573e9: { // 8b5df0  mov ebx, dword ptr [ebp - 0x10]
put(3,read((0xfffffff0u+r[5]),4),4,0);
}
L4573ec: { // eb03  jmp 0x4573f1
goto L4573f1;
}
L4573ee: { // 832200  and dword ptr [edx], 0
write((0x0u+r[2]),logic(read((0x0u+r[2]),4)&0x0u,4),4);
}
L4573f1: { // 83450c08  add dword ptr [ebp + 0xc], 8
write((0xcu+r[5]),add(read((0xcu+r[5]),4),0x8u,4,false),4);
}
L4573f5: { // 81c628800000  add esi, 0x8028
put(6,add(get(6,4,0),0x8028u,4,false),4,0);
}
L4573fb: { // 8b450c  mov eax, dword ptr [ebp + 0xc]
put(0,read((0xcu+r[5]),4),4,0);
}
L4573fe: { // 81c200400000  add edx, 0x4000
put(2,add(get(2,4,0),0x4000u,4,false),4,0);
}
L457404: { // ff4d18  dec dword ptr [ebp + 0x18]
write((0x18u+r[5]),inc(read((0x18u+r[5]),4),4,-1),4);
}
L457407: { // 895508  mov dword ptr [ebp + 8], edx
write((0x8u+r[5]),get(2,4,0),4);
}
L45740a: { // 7592  jne 0x45739e
if(condition(1))goto L45739e;
}
L45740c: { // 41  inc ecx
put(1,inc(get(1,4,0),4,1),4,0);
}
L45740d: { // ff4dfc  dec dword ptr [ebp - 4]
write((0xfffffffcu+r[5]),inc(read((0xfffffffcu+r[5]),4),4,-1),4);
}
L457410: { // 0f856dffffff  jne 0x457383
if(condition(1))goto L457383;
}
L457416: { // 8b5514  mov edx, dword ptr [ebp + 0x14]
put(2,read((0x14u+r[5]),4),4,0);
}
L457419: { // a1c4607700  mov eax, dword ptr [0x7760c4]
put(0,read((0x7760c4u),4),4,0);
}
L45741e: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L457420: { // 03c8  add ecx, eax
put(1,add(get(1,4,0),get(0,4,0),4,false),4,0);
}
L457422: { // ff4df8  dec dword ptr [ebp - 8]
write((0xfffffff8u+r[5]),inc(read((0xfffffff8u+r[5]),4),4,-1),4);
}
L457425: { // 0f853effffff  jne 0x457369
if(condition(1))goto L457369;
}
L45742b: { // 5e  pop esi
put(6,pop(),4,0);
}
L45742c: { // 5f  pop edi
put(7,pop(),4,0);
}
L45742d: { // 5b  pop ebx
put(3,pop(),4,0);
}
L45742e: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L45742f: { // c21800  ret 0x18
pop();r[4]+=0x18u;return;
}
}
// 00457432_clear_mfo_jmp_act_sentinel_table_mc_457432
void RecoveredBattle::fn_457432(){
goto L457432;
L457432: { // b8acb57a00  mov eax, 0x7ab5ac
put(0,0x7ab5acu,4,0);
}
L457437: { // 8308ff  or dword ptr [eax], 0xffffffff
write((0x0u+r[0]),logic(read((0x0u+r[0]),4)|0xffffffffu,4),4);
}
L45743a: { // 83c020  add eax, 0x20
put(0,add(get(0,4,0),0x20u,4,false),4,0);
}
L45743d: { // 3dacb97a00  cmp eax, 0x7ab9ac
sub(get(0,4,0),0x7ab9acu,4);
}
L457442: { // 7cf3  jl 0x457437
if(condition(2))goto L457437;
}
L457444: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00457445_clear_pcpos_battle_entry_selector_table_mc_457445
void RecoveredBattle::fn_457445(){
goto L457445;
L457445: { // b8b0b97a00  mov eax, 0x7ab9b0
put(0,0x7ab9b0u,4,0);
}
L45744a: { // 8308ff  or dword ptr [eax], 0xffffffff
write((0x0u+r[0]),logic(read((0x0u+r[0]),4)|0xffffffffu,4),4);
}
L45744d: { // 83c018  add eax, 0x18
put(0,add(get(0,4,0),0x18u,4,false),4,0);
}
L457450: { // 3db0bc7a00  cmp eax, 0x7abcb0
sub(get(0,4,0),0x7abcb0u,4);
}
L457455: { // 7cf3  jl 0x45744a
if(condition(2))goto L45744a;
}
L457457: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00457700_restore_active_field_actor_from_transition_position_mc_457700
void RecoveredBattle::fn_457700(){
goto L457700;
L457700: { // 56  push esi
push(get(6,4,0));
}
L457701: { // 8b351c3a8000  mov esi, dword ptr [0x803a1c]
put(6,read((0x803a1cu),4),4,0);
}
L457707: { // 893578747800  mov dword ptr [0x787478], esi
write((0x787478u),get(6,4,0),4);
}
L45770d: { // 69f6ac010000  imul esi, esi, 0x1ac
put(6,multiply(get(6,4,0),0x1acu,4),4,0);
}
L457713: { // 81c6d8738000  add esi, 0x8073d8
put(6,add(get(6,4,0),0x8073d8u,4,false),4,0);
}
L457719: { // 814e04c0000100  or dword ptr [esi + 4], 0x100c0
write((0x4u+r[6]),logic(read((0x4u+r[6]),4)|0x100c0u,4),4);
}
L457720: { // a1283a8000  mov eax, dword ptr [0x803a28]
put(0,read((0x803a28u),4),4,0);
}
L457725: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L457727: { // 7d14  jge 0x45773d
if(condition(3))goto L45773d;
}
L457729: { // ff35143a8000  push dword ptr [0x803a14]
push(read((0x803a14u),4));
}
L45772f: { // ffb62c010000  push dword ptr [esi + 0x12c]
push(read((0x12cu+r[6]),4));
}
L457735: { // ffb628010000  push dword ptr [esi + 0x128]
push(read((0x128u+r[6]),4));
}
L45773b: { // eb18  jmp 0x457755
goto L457755;
}
L45773d: { // 8d0440  lea eax, [eax + eax*2]
put(0,(0x0u+r[0]+r[0]*2u),4,0);
}
L457740: { // c1e003  shl eax, 3
put(0,shift(get(0,4,0),0x3u,4,0),4,0);
}
L457743: { // ffb0a8b97a00  push dword ptr [eax + 0x7ab9a8]
push(read((0x7ab9a8u+r[0]),4));
}
L457749: { // ffb0a4b97a00  push dword ptr [eax + 0x7ab9a4]
push(read((0x7ab9a4u+r[0]),4));
}
L45774f: { // ffb0a0b97a00  push dword ptr [eax + 0x7ab9a0]
push(read((0x7ab9a0u+r[0]),4));
}
L457755: { // 56  push esi
push(get(6,4,0));
}
L457756: { // e819600000  call 0x45d774
push(0x45775bu);dispatch(0x45d774u);
}
L45775b: { // a1283a8000  mov eax, dword ptr [0x803a28]
put(0,read((0x803a28u),4),4,0);
}
L457760: { // 8d0440  lea eax, [eax + eax*2]
put(0,(0x0u+r[0]+r[0]*2u),4,0);
}
L457763: { // 8b04c5a0b97a00  mov eax, dword ptr [eax*8 + 0x7ab9a0]
put(0,read((0x7ab9a0u+r[0]*8u),4),4,0);
}
L45776a: { // 898628010000  mov dword ptr [esi + 0x128], eax
write((0x128u+r[6]),get(0,4,0),4);
}
L457770: { // a1283a8000  mov eax, dword ptr [0x803a28]
put(0,read((0x803a28u),4),4,0);
}
L457775: { // 8d0440  lea eax, [eax + eax*2]
put(0,(0x0u+r[0]+r[0]*2u),4,0);
}
L457778: { // 8b04c5a4b97a00  mov eax, dword ptr [eax*8 + 0x7ab9a4]
put(0,read((0x7ab9a4u+r[0]*8u),4),4,0);
}
L45777f: { // 83662c00  and dword ptr [esi + 0x2c], 0
write((0x2cu+r[6]),logic(read((0x2cu+r[6]),4)&0x0u,4),4);
}
L457783: { // 83663000  and dword ptr [esi + 0x30], 0
write((0x30u+r[6]),logic(read((0x30u+r[6]),4)&0x0u,4),4);
}
L457787: { // 83663400  and dword ptr [esi + 0x34], 0
write((0x34u+r[6]),logic(read((0x34u+r[6]),4)&0x0u,4),4);
}
L45778b: { // 83663800  and dword ptr [esi + 0x38], 0
write((0x38u+r[6]),logic(read((0x38u+r[6]),4)&0x0u,4),4);
}
L45778f: { // 89862c010000  mov dword ptr [esi + 0x12c], eax
write((0x12cu+r[6]),get(0,4,0),4);
}
L457795: { // c78648010000d78e4500  mov dword ptr [esi + 0x148], 0x458ed7
write((0x148u+r[6]),0x458ed7u,4);
}
L45779f: { // a1283a8000  mov eax, dword ptr [0x803a28]
put(0,read((0x803a28u),4),4,0);
}
L4577a4: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L4577a6: { // 7d04  jge 0x4577ac
if(condition(3))goto L4577ac;
}
L4577a8: { // 6aff  push -1
push(0xffffffffu);
}
L4577aa: { // eb0a  jmp 0x4577b6
goto L4577b6;
}
L4577ac: { // 8d0440  lea eax, [eax + eax*2]
put(0,(0x0u+r[0]+r[0]*2u),4,0);
}
L4577af: { // ff34c5acb97a00  push dword ptr [eax*8 + 0x7ab9ac]
push(read((0x7ab9acu+r[0]*8u),4));
}
L4577b6: { // 56  push esi
push(get(6,4,0));
}
L4577b7: { // e808160000  call 0x458dc4
push(0x4577bcu);dispatch(0x458dc4u);
}
L4577bc: { // a19c225d00  mov eax, dword ptr [0x5d229c]
put(0,read((0x5d229cu),4),4,0);
}
L4577c1: { // 3dc8010000  cmp eax, 0x1c8
sub(get(0,4,0),0x1c8u,4);
}
L4577c6: { // 7e0c  jle 0x4577d4
if(condition(4))goto L4577d4;
}
L4577c8: { // 3dd4010000  cmp eax, 0x1d4
sub(get(0,4,0),0x1d4u,4);
}
L4577cd: { // 7d05  jge 0x4577d4
if(condition(3))goto L4577d4;
}
L4577cf: { // e815d20300  call 0x4949e9
push(0x4577d4u);dispatch(0x4949e9u);
}
L4577d4: { // 5e  pop esi
put(6,pop(),4,0);
}
L4577d5: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00457b7c_clear_overlay_effect_entry_mc_457b7c
void RecoveredBattle::fn_457b7c(){
goto L457b7c;
L457b7c: { // 6a30  push 0x30
push(0x30u);
}
L457b7e: { // 6a00  push 0
push(0x0u);
}
L457b80: { // ff74240c  push dword ptr [esp + 0xc]
push(read((0xcu+r[4]),4));
}
L457b84: { // e8e7010400  call 0x497d70
push(0x457b89u);dispatch(0x497d70u);
}
L457b89: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L457b8c: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00457b8f_clear_all_overlay_effects_mc_457b8f
void RecoveredBattle::fn_457b8f(){
goto L457b8f;
L457b8f: { // 68000c0000  push 0xc00
push(0xc00u);
}
L457b94: { // 6a00  push 0
push(0x0u);
}
L457b96: { // 68c80d8000  push 0x800dc8
push(0x800dc8u);
}
L457b9b: { // e8d0010400  call 0x497d70
push(0x457ba0u);dispatch(0x497d70u);
}
L457ba0: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L457ba3: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00457ba4_validate_or_trigger_field_step
void RecoveredBattle::fn_457ba4(){
goto L457ba4;
L457ba4: { // 55  push ebp
push(get(5,4,0));
}
L457ba5: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L457ba7: { // 51  push ecx
push(get(1,4,0));
}
L457ba8: { // 8b4514  mov eax, dword ptr [ebp + 0x14]
put(0,read((0x14u+r[5]),4),4,0);
}
L457bab: { // 8365fc00  and dword ptr [ebp - 4], 0
write((0xfffffffcu+r[5]),logic(read((0xfffffffcu+r[5]),4)&0x0u,4),4);
}
L457baf: { // 53  push ebx
push(get(3,4,0));
}
L457bb0: { // 56  push esi
push(get(6,4,0));
}
L457bb1: { // 57  push edi
push(get(7,4,0));
}
L457bb2: { // 6a04  push 4
push(0x4u);
}
L457bb4: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L457bb5: { // 59  pop ecx
put(1,pop(),4,0);
}
L457bb6: { // bf00000002  mov edi, 0x2000000
put(7,0x2000000u,4,0);
}
L457bbb: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L457bbd: { // b9d00d8000  mov ecx, 0x800dd0
put(1,0x800dd0u,4,0);
}
L457bc2: { // 8bf2  mov esi, edx
put(6,get(2,4,0),4,0);
}
L457bc4: { // b20f  mov dl, 0xf
put(2,0xfu,1,0);
}
L457bc6: { // 8b41f8  mov eax, dword ptr [ecx - 8]
put(0,read((0xfffffff8u+r[1]),4),4,0);
}
L457bc9: { // a900000001  test eax, 0x1000000
logic(get(0,4,0)&0x1000000u,4);
}
L457bce: { // 7477  je 0x457c47
if(condition(0))goto L457c47;
}
L457bd0: { // 85c7  test edi, eax
logic(get(7,4,0)&get(0,4,0),4);
}
L457bd2: { // 7573  jne 0x457c47
if(condition(1))goto L457c47;
}
L457bd4: { // 8bd8  mov ebx, eax
put(3,get(0,4,0),4,0);
}
L457bd6: { // 235d10  and ebx, dword ptr [ebp + 0x10]
put(3,logic(get(3,4,0)&read((0x10u+r[5]),4),4),4,0);
}
L457bd9: { // f6c70f  test bh, 0xf
logic(get(3,1,8)&0xfu,1);
}
L457bdc: { // 7469  je 0x457c47
if(condition(0))goto L457c47;
}
L457bde: { // 8b5d08  mov ebx, dword ptr [ebp + 8]
put(3,read((0x8u+r[5]),4),4,0);
}
L457be1: { // 3b59fc  cmp ebx, dword ptr [ecx - 4]
sub(get(3,4,0),read((0xfffffffcu+r[1]),4),4);
}
L457be4: { // 7c61  jl 0x457c47
if(condition(2))goto L457c47;
}
L457be6: { // 3b5904  cmp ebx, dword ptr [ecx + 4]
sub(get(3,4,0),read((0x4u+r[1]),4),4);
}
L457be9: { // 7f5c  jg 0x457c47
if(condition(5))goto L457c47;
}
L457beb: { // 8b5d0c  mov ebx, dword ptr [ebp + 0xc]
put(3,read((0xcu+r[5]),4),4,0);
}
L457bee: { // 3b19  cmp ebx, dword ptr [ecx]
sub(get(3,4,0),read((0x0u+r[1]),4),4);
}
L457bf0: { // 7c55  jl 0x457c47
if(condition(2))goto L457c47;
}
L457bf2: { // 3b5908  cmp ebx, dword ptr [ecx + 8]
sub(get(3,4,0),read((0x8u+r[1]),4),4);
}
L457bf5: { // 7f50  jg 0x457c47
if(condition(5))goto L457c47;
}
L457bf7: { // f6c404  test ah, 4
logic(get(0,1,8)&0x4u,1);
}
L457bfa: { // 740c  je 0x457c08
if(condition(0))goto L457c08;
}
L457bfc: { // 8a9e48005d00  mov bl, byte ptr [esi + 0x5d0048]
put(3,read((0x5d0048u+r[6]),1),1,0);
}
L457c02: { // 23d8  and ebx, eax
put(3,logic(get(3,4,0)&get(0,4,0),4),4,0);
}
L457c04: { // 84da  test dl, bl
logic(get(2,1,0)&get(3,1,0),1);
}
L457c06: { // 7533  jne 0x457c3b
if(condition(1))goto L457c3b;
}
L457c08: { // f6c402  test ah, 2
logic(get(0,1,8)&0x2u,1);
}
L457c0b: { // 740c  je 0x457c19
if(condition(0))goto L457c19;
}
L457c0d: { // 8a9e48005d00  mov bl, byte ptr [esi + 0x5d0048]
put(3,read((0x5d0048u+r[6]),1),1,0);
}
L457c13: { // 23d8  and ebx, eax
put(3,logic(get(3,4,0)&get(0,4,0),4),4,0);
}
L457c15: { // 84da  test dl, bl
logic(get(2,1,0)&get(3,1,0),1);
}
L457c17: { // 7522  jne 0x457c3b
if(condition(1))goto L457c3b;
}
L457c19: { // f6c408  test ah, 8
logic(get(0,1,8)&0x8u,1);
}
L457c1c: { // 740c  je 0x457c2a
if(condition(0))goto L457c2a;
}
L457c1e: { // 8a9e48005d00  mov bl, byte ptr [esi + 0x5d0048]
put(3,read((0x5d0048u+r[6]),1),1,0);
}
L457c24: { // 23d8  and ebx, eax
put(3,logic(get(3,4,0)&get(0,4,0),4),4,0);
}
L457c26: { // 84da  test dl, bl
logic(get(2,1,0)&get(3,1,0),1);
}
L457c28: { // 7511  jne 0x457c3b
if(condition(1))goto L457c3b;
}
L457c2a: { // f6c401  test ah, 1
logic(get(0,1,8)&0x1u,1);
}
L457c2d: { // 7418  je 0x457c47
if(condition(0))goto L457c47;
}
L457c2f: { // 8a9e48005d00  mov bl, byte ptr [esi + 0x5d0048]
put(3,read((0x5d0048u+r[6]),1),1,0);
}
L457c35: { // 23d8  and ebx, eax
put(3,logic(get(3,4,0)&get(0,4,0),4),4,0);
}
L457c37: { // 84da  test dl, bl
logic(get(2,1,0)&get(3,1,0),1);
}
L457c39: { // 740c  je 0x457c47
if(condition(0))goto L457c47;
}
L457c3b: { // 0bc7  or eax, edi
put(0,logic(get(0,4,0)|get(7,4,0),4),4,0);
}
L457c3d: { // c745fc01000000  mov dword ptr [ebp - 4], 1
write((0xfffffffcu+r[5]),0x1u,4);
}
L457c44: { // 8941f8  mov dword ptr [ecx - 8], eax
write((0xfffffff8u+r[1]),get(0,4,0),4);
}
L457c47: { // 83c130  add ecx, 0x30
put(1,add(get(1,4,0),0x30u,4,false),4,0);
}
L457c4a: { // 81f9d0198000  cmp ecx, 0x8019d0
sub(get(1,4,0),0x8019d0u,4);
}
L457c50: { // 0f8c70ffffff  jl 0x457bc6
if(condition(2))goto L457bc6;
}
L457c56: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L457c58: { // 5f  pop edi
put(7,pop(),4,0);
}
L457c59: { // 3945fc  cmp dword ptr [ebp - 4], eax
sub(read((0xfffffffcu+r[5]),4),get(0,4,0),4);
}
L457c5c: { // 5e  pop esi
put(6,pop(),4,0);
}
L457c5d: { // 5b  pop ebx
put(3,pop(),4,0);
}
L457c5e: { // 0f95c0  setne al
put(0,condition(1),1,0);
}
L457c61: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L457c62: { // c21000  ret 0x10
pop();r[4]+=0x10u;return;
}
}
// 0045457d_camera_focus_snapshot_actor_and_enter_tile_mode_mc_45457d
void RecoveredBattle::fn_45457d(){
goto L45457d;
L45457d: { // a178747800  mov eax, dword ptr [0x787478]
put(0,read((0x787478u),4),4,0);
}
L454582: { // 69c0ac010000  imul eax, eax, 0x1ac
put(0,multiply(get(0,4,0),0x1acu,4),4,0);
}
L454588: { // 05d8738000  add eax, 0x8073d8
put(0,add(get(0,4,0),0x8073d8u,4,false),4,0);
}
L45458d: { // 8b4808  mov ecx, dword ptr [eax + 8]
put(1,read((0x8u+r[0]),4),4,0);
}
L454590: { // 890d34768500  mov dword ptr [0x857634], ecx
write((0x857634u),get(1,4,0),4);
}
L454596: { // 8b480c  mov ecx, dword ptr [eax + 0xc]
put(1,read((0xcu+r[0]),4),4,0);
}
L454599: { // 890d38768500  mov dword ptr [0x857638], ecx
write((0x857638u),get(1,4,0),4);
}
L45459f: { // 8b4010  mov eax, dword ptr [eax + 0x10]
put(0,read((0x10u+r[0]),4),4,0);
}
L4545a2: { // a33c768500  mov dword ptr [0x85763c], eax
write((0x85763cu),get(0,4,0),4);
}
L4545a7: { // c70578747800ff020000  mov dword ptr [0x787478], 0x2ff
write((0x787478u),0x2ffu,4);
}
L4545b1: { // b82c768500  mov eax, 0x85762c
put(0,0x85762cu,4,0);
}
L4545b6: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00455238_dynamic_map_sparkle_object_tick_mc_455238
void RecoveredBattle::fn_455238(){
goto L455238;
L455238: { // 8b442404  mov eax, dword ptr [esp + 4]
put(0,read((0x4u+r[4]),4),4,0);
}
L45523c: { // 8b884c010000  mov ecx, dword ptr [eax + 0x14c]
put(1,read((0x14cu+r[0]),4),4,0);
}
L455242: { // 83f9ff  cmp ecx, -1
sub(get(1,4,0),0xffffffffu,4);
}
L455245: { // 7446  je 0x45528d
if(condition(0))goto L45528d;
}
L455247: { // 85c9  test ecx, ecx
logic(get(1,4,0)&get(1,4,0),4);
}
L455249: { // 7429  je 0x455274
if(condition(0))goto L455274;
}
L45524b: { // 83f90a  cmp ecx, 0xa
sub(get(1,4,0),0xau,4);
}
L45524e: { // 7550  jne 0x4552a0
if(condition(1))goto L4552a0;
}
L455250: { // 8b8860010000  mov ecx, dword ptr [eax + 0x160]
put(1,read((0x160u+r[0]),4),4,0);
}
L455256: { // 3b0d9c225d00  cmp ecx, dword ptr [0x5d229c]
sub(get(1,4,0),read((0x5d229cu),4),4);
}
L45525c: { // 7442  je 0x4552a0
if(condition(0))goto L4552a0;
}
L45525e: { // 8b889c010000  mov ecx, dword ptr [eax + 0x19c]
put(1,read((0x19cu+r[0]),4),4,0);
}
L455264: { // 50  push eax
push(get(0,4,0));
}
L455265: { // 83248d60b57a0000  and dword ptr [ecx*4 + 0x7ab560], 0
write((0x7ab560u+r[1]*4u),logic(read((0x7ab560u+r[1]*4u),4)&0x0u,4),4);
}
L45526d: { // e8ab860000  call 0x45d91d
push(0x455272u);dispatch(0x45d91du);
}
L455272: { // eb2c  jmp 0x4552a0
goto L4552a0;
}
L455274: { // 8140100000feff  add dword ptr [eax + 0x10], 0xfffe0000
write((0x10u+r[0]),add(read((0x10u+r[0]),4),0xfffe0000u,4,false),4);
}
L45527b: { // 83781000  cmp dword ptr [eax + 0x10], 0
sub(read((0x10u+r[0]),4),0x0u,4);
}
L45527f: { // 7f1f  jg 0x4552a0
if(condition(5))goto L4552a0;
}
L455281: { // c7804c0100000a000000  mov dword ptr [eax + 0x14c], 0xa
write((0x14cu+r[0]),0xau,4);
}
L45528b: { // eb13  jmp 0x4552a0
goto L4552a0;
}
L45528d: { // 8b0d9c225d00  mov ecx, dword ptr [0x5d229c]
put(1,read((0x5d229cu),4),4,0);
}
L455293: { // c7401000002000  mov dword ptr [eax + 0x10], 0x200000
write((0x10u+r[0]),0x200000u,4);
}
L45529a: { // 898860010000  mov dword ptr [eax + 0x160], ecx
write((0x160u+r[0]),get(1,4,0),4);
}
L4552a0: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
} // namespace fsb::core
