// Generated by tools/translate_battle.py; edit the generator, not this file.
// Original EXE SHA256: 710881d024ab1fcf738b342c248631363c9de3a51b32a7e3d61781b791eff454
#include "fsb_core/recovered_battle.hpp"
#include <cstring>
#include <cmath>
namespace fsb::core {
// 00431869_debug_overlay_enable_color_init_mc_431869
void RecoveredBattle::fn_431869(){
goto L431869;
L431869: { // 6a10  push 0x10
push(0x10u);
}
L43186b: { // 6a00  push 0
push(0x0u);
}
L43186d: { // 6810b25a00  push 0x5ab210
push(0x5ab210u);
}
L431872: { // c7051494760001000000  mov dword ptr [0x769414], 1
write((0x769414u),0x1u,4);
}
L43187c: { // e89b33fdff  call 0x404c1c
push(0x431881u);dispatch(0x404c1cu);
}
L431881: { // 6a08  push 8
push(0x8u);
}
L431883: { // 68f8000000  push 0xf8
push(0xf8u);
}
L431888: { // 6850b25a00  push 0x5ab250
push(0x5ab250u);
}
L43188d: { // e88a33fdff  call 0x404c1c
push(0x431892u);dispatch(0x404c1cu);
}
L431892: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00431893_sync_dialog_timing_options_431893
void RecoveredBattle::fn_431893(){
goto L431893;
L431893: { // a1e02f7700  mov eax, dword ptr [0x772fe0]
put(0,read((0x772fe0u),4),4,0);
}
L431898: { // 56  push esi
push(get(6,4,0));
}
L431899: { // 6a64  push 0x64
push(0x64u);
}
L43189b: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L43189d: { // 5a  pop edx
put(2,pop(),4,0);
}
L43189e: { // 7f04  jg 0x4318a4
if(condition(5))goto L4318a4;
}
L4318a0: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L4318a2: { // eb06  jmp 0x4318aa
goto L4318aa;
}
L4318a4: { // 3bc2  cmp eax, edx
sub(get(0,4,0),get(2,4,0),4);
}
L4318a6: { // 7c07  jl 0x4318af
if(condition(2))goto L4318af;
}
L4318a8: { // 8bc2  mov eax, edx
put(0,get(2,4,0),4,0);
}
L4318aa: { // a3e02f7700  mov dword ptr [0x772fe0], eax
write((0x772fe0u),get(0,4,0),4);
}
L4318af: { // 8b35e42f7700  mov esi, dword ptr [0x772fe4]
put(6,read((0x772fe4u),4),4,0);
}
L4318b5: { // 85f6  test esi, esi
logic(get(6,4,0)&get(6,4,0),4);
}
L4318b7: { // 7f04  jg 0x4318bd
if(condition(5))goto L4318bd;
}
L4318b9: { // 33f6  xor esi, esi
put(6,logic(get(6,4,0)^get(6,4,0),4),4,0);
}
L4318bb: { // eb06  jmp 0x4318c3
goto L4318c3;
}
L4318bd: { // 3bf2  cmp esi, edx
sub(get(6,4,0),get(2,4,0),4);
}
L4318bf: { // 7c08  jl 0x4318c9
if(condition(2))goto L4318c9;
}
L4318c1: { // 8bf2  mov esi, edx
put(6,get(2,4,0),4,0);
}
L4318c3: { // 8935e42f7700  mov dword ptr [0x772fe4], esi
write((0x772fe4u),get(6,4,0),4);
}
L4318c9: { // 8b0de82f7700  mov ecx, dword ptr [0x772fe8]
put(1,read((0x772fe8u),4),4,0);
}
L4318cf: { // 85c9  test ecx, ecx
logic(get(1,4,0)&get(1,4,0),4);
}
L4318d1: { // 7f04  jg 0x4318d7
if(condition(5))goto L4318d7;
}
L4318d3: { // 33c9  xor ecx, ecx
put(1,logic(get(1,4,0)^get(1,4,0),4),4,0);
}
L4318d5: { // eb06  jmp 0x4318dd
goto L4318dd;
}
L4318d7: { // 3bca  cmp ecx, edx
sub(get(1,4,0),get(2,4,0),4);
}
L4318d9: { // 7c08  jl 0x4318e3
if(condition(2))goto L4318e3;
}
L4318db: { // 8bca  mov ecx, edx
put(1,get(2,4,0),4,0);
}
L4318dd: { // 890de82f7700  mov dword ptr [0x772fe8], ecx
write((0x772fe8u),get(1,4,0),4);
}
L4318e3: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4318e4: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L4318e6: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L4318e8: { // a37c847600  mov dword ptr [0x76847c], eax
write((0x76847cu),get(0,4,0),4);
}
L4318ed: { // 8bc6  mov eax, esi
put(0,get(6,4,0),4,0);
}
L4318ef: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4318f0: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L4318f2: { // 5e  pop esi
put(6,pop(),4,0);
}
L4318f3: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L4318f5: { // a364847600  mov dword ptr [0x768464], eax
write((0x768464u),get(0,4,0),4);
}
L4318fa: { // 8bc1  mov eax, ecx
put(0,get(1,4,0),4,0);
}
L4318fc: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4318fd: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L4318ff: { // d1f8  sar eax, 1
put(0,shift(get(0,4,0),0x1u,4,2),4,0);
}
L431901: { // a378847600  mov dword ptr [0x768478], eax
write((0x768478u),get(0,4,0),4);
}
L431906: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00431e95_event_count_serializer
void RecoveredBattle::fn_431e95(){
goto L431e95;
L431e95: { // 56  push esi
push(get(6,4,0));
}
L431e96: { // 8b742408  mov esi, dword ptr [esp + 8]
put(6,read((0x8u+r[4]),4),4,0);
}
L431e9a: { // 85f6  test esi, esi
logic(get(6,4,0)&get(6,4,0),4);
}
L431e9c: { // 7527  jne 0x431ec5
if(condition(1))goto L431ec5;
}
L431e9e: { // 68b0020000  push 0x2b0
push(0x2b0u);
}
L431ea3: { // 6a5c  push 0x5c
push(0x5cu);
}
L431ea5: { // 68dcb75a00  push 0x5ab7dc
push(0x5ab7dcu);
}
L431eaa: { // e8c1550600  call 0x497470
push(0x431eafu);dispatch(0x497470u);
}
L431eaf: { // 59  pop ecx
put(1,pop(),4,0);
}
L431eb0: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L431eb1: { // 59  pop ecx
put(1,pop(),4,0);
}
L431eb2: { // 50  push eax
push(get(0,4,0));
}
L431eb3: { // 6814b85a00  push 0x5ab814
push(0x5ab814u);
}
L431eb8: { // 685c604a00  push 0x4a605c
push(0x4a605cu);
}
L431ebd: { // e868fafcff  call 0x40192a
push(0x431ec2u);dispatch(0x40192au);
}
L431ec2: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L431ec5: { // e814000000  call 0x431ede
push(0x431ecau);dispatch(0x431edeu);
}
L431eca: { // a328897600  mov dword ptr [0x768928], eax
write((0x768928u),get(0,4,0),4);
}
L431ecf: { // c706a4020000  mov dword ptr [esi], 0x2a4
write((0x0u+r[6]),0x2a4u,4);
}
L431ed5: { // b888867600  mov eax, 0x768688
put(0,0x768688u,4,0);
}
L431eda: { // 5e  pop esi
put(6,pop(),4,0);
}
L431edb: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00431ede_compute_event_table_size_mc_431ede
void RecoveredBattle::fn_431ede(){
goto L431ede;
L431ede: { // 56  push esi
push(get(6,4,0));
}
L431edf: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L431ee1: { // 57  push edi
push(get(7,4,0));
}
L431ee2: { // 33d2  xor edx, edx
put(2,logic(get(2,4,0)^get(2,4,0),4),4,0);
}
L431ee4: { // b988867600  mov ecx, 0x768688
put(1,0x768688u,4,0);
}
L431ee9: { // 8b39  mov edi, dword ptr [ecx]
put(7,read((0x0u+r[1]),4),4,0);
}
L431eeb: { // 8d7208  lea esi, [edx + 8]
put(6,(0x8u+r[2]),4,0);
}
L431eee: { // 83c708  add edi, 8
put(7,add(get(7,4,0),0x8u,4,false),4,0);
}
L431ef1: { // 83c104  add ecx, 4
put(1,add(get(1,4,0),0x4u,4,false),4,0);
}
L431ef4: { // 0faff7  imul esi, edi
put(6,multiply(get(6,4,0),get(7,4,0),4),4,0);
}
L431ef7: { // 42  inc edx
put(2,inc(get(2,4,0),4,1),4,0);
}
L431ef8: { // 81f928897600  cmp ecx, 0x768928
sub(get(1,4,0),0x768928u,4);
}
L431efe: { // 8d04f0  lea eax, [eax + esi*8]
put(0,(0x0u+r[0]+r[6]*8u),4,0);
}
L431f01: { // 7ce6  jl 0x431ee9
if(condition(2))goto L431ee9;
}
L431f03: { // 5f  pop edi
put(7,pop(),4,0);
}
L431f04: { // 5e  pop esi
put(6,pop(),4,0);
}
L431f05: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00431f06_save_event_end_data_store_mc_431f06
void RecoveredBattle::fn_431f06(){
goto L431f06;
L431f06: { // 56  push esi
push(get(6,4,0));
}
L431f07: { // 33f6  xor esi, esi
put(6,logic(get(6,4,0)^get(6,4,0),4),4,0);
}
L431f09: { // 817c240ca4020000  cmp dword ptr [esp + 0xc], 0x2a4
sub(read((0xcu+r[4]),4),0x2a4u,4);
}
L431f11: { // 7427  je 0x431f3a
if(condition(0))goto L431f3a;
}
L431f13: { // 68bb020000  push 0x2bb
push(0x2bbu);
}
L431f18: { // 6a5c  push 0x5c
push(0x5cu);
}
L431f1a: { // 68dcb75a00  push 0x5ab7dc
push(0x5ab7dcu);
}
L431f1f: { // e84c550600  call 0x497470
push(0x431f24u);dispatch(0x497470u);
}
L431f24: { // 59  pop ecx
put(1,pop(),4,0);
}
L431f25: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L431f26: { // 59  pop ecx
put(1,pop(),4,0);
}
L431f27: { // 50  push eax
push(get(0,4,0));
}
L431f28: { // 68d4b85a00  push 0x5ab8d4
push(0x5ab8d4u);
}
L431f2d: { // 685c604a00  push 0x4a605c
push(0x4a605cu);
}
L431f32: { // e8f3f9fcff  call 0x40192a
push(0x431f37u);dispatch(0x40192au);
}
L431f37: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L431f3a: { // ff74240c  push dword ptr [esp + 0xc]
push(read((0xcu+r[4]),4));
}
L431f3e: { // ff74240c  push dword ptr [esp + 0xc]
push(read((0xcu+r[4]),4));
}
L431f42: { // 6888867600  push 0x768688
push(0x768688u);
}
L431f47: { // e844580600  call 0x497790
push(0x431f4cu);dispatch(0x497790u);
}
L431f4c: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L431f4f: { // e88affffff  call 0x431ede
push(0x431f54u);dispatch(0x431edeu);
}
L431f54: { // 390528897600  cmp dword ptr [0x768928], eax
sub(read((0x768928u),4),get(0,4,0),4);
}
L431f5a: { // 740e  je 0x431f6a
if(condition(0))goto L431f6a;
}
L431f5c: { // 6828b85a00  push 0x5ab828
push(0x5ab828u);
}
L431f61: { // e81cfbfcff  call 0x401a82
push(0x431f66u);dispatch(0x401a82u);
}
L431f66: { // 59  pop ecx
put(1,pop(),4,0);
}
L431f67: { // 6a01  push 1
push(0x1u);
}
L431f69: { // 5e  pop esi
put(6,pop(),4,0);
}
L431f6a: { // 830d28fd5700ff  or dword ptr [0x57fd28], 0xffffffff
write((0x57fd28u),logic(read((0x57fd28u),4)|0xffffffffu,4),4);
}
L431f71: { // 8bc6  mov eax, esi
put(0,get(6,4,0),4,0);
}
L431f73: { // 5e  pop esi
put(6,pop(),4,0);
}
L431f74: { // c20800  ret 8
pop();r[4]+=0x8u;return;
}
}
// 004321ab_screen_transition_dispatch_mc_4321ab
void RecoveredBattle::fn_4321ab(){
goto L4321ab;
L4321ab: { // 55  push ebp
push(get(5,4,0));
}
L4321ac: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L4321ae: { // 83ec10  sub esp, 0x10
put(4,sub(get(4,4,0),0x10u,4,false),4,0);
}
L4321b1: { // 53  push ebx
push(get(3,4,0));
}
L4321b2: { // 8b5d08  mov ebx, dword ptr [ebp + 8]
put(3,read((0x8u+r[5]),4),4,0);
}
L4321b5: { // 56  push esi
push(get(6,4,0));
}
L4321b6: { // 57  push edi
push(get(7,4,0));
}
L4321b7: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L4321b9: { // be24b95a00  mov esi, 0x5ab924
put(6,0x5ab924u,4,0);
}
L4321be: { // 3bdf  cmp ebx, edi
sub(get(3,4,0),get(7,4,0),4);
}
L4321c0: { // 743a  je 0x4321fc
if(condition(0))goto L4321fc;
}
L4321c2: { // 7e18  jle 0x4321dc
if(condition(4))goto L4321dc;
}
L4321c4: { // 83fb04  cmp ebx, 4
sub(get(3,4,0),0x4u,4);
}
L4321c7: { // 7e0c  jle 0x4321d5
if(condition(4))goto L4321d5;
}
L4321c9: { // 83fb09  cmp ebx, 9
sub(get(3,4,0),0x9u,4);
}
L4321cc: { // 7f0e  jg 0x4321dc
if(condition(5))goto L4321dc;
}
L4321ce: { // a1709e6d00  mov eax, dword ptr [0x6d9e70]
put(0,read((0x6d9e70u),4),4,0);
}
L4321d3: { // eb29  jmp 0x4321fe
goto L4321fe;
}
L4321d5: { // e89833fdff  call 0x405572
push(0x4321dau);dispatch(0x405572u);
}
L4321da: { // eb22  jmp 0x4321fe
goto L4321fe;
}
L4321dc: { // 6a7a  push 0x7a
push(0x7au);
}
L4321de: { // 6a5c  push 0x5c
push(0x5cu);
}
L4321e0: { // 56  push esi
push(get(6,4,0));
}
L4321e1: { // e88a520600  call 0x497470
push(0x4321e6u);dispatch(0x497470u);
}
L4321e6: { // 59  pop ecx
put(1,pop(),4,0);
}
L4321e7: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L4321e8: { // 59  pop ecx
put(1,pop(),4,0);
}
L4321e9: { // 50  push eax
push(get(0,4,0));
}
L4321ea: { // 6874614a00  push 0x4a6174
push(0x4a6174u);
}
L4321ef: { // 6854614a00  push 0x4a6154
push(0x4a6154u);
}
L4321f4: { // e831f7fcff  call 0x40192a
push(0x4321f9u);dispatch(0x40192au);
}
L4321f9: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L4321fc: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L4321fe: { // 393d44947600  cmp dword ptr [0x769444], edi
sub(read((0x769444u),4),get(7,4,0),4);
}
L432204: { // 7442  je 0x432248
if(condition(0))goto L432248;
}
L432206: { // 391d38947600  cmp dword ptr [0x769438], ebx
sub(read((0x769438u),4),get(3,4,0),4);
}
L43220c: { // 753a  jne 0x432248
if(condition(1))goto L432248;
}
L43220e: { // 8b0d3c947600  mov ecx, dword ptr [0x76943c]
put(1,read((0x76943cu),4),4,0);
}
L432214: { // 3b4d0c  cmp ecx, dword ptr [ebp + 0xc]
sub(get(1,4,0),read((0xcu+r[5]),4),4);
}
L432217: { // 752f  jne 0x432248
if(condition(1))goto L432248;
}
L432219: { // 813ddca26d0006040000  cmp dword ptr [0x6da2dc], 0x406
sub(read((0x6da2dcu),4),0x406u,4);
}
L432223: { // 750a  jne 0x43222f
if(condition(1))goto L43222f;
}
L432225: { // c7054894760001000000  mov dword ptr [0x769448], 1
write((0x769448u),0x1u,4);
}
L43222f: { // 3bc7  cmp eax, edi
sub(get(0,4,0),get(7,4,0),4);
}
L432231: { // 0f856a010000  jne 0x4323a1
if(condition(1))goto L4323a1;
}
L432237: { // 393d48947600  cmp dword ptr [0x769448], edi
sub(read((0x769448u),4),get(7,4,0),4);
}
L43223d: { // 0f845e010000  je 0x4323a1
if(condition(0))goto L4323a1;
}
L432243: { // e91c020000  jmp 0x432464
goto L432464;
}
L432248: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L43224b: { // 6a01  push 1
push(0x1u);
}
L43224d: { // 5b  pop ebx
put(3,pop(),4,0);
}
L43224e: { // a338947600  mov dword ptr [0x769438], eax
write((0x769438u),get(0,4,0),4);
}
L432253: { // 8b450c  mov eax, dword ptr [ebp + 0xc]
put(0,read((0xcu+r[5]),4),4,0);
}
L432256: { // 57  push edi
push(get(7,4,0));
}
L432257: { // 57  push edi
push(get(7,4,0));
}
L432258: { // 6806040000  push 0x406
push(0x406u);
}
L43225d: { // 891d44947600  mov dword ptr [0x769444], ebx
write((0x769444u),get(3,4,0),4);
}
L432263: { // a33c947600  mov dword ptr [0x76943c], eax
write((0x76943cu),get(0,4,0),4);
}
L432268: { // 893d48947600  mov dword ptr [0x769448], edi
write((0x769448u),get(7,4,0),4);
}
L43226e: { // e89ceefcff  call 0x40110f
push(0x432273u);dispatch(0x40110fu);
}
L432273: { // 53  push ebx
push(get(3,4,0));
}
L432274: { // e832060000  call 0x4328ab
push(0x432279u);dispatch(0x4328abu);
}
L432279: { // 8b5d10  mov ebx, dword ptr [ebp + 0x10]
put(3,read((0x10u+r[5]),4),4,0);
}
L43227c: { // 3bdf  cmp ebx, edi
sub(get(3,4,0),get(7,4,0),4);
}
L43227e: { // 7d06  jge 0x432286
if(condition(3))goto L432286;
}
L432280: { // 8bc3  mov eax, ebx
put(0,get(3,4,0),4,0);
}
L432282: { // f7d8  neg eax
put(0,sub(0,get(0,4,0),4),4,0);
}
L432284: { // eb0b  jmp 0x432291
goto L432291;
}
L432286: { // 8d045b  lea eax, [ebx + ebx*2]
put(0,(0x0u+r[3]+r[3]*2u),4,0);
}
L432289: { // 6a64  push 0x64
push(0x64u);
}
L43228b: { // d1e0  shl eax, 1
put(0,shift(get(0,4,0),0x1u,4,0),4,0);
}
L43228d: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L43228e: { // 59  pop ecx
put(1,pop(),4,0);
}
L43228f: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L432291: { // 894510  mov dword ptr [ebp + 0x10], eax
write((0x10u+r[5]),get(0,4,0),4);
}
L432294: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L432297: { // 83f809  cmp eax, 9
sub(get(0,4,0),0x9u,4);
}
L43229a: { // 0f878a010000  ja 0x43242a
if(condition(9))goto L43242a;
}
L4322a0: { // ff24857e244300  jmp dword ptr [eax*4 + 0x43247e]
switch(read((0x43247eu+r[0]*4u),4)){case 0x4322a7u:goto L4322a7;case 0x432314u:goto L432314;case 0x432354u:goto L432354;case 0x4323aau:goto L4323aa;case 0x4323e4u:goto L4323e4;case 0x4323f4u:goto L4323f4;case 0x432404u:goto L432404;case 0x432414u:goto L432414;case 0x43244du:goto L43244d;default:throw Fault(0x4322a0u,"unresolved recovered battle jump");}
}
L4322a7: { // 397d0c  cmp dword ptr [ebp + 0xc], edi
sub(read((0xcu+r[5]),4),get(7,4,0),4);
}
L4322aa: { // 7416  je 0x4322c2
if(condition(0))goto L4322c2;
}
L4322ac: { // b800010000  mov eax, 0x100
put(0,0x100u,4,0);
}
L4322b1: { // 57  push edi
push(get(7,4,0));
}
L4322b2: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L4322b3: { // f77d10  idiv dword ptr [ebp + 0x10]
divide(read((0x10u+r[5]),4),true);
}
L4322b6: { // 50  push eax
push(get(0,4,0));
}
L4322b7: { // 57  push edi
push(get(7,4,0));
}
L4322b8: { // 6800204a00  push 0x4a2000
push(0x4a2000u);
}
L4322bd: { // e9da000000  jmp 0x43239c
goto L43239c;
}
L4322c2: { // 397d14  cmp dword ptr [ebp + 0x14], edi
sub(read((0x14u+r[5]),4),get(7,4,0),4);
}
L4322c5: { // 7523  jne 0x4322ea
if(condition(1))goto L4322ea;
}
L4322c7: { // 68b3000000  push 0xb3
push(0xb3u);
}
L4322cc: { // 6a5c  push 0x5c
push(0x5cu);
}
L4322ce: { // 56  push esi
push(get(6,4,0));
}
L4322cf: { // e89c510600  call 0x497470
push(0x4322d4u);dispatch(0x497470u);
}
L4322d4: { // 59  pop ecx
put(1,pop(),4,0);
}
L4322d5: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L4322d6: { // 59  pop ecx
put(1,pop(),4,0);
}
L4322d7: { // 50  push eax
push(get(0,4,0));
}
L4322d8: { // 6814b95a00  push 0x5ab914
push(0x5ab914u);
}
L4322dd: { // 685c604a00  push 0x4a605c
push(0x4a605cu);
}
L4322e2: { // e843f6fcff  call 0x40192a
push(0x4322e7u);dispatch(0x40192au);
}
L4322e7: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L4322ea: { // 8b4508  mov eax, dword ptr [ebp + 8]
put(0,read((0x8u+r[5]),4),4,0);
}
L4322ed: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L4322ee: { // 745e  je 0x43234e
if(condition(0))goto L43234e;
}
L4322f0: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L4322f1: { // 0f8496000000  je 0x43238d
if(condition(0))goto L43238d;
}
L4322f7: { // 68b5000000  push 0xb5
push(0xb5u);
}
L4322fc: { // 6a5c  push 0x5c
push(0x5cu);
}
L4322fe: { // 56  push esi
push(get(6,4,0));
}
L4322ff: { // e86c510600  call 0x497470
push(0x432304u);dispatch(0x497470u);
}
L432304: { // 59  pop ecx
put(1,pop(),4,0);
}
L432305: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L432306: { // 59  pop ecx
put(1,pop(),4,0);
}
L432307: { // 50  push eax
push(get(0,4,0));
}
L432308: { // 6874614a00  push 0x4a6174
push(0x4a6174u);
}
L43230d: { // 6854614a00  push 0x4a6154
push(0x4a6154u);
}
L432312: { // eb32  jmp 0x432346
goto L432346;
}
L432314: { // 397d0c  cmp dword ptr [ebp + 0xc], edi
sub(read((0xcu+r[5]),4),get(7,4,0),4);
}
L432317: { // 740d  je 0x432326
if(condition(0))goto L432326;
}
L432319: { // b800010000  mov eax, 0x100
put(0,0x100u,4,0);
}
L43231e: { // 57  push edi
push(get(7,4,0));
}
L43231f: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L432320: { // f77d10  idiv dword ptr [ebp + 0x10]
divide(read((0x10u+r[5]),4),true);
}
L432323: { // 50  push eax
push(get(0,4,0));
}
L432324: { // eb37  jmp 0x43235d
goto L43235d;
}
L432326: { // 397d14  cmp dword ptr [ebp + 0x14], edi
sub(read((0x14u+r[5]),4),get(7,4,0),4);
}
L432329: { // 7523  jne 0x43234e
if(condition(1))goto L43234e;
}
L43232b: { // 68be000000  push 0xbe
push(0xbeu);
}
L432330: { // 6a5c  push 0x5c
push(0x5cu);
}
L432332: { // 56  push esi
push(get(6,4,0));
}
L432333: { // e838510600  call 0x497470
push(0x432338u);dispatch(0x497470u);
}
L432338: { // 59  pop ecx
put(1,pop(),4,0);
}
L432339: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L43233a: { // 59  pop ecx
put(1,pop(),4,0);
}
L43233b: { // 50  push eax
push(get(0,4,0));
}
L43233c: { // 6814b95a00  push 0x5ab914
push(0x5ab914u);
}
L432341: { // 685c604a00  push 0x4a605c
push(0x4a605cu);
}
L432346: { // e8dff5fcff  call 0x40192a
push(0x43234bu);dispatch(0x40192au);
}
L43234b: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L43234e: { // ff7510  push dword ptr [ebp + 0x10]
push(read((0x10u+r[5]),4));
}
L432351: { // 57  push edi
push(get(7,4,0));
}
L432352: { // eb44  jmp 0x432398
goto L432398;
}
L432354: { // 397d0c  cmp dword ptr [ebp + 0xc], edi
sub(read((0xcu+r[5]),4),get(7,4,0),4);
}
L432357: { // 740c  je 0x432365
if(condition(0))goto L432365;
}
L432359: { // ff7510  push dword ptr [ebp + 0x10]
push(read((0x10u+r[5]),4));
}
L43235c: { // 57  push edi
push(get(7,4,0));
}
L43235d: { // 57  push edi
push(get(7,4,0));
}
L43235e: { // 68c8534a00  push 0x4a53c8
push(0x4a53c8u);
}
L432363: { // eb37  jmp 0x43239c
goto L43239c;
}
L432365: { // 397d14  cmp dword ptr [ebp + 0x14], edi
sub(read((0x14u+r[5]),4),get(7,4,0),4);
}
L432368: { // 7523  jne 0x43238d
if(condition(1))goto L43238d;
}
L43236a: { // 68c3000000  push 0xc3
push(0xc3u);
}
L43236f: { // 6a5c  push 0x5c
push(0x5cu);
}
L432371: { // 56  push esi
push(get(6,4,0));
}
L432372: { // e8f9500600  call 0x497470
push(0x432377u);dispatch(0x497470u);
}
L432377: { // 59  pop ecx
put(1,pop(),4,0);
}
L432378: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L432379: { // 59  pop ecx
put(1,pop(),4,0);
}
L43237a: { // 50  push eax
push(get(0,4,0));
}
L43237b: { // 6814b95a00  push 0x5ab914
push(0x5ab914u);
}
L432380: { // 685c604a00  push 0x4a605c
push(0x4a605cu);
}
L432385: { // e8a0f5fcff  call 0x40192a
push(0x43238au);dispatch(0x40192au);
}
L43238a: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L43238d: { // b800010000  mov eax, 0x100
put(0,0x100u,4,0);
}
L432392: { // 57  push edi
push(get(7,4,0));
}
L432393: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L432394: { // f77d10  idiv dword ptr [ebp + 0x10]
divide(read((0x10u+r[5]),4),true);
}
L432397: { // 50  push eax
push(get(0,4,0));
}
L432398: { // 57  push edi
push(get(7,4,0));
}
L432399: { // ff7514  push dword ptr [ebp + 0x14]
push(read((0x14u+r[5]),4));
}
L43239c: { // e8ca2ffdff  call 0x40536b
push(0x4323a1u);dispatch(0x40536bu);
}
L4323a1: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L4323a3: { // 5f  pop edi
put(7,pop(),4,0);
}
L4323a4: { // 5e  pop esi
put(6,pop(),4,0);
}
L4323a5: { // 5b  pop ebx
put(3,pop(),4,0);
}
L4323a6: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L4323a7: { // c21000  ret 0x10
pop();r[4]+=0x10u;return;
}
L4323aa: { // 8b4d14  mov ecx, dword ptr [ebp + 0x14]
put(1,read((0x14u+r[5]),4),4,0);
}
L4323ad: { // 3bcf  cmp ecx, edi
sub(get(1,4,0),get(7,4,0),4);
}
L4323af: { // 740a  je 0x4323bb
if(condition(0))goto L4323bb;
}
L4323b1: { // 8b01  mov eax, dword ptr [ecx]
put(0,read((0x0u+r[1]),4),4,0);
}
L4323b3: { // 8b4904  mov ecx, dword ptr [ecx + 4]
put(1,read((0x4u+r[1]),4),4,0);
}
L4323b6: { // 8945f0  mov dword ptr [ebp - 0x10], eax
write((0xfffffff0u+r[5]),get(0,4,0),4);
}
L4323b9: { // eb0e  jmp 0x4323c9
goto L4323c9;
}
L4323bb: { // a16c9e6d00  mov eax, dword ptr [0x6d9e6c]
put(0,read((0x6d9e6cu),4),4,0);
}
L4323c0: { // 8b0d789e6d00  mov ecx, dword ptr [0x6d9e78]
put(1,read((0x6d9e78u),4),4,0);
}
L4323c6: { // 8945f0  mov dword ptr [ebp - 0x10], eax
write((0xfffffff0u+r[5]),get(0,4,0),4);
}
L4323c9: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L4323ca: { // 57  push edi
push(get(7,4,0));
}
L4323cb: { // 8945f8  mov dword ptr [ebp - 8], eax
write((0xfffffff8u+r[5]),get(0,4,0),4);
}
L4323ce: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L4323d1: { // 53  push ebx
push(get(3,4,0));
}
L4323d2: { // 50  push eax
push(get(0,4,0));
}
L4323d3: { // ff750c  push dword ptr [ebp + 0xc]
push(read((0xcu+r[5]),4));
}
L4323d6: { // 894df4  mov dword ptr [ebp - 0xc], ecx
write((0xfffffff4u+r[5]),get(1,4,0),4);
}
L4323d9: { // 41  inc ecx
put(1,inc(get(1,4,0),4,1),4,0);
}
L4323da: { // 894dfc  mov dword ptr [ebp - 4], ecx
write((0xfffffffcu+r[5]),get(1,4,0),4);
}
L4323dd: { // e884f9fcff  call 0x401d66
push(0x4323e2u);dispatch(0x401d66u);
}
L4323e2: { // ebbd  jmp 0x4323a1
goto L4323a1;
}
L4323e4: { // 53  push ebx
push(get(3,4,0));
}
L4323e5: { // 68309d6d00  push 0x6d9d30
push(0x6d9d30u);
}
L4323ea: { // ff750c  push dword ptr [ebp + 0xc]
push(read((0xcu+r[5]),4));
}
L4323ed: { // e8b9fbfcff  call 0x401fab
push(0x4323f2u);dispatch(0x401fabu);
}
L4323f2: { // ebad  jmp 0x4323a1
goto L4323a1;
}
L4323f4: { // 53  push ebx
push(get(3,4,0));
}
L4323f5: { // 68309d6d00  push 0x6d9d30
push(0x6d9d30u);
}
L4323fa: { // ff750c  push dword ptr [ebp + 0xc]
push(read((0xcu+r[5]),4));
}
L4323fd: { // e86efcfcff  call 0x402070
push(0x432402u);dispatch(0x402070u);
}
L432402: { // eb9d  jmp 0x4323a1
goto L4323a1;
}
L432404: { // 53  push ebx
push(get(3,4,0));
}
L432405: { // 68309d6d00  push 0x6d9d30
push(0x6d9d30u);
}
L43240a: { // ff750c  push dword ptr [ebp + 0xc]
push(read((0xcu+r[5]),4));
}
L43240d: { // e84cfefcff  call 0x40225e
push(0x432412u);dispatch(0x40225eu);
}
L432412: { // eb8d  jmp 0x4323a1
goto L4323a1;
}
L432414: { // ff7514  push dword ptr [ebp + 0x14]
push(read((0x14u+r[5]),4));
}
L432417: { // 53  push ebx
push(get(3,4,0));
}
L432418: { // 68309d6d00  push 0x6d9d30
push(0x6d9d30u);
}
L43241d: { // ff750c  push dword ptr [ebp + 0xc]
push(read((0xcu+r[5]),4));
}
L432420: { // e8d2fffcff  call 0x4023f7
push(0x432425u);dispatch(0x4023f7u);
}
L432425: { // e977ffffff  jmp 0x4323a1
goto L4323a1;
}
L43242a: { // 68a2000000  push 0xa2
push(0xa2u);
}
L43242f: { // 6a5c  push 0x5c
push(0x5cu);
}
L432431: { // 56  push esi
push(get(6,4,0));
}
L432432: { // e839500600  call 0x497470
push(0x432437u);dispatch(0x497470u);
}
L432437: { // 59  pop ecx
put(1,pop(),4,0);
}
L432438: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L432439: { // 59  pop ecx
put(1,pop(),4,0);
}
L43243a: { // 50  push eax
push(get(0,4,0));
}
L43243b: { // 6874614a00  push 0x4a6174
push(0x4a6174u);
}
L432440: { // 6854614a00  push 0x4a6154
push(0x4a6154u);
}
L432445: { // e8e0f4fcff  call 0x40192a
push(0x43244au);dispatch(0x40192au);
}
L43244a: { // 83c410  add esp, 0x10
put(4,add(get(4,4,0),0x10u,4,false),4,0);
}
L43244d: { // 397d0c  cmp dword ptr [ebp + 0xc], edi
sub(read((0xcu+r[5]),4),get(7,4,0),4);
}
L432450: { // 0f854bffffff  jne 0x4323a1
if(condition(1))goto L4323a1;
}
L432456: { // 6800010000  push 0x100
push(0x100u);
}
L43245b: { // 57  push edi
push(get(7,4,0));
}
L43245c: { // ff7514  push dword ptr [ebp + 0x14]
push(read((0x14u+r[5]),4));
}
L43245f: { // e84c27fdff  call 0x404bb0
push(0x432464u);dispatch(0x404bb0u);
}
L432464: { // 57  push edi
push(get(7,4,0));
}
L432465: { // 893d44947600  mov dword ptr [0x769444], edi
write((0x769444u),get(7,4,0),4);
}
L43246b: { // e82645fdff  call 0x406996
push(0x432470u);dispatch(0x406996u);
}
L432470: { // 6a01  push 1
push(0x1u);
}
L432472: { // 893d6c4a8000  mov dword ptr [0x804a6c], edi
write((0x804a6cu),get(7,4,0),4);
}
L432478: { // 58  pop eax
put(0,pop(),4,0);
}
L432479: { // e925ffffff  jmp 0x4323a3
goto L4323a3;
}
}
// 004325b4_debug_osd_message_show_mc_4325b4
void RecoveredBattle::fn_4325b4(){
goto L4325b4;
L4325b4: { // 55  push ebp
push(get(5,4,0));
}
L4325b5: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L4325b7: { // 81ec9c000000  sub esp, 0x9c
put(4,sub(get(4,4,0),0x9cu,4,false),4,0);
}
L4325bd: { // 53  push ebx
push(get(3,4,0));
}
L4325be: { // 56  push esi
push(get(6,4,0));
}
L4325bf: { // 57  push edi
push(get(7,4,0));
}
L4325c0: { // 8d8564ffffff  lea eax, [ebp - 0x9c]
put(0,(0xffffff64u+r[5]),4,0);
}
L4325c6: { // ff7508  push dword ptr [ebp + 8]
push(read((0x8u+r[5]),4));
}
L4325c9: { // 6844b95a00  push 0x5ab944
push(0x5ab944u);
}
L4325ce: { // 50  push eax
push(get(0,4,0));
}
L4325cf: { // ff15c0948500  call dword ptr [0x8594c0]
push(0x4325d5u);dispatch(0x8594c0u);
}
L4325d5: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L4325d8: { // ff3530947600  push dword ptr [0x769430]
push(read((0x769430u),4));
}
L4325de: { // e8b000fdff  call 0x402693
push(0x4325e3u);dispatch(0x402693u);
}
L4325e3: { // 33f6  xor esi, esi
put(6,logic(get(6,4,0)^get(6,4,0),4),4,0);
}
L4325e5: { // 3bc6  cmp eax, esi
sub(get(0,4,0),get(6,4,0),4);
}
L4325e7: { // 7404  je 0x4325ed
if(condition(0))goto L4325ed;
}
L4325e9: { // 834820ff  or dword ptr [eax + 0x20], 0xffffffff
write((0x20u+r[0]),logic(read((0x20u+r[0]),4)|0xffffffffu,4),4);
}
L4325ed: { // 8d8564ffffff  lea eax, [ebp - 0x9c]
put(0,(0xffffff64u+r[5]),4,0);
}
L4325f3: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L4325f5: { // 0f8440010000  je 0x43273b
if(condition(0))goto L43273b;
}
L4325fb: { // 80bd64ffffff00  cmp byte ptr [ebp - 0x9c], 0
sub(read((0xffffff64u+r[5]),1),0x0u,1);
}
L432602: { // 0f8433010000  je 0x43273b
if(condition(0))goto L43273b;
}
L432608: { // 56  push esi
push(get(6,4,0));
}
L432609: { // 56  push esi
push(get(6,4,0));
}
L43260a: { // 6842274300  push 0x432742
push(0x432742u);
}
L43260f: { // ff35385a6d00  push dword ptr [0x6d5a38]
push(read((0x6d5a38u),4));
}
L432615: { // e86001fdff  call 0x40277a
push(0x43261au);dispatch(0x40277au);
}
L43261a: { // 50  push eax
push(get(0,4,0));
}
L43261b: { // 8945e4  mov dword ptr [ebp - 0x1c], eax
write((0xffffffe4u+r[5]),get(0,4,0),4);
}
L43261e: { // e89e00fdff  call 0x4026c1
push(0x432623u);dispatch(0x4026c1u);
}
L432623: { // 8bd8  mov ebx, eax
put(3,get(0,4,0),4,0);
}
L432625: { // 8d8564ffffff  lea eax, [ebp - 0x9c]
put(0,(0xffffff64u+r[5]),4,0);
}
L43262b: { // 50  push eax
push(get(0,4,0));
}
L43262c: { // e8bf4d0600  call 0x4973f0
push(0x432631u);dispatch(0x4973f0u);
}
L432631: { // c1e003  shl eax, 3
put(0,shift(get(0,4,0),0x3u,4,0),4,0);
}
L432634: { // 8975e8  mov dword ptr [ebp - 0x18], esi
write((0xffffffe8u+r[5]),get(6,4,0),4);
}
L432637: { // 8975ec  mov dword ptr [ebp - 0x14], esi
write((0xffffffecu+r[5]),get(6,4,0),4);
}
L43263a: { // 8dbb8c010000  lea edi, [ebx + 0x18c]
put(7,(0x18cu+r[3]),4,0);
}
L432640: { // 8d75e8  lea esi, [ebp - 0x18]
put(6,(0xffffffe8u+r[5]),4,0);
}
L432643: { // 8945f0  mov dword ptr [ebp - 0x10], eax
write((0xfffffff0u+r[5]),get(0,4,0),4);
}
L432646: { // c745f410000000  mov dword ptr [ebp - 0xc], 0x10
write((0xfffffff4u+r[5]),0x10u,4);
}
L43264d: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L43264e: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L43264f: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L432650: { // 59  pop ecx
put(1,pop(),4,0);
}
L432651: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L432652: { // ffb398010000  push dword ptr [ebx + 0x198]
push(read((0x198u+r[3]),4));
}
L432658: { // ffb394010000  push dword ptr [ebx + 0x194]
push(read((0x194u+r[3]),4));
}
L43265e: { // e82139fdff  call 0x405f84
push(0x432663u);dispatch(0x405f84u);
}
L432663: { // 6a00  push 0
push(0x0u);
}
L432665: { // 6a00  push 0
push(0x0u);
}
L432667: { // 50  push eax
push(get(0,4,0));
}
L432668: { // 898388010000  mov dword ptr [ebx + 0x188], eax
write((0x188u+r[3]),get(0,4,0),4);
}
L43266e: { // e81936fdff  call 0x405c8c
push(0x432673u);dispatch(0x405c8cu);
}
L432673: { // ffb388010000  push dword ptr [ebx + 0x188]
push(read((0x188u+r[3]),4));
}
L432679: { // e88335fdff  call 0x405c01
push(0x43267eu);dispatch(0x405c01u);
}
L43267e: { // 8945f8  mov dword ptr [ebp - 8], eax
write((0xfffffff8u+r[5]),get(0,4,0),4);
}
L432681: { // c745fc02000000  mov dword ptr [ebp - 4], 2
write((0xfffffffcu+r[5]),0x2u,4);
}
L432688: { // c7450802000000  mov dword ptr [ebp + 8], 2
write((0x8u+r[5]),0x2u,4);
}
L43268f: { // 8db38c010000  lea esi, [ebx + 0x18c]
put(6,(0x18cu+r[3]),4,0);
}
L432695: { // 8d7de8  lea edi, [ebp - 0x18]
put(7,(0xffffffe8u+r[5]),4,0);
}
L432698: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L432699: { // ff75fc  push dword ptr [ebp - 4]
push(read((0xfffffffcu+r[5]),4));
}
L43269c: { // 8d45e8  lea eax, [ebp - 0x18]
put(0,(0xffffffe8u+r[5]),4,0);
}
L43269f: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4326a0: { // ff7508  push dword ptr [ebp + 8]
push(read((0x8u+r[5]),4));
}
L4326a3: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4326a4: { // 50  push eax
push(get(0,4,0));
}
L4326a5: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4326a6: { // ff15a8948500  call dword ptr [0x8594a8]
push(0x4326acu);dispatch(0x8594a8u);
}
L4326ac: { // 837d0801  cmp dword ptr [ebp + 8], 1
sub(read((0x8u+r[5]),4),0x1u,4);
}
L4326b0: { // 7506  jne 0x4326b8
if(condition(1))goto L4326b8;
}
L4326b2: { // 837dfc01  cmp dword ptr [ebp - 4], 1
sub(read((0xfffffffcu+r[5]),4),0x1u,4);
}
L4326b6: { // 7424  je 0x4326dc
if(condition(0))goto L4326dc;
}
L4326b8: { // 8d8564ffffff  lea eax, [ebp - 0x9c]
put(0,(0xffffff64u+r[5]),4,0);
}
L4326be: { // 50  push eax
push(get(0,4,0));
}
L4326bf: { // 8d45e8  lea eax, [ebp - 0x18]
put(0,(0xffffffe8u+r[5]),4,0);
}
L4326c2: { // 6824010000  push 0x124
push(0x124u);
}
L4326c7: { // 50  push eax
push(get(0,4,0));
}
L4326c8: { // 6a09  push 9
push(0x9u);
}
L4326ca: { // 6aff  push -1
push(0xffffffffu);
}
L4326cc: { // 68d7000001  push 0x10000d7
push(0x10000d7u);
}
L4326d1: { // ff75f8  push dword ptr [ebp - 8]
push(read((0xfffffff8u+r[5]),4));
}
L4326d4: { // e84840fdff  call 0x406721
push(0x4326d9u);dispatch(0x406721u);
}
L4326d9: { // 83c41c  add esp, 0x1c
put(4,add(get(4,4,0),0x1cu,4,false),4,0);
}
L4326dc: { // ff4d08  dec dword ptr [ebp + 8]
write((0x8u+r[5]),inc(read((0x8u+r[5]),4),4,-1),4);
}
L4326df: { // 79ae  jns 0x43268f
if(condition(11))goto L43268f;
}
L4326e1: { // ff4dfc  dec dword ptr [ebp - 4]
write((0xfffffffcu+r[5]),inc(read((0xfffffffcu+r[5]),4),4,-1),4);
}
L4326e4: { // 79a2  jns 0x432688
if(condition(11))goto L432688;
}
L4326e6: { // 8db38c010000  lea esi, [ebx + 0x18c]
put(6,(0x18cu+r[3]),4,0);
}
L4326ec: { // 8d7de8  lea edi, [ebp - 0x18]
put(7,(0xffffffe8u+r[5]),4,0);
}
L4326ef: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4326f0: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4326f1: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4326f2: { // 6a01  push 1
push(0x1u);
}
L4326f4: { // 8d45e8  lea eax, [ebp - 0x18]
put(0,(0xffffffe8u+r[5]),4,0);
}
L4326f7: { // 6a01  push 1
push(0x1u);
}
L4326f9: { // 50  push eax
push(get(0,4,0));
}
L4326fa: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L4326fb: { // ff15a8948500  call dword ptr [0x8594a8]
push(0x432701u);dispatch(0x8594a8u);
}
L432701: { // 8d8564ffffff  lea eax, [ebp - 0x9c]
put(0,(0xffffff64u+r[5]),4,0);
}
L432707: { // 50  push eax
push(get(0,4,0));
}
L432708: { // 8d45e8  lea eax, [ebp - 0x18]
put(0,(0xffffffe8u+r[5]),4,0);
}
L43270b: { // 6824010000  push 0x124
push(0x124u);
}
L432710: { // 50  push eax
push(get(0,4,0));
}
L432711: { // 6a09  push 9
push(0x9u);
}
L432713: { // 6aff  push -1
push(0xffffffffu);
}
L432715: { // 68b2000001  push 0x10000b2
push(0x10000b2u);
}
L43271a: { // ff75f8  push dword ptr [ebp - 8]
push(read((0xfffffff8u+r[5]),4));
}
L43271d: { // e8ff3ffdff  call 0x406721
push(0x432722u);dispatch(0x406721u);
}
L432722: { // 83c41c  add esp, 0x1c
put(4,add(get(4,4,0),0x1cu,4,false),4,0);
}
L432725: { // ff75f8  push dword ptr [ebp - 8]
push(read((0xfffffff8u+r[5]),4));
}
L432728: { // ffb388010000  push dword ptr [ebx + 0x188]
push(read((0x188u+r[3]),4));
}
L43272e: { // e8ed34fdff  call 0x405c20
push(0x432733u);dispatch(0x405c20u);
}
L432733: { // 8b45e4  mov eax, dword ptr [ebp - 0x1c]
put(0,read((0xffffffe4u+r[5]),4),4,0);
}
L432736: { // a330947600  mov dword ptr [0x769430], eax
write((0x769430u),get(0,4,0),4);
}
L43273b: { // 5f  pop edi
put(7,pop(),4,0);
}
L43273c: { // 5e  pop esi
put(6,pop(),4,0);
}
L43273d: { // 5b  pop ebx
put(3,pop(),4,0);
}
L43273e: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L43273f: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00432742_debug_osd_message_tick_mc_432742
void RecoveredBattle::fn_432742(){
goto L432742;
L432742: { // 55  push ebp
push(get(5,4,0));
}
L432743: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L432745: { // 83ec10  sub esp, 0x10
put(4,sub(get(4,4,0),0x10u,4,false),4,0);
}
L432748: { // 53  push ebx
push(get(3,4,0));
}
L432749: { // 8b5d08  mov ebx, dword ptr [ebp + 8]
put(3,read((0x8u+r[5]),4),4,0);
}
L43274c: { // 56  push esi
push(get(6,4,0));
}
L43274d: { // 57  push edi
push(get(7,4,0));
}
L43274e: { // 33d2  xor edx, edx
put(2,logic(get(2,4,0)^get(2,4,0),4),4,0);
}
L432750: { // 6a04  push 4
push(0x4u);
}
L432752: { // 39151cfd5700  cmp dword ptr [0x57fd1c], edx
sub(read((0x57fd1cu),4),get(2,4,0),4);
}
L432758: { // 59  pop ecx
put(1,pop(),4,0);
}
L432759: { // 7c1d  jl 0x432778
if(condition(2))goto L432778;
}
L43275b: { // 8b4320  mov eax, dword ptr [ebx + 0x20]
put(0,read((0x20u+r[3]),4),4,0);
}
L43275e: { // 3bc1  cmp eax, ecx
sub(get(0,4,0),get(1,4,0),4);
}
L432760: { // 7416  je 0x432778
if(condition(0))goto L432778;
}
L432762: { // 83f801  cmp eax, 1
sub(get(0,4,0),0x1u,4);
}
L432765: { // 750b  jne 0x432772
if(condition(1))goto L432772;
}
L432767: { // 6a14  push 0x14
push(0x14u);
}
L432769: { // 58  pop eax
put(0,pop(),4,0);
}
L43276a: { // 2b432c  sub eax, dword ptr [ebx + 0x2c]
put(0,sub(get(0,4,0),read((0x2cu+r[3]),4),4,false),4,0);
}
L43276d: { // 89432c  mov dword ptr [ebx + 0x2c], eax
write((0x2cu+r[3]),get(0,4,0),4);
}
L432770: { // eb03  jmp 0x432775
goto L432775;
}
L432772: { // 89532c  mov dword ptr [ebx + 0x2c], edx
write((0x2cu+r[3]),get(2,4,0),4);
}
L432775: { // 894b20  mov dword ptr [ebx + 0x20], ecx
write((0x20u+r[3]),get(1,4,0),4);
}
L432778: { // a140504a00  mov eax, dword ptr [0x4a5040]
put(0,read((0x4a5040u),4),4,0);
}
L43277d: { // 3bc2  cmp eax, edx
sub(get(0,4,0),get(2,4,0),4);
}
L43277f: { // 7406  je 0x432787
if(condition(0))goto L432787;
}
L432781: { // ff432c  inc dword ptr [ebx + 0x2c]
write((0x2cu+r[3]),inc(read((0x2cu+r[3]),4),4,1),4);
}
L432784: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L432785: { // 75fa  jne 0x432781
if(condition(1))goto L432781;
}
L432787: { // 8db38c010000  lea esi, [ebx + 0x18c]
put(6,(0x18cu+r[3]),4,0);
}
L43278d: { // 8d7df0  lea edi, [ebp - 0x10]
put(7,(0xfffffff0u+r[5]),4,0);
}
L432790: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L432791: { // 8b4320  mov eax, dword ptr [ebx + 0x20]
put(0,read((0x20u+r[3]),4),4,0);
}
L432794: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L432795: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L432796: { // 83f8ff  cmp eax, -1
sub(get(0,4,0),0xffffffffu,4);
}
L432799: { // a5  movsd dword ptr es:[edi], dword ptr [esi]
write(r[7],read(r[6],4),4);r[6]+=4;r[7]+=4;
}
L43279a: { // 0f84a2000000  je 0x432842
if(condition(0))goto L432842;
}
L4327a0: { // 3bc2  cmp eax, edx
sub(get(0,4,0),get(2,4,0),4);
}
L4327a2: { // 741b  je 0x4327bf
if(condition(0))goto L4327bf;
}
L4327a4: { // 83f801  cmp eax, 1
sub(get(0,4,0),0x1u,4);
}
L4327a7: { // 741d  je 0x4327c6
if(condition(0))goto L4327c6;
}
L4327a9: { // 83f802  cmp eax, 2
sub(get(0,4,0),0x2u,4);
}
L4327ac: { // 742a  je 0x4327d8
if(condition(0))goto L4327d8;
}
L4327ae: { // 83f803  cmp eax, 3
sub(get(0,4,0),0x3u,4);
}
L4327b1: { // 7435  je 0x4327e8
if(condition(0))goto L4327e8;
}
L4327b3: { // 3bc1  cmp eax, ecx
sub(get(0,4,0),get(1,4,0),4);
}
L4327b5: { // 7477  je 0x43282e
if(condition(0))goto L43282e;
}
L4327b7: { // 8b5508  mov edx, dword ptr [ebp + 8]
put(2,read((0x8u+r[5]),4),4,0);
}
L4327ba: { // e9bf000000  jmp 0x43287e
goto L43287e;
}
L4327bf: { // c7432001000000  mov dword ptr [ebx + 0x20], 1
write((0x20u+r[3]),0x1u,4);
}
L4327c6: { // 8b432c  mov eax, dword ptr [ebx + 0x2c]
put(0,read((0x2cu+r[3]),4),4,0);
}
L4327c9: { // 83f814  cmp eax, 0x14
sub(get(0,4,0),0x14u,4);
}
L4327cc: { // 0f8c9e000000  jl 0x432870
if(condition(2))goto L432870;
}
L4327d2: { // ff4320  inc dword ptr [ebx + 0x20]
write((0x20u+r[3]),inc(read((0x20u+r[3]),4),4,1),4);
}
L4327d5: { // 89532c  mov dword ptr [ebx + 0x2c], edx
write((0x2cu+r[3]),get(2,4,0),4);
}
L4327d8: { // 837b2c28  cmp dword ptr [ebx + 0x2c], 0x28
sub(read((0x2cu+r[3]),4),0x28u,4);
}
L4327dc: { // 0f8c89000000  jl 0x43286b
if(condition(2))goto L43286b;
}
L4327e2: { // ff4320  inc dword ptr [ebx + 0x20]
write((0x20u+r[3]),inc(read((0x20u+r[3]),4),4,1),4);
}
L4327e5: { // 89532c  mov dword ptr [ebx + 0x2c], edx
write((0x2cu+r[3]),get(2,4,0),4);
}
L4327e8: { // 391588a86d00  cmp dword ptr [0x6da888], edx
sub(read((0x6da888u),4),get(2,4,0),4);
}
L4327ee: { // 7538  jne 0x432828
if(condition(1))goto L432828;
}
L4327f0: { // 3915a8a86d00  cmp dword ptr [0x6da8a8], edx
sub(read((0x6da8a8u),4),get(2,4,0),4);
}
L4327f6: { // 7530  jne 0x432828
if(condition(1))goto L432828;
}
L4327f8: { // 391594a86d00  cmp dword ptr [0x6da894], edx
sub(read((0x6da894u),4),get(2,4,0),4);
}
L4327fe: { // 7528  jne 0x432828
if(condition(1))goto L432828;
}
L432800: { // 39159ca86d00  cmp dword ptr [0x6da89c], edx
sub(read((0x6da89cu),4),get(2,4,0),4);
}
L432806: { // 7520  jne 0x432828
if(condition(1))goto L432828;
}
L432808: { // 391588a66d00  cmp dword ptr [0x6da688], edx
sub(read((0x6da688u),4),get(2,4,0),4);
}
L43280e: { // 7518  jne 0x432828
if(condition(1))goto L432828;
}
L432810: { // 3915a8a66d00  cmp dword ptr [0x6da6a8], edx
sub(read((0x6da6a8u),4),get(2,4,0),4);
}
L432816: { // 7510  jne 0x432828
if(condition(1))goto L432828;
}
L432818: { // 391594a66d00  cmp dword ptr [0x6da694], edx
sub(read((0x6da694u),4),get(2,4,0),4);
}
L43281e: { // 7508  jne 0x432828
if(condition(1))goto L432828;
}
L432820: { // 39159ca66d00  cmp dword ptr [0x6da69c], edx
sub(read((0x6da69cu),4),get(2,4,0),4);
}
L432826: { // 7443  je 0x43286b
if(condition(0))goto L43286b;
}
L432828: { // ff4320  inc dword ptr [ebx + 0x20]
write((0x20u+r[3]),inc(read((0x20u+r[3]),4),4,1),4);
}
L43282b: { // 89532c  mov dword ptr [ebx + 0x2c], edx
write((0x2cu+r[3]),get(2,4,0),4);
}
L43282e: { // 8b432c  mov eax, dword ptr [ebx + 0x2c]
put(0,read((0x2cu+r[3]),4),4,0);
}
L432831: { // 83f814  cmp eax, 0x14
sub(get(0,4,0),0x14u,4);
}
L432834: { // 7c25  jl 0x43285b
if(condition(2))goto L43285b;
}
L432836: { // ff4320  inc dword ptr [ebx + 0x20]
write((0x20u+r[3]),inc(read((0x20u+r[3]),4),4,1),4);
}
L432839: { // 89532c  mov dword ptr [ebx + 0x2c], edx
write((0x2cu+r[3]),get(2,4,0),4);
}
L43283c: { // 891530947600  mov dword ptr [0x769430], edx
write((0x769430u),get(2,4,0),4);
}
L432842: { // 8d8388010000  lea eax, [ebx + 0x188]
put(0,(0x188u+r[3]),4,0);
}
L432848: { // 6a01  push 1
push(0x1u);
}
L43284a: { // 50  push eax
push(get(0,4,0));
}
L43284b: { // e8c237fdff  call 0x406012
push(0x432850u);dispatch(0x406012u);
}
L432850: { // 83632000  and dword ptr [ebx + 0x20], 0
write((0x20u+r[3]),logic(read((0x20u+r[3]),4)&0x0u,4),4);
}
L432854: { // 5f  pop edi
put(7,pop(),4,0);
}
L432855: { // 5e  pop esi
put(6,pop(),4,0);
}
L432856: { // 5b  pop ebx
put(3,pop(),4,0);
}
L432857: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L432858: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
L43285b: { // c1e004  shl eax, 4
put(0,shift(get(0,4,0),0x4u,4,0),4,0);
}
L43285e: { // 6a14  push 0x14
push(0x14u);
}
L432860: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L432861: { // 59  pop ecx
put(1,pop(),4,0);
}
L432862: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L432864: { // 6a10  push 0x10
push(0x10u);
}
L432866: { // 5a  pop edx
put(2,pop(),4,0);
}
L432867: { // 2bd0  sub edx, eax
put(2,sub(get(2,4,0),get(0,4,0),4,false),4,0);
}
L432869: { // eb10  jmp 0x43287b
goto L43287b;
}
L43286b: { // 6a10  push 0x10
push(0x10u);
}
L43286d: { // 5a  pop edx
put(2,pop(),4,0);
}
L43286e: { // eb0e  jmp 0x43287e
goto L43287e;
}
L432870: { // c1e004  shl eax, 4
put(0,shift(get(0,4,0),0x4u,4,0),4,0);
}
L432873: { // 6a14  push 0x14
push(0x14u);
}
L432875: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L432876: { // 59  pop ecx
put(1,pop(),4,0);
}
L432877: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L432879: { // 8bd0  mov edx, eax
put(2,get(0,4,0),4,0);
}
L43287b: { // 8955fc  mov dword ptr [ebp - 4], edx
write((0xfffffffcu+r[5]),get(2,4,0),4);
}
L43287e: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L432881: { // 6a01  push 1
push(0x1u);
}
L432883: { // 50  push eax
push(get(0,4,0));
}
L432884: { // a1c0b67400  mov eax, dword ptr [0x74b6c0]
put(0,read((0x74b6c0u),4),4,0);
}
L432889: { // ffb388010000  push dword ptr [ebx + 0x188]
push(read((0x188u+r[3]),4));
}
L43288f: { // 2bc2  sub eax, edx
put(0,sub(get(0,4,0),get(2,4,0),4,false),4,0);
}
L432891: { // 83e803  sub eax, 3
put(0,sub(get(0,4,0),0x3u,4,false),4,0);
}
L432894: { // 50  push eax
push(get(0,4,0));
}
L432895: { // a168146e00  mov eax, dword ptr [0x6e1468]
put(0,read((0x6e1468u),4),4,0);
}
L43289a: { // 83c003  add eax, 3
put(0,add(get(0,4,0),0x3u,4,false),4,0);
}
L43289d: { // 50  push eax
push(get(0,4,0));
}
L43289e: { // ff356cb16d00  push dword ptr [0x6db16c]
push(read((0x6db16cu),4));
}
L4328a4: { // e80a35fdff  call 0x405db3
push(0x4328a9u);dispatch(0x405db3u);
}
L4328a9: { // eba9  jmp 0x432854
goto L432854;
}
}
// 004328ab_event_map_transition_state_reset_4328ab
void RecoveredBattle::fn_4328ab(){
goto L4328ab;
L4328ab: { // 837c240400  cmp dword ptr [esp + 4], 0
sub(read((0x4u+r[4]),4),0x0u,4);
}
L4328b0: { // 740c  je 0x4328be
if(condition(0))goto L4328be;
}
L4328b2: { // 6830947600  push 0x769430
push(0x769430u);
}
L4328b7: { // e89efefcff  call 0x40275a
push(0x4328bcu);dispatch(0x40275au);
}
L4328bc: { // eb30  jmp 0x4328ee
goto L4328ee;
}
L4328be: { // ff3530947600  push dword ptr [0x769430]
push(read((0x769430u),4));
}
L4328c4: { // e8cafdfcff  call 0x402693
push(0x4328c9u);dispatch(0x402693u);
}
L4328c9: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L4328cb: { // 7421  je 0x4328ee
if(condition(0))goto L4328ee;
}
L4328cd: { // 8b4820  mov ecx, dword ptr [eax + 0x20]
put(1,read((0x20u+r[0]),4),4,0);
}
L4328d0: { // 6a04  push 4
push(0x4u);
}
L4328d2: { // 5a  pop edx
put(2,pop(),4,0);
}
L4328d3: { // 3bca  cmp ecx, edx
sub(get(1,4,0),get(2,4,0),4);
}
L4328d5: { // 7417  je 0x4328ee
if(condition(0))goto L4328ee;
}
L4328d7: { // 83f901  cmp ecx, 1
sub(get(1,4,0),0x1u,4);
}
L4328da: { // 750b  jne 0x4328e7
if(condition(1))goto L4328e7;
}
L4328dc: { // 6a14  push 0x14
push(0x14u);
}
L4328de: { // 59  pop ecx
put(1,pop(),4,0);
}
L4328df: { // 2b482c  sub ecx, dword ptr [eax + 0x2c]
put(1,sub(get(1,4,0),read((0x2cu+r[0]),4),4,false),4,0);
}
L4328e2: { // 89482c  mov dword ptr [eax + 0x2c], ecx
write((0x2cu+r[0]),get(1,4,0),4);
}
L4328e5: { // eb04  jmp 0x4328eb
goto L4328eb;
}
L4328e7: { // 83602c00  and dword ptr [eax + 0x2c], 0
write((0x2cu+r[0]),logic(read((0x2cu+r[0]),4)&0x0u,4),4);
}
L4328eb: { // 895020  mov dword ptr [eax + 0x20], edx
write((0x20u+r[0]),get(2,4,0),4);
}
L4328ee: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00431f77_cleanup_rect_effect_state_mc_431f77
void RecoveredBattle::fn_431f77(){
goto L431f77;
L431f77: { // 6800b95a00  push 0x5ab900
push(0x5ab900u);
}
L431f7c: { // e801fbfcff  call 0x401a82
push(0x431f81u);dispatch(0x401a82u);
}
L431f81: { // 59  pop ecx
put(1,pop(),4,0);
}
L431f82: { // 33c0  xor eax, eax
put(0,logic(get(0,4,0)^get(0,4,0),4),4,0);
}
L431f84: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 0043217c_event_dialog_viewport_pair_apply_43217c
void RecoveredBattle::fn_43217c(){
goto L43217c;
L43217c: { // 55  push ebp
push(get(5,4,0));
}
L43217d: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L43217f: { // 837d1000  cmp dword ptr [ebp + 0x10], 0
sub(read((0x10u+r[5]),4),0x0u,4);
}
L432183: { // 6a01  push 1
push(0x1u);
}
L432185: { // 6a01  push 1
push(0x1u);
}
L432187: { // ff750c  push dword ptr [ebp + 0xc]
push(read((0xcu+r[5]),4));
}
L43218a: { // ff7508  push dword ptr [ebp + 8]
push(read((0x8u+r[5]),4));
}
L43218d: { // 7407  je 0x432196
if(condition(0))goto L432196;
}
L43218f: { // e84e4bfdff  call 0x406ce2
push(0x432194u);dispatch(0x406ce2u);
}
L432194: { // eb07  jmp 0x43219d
goto L43219d;
}
L432196: { // 6a1e  push 0x1e
push(0x1eu);
}
L432198: { // e8fb4bfdff  call 0x406d98
push(0x43219du);dispatch(0x406d98u);
}
L43219d: { // c7054094760002000000  mov dword ptr [0x769440], 2
write((0x769440u),0x2u,4);
}
L4321a7: { // 5d  pop ebp
put(5,pop(),4,0);
}
L4321a8: { // c20c00  ret 0xc
pop();r[4]+=0xcu;return;
}
}
} // namespace fsb::core
