// Generated by tools/translate_battle.py; edit the generator, not this file.
// Original EXE SHA256: 710881d024ab1fcf738b342c248631363c9de3a51b32a7e3d61781b791eff454
#include "fsb_core/recovered_battle.hpp"
#include <cstring>
#include <cmath>
namespace fsb::core {
// 004385e9_title_menu_state_machine_mc_4385e9
void RecoveredBattle::fn_4385e9(){
goto L4385e9;
L4385e9: { // a1441b7700  mov eax, dword ptr [0x771b44]
put(0,read((0x771b44u),4),4,0);
}
L4385ee: { // 53  push ebx
push(get(3,4,0));
}
L4385ef: { // 55  push ebp
push(get(5,4,0));
}
L4385f0: { // 56  push esi
push(get(6,4,0));
}
L4385f1: { // 57  push edi
push(get(7,4,0));
}
L4385f2: { // 33ff  xor edi, edi
put(7,logic(get(7,4,0)^get(7,4,0),4),4,0);
}
L4385f4: { // 2bc7  sub eax, edi
put(0,sub(get(0,4,0),get(7,4,0),4,false),4,0);
}
L4385f6: { // 0f84f6010000  je 0x4387f2
if(condition(0))goto L4387f2;
}
L4385fc: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L4385fd: { // 0f84d7010000  je 0x4387da
if(condition(0))goto L4387da;
}
L438603: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L438604: { // 0f84da000000  je 0x4386e4
if(condition(0))goto L4386e4;
}
L43860a: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L43860b: { // 0f8499000000  je 0x4386aa
if(condition(0))goto L4386aa;
}
L438611: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L438612: { // 747a  je 0x43868e
if(condition(0))goto L43868e;
}
L438614: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L438615: { // 7442  je 0x438659
if(condition(0))goto L438659;
}
L438617: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L438618: { // 7410  je 0x43862a
if(condition(0))goto L43862a;
}
L43861a: { // 6808155b00  push 0x5b1508
push(0x5b1508u);
}
L43861f: { // e8b494fcff  call 0x401ad8
push(0x438624u);dispatch(0x401ad8u);
}
L438624: { // 59  pop ecx
put(1,pop(),4,0);
}
L438625: { // e901020000  jmp 0x43882b
goto L43882b;
}
L43862a: { // e843cffcff  call 0x405572
push(0x43862fu);dispatch(0x405572u);
}
L43862f: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L438631: { // 0f85f4010000  jne 0x43882b
if(condition(1))goto L43882b;
}
L438637: { // e84cb1ffff  call 0x433788
push(0x43863cu);dispatch(0x433788u);
}
L43863c: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L43863e: { // 0f85e7010000  jne 0x43882b
if(condition(1))goto L43882b;
}
L438644: { // 57  push edi
push(get(7,4,0));
}
L438645: { // e872d6fcff  call 0x405cbc
push(0x43864au);dispatch(0x405cbcu);
}
L43864a: { // c705441b770001000000  mov dword ptr [0x771b44], 1
write((0x771b44u),0x1u,4);
}
L438654: { // e9d2010000  jmp 0x43882b
goto L43882b;
}
L438659: { // 6800040000  push 0x400
push(0x400u);
}
L43865e: { // be581b7700  mov esi, 0x771b58
put(6,0x771b58u,4,0);
}
L438663: { // 57  push edi
push(get(7,4,0));
}
L438664: { // 56  push esi
push(get(6,4,0));
}
L438665: { // e806f70500  call 0x497d70
push(0x43866au);dispatch(0x497d70u);
}
L43866a: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L43866d: { // 6a1e  push 0x1e
push(0x1eu);
}
L43866f: { // 57  push edi
push(get(7,4,0));
}
L438670: { // 57  push edi
push(get(7,4,0));
}
L438671: { // 56  push esi
push(get(6,4,0));
}
L438672: { // e8f4ccfcff  call 0x40536b
push(0x438677u);dispatch(0x40536bu);
}
L438677: { // 57  push edi
push(get(7,4,0));
}
L438678: { // 6a1e  push 0x1e
push(0x1eu);
}
L43867a: { // e815b1ffff  call 0x433794
push(0x43867fu);dispatch(0x433794u);
}
L43867f: { // c705441b770006000000  mov dword ptr [0x771b44], 6
write((0x771b44u),0x6u,4);
}
L438689: { // e99d010000  jmp 0x43882b
goto L43882b;
}
L43868e: { // e8dfcefcff  call 0x405572
push(0x438693u);dispatch(0x405572u);
}
L438693: { // 85c0  test eax, eax
logic(get(0,4,0)&get(0,4,0),4);
}
L438695: { // 0f8590010000  jne 0x43882b
if(condition(1))goto L43882b;
}
L43869b: { // c705441b770002000000  mov dword ptr [0x771b44], 2
write((0x771b44u),0x2u,4);
}
L4386a5: { // e981010000  jmp 0x43882b
goto L43882b;
}
L4386aa: { // 6800040000  push 0x400
push(0x400u);
}
L4386af: { // be581b7700  mov esi, 0x771b58
put(6,0x771b58u,4,0);
}
L4386b4: { // 6840177700  push 0x771740
push(0x771740u);
}
L4386b9: { // 56  push esi
push(get(6,4,0));
}
L4386ba: { // e8d1f00500  call 0x497790
push(0x4386bfu);dispatch(0x497790u);
}
L4386bf: { // 83c40c  add esp, 0xc
put(4,add(get(4,4,0),0xcu,4,false),4,0);
}
L4386c2: { // 6a0f  push 0xf
push(0xfu);
}
L4386c4: { // 57  push edi
push(get(7,4,0));
}
L4386c5: { // 57  push edi
push(get(7,4,0));
}
L4386c6: { // 56  push esi
push(get(6,4,0));
}
L4386c7: { // e89fccfcff  call 0x40536b
push(0x4386ccu);dispatch(0x40536bu);
}
L4386cc: { // 6a64  push 0x64
push(0x64u);
}
L4386ce: { // 6a1e  push 0x1e
push(0x1eu);
}
L4386d0: { // e8bfb0ffff  call 0x433794
push(0x4386d5u);dispatch(0x433794u);
}
L4386d5: { // c705441b770004000000  mov dword ptr [0x771b44], 4
write((0x771b44u),0x4u,4);
}
L4386df: { // e947010000  jmp 0x43882b
goto L43882b;
}
L4386e4: { // be00010000  mov esi, 0x100
put(6,0x100u,4,0);
}
L4386e9: { // 6a03  push 3
push(0x3u);
}
L4386eb: { // 3935dca26d00  cmp dword ptr [0x6da2dc], esi
sub(read((0x6da2dcu),4),get(6,4,0),4);
}
L4386f1: { // 5d  pop ebp
put(5,pop(),4,0);
}
L4386f2: { // bb45010000  mov ebx, 0x145
put(3,0x145u,4,0);
}
L4386f7: { // 0f852e010000  jne 0x43882b
if(condition(1))goto L43882b;
}
L4386fd: { // f6058b666d0040  test byte ptr [0x6d668b], 0x40
logic(read((0x6d668bu),1)&0x40u,1);
}
L438704: { // 7541  jne 0x438747
if(condition(1))goto L438747;
}
L438706: { // 393d88a86d00  cmp dword ptr [0x6da888], edi
sub(read((0x6da888u),4),get(7,4,0),4);
}
L43870c: { // 7508  jne 0x438716
if(condition(1))goto L438716;
}
L43870e: { // 393d88a66d00  cmp dword ptr [0x6da688], edi
sub(read((0x6da688u),4),get(7,4,0),4);
}
L438714: { // 7431  je 0x438747
if(condition(0))goto L438747;
}
L438716: { // a1ec145b00  mov eax, dword ptr [0x5b14ec]
put(0,read((0x5b14ecu),4),4,0);
}
L43871b: { // 8bcd  mov ecx, ebp
put(1,get(5,4,0),4,0);
}
L43871d: { // 83c002  add eax, 2
put(0,add(get(0,4,0),0x2u,4,false),4,0);
}
L438720: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L438721: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L438723: { // 393d481b7700  cmp dword ptr [0x771b48], edi
sub(read((0x771b48u),4),get(7,4,0),4);
}
L438729: { // 8915ec145b00  mov dword ptr [0x5b14ec], edx
write((0x5b14ecu),get(2,4,0),4);
}
L43872f: { // 7510  jne 0x438741
if(condition(1))goto L438741;
}
L438731: { // 3bd7  cmp edx, edi
sub(get(2,4,0),get(7,4,0),4);
}
L438733: { // 750c  jne 0x438741
if(condition(1))goto L438741;
}
L438735: { // 8d4202  lea eax, [edx + 2]
put(0,(0x2u+r[2]),4,0);
}
L438738: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L438739: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L43873b: { // 8915ec145b00  mov dword ptr [0x5b14ec], edx
write((0x5b14ecu),get(2,4,0),4);
}
L438741: { // 53  push ebx
push(get(3,4,0));
}
L438742: { // e82cccffff  call 0x435373
push(0x438747u);dispatch(0x435373u);
}
L438747: { // 3935dca26d00  cmp dword ptr [0x6da2dc], esi
sub(read((0x6da2dcu),4),get(6,4,0),4);
}
L43874d: { // 0f85d8000000  jne 0x43882b
if(condition(1))goto L43882b;
}
L438753: { // f6058b666d0040  test byte ptr [0x6d668b], 0x40
logic(read((0x6d668bu),1)&0x40u,1);
}
L43875a: { // 753f  jne 0x43879b
if(condition(1))goto L43879b;
}
L43875c: { // 393da8a86d00  cmp dword ptr [0x6da8a8], edi
sub(read((0x6da8a8u),4),get(7,4,0),4);
}
L438762: { // 7508  jne 0x43876c
if(condition(1))goto L43876c;
}
L438764: { // 393da8a66d00  cmp dword ptr [0x6da6a8], edi
sub(read((0x6da6a8u),4),get(7,4,0),4);
}
L43876a: { // 742f  je 0x43879b
if(condition(0))goto L43879b;
}
L43876c: { // a1ec145b00  mov eax, dword ptr [0x5b14ec]
put(0,read((0x5b14ecu),4),4,0);
}
L438771: { // 8bcd  mov ecx, ebp
put(1,get(5,4,0),4,0);
}
L438773: { // 40  inc eax
put(0,inc(get(0,4,0),4,1),4,0);
}
L438774: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L438775: { // f7f9  idiv ecx
divide(get(1,4,0),true);
}
L438777: { // 393d481b7700  cmp dword ptr [0x771b48], edi
sub(read((0x771b48u),4),get(7,4,0),4);
}
L43877d: { // 8915ec145b00  mov dword ptr [0x5b14ec], edx
write((0x5b14ecu),get(2,4,0),4);
}
L438783: { // 7510  jne 0x438795
if(condition(1))goto L438795;
}
L438785: { // 3bd7  cmp edx, edi
sub(get(2,4,0),get(7,4,0),4);
}
L438787: { // 750c  jne 0x438795
if(condition(1))goto L438795;
}
L438789: { // 8d4201  lea eax, [edx + 1]
put(0,(0x1u+r[2]),4,0);
}
L43878c: { // 99  cdq 
r[2]=(r[0]&0x80000000u)?0xffffffffu:0;
}
L43878d: { // f7fd  idiv ebp
divide(get(5,4,0),true);
}
L43878f: { // 8915ec145b00  mov dword ptr [0x5b14ec], edx
write((0x5b14ecu),get(2,4,0),4);
}
L438795: { // 53  push ebx
push(get(3,4,0));
}
L438796: { // e8d8cbffff  call 0x435373
push(0x43879bu);dispatch(0x435373u);
}
L43879b: { // 3935dca26d00  cmp dword ptr [0x6da2dc], esi
sub(read((0x6da2dcu),4),get(6,4,0),4);
}
L4387a1: { // 0f8584000000  jne 0x43882b
if(condition(1))goto L43882b;
}
L4387a7: { // f6058b666d0040  test byte ptr [0x6d668b], 0x40
logic(read((0x6d668bu),1)&0x40u,1);
}
L4387ae: { // 757b  jne 0x43882b
if(condition(1))goto L43882b;
}
L4387b0: { // a1b0666d00  mov eax, dword ptr [0x6d66b0]
put(0,read((0x6d66b0u),4),4,0);
}
L4387b5: { // 83f858  cmp eax, 0x58
sub(get(0,4,0),0x58u,4);
}
L4387b8: { // 740a  je 0x4387c4
if(condition(0))goto L4387c4;
}
L4387ba: { // 83f80d  cmp eax, 0xd
sub(get(0,4,0),0xdu,4);
}
L4387bd: { // 7405  je 0x4387c4
if(condition(0))goto L4387c4;
}
L4387bf: { // 83f861  cmp eax, 0x61
sub(get(0,4,0),0x61u,4);
}
L4387c2: { // 7567  jne 0x43882b
if(condition(1))goto L43882b;
}
L4387c4: { // 6843010000  push 0x143
push(0x143u);
}
L4387c9: { // c705441b770005000000  mov dword ptr [0x771b44], 5
write((0x771b44u),0x5u,4);
}
L4387d3: { // e89bcbffff  call 0x435373
push(0x4387d8u);dispatch(0x435373u);
}
L4387d8: { // eb51  jmp 0x43882b
goto L43882b;
}
L4387da: { // e8befdffff  call 0x43859d
push(0x4387dfu);dispatch(0x43859du);
}
L4387df: { // 57  push edi
push(get(7,4,0));
}
L4387e0: { // e8d7d4fcff  call 0x405cbc
push(0x4387e5u);dispatch(0x405cbcu);
}
L4387e5: { // a1ec145b00  mov eax, dword ptr [0x5b14ec]
put(0,read((0x5b14ecu),4),4,0);
}
L4387ea: { // 893d441b7700  mov dword ptr [0x771b44], edi
write((0x771b44u),get(7,4,0),4);
}
L4387f0: { // eb3c  jmp 0x43882e
goto L43882e;
}
L4387f2: { // e8acfcffff  call 0x4384a3
push(0x4387f7u);dispatch(0x4384a3u);
}
L4387f7: { // b8591b7700  mov eax, 0x771b59
put(0,0x771b59u,4,0);
}
L4387fc: { // 8048ffff  or byte ptr [eax - 1], 0xff
write((0xffffffffu+r[0]),logic(read((0xffffffffu+r[0]),1)|0xffu,1),1);
}
L438800: { // 8008ff  or byte ptr [eax], 0xff
write((0x0u+r[0]),logic(read((0x0u+r[0]),1)|0xffu,1),1);
}
L438803: { // 804801ff  or byte ptr [eax + 1], 0xff
write((0x1u+r[0]),logic(read((0x1u+r[0]),1)|0xffu,1),1);
}
L438807: { // 83c004  add eax, 4
put(0,add(get(0,4,0),0x4u,4,false),4,0);
}
L43880a: { // 3d591f7700  cmp eax, 0x771f59
sub(get(0,4,0),0x771f59u,4);
}
L43880f: { // 7ceb  jl 0x4387fc
if(condition(2))goto L4387fc;
}
L438811: { // 6800010000  push 0x100
push(0x100u);
}
L438816: { // 57  push edi
push(get(7,4,0));
}
L438817: { // 68581b7700  push 0x771b58
push(0x771b58u);
}
L43881c: { // e88fc3fcff  call 0x404bb0
push(0x438821u);dispatch(0x404bb0u);
}
L438821: { // c705441b770003000000  mov dword ptr [0x771b44], 3
write((0x771b44u),0x3u,4);
}
L43882b: { // 83c8ff  or eax, 0xffffffff
put(0,logic(get(0,4,0)|0xffffffffu,4),4,0);
}
L43882e: { // 5f  pop edi
put(7,pop(),4,0);
}
L43882f: { // 5e  pop esi
put(6,pop(),4,0);
}
L438830: { // 5d  pop ebp
put(5,pop(),4,0);
}
L438831: { // 5b  pop ebx
put(3,pop(),4,0);
}
L438832: { // c3  ret 
pop();r[4]+=0;return;
}
}
// 00438833_title_background_draw_machine_code
void RecoveredBattle::fn_438833(){
goto L438833;
L438833: { // 833d441b770001  cmp dword ptr [0x771b44], 1
sub(read((0x771b44u),4),0x1u,4);
}
L43883a: { // 7421  je 0x43885d
if(condition(0))goto L43885d;
}
L43883c: { // 6a00  push 0
push(0x0u);
}
L43883e: { // 6a00  push 0
push(0x0u);
}
L438840: { // ff354c1b7700  push dword ptr [0x771b4c]
push(read((0x771b4cu),4));
}
L438846: { // ff352c167700  push dword ptr [0x77162c]
push(read((0x77162cu),4));
}
L43884c: { // ff3530167700  push dword ptr [0x771630]
push(read((0x771630u),4));
}
L438852: { // ff356cb16d00  push dword ptr [0x6db16c]
push(read((0x6db16cu),4));
}
L438858: { // e856d5fcff  call 0x405db3
push(0x43885du);dispatch(0x405db3u);
}
L43885d: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00438860_title_menu_item_blit_left_mc_438860
void RecoveredBattle::fn_438860(){
goto L438860;
L438860: { // 55  push ebp
push(get(5,4,0));
}
L438861: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L438863: { // 83ec18  sub esp, 0x18
put(4,sub(get(4,4,0),0x18u,4,false),4,0);
}
L438866: { // 56  push esi
push(get(6,4,0));
}
L438867: { // 8b7508  mov esi, dword ptr [ebp + 8]
put(6,read((0x8u+r[5]),4),4,0);
}
L43886a: { // 6a66  push 0x66
push(0x66u);
}
L43886c: { // b982000000  mov ecx, 0x82
put(1,0x82u,4,0);
}
L438871: { // 8b5620  mov edx, dword ptr [esi + 0x20]
put(2,read((0x20u+r[6]),4),4,0);
}
L438874: { // 58  pop eax
put(0,pop(),4,0);
}
L438875: { // 4a  dec edx
put(2,inc(get(2,4,0),4,-1),4,0);
}
L438876: { // 894de8  mov dword ptr [ebp - 0x18], ecx
write((0xffffffe8u+r[5]),get(1,4,0),4);
}
L438879: { // 8945ec  mov dword ptr [ebp - 0x14], eax
write((0xffffffecu+r[5]),get(0,4,0),4);
}
L43887c: { // c745f004010000  mov dword ptr [ebp - 0x10], 0x104
write((0xfffffff0u+r[5]),0x104u,4);
}
L438883: { // 8945f4  mov dword ptr [ebp - 0xc], eax
write((0xfffffff4u+r[5]),get(0,4,0),4);
}
L438886: { // c745f886010000  mov dword ptr [ebp - 8], 0x186
write((0xfffffff8u+r[5]),0x186u,4);
}
L43888d: { // 8945fc  mov dword ptr [ebp - 4], eax
write((0xfffffffcu+r[5]),get(0,4,0),4);
}
L438890: { // 0f84e5000000  je 0x43897b
if(condition(0))goto L43897b;
}
L438896: { // 4a  dec edx
put(2,inc(get(2,4,0),4,-1),4,0);
}
L438897: { // 7460  je 0x4388f9
if(condition(0))goto L4388f9;
}
L438899: { // 4a  dec edx
put(2,inc(get(2,4,0),4,-1),4,0);
}
L43889a: { // 0f85eb000000  jne 0x43898b
if(condition(1))goto L43898b;
}
L4388a0: { // 6899000000  push 0x99
push(0x99u);
}
L4388a5: { // 51  push ecx
push(get(1,4,0));
}
L4388a6: { // 50  push eax
push(get(0,4,0));
}
L4388a7: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L4388aa: { // 6a00  push 0
push(0x0u);
}
L4388ac: { // 50  push eax
push(get(0,4,0));
}
L4388ad: { // ff1550958500  call dword ptr [0x859550]
push(0x4388b3u);dispatch(0x859550u);
}
L4388b3: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L4388b6: { // 6a00  push 0
push(0x0u);
}
L4388b8: { // 50  push eax
push(get(0,4,0));
}
L4388b9: { // a12c167700  mov eax, dword ptr [0x77162c]
put(0,read((0x77162cu),4),4,0);
}
L4388be: { // ff35501b7700  push dword ptr [0x771b50]
push(read((0x771b50u),4));
}
L4388c4: { // 053d010000  add eax, 0x13d
put(0,add(get(0,4,0),0x13du,4,false),4,0);
}
L4388c9: { // 50  push eax
push(get(0,4,0));
}
L4388ca: { // a130167700  mov eax, dword ptr [0x771630]
put(0,read((0x771630u),4),4,0);
}
L4388cf: { // 05b8010000  add eax, 0x1b8
put(0,add(get(0,4,0),0x1b8u,4,false),4,0);
}
L4388d4: { // 50  push eax
push(get(0,4,0));
}
L4388d5: { // ff356cb16d00  push dword ptr [0x6db16c]
push(read((0x6db16cu),4));
}
L4388db: { // e8d3d4fcff  call 0x405db3
push(0x4388e0u);dispatch(0x405db3u);
}
L4388e0: { // 833d441b770006  cmp dword ptr [0x771b44], 6
sub(read((0x771b44u),4),0x6u,4);
}
L4388e7: { // 0f849e000000  je 0x43898b
if(condition(0))goto L43898b;
}
L4388ed: { // c7462004000000  mov dword ptr [esi + 0x20], 4
write((0x20u+r[6]),0x4u,4);
}
L4388f4: { // e992000000  jmp 0x43898b
goto L43898b;
}
L4388f9: { // 833dec145b0000  cmp dword ptr [0x5b14ec], 0
sub(read((0x5b14ecu),4),0x0u,4);
}
L438900: { // 7407  je 0x438909
if(condition(0))goto L438909;
}
L438902: { // c7462001000000  mov dword ptr [esi + 0x20], 1
write((0x20u+r[6]),0x1u,4);
}
L438909: { // 833d441b770005  cmp dword ptr [0x771b44], 5
sub(read((0x771b44u),4),0x5u,4);
}
L438910: { // 6a03  push 3
push(0x3u);
}
L438912: { // 59  pop ecx
put(1,pop(),4,0);
}
L438913: { // 7503  jne 0x438918
if(condition(1))goto L438918;
}
L438915: { // 894e20  mov dword ptr [esi + 0x20], ecx
write((0x20u+r[6]),get(1,4,0),4);
}
L438918: { // a1d4a26d00  mov eax, dword ptr [0x6da2d4]
put(0,read((0x6da2d4u),4),4,0);
}
L43891d: { // 6a05  push 5
push(0x5u);
}
L43891f: { // 33d2  xor edx, edx
put(2,logic(get(2,4,0)^get(2,4,0),4),4,0);
}
L438921: { // 5e  pop esi
put(6,pop(),4,0);
}
L438922: { // f7f6  div esi
divide(get(6,4,0),false);
}
L438924: { // 33d2  xor edx, edx
put(2,logic(get(2,4,0)^get(2,4,0),4),4,0);
}
L438926: { // f7f1  div ecx
divide(get(1,4,0),false);
}
L438928: { // 8bc2  mov eax, edx
put(0,get(2,4,0),4,0);
}
L43892a: { // c1e003  shl eax, 3
put(0,shift(get(0,4,0),0x3u,4,0),4,0);
}
L43892d: { // 8b4c05ec  mov ecx, dword ptr [ebp + eax - 0x14]
put(1,read((0xffffffecu+r[5]+r[0]*1u),4),4,0);
}
L438931: { // 8b4405e8  mov eax, dword ptr [ebp + eax - 0x18]
put(0,read((0xffffffe8u+r[5]+r[0]*1u),4),4,0);
}
L438935: { // 8d5133  lea edx, [ecx + 0x33]
put(2,(0x33u+r[1]),4,0);
}
L438938: { // 52  push edx
push(get(2,4,0));
}
L438939: { // 8d9082000000  lea edx, [eax + 0x82]
put(2,(0x82u+r[0]),4,0);
}
L43893f: { // 52  push edx
push(get(2,4,0));
}
L438940: { // 51  push ecx
push(get(1,4,0));
}
L438941: { // 50  push eax
push(get(0,4,0));
}
L438942: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L438945: { // 50  push eax
push(get(0,4,0));
}
L438946: { // ff1550958500  call dword ptr [0x859550]
push(0x43894cu);dispatch(0x859550u);
}
L43894c: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L43894f: { // 6a00  push 0
push(0x0u);
}
L438951: { // 50  push eax
push(get(0,4,0));
}
L438952: { // a12c167700  mov eax, dword ptr [0x77162c]
put(0,read((0x77162cu),4),4,0);
}
L438957: { // ff35501b7700  push dword ptr [0x771b50]
push(read((0x771b50u),4));
}
L43895d: { // 053d010000  add eax, 0x13d
put(0,add(get(0,4,0),0x13du,4,false),4,0);
}
L438962: { // 50  push eax
push(get(0,4,0));
}
L438963: { // a130167700  mov eax, dword ptr [0x771630]
put(0,read((0x771630u),4),4,0);
}
L438968: { // 05b8010000  add eax, 0x1b8
put(0,add(get(0,4,0),0x1b8u,4,false),4,0);
}
L43896d: { // 50  push eax
push(get(0,4,0));
}
L43896e: { // ff356cb16d00  push dword ptr [0x6db16c]
push(read((0x6db16cu),4));
}
L438974: { // e83ad4fcff  call 0x405db3
push(0x438979u);dispatch(0x405db3u);
}
L438979: { // eb10  jmp 0x43898b
goto L43898b;
}
L43897b: { // 833dec145b0000  cmp dword ptr [0x5b14ec], 0
sub(read((0x5b14ecu),4),0x0u,4);
}
L438982: { // 7507  jne 0x43898b
if(condition(1))goto L43898b;
}
L438984: { // c7462002000000  mov dword ptr [esi + 0x20], 2
write((0x20u+r[6]),0x2u,4);
}
L43898b: { // 5e  pop esi
put(6,pop(),4,0);
}
L43898c: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L43898d: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00438990_title_menu_item_blit_mid_mc_438990
void RecoveredBattle::fn_438990(){
goto L438990;
L438990: { // 55  push ebp
push(get(5,4,0));
}
L438991: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L438993: { // 83ec18  sub esp, 0x18
put(4,sub(get(4,4,0),0x18u,4,false),4,0);
}
L438996: { // 56  push esi
push(get(6,4,0));
}
L438997: { // 8b7508  mov esi, dword ptr [ebp + 8]
put(6,read((0x8u+r[5]),4),4,0);
}
L43899a: { // 6a33  push 0x33
push(0x33u);
}
L43899c: { // b995000000  mov ecx, 0x95
put(1,0x95u,4,0);
}
L4389a1: { // 8b5620  mov edx, dword ptr [esi + 0x20]
put(2,read((0x20u+r[6]),4),4,0);
}
L4389a4: { // 58  pop eax
put(0,pop(),4,0);
}
L4389a5: { // 4a  dec edx
put(2,inc(get(2,4,0),4,-1),4,0);
}
L4389a6: { // 894de8  mov dword ptr [ebp - 0x18], ecx
write((0xffffffe8u+r[5]),get(1,4,0),4);
}
L4389a9: { // 8945ec  mov dword ptr [ebp - 0x14], eax
write((0xffffffecu+r[5]),get(0,4,0),4);
}
L4389ac: { // c745f02a010000  mov dword ptr [ebp - 0x10], 0x12a
write((0xfffffff0u+r[5]),0x12au,4);
}
L4389b3: { // 8945f4  mov dword ptr [ebp - 0xc], eax
write((0xfffffff4u+r[5]),get(0,4,0),4);
}
L4389b6: { // c745f8bf010000  mov dword ptr [ebp - 8], 0x1bf
write((0xfffffff8u+r[5]),0x1bfu,4);
}
L4389bd: { // 8945fc  mov dword ptr [ebp - 4], eax
write((0xfffffffcu+r[5]),get(0,4,0),4);
}
L4389c0: { // 0f84e0000000  je 0x438aa6
if(condition(0))goto L438aa6;
}
L4389c6: { // 4a  dec edx
put(2,inc(get(2,4,0),4,-1),4,0);
}
L4389c7: { // 745d  je 0x438a26
if(condition(0))goto L438a26;
}
L4389c9: { // 4a  dec edx
put(2,inc(get(2,4,0),4,-1),4,0);
}
L4389ca: { // 0f85e6000000  jne 0x438ab6
if(condition(1))goto L438ab6;
}
L4389d0: { // 6a66  push 0x66
push(0x66u);
}
L4389d2: { // 51  push ecx
push(get(1,4,0));
}
L4389d3: { // 50  push eax
push(get(0,4,0));
}
L4389d4: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L4389d7: { // 6a00  push 0
push(0x0u);
}
L4389d9: { // 50  push eax
push(get(0,4,0));
}
L4389da: { // ff1550958500  call dword ptr [0x859550]
push(0x4389e0u);dispatch(0x859550u);
}
L4389e0: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L4389e3: { // 6a00  push 0
push(0x0u);
}
L4389e5: { // 50  push eax
push(get(0,4,0));
}
L4389e6: { // a12c167700  mov eax, dword ptr [0x77162c]
put(0,read((0x77162cu),4),4,0);
}
L4389eb: { // ff35501b7700  push dword ptr [0x771b50]
push(read((0x771b50u),4));
}
L4389f1: { // 056c010000  add eax, 0x16c
put(0,add(get(0,4,0),0x16cu,4,false),4,0);
}
L4389f6: { // 50  push eax
push(get(0,4,0));
}
L4389f7: { // a130167700  mov eax, dword ptr [0x771630]
put(0,read((0x771630u),4),4,0);
}
L4389fc: { // 05ab010000  add eax, 0x1ab
put(0,add(get(0,4,0),0x1abu,4,false),4,0);
}
L438a01: { // 50  push eax
push(get(0,4,0));
}
L438a02: { // ff356cb16d00  push dword ptr [0x6db16c]
push(read((0x6db16cu),4));
}
L438a08: { // e8a6d3fcff  call 0x405db3
push(0x438a0du);dispatch(0x405db3u);
}
L438a0d: { // 833d441b770006  cmp dword ptr [0x771b44], 6
sub(read((0x771b44u),4),0x6u,4);
}
L438a14: { // 0f849c000000  je 0x438ab6
if(condition(0))goto L438ab6;
}
L438a1a: { // c7462004000000  mov dword ptr [esi + 0x20], 4
write((0x20u+r[6]),0x4u,4);
}
L438a21: { // e990000000  jmp 0x438ab6
goto L438ab6;
}
L438a26: { // 6a01  push 1
push(0x1u);
}
L438a28: { // 58  pop eax
put(0,pop(),4,0);
}
L438a29: { // 3905ec145b00  cmp dword ptr [0x5b14ec], eax
sub(read((0x5b14ecu),4),get(0,4,0),4);
}
L438a2f: { // 7403  je 0x438a34
if(condition(0))goto L438a34;
}
L438a31: { // 894620  mov dword ptr [esi + 0x20], eax
write((0x20u+r[6]),get(0,4,0),4);
}
L438a34: { // 833d441b770005  cmp dword ptr [0x771b44], 5
sub(read((0x771b44u),4),0x5u,4);
}
L438a3b: { // 6a03  push 3
push(0x3u);
}
L438a3d: { // 59  pop ecx
put(1,pop(),4,0);
}
L438a3e: { // 7503  jne 0x438a43
if(condition(1))goto L438a43;
}
L438a40: { // 894e20  mov dword ptr [esi + 0x20], ecx
write((0x20u+r[6]),get(1,4,0),4);
}
L438a43: { // a1d4a26d00  mov eax, dword ptr [0x6da2d4]
put(0,read((0x6da2d4u),4),4,0);
}
L438a48: { // 6a05  push 5
push(0x5u);
}
L438a4a: { // 33d2  xor edx, edx
put(2,logic(get(2,4,0)^get(2,4,0),4),4,0);
}
L438a4c: { // 5e  pop esi
put(6,pop(),4,0);
}
L438a4d: { // f7f6  div esi
divide(get(6,4,0),false);
}
L438a4f: { // 33d2  xor edx, edx
put(2,logic(get(2,4,0)^get(2,4,0),4),4,0);
}
L438a51: { // f7f1  div ecx
divide(get(1,4,0),false);
}
L438a53: { // 8bc2  mov eax, edx
put(0,get(2,4,0),4,0);
}
L438a55: { // c1e003  shl eax, 3
put(0,shift(get(0,4,0),0x3u,4,0),4,0);
}
L438a58: { // 8b4c05ec  mov ecx, dword ptr [ebp + eax - 0x14]
put(1,read((0xffffffecu+r[5]+r[0]*1u),4),4,0);
}
L438a5c: { // 8b4405e8  mov eax, dword ptr [ebp + eax - 0x18]
put(0,read((0xffffffe8u+r[5]+r[0]*1u),4),4,0);
}
L438a60: { // 8d5133  lea edx, [ecx + 0x33]
put(2,(0x33u+r[1]),4,0);
}
L438a63: { // 52  push edx
push(get(2,4,0));
}
L438a64: { // 8d9095000000  lea edx, [eax + 0x95]
put(2,(0x95u+r[0]),4,0);
}
L438a6a: { // 52  push edx
push(get(2,4,0));
}
L438a6b: { // 51  push ecx
push(get(1,4,0));
}
L438a6c: { // 50  push eax
push(get(0,4,0));
}
L438a6d: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L438a70: { // 50  push eax
push(get(0,4,0));
}
L438a71: { // ff1550958500  call dword ptr [0x859550]
push(0x438a77u);dispatch(0x859550u);
}
L438a77: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L438a7a: { // 6a00  push 0
push(0x0u);
}
L438a7c: { // 50  push eax
push(get(0,4,0));
}
L438a7d: { // a12c167700  mov eax, dword ptr [0x77162c]
put(0,read((0x77162cu),4),4,0);
}
L438a82: { // ff35501b7700  push dword ptr [0x771b50]
push(read((0x771b50u),4));
}
L438a88: { // 056c010000  add eax, 0x16c
put(0,add(get(0,4,0),0x16cu,4,false),4,0);
}
L438a8d: { // 50  push eax
push(get(0,4,0));
}
L438a8e: { // a130167700  mov eax, dword ptr [0x771630]
put(0,read((0x771630u),4),4,0);
}
L438a93: { // 05ab010000  add eax, 0x1ab
put(0,add(get(0,4,0),0x1abu,4,false),4,0);
}
L438a98: { // 50  push eax
push(get(0,4,0));
}
L438a99: { // ff356cb16d00  push dword ptr [0x6db16c]
push(read((0x6db16cu),4));
}
L438a9f: { // e80fd3fcff  call 0x405db3
push(0x438aa4u);dispatch(0x405db3u);
}
L438aa4: { // eb10  jmp 0x438ab6
goto L438ab6;
}
L438aa6: { // 833dec145b0001  cmp dword ptr [0x5b14ec], 1
sub(read((0x5b14ecu),4),0x1u,4);
}
L438aad: { // 7507  jne 0x438ab6
if(condition(1))goto L438ab6;
}
L438aaf: { // c7462002000000  mov dword ptr [esi + 0x20], 2
write((0x20u+r[6]),0x2u,4);
}
L438ab6: { // 5e  pop esi
put(6,pop(),4,0);
}
L438ab7: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L438ab8: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
// 00438abb_title_menu_item_blit_right_mc_438abb
void RecoveredBattle::fn_438abb(){
goto L438abb;
L438abb: { // 55  push ebp
push(get(5,4,0));
}
L438abc: { // 8bec  mov ebp, esp
put(5,get(4,4,0),4,0);
}
L438abe: { // 83ec18  sub esp, 0x18
put(4,sub(get(4,4,0),0x18u,4,false),4,0);
}
L438ac1: { // 56  push esi
push(get(6,4,0));
}
L438ac2: { // 57  push edi
push(get(7,4,0));
}
L438ac3: { // 8b7d08  mov edi, dword ptr [ebp + 8]
put(7,read((0x8u+r[5]),4),4,0);
}
L438ac6: { // 6a70  push 0x70
push(0x70u);
}
L438ac8: { // 59  pop ecx
put(1,pop(),4,0);
}
L438ac9: { // 33f6  xor esi, esi
put(6,logic(get(6,4,0)^get(6,4,0),4),4,0);
}
L438acb: { // 8b4720  mov eax, dword ptr [edi + 0x20]
put(0,read((0x20u+r[7]),4),4,0);
}
L438ace: { // 894de8  mov dword ptr [ebp - 0x18], ecx
write((0xffffffe8u+r[5]),get(1,4,0),4);
}
L438ad1: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L438ad2: { // 8975ec  mov dword ptr [ebp - 0x14], esi
write((0xffffffecu+r[5]),get(6,4,0),4);
}
L438ad5: { // c745f0e0000000  mov dword ptr [ebp - 0x10], 0xe0
write((0xfffffff0u+r[5]),0xe0u,4);
}
L438adc: { // 8975f4  mov dword ptr [ebp - 0xc], esi
write((0xfffffff4u+r[5]),get(6,4,0),4);
}
L438adf: { // c745f850010000  mov dword ptr [ebp - 8], 0x150
write((0xfffffff8u+r[5]),0x150u,4);
}
L438ae6: { // 8975fc  mov dword ptr [ebp - 4], esi
write((0xfffffffcu+r[5]),get(6,4,0),4);
}
L438ae9: { // 0f84dc000000  je 0x438bcb
if(condition(0))goto L438bcb;
}
L438aef: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L438af0: { // 745b  je 0x438b4d
if(condition(0))goto L438b4d;
}
L438af2: { // 48  dec eax
put(0,inc(get(0,4,0),4,-1),4,0);
}
L438af3: { // 0f85e0000000  jne 0x438bd9
if(condition(1))goto L438bd9;
}
L438af9: { // 6a33  push 0x33
push(0x33u);
}
L438afb: { // 51  push ecx
push(get(1,4,0));
}
L438afc: { // 56  push esi
push(get(6,4,0));
}
L438afd: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L438b00: { // 56  push esi
push(get(6,4,0));
}
L438b01: { // 50  push eax
push(get(0,4,0));
}
L438b02: { // ff1550958500  call dword ptr [0x859550]
push(0x438b08u);dispatch(0x859550u);
}
L438b08: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L438b0b: { // 56  push esi
push(get(6,4,0));
}
L438b0c: { // 50  push eax
push(get(0,4,0));
}
L438b0d: { // a12c167700  mov eax, dword ptr [0x77162c]
put(0,read((0x77162cu),4),4,0);
}
L438b12: { // ff35501b7700  push dword ptr [0x771b50]
push(read((0x771b50u),4));
}
L438b18: { // 0597010000  add eax, 0x197
put(0,add(get(0,4,0),0x197u,4,false),4,0);
}
L438b1d: { // 50  push eax
push(get(0,4,0));
}
L438b1e: { // a130167700  mov eax, dword ptr [0x771630]
put(0,read((0x771630u),4),4,0);
}
L438b23: { // 05c3010000  add eax, 0x1c3
put(0,add(get(0,4,0),0x1c3u,4,false),4,0);
}
L438b28: { // 50  push eax
push(get(0,4,0));
}
L438b29: { // ff356cb16d00  push dword ptr [0x6db16c]
push(read((0x6db16cu),4));
}
L438b2f: { // e87fd2fcff  call 0x405db3
push(0x438b34u);dispatch(0x405db3u);
}
L438b34: { // 833d441b770006  cmp dword ptr [0x771b44], 6
sub(read((0x771b44u),4),0x6u,4);
}
L438b3b: { // 0f8498000000  je 0x438bd9
if(condition(0))goto L438bd9;
}
L438b41: { // c7472004000000  mov dword ptr [edi + 0x20], 4
write((0x20u+r[7]),0x4u,4);
}
L438b48: { // e98c000000  jmp 0x438bd9
goto L438bd9;
}
L438b4d: { // 833dec145b0002  cmp dword ptr [0x5b14ec], 2
sub(read((0x5b14ecu),4),0x2u,4);
}
L438b54: { // 7407  je 0x438b5d
if(condition(0))goto L438b5d;
}
L438b56: { // c7472001000000  mov dword ptr [edi + 0x20], 1
write((0x20u+r[7]),0x1u,4);
}
L438b5d: { // 833d441b770005  cmp dword ptr [0x771b44], 5
sub(read((0x771b44u),4),0x5u,4);
}
L438b64: { // 6a03  push 3
push(0x3u);
}
L438b66: { // 59  pop ecx
put(1,pop(),4,0);
}
L438b67: { // 7503  jne 0x438b6c
if(condition(1))goto L438b6c;
}
L438b69: { // 894f20  mov dword ptr [edi + 0x20], ecx
write((0x20u+r[7]),get(1,4,0),4);
}
L438b6c: { // a1d4a26d00  mov eax, dword ptr [0x6da2d4]
put(0,read((0x6da2d4u),4),4,0);
}
L438b71: { // 6a05  push 5
push(0x5u);
}
L438b73: { // 33d2  xor edx, edx
put(2,logic(get(2,4,0)^get(2,4,0),4),4,0);
}
L438b75: { // 5f  pop edi
put(7,pop(),4,0);
}
L438b76: { // f7f7  div edi
divide(get(7,4,0),false);
}
L438b78: { // 33d2  xor edx, edx
put(2,logic(get(2,4,0)^get(2,4,0),4),4,0);
}
L438b7a: { // f7f1  div ecx
divide(get(1,4,0),false);
}
L438b7c: { // 8bc2  mov eax, edx
put(0,get(2,4,0),4,0);
}
L438b7e: { // c1e003  shl eax, 3
put(0,shift(get(0,4,0),0x3u,4,0),4,0);
}
L438b81: { // 8b4c05ec  mov ecx, dword ptr [ebp + eax - 0x14]
put(1,read((0xffffffecu+r[5]+r[0]*1u),4),4,0);
}
L438b85: { // 8b4405e8  mov eax, dword ptr [ebp + eax - 0x18]
put(0,read((0xffffffe8u+r[5]+r[0]*1u),4),4,0);
}
L438b89: { // 8d5133  lea edx, [ecx + 0x33]
put(2,(0x33u+r[1]),4,0);
}
L438b8c: { // 52  push edx
push(get(2,4,0));
}
L438b8d: { // 8d5070  lea edx, [eax + 0x70]
put(2,(0x70u+r[0]),4,0);
}
L438b90: { // 52  push edx
push(get(2,4,0));
}
L438b91: { // 51  push ecx
push(get(1,4,0));
}
L438b92: { // 50  push eax
push(get(0,4,0));
}
L438b93: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L438b96: { // 50  push eax
push(get(0,4,0));
}
L438b97: { // ff1550958500  call dword ptr [0x859550]
push(0x438b9du);dispatch(0x859550u);
}
L438b9d: { // 8d45f0  lea eax, [ebp - 0x10]
put(0,(0xfffffff0u+r[5]),4,0);
}
L438ba0: { // 56  push esi
push(get(6,4,0));
}
L438ba1: { // 50  push eax
push(get(0,4,0));
}
L438ba2: { // a12c167700  mov eax, dword ptr [0x77162c]
put(0,read((0x77162cu),4),4,0);
}
L438ba7: { // ff35501b7700  push dword ptr [0x771b50]
push(read((0x771b50u),4));
}
L438bad: { // 0597010000  add eax, 0x197
put(0,add(get(0,4,0),0x197u,4,false),4,0);
}
L438bb2: { // 50  push eax
push(get(0,4,0));
}
L438bb3: { // a130167700  mov eax, dword ptr [0x771630]
put(0,read((0x771630u),4),4,0);
}
L438bb8: { // 05c3010000  add eax, 0x1c3
put(0,add(get(0,4,0),0x1c3u,4,false),4,0);
}
L438bbd: { // 50  push eax
push(get(0,4,0));
}
L438bbe: { // ff356cb16d00  push dword ptr [0x6db16c]
push(read((0x6db16cu),4));
}
L438bc4: { // e8ead1fcff  call 0x405db3
push(0x438bc9u);dispatch(0x405db3u);
}
L438bc9: { // eb0e  jmp 0x438bd9
goto L438bd9;
}
L438bcb: { // 6a02  push 2
push(0x2u);
}
L438bcd: { // 58  pop eax
put(0,pop(),4,0);
}
L438bce: { // 3905ec145b00  cmp dword ptr [0x5b14ec], eax
sub(read((0x5b14ecu),4),get(0,4,0),4);
}
L438bd4: { // 7503  jne 0x438bd9
if(condition(1))goto L438bd9;
}
L438bd6: { // 894720  mov dword ptr [edi + 0x20], eax
write((0x20u+r[7]),get(0,4,0),4);
}
L438bd9: { // 5f  pop edi
put(7,pop(),4,0);
}
L438bda: { // 5e  pop esi
put(6,pop(),4,0);
}
L438bdb: { // c9  leave 
r[4]=r[5];r[5]=pop();
}
L438bdc: { // c20400  ret 4
pop();r[4]+=0x4u;return;
}
}
} // namespace fsb::core
