// Generated by tools/parallel/D_EFFECTS/generate_skill_callbacks.py.
// Evidence: the original instruction bytes recorded in the battle manifest.
// Original EXE SHA256: 710881d024ab1fcf738b342c248631363c9de3a51b32a7e3d61781b791eff454
// Edit the generator, not this file.
//
// Temporary ABI boundary for callers that still use the original execution
// model. The skill callbacks are gone from the generated product code; what is
// left here is reading the incoming argument and clearing it.
//
// The action routines the table forwards to belong to the battle scope and are
// still generated, so they keep running through the existing call path. Each is
// bound by its original address, which keeps the remaining dependency visible
// instead of hiding it inside a reconstructed body.
#include "fsb_core/recovered_battle.hpp"
#include "fsb_core/original_audio.hpp"
#include "fsb_core/visual_effects/skill_callbacks.hpp"

namespace fsb::core {

bool RecoveredBattle::dispatch_d_effects(Address entry) {
    switch (entry) {
    case 0x46a7e8u:
    case 0x46a7feu:
    case 0x46a80fu:
    case 0x46a820u:
    case 0x46a836u:
    case 0x46a859u:
    case 0x46a86fu:
    case 0x46a885u:
    case 0x46a89bu:
    case 0x46a8acu:
    case 0x46a8bdu:
    case 0x46a8d3u:
    case 0x46aba0u:
    case 0x46abb6u:
    case 0x46abccu:
    case 0x46abe2u:
    case 0x46abf3u:
    case 0x46ac04u:
    case 0x46ac1au:
    case 0x46ac2bu:
    case 0x46ac3cu:
    case 0x46ac52u:
    case 0x46ac63u:
    case 0x46ac74u:
    case 0x46b01cu:
    case 0x46b3f2u:
    case 0x46b445u:
    case 0x46b456u:
    case 0x46b4a9u:
    case 0x46b4bau:
    case 0x46b50du:
    case 0x46b51eu:
    case 0x46b571u:
    case 0x46b582u:
    case 0x46b593u:
    case 0x46b5b6u:
    case 0x46b5ccu:
    case 0x46b5e2u:
    case 0x46b605u:
    case 0x46b628u:
    case 0x46b64bu:
    case 0x46b66eu:
    case 0x46b691u:
    case 0x46b6a2u:
    case 0x46b6c5u:
    case 0x46b6d6u:
    case 0x46b6e7u:
    case 0x46b6fdu:
    case 0x46b70eu:
    case 0x46b71fu:
    case 0x46b735u:
    case 0x46b746u:
    case 0x46b75cu:
    case 0x46ba34u:
    case 0x46ba4au:
    case 0x46ba60u:
    case 0x46ba71u:
    case 0x46bcf1u:
    case 0x46bd07u:
    case 0x46bd1du:
    case 0x46bd5au:
    case 0x46bd6bu:
    case 0x46bd7cu:
    case 0x46bfdau:
    case 0x46bfebu:
    case 0x46bffcu:
    case 0x46c012u:
    case 0x46c028u:
    case 0x46c060u:
    case 0x46c076u:
    case 0x46c56du:
    case 0x46c583u:
    case 0x46c594u:
    case 0x46c5a5u:
    case 0x46cae9u:
    case 0x46cafau:
    case 0x46cba2u:
    case 0x46d203u:
    case 0x46d214u:
    case 0x46d225u:
    case 0x46d236u:
    case 0x46d8ddu:
    case 0x46d8eeu:
    case 0x46dbb3u:
    case 0x46dbc4u:
    case 0x46dbd5u:
    case 0x46dbf8u:
    case 0x46dc09u:
    case 0x46dc1au:
    case 0x46dc8fu:
    case 0x46df9cu:
    case 0x46dfadu:
    case 0x46e30cu:
    case 0x46e31du:
    case 0x46e32eu:
    case 0x46e5fbu:
    case 0x46e60cu:
    case 0x46e622u:
    case 0x46e633u:
    case 0x46e649u:
    case 0x46e65au:
    case 0x46e66bu:
    case 0x46e681u:
    case 0x46e692u:
    case 0x46e6a3u:
    case 0x46e6b4u:
    case 0x46e6d7u:
    case 0x46e6fau:
    case 0x46e71du:
    case 0x46e740u:
    case 0x46e763u:
    case 0x46e779u:
    case 0x46e79cu:
    case 0x46e7bfu:
    case 0x46e7e2u:
    case 0x46e7f3u:
    case 0x46e809u:
    case 0x46e82cu:
    case 0x46e842u:
    case 0x46e853u:
    case 0x46e869u:
    case 0x46e88cu:
    case 0x46e89du:
    case 0x46eb9cu:
    case 0x46ebb2u:
    case 0x46ebc3u:
    case 0x46ebd4u:
    case 0x46ebeau:
    case 0x46ec0du:
    case 0x46ec1eu:
    case 0x46ec2fu:
    case 0x46ec52u:
    case 0x46ec68u:
    case 0x46ec8bu:
    case 0x46eca1u:
    case 0x46ecc4u:
    case 0x46ece7u:
    case 0x46ecf8u:
    case 0x46f661u:
    case 0x46fbe8u:
    case 0x46fec1u:
    case 0x46fee4u:
    case 0x46ff07u:
    case 0x46ff1du:
    case 0x47016eu:
    case 0x47017fu:
    case 0x470195u:
    case 0x4701b8u:
    case 0x4701ceu:
    case 0x4701e4u:
    case 0x4701fau:
    case 0x47020bu:
    case 0x47021cu:
    case 0x47022du:
    case 0x470243u:
    case 0x470259u:
    case 0x47026au:
    case 0x470280u:
    case 0x470296u:
    case 0x4702a7u:
    case 0x4705a3u:
    case 0x4708ceu:
    case 0x4708f1u:
    case 0x470914u:
    case 0x470925u:
    case 0x470948u:
    case 0x47096bu:
    case 0x47097cu:
    case 0x470992u:
    case 0x470ae0u:
    case 0x470af1u:
    case 0x470b14u:
    case 0x470b25u:
    case 0x470b36u:
    case 0x470b47u:
    case 0x470b58u:
    case 0x470b69u:
    case 0x470b7au:
    case 0x471347u:
    case 0x471358u:
    case 0x471369u:
    case 0x47137au:
    case 0x47138bu:
    case 0x4713aeu:
    case 0x4719c0u:
    case 0x4719d1u:
    case 0x472548u:
    case 0x47354du:
    case 0x4739e8u:
    case 0x4739feu:
    case 0x473cb1u:
    case 0x474766u:
    case 0x476765u:
    case 0x477444u:
    case 0x477482u:
    case 0x4774c0u:
    case 0x47aa55u:
    case 0x47aaa5u:
    case 0x47aaf5u:
    case 0x47b5f9u:
    case 0x47b60au:
    case 0x47bb59u:
    case 0x47bedfu:
    case 0x47d052u:
    case 0x47d095u:
    case 0x47d0d8u:
    case 0x47d11bu:
    case 0x47d15eu:
    case 0x47d1a1u:
    case 0x47d59fu:
    case 0x47db70u:
    case 0x47dbf5u:
    case 0x47dfd5u:
    case 0x47dfe6u:
    case 0x4806ebu:
    case 0x4807d7u:
    case 0x480827u:
    case 0x480877u:
    case 0x481387u:
    case 0x481406u:
    case 0x481449u:
    case 0x48148cu:
    case 0x48239eu:
    case 0x48281au:
    case 0x48282bu:
    case 0x48283cu:
    case 0x482aa9u:
    case 0x482ef9u:
    case 0x482f0au:
    case 0x48314fu:
    case 0x48315du:
    case 0x48316bu:
    case 0x4837b7u:
    case 0x4837c3u:
    case 0x4837d1u:
    case 0x483c68u:
    case 0x4840a2u:
    case 0x48456au:
    case 0x484bc0u:
    case 0x484c03u:
    case 0x4853e2u:
    case 0x485de2u:
    case 0x486577u:
    case 0x48659au:
        break;
    default:
        return false;
    }
    visual_effects::SkillCallbacks callbacks(memory_);
    callbacks.play_cue = [this](unsigned cue) { return callback(original_audio::play_cue, {cue}); };
    for (const auto& row : visual_effects::SkillCallbacks::rows()) {
        const auto pushed = visual_effects::pushed_arguments(row);
        callbacks.bind(row.routine, [this, routine = row.routine, pushed](
                           Address sequence, std::int32_t first, std::int32_t second) {
            std::vector<std::uint32_t> args{sequence, std::uint32_t(first), std::uint32_t(second)};
            args.resize(pushed);
            return callback(routine, args);
        });
    }
    result(callbacks.invoke(entry, argument(0)), 4);
    return true;
}

}
