#!/usr/bin/env python3
"""Turn the recovered installer tables into the C++ table map_logic replays."""
import json,sys
from pathlib import Path

FIELDS=[32,36,40,44]

def main(tables,output,bridge_output):
    data=json.loads(Path(tables).read_text())
    accepted={int(k,16):v for k,v in data['accepted'].items()}
    lines=['// Generated by tools/parallel/C_MAPS/emit_map_setup_tables.py; edit the',
           '// extractor, not this file. Recovered from the original installer bodies.',
           '// Original EXE SHA256: '+data['source_sha256'],'']
    for entry in sorted(accepted):
        lines.append('constexpr OverlayRegistration installer_%x[]={'%entry)
        for record in accepted[entry]['records']:
            fields=record.get('fields',{})
            mask=sum(1<<i for i,offset in enumerate(FIELDS) if str(offset) in fields)
            values=','.join('0x%x'%fields.get(str(offset),0) for offset in FIELDS)
            lines.append('    {%d,%d,%d,%d,0x%x,0x%x,%s,%s,0x%x},'%(
                *[v if v<0x80000000 else v-0x100000000 for v in record['rect']],
                record['callback'],record['flags'],
                'true' if record.get('publish') else 'false',values,mask))
        lines.append('};')
    lines.append('constexpr MapInstaller installers[]={')
    for entry in sorted(accepted):
        lines.append('    {0x%x,installer_%x,%d},'%(entry,entry,len(accepted[entry]['records'])))
    lines+=['};','']
    Path(output).write_text('\n'.join(lines)+'\n')
    bridge=['#include "fsb_core/recovered_battle.hpp"','#include "fsb_core/map_logic/map_setup.hpp"',
            '#include "fsb_core/map.hpp"','',
            '// Generated by tools/parallel/C_MAPS/emit_map_setup_tables.py; edit the',
            '// extractor, not this file. Temporary ABI boundary for the recovered map',
            '// installers, whose original callers still use the old execution model.',
            'namespace fsb::core {','bool RecoveredBattle::dispatch_c_maps_installers(Address entry){',
            '    switch(entry){']
    for pops in sorted({v['pops'] for v in accepted.values()}):
        for entry in sorted(accepted):
            if accepted[entry]['pops']==pops:bridge.append('    case 0x%x:'%entry)
        bridge+=['    {','        Map map(memory_);',
                 '        if(!map_logic::install_map_overlays(memory_,map,entry))return false;',
                 '        result(0,%d);return true; // The setup dispatcher ignores EAX.'%pops,'    }']
    bridge+=['    default:return false;','    }','}','} // namespace fsb::core','']
    Path(bridge_output).write_text('\n'.join(bridge))
    print('installers',len(accepted),'records',sum(len(v['records']) for v in accepted.values()))
if __name__=='__main__':main(*sys.argv[1:])
