#!/usr/bin/env python3
"""Regenerate portable shader bytes. Requires glslangValidator and spirv-cross."""
import pathlib, subprocess, tempfile
root=pathlib.Path(__file__).resolve().parent
with tempfile.TemporaryDirectory() as d:
    spv=pathlib.Path(d)/'presentation.spv'
    msl=pathlib.Path(d)/'presentation.metal'
    subprocess.run(['glslangValidator','-V',str(root/'shaders/presentation.frag'),'-o',str(spv)],check=True)
    subprocess.run(['spirv-cross',str(spv),'--msl','--msl-version','20100','--output',str(msl)],check=True)
    text='// Generated by tools/build_presentation_shaders.py; edit presentation.frag.\n#pragma once\nnamespace fsb::host::shaders {\n'
    for name,data in [('spirv',spv.read_bytes()),('msl',msl.read_bytes()+b'\0')]:
        text+='inline constexpr unsigned char '+name+'[]={\n'
        text+='\n'.join('    '+','.join(str(v) for v in data[i:i+24])+',' for i in range(0,len(data),24))
        text+='\n};\n'
    (root/'shaders/presentation_shaders.hpp').write_text(text+'}\n')
