#!/usr/bin/env python3
"""Extract only complete literal/locale template arms; never infer story effects."""
from pathlib import Path
import re,json,hashlib,sys

def main(source,root):
 source=Path(source);root=Path(root);raw=source.read_text();s=re.sub(r'/\*.*?\*/','',raw,flags=re.S)
 constants={name:int(value,0) for name,value in re.findall(r'#define\s+(DIALOG_TEMPLATE_\w+)\s+(0x[0-9a-fA-F]+|\d+)\b',s)}
 body=s[s.index('int dialog_markup_template_expander'):];pieces=re.split(r'^  case ([^:]+):',body,flags=re.M)
 pending=[];rows=[]
 for i in range(1,len(pieces),2):
  pending.append(pieces[i].strip());flat=' '.join(pieces[i+1].split())
  if not flat:continue
  literal=re.fullmatch(r'selected_markup_blob = DIALOG_TEMPLATE_MARKUP_BLOB\((0x[0-9a-fA-F]+)\); break;',flat)
  localized=re.fullmatch(r'if \(build_language_flag_7686bc < 0\) \{ selected_markup_blob = DIALOG_TEMPLATE_MARKUP_BLOB\((0x[0-9a-fA-F]+)\); \} else \{ selected_markup_blob = DIALOG_TEMPLATE_MARKUP_BLOB\((0x[0-9a-fA-F]+)\); \} break;',flat)
  if literal or localized:
   blobs=[int(v,0) for v in (literal or localized).groups()]
   for name in pending:
    ident=constants[name] if name.startswith('DIALOG_') else int(name,0)
    rows.append({'id':ident,'source_symbol':name,'korean':hex(blobs[0]),'other':hex(blobs[-1]),'localized':localized is not None})
  pending=[]
 rows.sort(key=lambda r:r['id']);assert len({r['id'] for r in rows})==len(rows)
 data={'entry':'0x413da7','source':source.name,'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'rows':rows,'scope':'complete literal and locale-only arms; common prefix/return is implemented separately; all remaining IDs stay explicit legacy cases'}
 (root/'reference/dialog-template-rows.json').write_text(json.dumps(data,indent=2)+'\n')
 lines=['// Generated by tools/extract_dialog_template_rows.py; selectors are original data IDs.']
 for row in rows:lines.append('    {%s, %s, %s, %s}, // %s'%(hex(row['id']),row['korean'],row['other'],'true' if row['localized'] else 'false',row['source_symbol']))
 (root/'src/dialog_template_rows.inc').write_text('\n'.join(lines)+'\n')
 print('static_template_rows',len(rows))
if __name__=='__main__':main(*sys.argv[1:])
