#!/usr/bin/env python3
"""Original x86 draw-record oracle with explicitly preloaded surface metadata.

No Windows call replacements. This isolates actor record construction; it does
not validate resource decoding, surface allocation or full-game timing.
Requires unicorn and the local original assets generated by prepare_event0.py.
"""
import hashlib
import json
from pathlib import Path
import struct
import sys
import unicorn
from unicorn import Uc, UC_ARCH_X86, UC_MODE_32
from unicorn.x86_const import UC_X86_REG_EAX, UC_X86_REG_EIP, UC_X86_REG_ESP
from prepare_event0 import PE

def main(assets, output):
    assets=Path(assets); pe=PE(assets/'FLYINGSB.EXE')
    sha=hashlib.sha256(pe.data).hexdigest()
    if sha!='710881d024ab1fcf738b342c248631363c9de3a51b32a7e3d61781b791eff454': raise ValueError('wrong original EXE')
    u=Uc(UC_ARCH_X86,UC_MODE_32);u.mem_map(0x400000,0x600000);u.mem_map(0x1000000,0x10000)
    for _,va,size,offset in pe.sections: u.mem_write(pe.base+va,pe.data[offset:offset+size])
    def write(a,v):u.mem_write(a,struct.pack('<I',v&0xffffffff))
    def read(a):return struct.unpack('<I',u.mem_read(a,4))[0]
    def call(a,*args):
        u.reg_write(UC_X86_REG_ESP,0x100f000)
        u.mem_write(0x100f000,struct.pack('<'+'I'*(len(args)+1),0x1000000,*args))
        u.emu_start(a,0x1000000,count=20000000)
        if u.reg_read(UC_X86_REG_EIP)!=0x1000000: raise RuntimeError('original routine did not return')
        return u.reg_read(UC_X86_REG_EAX)
    call(0x40c0ad)
    for i in range(6610):write(0x514b94+i*64,0xe00000+i*16)
    image=(assets/'ASE_PS/CSON000.pcx').read_bytes()
    width=struct.unpack_from('<H',image,8)[0]-struct.unpack_from('<H',image,4)[0]+1
    height=struct.unpack_from('<H',image,10)[0]-struct.unpack_from('<H',image,6)[0]+1
    definition=0x500638+8*68
    u.mem_write(definition+0x2c,struct.pack('<HHH',width//6,height//4,24));write(definition+0x40,0xd00000)
    for a,v in [(0x6e12b0,640),(0x6e1440,360),(0x6d9d30,0),(0x6d9d34,60),(0x7873c0,384),(0x7873c4,1560),
                (0x6da2d4,1),(0x768370,1),(0x757dbc,1),(0x74b6d8,1),(0x766f74,266)]:write(a,v)
    fields=(8,12,16,28,32,36,0x130,0x134,0x138)
    cases=[]
    for kind in range(3):
        for i in range(8):
            index=(0,1,10,90)[i%4]; actor=0x8073d8+index*428
            values=[(416 if i%2 else -17)*65536+123,1560*65536-456,24*65536,i%4*32768,3*65536+78,-96*65536-123,8,
                    (0x20000,26,266)[kind],i if kind!=1 else i%7]
            for a,v in zip(fields,values):write(actor+a,v)
            for p in range(4):write(0x787488+p*4,0);u.mem_write(0x788118+p*428*84,bytes(84))
            address=call(0x454cb5,index)
            record=list(struct.unpack('<21I',u.mem_read(address,84)));record[20]=0 # Opaque surface identity is intentionally normalized.
            anchors=[read(actor+0x120),read(actor+0x124)]
            cases.append([index]+values+record+anchors)
    blob=b'FSBREN1\0'+struct.pack('<I',len(cases))+b''.join(struct.pack('<33I',*(v&0xffffffff for v in c)) for c in cases)
    out=Path(output);out.parent.mkdir(parents=True,exist_ok=True);out.write_bytes(blob)
    report={'exe_sha256':sha,'generator':'Unicorn '+unicorn.__version__,'routine':'0x454cb5 with actual cached-asset callees',
            'cases':len(cases),'record_fields_compared':20,'anchor_fields_compared':2,'normalized_field':'record+0x50 opaque surface identity',
            'scope':'actor draw-command numerical construction with explicit preloaded sheet/frame metadata; no full-scene timing proof',
            'binary_sha256':hashlib.sha256(blob).hexdigest()}
    out.with_suffix('.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))

if __name__=='__main__':
    if len(sys.argv)!=3:raise SystemExit('usage: prepare_render_reference.py ASSETS OUTPUT.bin')
    main(*sys.argv[1:])
