#!/usr/bin/env python3
"""Original x86 edge cases for the resumed B_COMBAT integration."""
from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).parent/'parallel/B_COMBAT'))
from prepare_combat_reference import Oracle,ACTOR_SLOT,ACTOR_STRIDE

def main(snapshot,output):
    o=Oracle(snapshot)
    o.substitute(0x4353cb,1,'sound stop device boundary; does not alter compared game state')
    obj=ACTOR_SLOT+700*ACTOR_STRIDE
    for value in [0x7fffffff,0x80000000,0xffffffff]:
        # Negating INT_MIN must retain the original two-complement bit pattern.
        for entry in [0x46562e,0x46570a]:
            o.case(entry,[obj],[(obj+0x14c,4,20),(obj+0x144,4,10),
                               (obj+0x194,4,0),(obj+0x174,4,value)],0)
        # Keep motion disabled and tick odd, isolating orbit ADDs without a
        # spawned trail. Callees still run original instructions.
        for state in [0,10]:
            for speed in [0x20,value]:
                o.case(0x466ed1,[obj],[(obj+0x14c,4,state),(obj+0x144,4,1),
                    (obj+0x168,4,0),(obj+4,4,0),(obj+0x10,4,0),
                    (obj+0x1a0,4,value),(obj+0x1a4,4,speed),(obj+0x194,4,2)],0)
    o.write(output,'refresh_edges','Original beam NEG and orbit ADD boundary cases. Sound stop alone is substituted; expectations are not generated by the port.')
if __name__=='__main__':main(*sys.argv[1:])
