"""Provisional ownership of legacy functions during semantic reconstruction.

Names describe current responsibilities, not claimed original filenames.
Boundaries combine original assert-path evidence and the named call families in
reports/generated-split/FINDINGS.md. Ownership is explicit and reproducible;
direct calls crossing it are reported, not hidden behind a cohesion score.
"""
MODULES = [
    (0x401000, 'platform_helpers', 'Rectangles, palette, viewport and fixed arithmetic'),
    (0x40b000, 'dialogue', 'Dialogue layout and presentation'),
    (0x412000, 'events', 'Event lifecycle and interaction entry points'),
    (0x413900, 'field_interaction', 'Field conversation and station interactions'),
    (0x41a000, 'sequence', 'Event instruction handlers and control stack'),
    (0x42feaa, 'sequence_actors', 'Actor operations called by event instructions'),
    (0x431800, 'session', 'Session settings, serialization and transitions'),
    (0x435740, 'worldmap', 'World map routes, markers and movement'),
    (0x4385e9, 'title', 'Title screen state and drawing'),
    (0x439000, 'menus', 'Field and battle menus, items and equipment panels'),
    (0x447841, 'effect_script', 'Actor visual effect instruction language'),
    (0x447e31, 'battle_grid', 'Battle actor placement, reachable cells and targeting'),
    (0x44c1fc, 'battle_status', 'Status application and battle state'),
    (0x44e775, 'battle_rules', 'Accuracy, damage and combat rules'),
    (0x451601, 'battle_ai', 'Target collection and action selection'),
    (0x4544cf, 'scene', 'Camera, scene drawing and map resources'),
    (0x457e1c, 'actors', 'Actor allocation, party, movement and visual state'),
    (0x461854, 'battle_flow', 'Battle lifecycle and active controller'),
    (0x463258, 'battle_presentation', 'Battle panels and command presentation'),
    (0x464258, 'battle_actions', 'Combat actions and damage displays'),
    (0x4672b5, 'effect_objects', 'Effect object lifetime and animation'),
    (0x46d214, 'skill_effects', 'Skill effect dispatch and monster actions'),
    (0x474777, 'particles', 'Particle spawning and trajectories'),
    (0x47aa55, 'screen_effects', 'Screen-wide visual effects'),
    (0x47d052, 'projectiles', 'Weapon and projectile motion'),
    (0x480d0c, 'character_skills', 'Character skill dispatch'),
    (0x486b53, 'map_objects', 'Map objects, switches and movement callbacks'),
    (0x48ab3b, 'map_setup', 'Map-specific object and trigger construction'),
    (0x496fe8, 'event_flags', 'Shared event flags and patch synchronization'),
    (0x4971f0, 'crt', 'Remaining compiler runtime functions'),
]

# Late callback discovery must stay with the subsystem owning its state.
OVERRIDES = {
    0x493a26: 'map_objects',  # Falling-floor callback, not map construction.
    0x461d25: 'effect_script',  # Active-controller notification used by effects.
}


def module_for(entry):
    if entry in OVERRIDES:
        return OVERRIDES[entry]
    return next(name for start, name, _ in reversed(MODULES) if entry >= start)


def emit_modules(root, preamble, bodies, dispatch, functions, write_changed):
    import collections
    import json
    from capstone.x86_const import X86_OP_IMM

    folder = root / 'src' / 'recovered'
    folder.mkdir(parents=True, exist_ok=True)
    groups = collections.defaultdict(list)
    assignments = {}
    for entry, body in bodies.items():
        module = module_for(entry)
        groups[module].extend(body)
        assignments[hex(entry)] = 'src/recovered/' + module + '.cpp'
    sources = []
    for module, lines in sorted(groups.items()):
        relative = 'src/recovered/' + module + '.cpp'
        write_changed(root / relative, '\n'.join(preamble + lines + ['} // namespace fsb::core']) + '\n')
        sources.append(relative)
    dispatcher = 'src/recovered/dispatch.cpp'
    write_changed(root / dispatcher, '\n'.join(preamble + dispatch) + '\n')
    sources.append(dispatcher)
    # Only remove stale generated files listed by the previous manifest.
    old_manifest = root / 'reference/recovered-battle-manifest.json'
    if old_manifest.exists():
        old = json.loads(old_manifest.read_text()).get('generated_sources', [])
        for relative in set(old) - set(sources):
            path = root / relative
            if relative.startswith('src/recovered/') and path.exists() and path.read_text().startswith('// Generated by tools/translate_battle.py;'):
                path.unlink()
    write_changed(root / 'src/recovered_sources.cmake', '# Generated by tools/translate_battle.py.\nset(FSB_RECOVERED_SOURCES\n' + ''.join('    ' + path + '\n' for path in sources) + ')\n')
    calls = collections.Counter()
    for caller, instructions in functions.items():
        for instruction in instructions.values():
            if instruction.mnemonic == 'call' and instruction.operands[0].type == X86_OP_IMM:
                target = instruction.operands[0].imm
                if target in functions:
                    calls[module_for(caller), module_for(target)] += 1
    return sources, assignments, {
        'basis': 'Provisional source-family ownership; file partition does not remove shared CPU/global state coupling.',
        'modules': {name: description for _, name, description in MODULES},
        'direct_calls_within_modules': sum(n for (a, b), n in calls.items() if a == b),
        'direct_calls_between_modules': sum(n for (a, b), n in calls.items() if a != b),
        'direct_call_counts': [{'caller': a, 'callee': b, 'count': n} for (a, b), n in sorted(calls.items())],
    }
